
set(CMAKE_CSharp_COMPILER "/usr/bin/mcs")
set(CMAKE_CSharp_COMPILER_ID "Mono")
set(CMAKE_CSharp_COMPILER_VERSION "3.2.8.0")
set(CMAKE_CSharp_COMPILER_LOADED 1)
set(CMAKE_CSharp_PLATFORM_ID "Mono")

SET(CMAKE_CSharp_SOURCE_FILE_EXTENSIONS cs)
SET(CMAKE_CSharp_LINKER_PREFERENCE 40)
SET(CMAKE_CSharp_OUTPUT_EXTENSION "")
#SET(CMAKE_CSharp_OUTPUT_EXTENSION_REPLACE 1)
SET(CMAKE_STATIC_LIBRARY_PREFIX_CSharp "")
SET(CMAKE_STATIC_LIBRARY_SUFFIX_CSharp ".dll")

set(CMAKE_CSharp_COMPILER_ENV_VAR "CSC")

