(define (problem bridge)
  (:domain montlake)
  (:init (joe-at tower)
	 (first-gates-up)
	 (second-gates-up)
	 (pin-in)
	 (boats-waiting)
	 (semaphore green))
  (:goal (and (not (boats-waiting))
	      (semaphore green))))