( DEFINE ( PROBLEM D1S1-8 )
    (:domain
    D1S1)
    (:init
        ( I5 ) 
        ( I4 ) 
        ( I8 ) 
        ( I3 ) 
        ( I1 ) 
        ( I2 ) 
        ( I7 ) 
        ( I6 ) 
     ) 
    (:goal
    ( AND
        ( G5 ) 
        ( G1 ) 
        ( G7 ) 
        ( G6 ) 
        ( G8 ) 
        ( G2 ) 
        ( G3 ) 
        ( G4 ) 
	) )
    (:length (:serial 8) (:parallel 8))
 )