( DEFINE ( PROBLEM D1S1-10 )
    (:domain
    D1S1)
    (:init
        ( I1 ) 
        ( I3 ) 
        ( I7 ) 
        ( I4 ) 
        ( I2 ) 
        ( I10 ) 
        ( I6 ) 
        ( I8 ) 
        ( I9 ) 
        ( I5 ) 
     ) 
    (:goal
    ( AND
        ( G7 ) 
        ( G5 ) 
        ( G2 ) 
        ( G4 ) 
        ( G10 ) 
        ( G3 ) 
        ( G8 ) 
        ( G1 ) 
        ( G6 ) 
        ( G9 ) 
	) )
    (:length (:serial 10) (:parallel 10))
 )