grandparent(dad(dad(bob)),bob).
grandparent(dad(mum(bob)),bob).
grandparent(mum(dad(bob)),bob).
grandparent(mum(mum(bob)),bob).
grandparent(dad(dad(jo)),jo).
grandparent(dad(mum(jo)),jo).
grandparent(mum(dad(jo)),jo).
grandparent(mum(mum(jo)),jo).
grandparent(dad(dad(peter)),peter).
grandparent(dad(mum(peter)),peter).
grandparent(mum(dad(peter)),peter).
grandparent(mum(mum(peter)),peter).
grandparent(dad(dad(jane)),jane).
grandparent(dad(mum(jane)),jane).
grandparent(mum(dad(jane)),jane).
grandparent(mum(mum(jane)),jane).
