(define
    (domain Car-Inspection-659ec0ca-00c3-5d29-4028-2dca3c489a64)
    (:requirements :strips :typing)
    (:types )
    (:constants
      
    )

    (:predicates 
        (have_spark_plug_status)
        (maybe-have_spark_plug_status)
        (have_break_pad_status)
        (maybe-have_break_pad_status)
        (have_user_initiative_message)
        (maybe-have_user_initiative_message)
        (have_clutch_seal_tightness_status)
        (maybe-have_clutch_seal_tightness_status)
        (have_pass_status_options)
        (maybe-have_pass_status_options)
        (have_oil_status)
        (maybe-have_oil_status)
        (user_initiative)
        (have_message)
        (maybe-have_message)
        (GOAL)
        (STARTED)
        (can-do_dialogue-disambiguation-start_conversation)
        (can-do_dialogue-disambiguation-ask-for_oil-level)
        (can-do_dialogue-disambiguation-ask-for_clutch-seal-tightness)
        (can-do_dialogue-disambiguation-ask-for_break-pad)
        (can-do_dialogue-disambiguation-ask-for_spark-plug)
        (can-do_dialogue-disambiguation-end_conversation)
        (can-do_dialogue-disambiguation-state-message)
    )
    (:action dialogue-disambiguation-start_conversation
        :parameters ()
        :precondition
            (and
                (can-do_dialogue-disambiguation-start_conversation)
                (have_user_initiative_message)
                (not
                    (maybe-have_user_initiative_message)
                )
                (user_initiative)
            )
        :effect
            (labeled-oneof resolve-start_conversation
                (outcome start_conversation_what__
                    (and
                        (have_user_initiative_message)
                        (not
                            (maybe-have_user_initiative_message)
                        )
                        (STARTED)
                        (can-do_dialogue-disambiguation-start_conversation)
                        (can-do_dialogue-disambiguation-ask-for_oil-level)
                        (can-do_dialogue-disambiguation-ask-for_clutch-seal-tightness)
                        (can-do_dialogue-disambiguation-ask-for_break-pad)
                        (can-do_dialogue-disambiguation-ask-for_spark-plug)
                        (can-do_dialogue-disambiguation-end_conversation)
                        (can-do_dialogue-disambiguation-state-message)
                    )
                )
                (outcome start_conversation_initiative-switch__
                    (and
                        (not
                            (user_initiative)
                        )
                        (STARTED)
                        (can-do_dialogue-disambiguation-start_conversation)
                        (can-do_dialogue-disambiguation-ask-for_oil-level)
                        (can-do_dialogue-disambiguation-ask-for_clutch-seal-tightness)
                        (can-do_dialogue-disambiguation-ask-for_break-pad)
                        (can-do_dialogue-disambiguation-ask-for_spark-plug)
                        (can-do_dialogue-disambiguation-end_conversation)
                        (can-do_dialogue-disambiguation-state-message)
                    )
                )
                (outcome start_conversation_break-pad__check-pass_status_options-eq-found
                    (and
                        (have_pass_status_options)
                        (not
                            (maybe-have_pass_status_options)
                        )
                        (have_user_initiative_message)
                        (not
                            (maybe-have_user_initiative_message)
                        )
                        (have_break_pad_status)
                        (not
                            (maybe-have_break_pad_status)
                        )
                        (have_pass_status_options)
                        (not
                            (maybe-have_pass_status_options)
                        )
                        (STARTED)
                        (can-do_dialogue-disambiguation-start_conversation)
                        (can-do_dialogue-disambiguation-ask-for_oil-level)
                        (can-do_dialogue-disambiguation-ask-for_clutch-seal-tightness)
                        (can-do_dialogue-disambiguation-ask-for_break-pad)
                        (can-do_dialogue-disambiguation-ask-for_spark-plug)
                        (can-do_dialogue-disambiguation-end_conversation)
                        (can-do_dialogue-disambiguation-state-message)
                    )
                )
                (outcome start_conversation_spark-plug__check-pass_status_options-eq-found
                    (and
                        (have_pass_status_options)
                        (not
                            (maybe-have_pass_status_options)
                        )
                        (have_user_initiative_message)
                        (not
                            (maybe-have_user_initiative_message)
                        )
                        (have_spark_plug_status)
                        (not
                            (maybe-have_spark_plug_status)
                        )
                        (have_pass_status_options)
                        (not
                            (maybe-have_pass_status_options)
                        )
                        (STARTED)
                        (can-do_dialogue-disambiguation-start_conversation)
                        (can-do_dialogue-disambiguation-ask-for_oil-level)
                        (can-do_dialogue-disambiguation-ask-for_clutch-seal-tightness)
                        (can-do_dialogue-disambiguation-ask-for_break-pad)
                        (can-do_dialogue-disambiguation-ask-for_spark-plug)
                        (can-do_dialogue-disambiguation-end_conversation)
                        (can-do_dialogue-disambiguation-state-message)
                    )
                )
                (outcome start_conversation_clutch-seal-tightness__check-clutch_seal_tightness_status-eq-found
                    (and
                        (have_clutch_seal_tightness_status)
                        (not
                            (maybe-have_clutch_seal_tightness_status)
                        )
                        (have_user_initiative_message)
                        (not
                            (maybe-have_user_initiative_message)
                        )
                        (have_clutch_seal_tightness_status)
                        (not
                            (maybe-have_clutch_seal_tightness_status)
                        )
                        (STARTED)
                        (can-do_dialogue-disambiguation-start_conversation)
                        (can-do_dialogue-disambiguation-ask-for_oil-level)
                        (can-do_dialogue-disambiguation-ask-for_clutch-seal-tightness)
                        (can-do_dialogue-disambiguation-ask-for_break-pad)
                        (can-do_dialogue-disambiguation-ask-for_spark-plug)
                        (can-do_dialogue-disambiguation-end_conversation)
                        (can-do_dialogue-disambiguation-state-message)
                    )
                )
                (outcome start_conversation_oil__check-oil_status-eq-found
                    (and
                        (have_oil_status)
                        (not
                            (maybe-have_oil_status)
                        )
                        (have_user_initiative_message)
                        (not
                            (maybe-have_user_initiative_message)
                        )
                        (have_oil_status)
                        (not
                            (maybe-have_oil_status)
                        )
                        (STARTED)
                        (can-do_dialogue-disambiguation-start_conversation)
                        (can-do_dialogue-disambiguation-ask-for_oil-level)
                        (can-do_dialogue-disambiguation-ask-for_clutch-seal-tightness)
                        (can-do_dialogue-disambiguation-ask-for_break-pad)
                        (can-do_dialogue-disambiguation-ask-for_spark-plug)
                        (can-do_dialogue-disambiguation-end_conversation)
                        (can-do_dialogue-disambiguation-state-message)
                    )
                )
                (outcome start_conversation_fallback__
                    (and
                        (have_user_initiative_message)
                        (not
                            (maybe-have_user_initiative_message)
                        )
                        (STARTED)
                        (can-do_dialogue-disambiguation-start_conversation)
                        (not
                            (can-do_dialogue-disambiguation-ask-for_oil-level)
                        )
                        (not
                            (can-do_dialogue-disambiguation-ask-for_clutch-seal-tightness)
                        )
                        (not
                            (can-do_dialogue-disambiguation-ask-for_break-pad)
                        )
                        (not
                            (can-do_dialogue-disambiguation-ask-for_spark-plug)
                        )
                        (not
                            (can-do_dialogue-disambiguation-end_conversation)
                        )
                        (not
                            (can-do_dialogue-disambiguation-state-message)
                        )
                    )
                )
            )
    )
    (:action dialogue-disambiguation-ask-for_oil-level
        :parameters ()
        :precondition
            (and
                (can-do_dialogue-disambiguation-ask-for_oil-level)
                (not
                    (user_initiative)
                )
                (not
                    (have_oil_status)
                )
                (not
                    (maybe-have_oil_status)
                )
                (STARTED)
            )
        :effect
            (labeled-oneof resolve-ask-for_oil-level
                (outcome ask-for_oil-level_initiative-switch__
                    (and
                        (have_user_initiative_message)
                        (not
                            (maybe-have_user_initiative_message)
                        )
                        (user_initiative)
                        (can-do_dialogue-disambiguation-start_conversation)
                        (can-do_dialogue-disambiguation-ask-for_oil-level)
                        (can-do_dialogue-disambiguation-ask-for_clutch-seal-tightness)
                        (can-do_dialogue-disambiguation-ask-for_break-pad)
                        (can-do_dialogue-disambiguation-ask-for_spark-plug)
                        (can-do_dialogue-disambiguation-end_conversation)
                        (can-do_dialogue-disambiguation-state-message)
                    )
                )
                (outcome ask-for_oil-level_detected__check-oil_status-eq-found
                    (and
                        (have_oil_status)
                        (not
                            (maybe-have_oil_status)
                        )
                        (have_message)
                        (not
                            (maybe-have_message)
                        )
                        (have_oil_status)
                        (not
                            (maybe-have_oil_status)
                        )
                        (not
                            (can-do_dialogue-disambiguation-start_conversation)
                        )
                        (not
                            (can-do_dialogue-disambiguation-ask-for_oil-level)
                        )
                        (not
                            (can-do_dialogue-disambiguation-ask-for_clutch-seal-tightness)
                        )
                        (not
                            (can-do_dialogue-disambiguation-ask-for_break-pad)
                        )
                        (not
                            (can-do_dialogue-disambiguation-ask-for_spark-plug)
                        )
                        (not
                            (can-do_dialogue-disambiguation-end_conversation)
                        )
                        (can-do_dialogue-disambiguation-state-message)
                    )
                )
                (outcome ask-for_oil-level_help-local-options__
                    (and
                        (have_message)
                        (not
                            (maybe-have_message)
                        )
                        (not
                            (can-do_dialogue-disambiguation-start_conversation)
                        )
                        (not
                            (can-do_dialogue-disambiguation-ask-for_oil-level)
                        )
                        (not
                            (can-do_dialogue-disambiguation-ask-for_clutch-seal-tightness)
                        )
                        (not
                            (can-do_dialogue-disambiguation-ask-for_break-pad)
                        )
                        (not
                            (can-do_dialogue-disambiguation-ask-for_spark-plug)
                        )
                        (not
                            (can-do_dialogue-disambiguation-end_conversation)
                        )
                        (can-do_dialogue-disambiguation-state-message)
                    )
                )
            )
    )
    (:action dialogue-disambiguation-ask-for_clutch-seal-tightness
        :parameters ()
        :precondition
            (and
                (can-do_dialogue-disambiguation-ask-for_clutch-seal-tightness)
                (not
                    (user_initiative)
                )
                (not
                    (have_clutch_seal_tightness_status)
                )
                (not
                    (maybe-have_clutch_seal_tightness_status)
                )
                (STARTED)
            )
        :effect
            (labeled-oneof resolve-ask-for_clutch-seal-tightness
                (outcome ask-for_clutch-seal-tightness_initiative-switch__
                    (and
                        (have_user_initiative_message)
                        (not
                            (maybe-have_user_initiative_message)
                        )
                        (user_initiative)
                        (can-do_dialogue-disambiguation-start_conversation)
                        (can-do_dialogue-disambiguation-ask-for_oil-level)
                        (can-do_dialogue-disambiguation-ask-for_clutch-seal-tightness)
                        (can-do_dialogue-disambiguation-ask-for_break-pad)
                        (can-do_dialogue-disambiguation-ask-for_spark-plug)
                        (can-do_dialogue-disambiguation-end_conversation)
                        (can-do_dialogue-disambiguation-state-message)
                    )
                )
                (outcome ask-for_clutch-seal-tightness_detected__check-clutch_seal_tightness_status-eq-found
                    (and
                        (have_clutch_seal_tightness_status)
                        (not
                            (maybe-have_clutch_seal_tightness_status)
                        )
                        (have_message)
                        (not
                            (maybe-have_message)
                        )
                        (have_clutch_seal_tightness_status)
                        (not
                            (maybe-have_clutch_seal_tightness_status)
                        )
                        (not
                            (can-do_dialogue-disambiguation-start_conversation)
                        )
                        (not
                            (can-do_dialogue-disambiguation-ask-for_oil-level)
                        )
                        (not
                            (can-do_dialogue-disambiguation-ask-for_clutch-seal-tightness)
                        )
                        (not
                            (can-do_dialogue-disambiguation-ask-for_break-pad)
                        )
                        (not
                            (can-do_dialogue-disambiguation-ask-for_spark-plug)
                        )
                        (not
                            (can-do_dialogue-disambiguation-end_conversation)
                        )
                        (can-do_dialogue-disambiguation-state-message)
                    )
                )
                (outcome ask-for_clutch-seal-tightness_help-local-options__
                    (and
                        (have_message)
                        (not
                            (maybe-have_message)
                        )
                        (not
                            (can-do_dialogue-disambiguation-start_conversation)
                        )
                        (not
                            (can-do_dialogue-disambiguation-ask-for_oil-level)
                        )
                        (not
                            (can-do_dialogue-disambiguation-ask-for_clutch-seal-tightness)
                        )
                        (not
                            (can-do_dialogue-disambiguation-ask-for_break-pad)
                        )
                        (not
                            (can-do_dialogue-disambiguation-ask-for_spark-plug)
                        )
                        (not
                            (can-do_dialogue-disambiguation-end_conversation)
                        )
                        (can-do_dialogue-disambiguation-state-message)
                    )
                )
            )
    )
    (:action dialogue-disambiguation-ask-for_break-pad
        :parameters ()
        :precondition
            (and
                (can-do_dialogue-disambiguation-ask-for_break-pad)
                (not
                    (user_initiative)
                )
                (not
                    (have_break_pad_status)
                )
                (not
                    (maybe-have_break_pad_status)
                )
                (STARTED)
            )
        :effect
            (labeled-oneof resolve-ask-for_break-pad
                (outcome ask-for_break-pad_initiative-switch__
                    (and
                        (user_initiative)
                        (have_user_initiative_message)
                        (not
                            (maybe-have_user_initiative_message)
                        )
                        (can-do_dialogue-disambiguation-start_conversation)
                        (can-do_dialogue-disambiguation-ask-for_oil-level)
                        (can-do_dialogue-disambiguation-ask-for_clutch-seal-tightness)
                        (can-do_dialogue-disambiguation-ask-for_break-pad)
                        (can-do_dialogue-disambiguation-ask-for_spark-plug)
                        (can-do_dialogue-disambiguation-end_conversation)
                        (can-do_dialogue-disambiguation-state-message)
                    )
                )
                (outcome ask-for_break-pad_detected__check-pass_status_options-eq-found
                    (and
                        (have_pass_status_options)
                        (not
                            (maybe-have_pass_status_options)
                        )
                        (have_message)
                        (not
                            (maybe-have_message)
                        )
                        (have_break_pad_status)
                        (not
                            (maybe-have_break_pad_status)
                        )
                        (have_pass_status_options)
                        (not
                            (maybe-have_pass_status_options)
                        )
                        (not
                            (can-do_dialogue-disambiguation-start_conversation)
                        )
                        (not
                            (can-do_dialogue-disambiguation-ask-for_oil-level)
                        )
                        (not
                            (can-do_dialogue-disambiguation-ask-for_clutch-seal-tightness)
                        )
                        (not
                            (can-do_dialogue-disambiguation-ask-for_break-pad)
                        )
                        (not
                            (can-do_dialogue-disambiguation-ask-for_spark-plug)
                        )
                        (not
                            (can-do_dialogue-disambiguation-end_conversation)
                        )
                        (can-do_dialogue-disambiguation-state-message)
                    )
                )
                (outcome ask-for_break-pad_help-local-options__
                    (and
                        (have_message)
                        (not
                            (maybe-have_message)
                        )
                        (not
                            (can-do_dialogue-disambiguation-start_conversation)
                        )
                        (not
                            (can-do_dialogue-disambiguation-ask-for_oil-level)
                        )
                        (not
                            (can-do_dialogue-disambiguation-ask-for_clutch-seal-tightness)
                        )
                        (not
                            (can-do_dialogue-disambiguation-ask-for_break-pad)
                        )
                        (not
                            (can-do_dialogue-disambiguation-ask-for_spark-plug)
                        )
                        (not
                            (can-do_dialogue-disambiguation-end_conversation)
                        )
                        (can-do_dialogue-disambiguation-state-message)
                    )
                )
            )
    )
    (:action dialogue-disambiguation-ask-for_spark-plug
        :parameters ()
        :precondition
            (and
                (can-do_dialogue-disambiguation-ask-for_spark-plug)
                (not
                    (user_initiative)
                )
                (not
                    (have_spark_plug_status)
                )
                (not
                    (maybe-have_spark_plug_status)
                )
                (STARTED)
            )
        :effect
            (labeled-oneof resolve-ask-for_spark-plug
                (outcome ask-for_spark-plug_initiative-switch__
                    (and
                        (have_user_initiative_message)
                        (not
                            (maybe-have_user_initiative_message)
                        )
                        (user_initiative)
                        (can-do_dialogue-disambiguation-start_conversation)
                        (can-do_dialogue-disambiguation-ask-for_oil-level)
                        (can-do_dialogue-disambiguation-ask-for_clutch-seal-tightness)
                        (can-do_dialogue-disambiguation-ask-for_break-pad)
                        (can-do_dialogue-disambiguation-ask-for_spark-plug)
                        (can-do_dialogue-disambiguation-end_conversation)
                        (can-do_dialogue-disambiguation-state-message)
                    )
                )
                (outcome ask-for_spark-plug_detected__check-pass_status_options-eq-found
                    (and
                        (have_pass_status_options)
                        (not
                            (maybe-have_pass_status_options)
                        )
                        (have_message)
                        (not
                            (maybe-have_message)
                        )
                        (have_spark_plug_status)
                        (not
                            (maybe-have_spark_plug_status)
                        )
                        (have_pass_status_options)
                        (not
                            (maybe-have_pass_status_options)
                        )
                        (not
                            (can-do_dialogue-disambiguation-start_conversation)
                        )
                        (not
                            (can-do_dialogue-disambiguation-ask-for_oil-level)
                        )
                        (not
                            (can-do_dialogue-disambiguation-ask-for_clutch-seal-tightness)
                        )
                        (not
                            (can-do_dialogue-disambiguation-ask-for_break-pad)
                        )
                        (not
                            (can-do_dialogue-disambiguation-ask-for_spark-plug)
                        )
                        (not
                            (can-do_dialogue-disambiguation-end_conversation)
                        )
                        (can-do_dialogue-disambiguation-state-message)
                    )
                )
                (outcome ask-for_spark-plug_help-local-options__
                    (and
                        (have_message)
                        (not
                            (maybe-have_message)
                        )
                        (not
                            (can-do_dialogue-disambiguation-start_conversation)
                        )
                        (not
                            (can-do_dialogue-disambiguation-ask-for_oil-level)
                        )
                        (not
                            (can-do_dialogue-disambiguation-ask-for_clutch-seal-tightness)
                        )
                        (not
                            (can-do_dialogue-disambiguation-ask-for_break-pad)
                        )
                        (not
                            (can-do_dialogue-disambiguation-ask-for_spark-plug)
                        )
                        (not
                            (can-do_dialogue-disambiguation-end_conversation)
                        )
                        (can-do_dialogue-disambiguation-state-message)
                    )
                )
            )
    )
    (:action dialogue-disambiguation-end_conversation
        :parameters ()
        :precondition
            (and
                (can-do_dialogue-disambiguation-end_conversation)
                (have_oil_status)
                (not
                    (maybe-have_oil_status)
                )
                (have_clutch_seal_tightness_status)
                (not
                    (maybe-have_clutch_seal_tightness_status)
                )
                (have_break_pad_status)
                (not
                    (maybe-have_break_pad_status)
                )
                (have_spark_plug_status)
                (not
                    (maybe-have_spark_plug_status)
                )
                (STARTED)
            )
        :effect
            (labeled-oneof resolve-end_conversation
                (outcome end_conversation-outcome-fallback__
                    (and
                        (GOAL)
                        (can-do_dialogue-disambiguation-start_conversation)
                        (can-do_dialogue-disambiguation-ask-for_oil-level)
                        (can-do_dialogue-disambiguation-ask-for_clutch-seal-tightness)
                        (can-do_dialogue-disambiguation-ask-for_break-pad)
                        (can-do_dialogue-disambiguation-ask-for_spark-plug)
                        (can-do_dialogue-disambiguation-end_conversation)
                        (can-do_dialogue-disambiguation-state-message)
                    )
                )
            )
    )
    (:action dialogue-disambiguation-state-message
        :parameters ()
        :precondition
            (and
                (can-do_dialogue-disambiguation-state-message)
                (have_message)
                (not
                    (maybe-have_message)
                )
                (STARTED)
            )
        :effect
            (labeled-oneof resolve-state-message
                (outcome state-message-outcome-fallback__
                    (and
                        (not
                            (have_message)
                        )
                        (not
                            (maybe-have_message)
                        )
                        (can-do_dialogue-disambiguation-start_conversation)
                        (can-do_dialogue-disambiguation-ask-for_oil-level)
                        (can-do_dialogue-disambiguation-ask-for_clutch-seal-tightness)
                        (can-do_dialogue-disambiguation-ask-for_break-pad)
                        (can-do_dialogue-disambiguation-ask-for_spark-plug)
                        (can-do_dialogue-disambiguation-end_conversation)
                        (can-do_dialogue-disambiguation-state-message)
                    )
                )
            )
    )
)
