
git update-index --assume-unchanged packs_sys/logicmoo_nlu/ext/pldata/ac_xnl
git update-index --assume-unchanged packs_sys/logicmoo_nlu/ext/pldata/plkb0988
git update-index --assume-unchanged packs_sys/logicmoo_ec/prolog/ec_planner/hist/ec_planner_current.pl
git update-index --assume-unchanged bin
git update-index --assume-unchanged lib
git update-index --assume-unchanged packs_web/logicmoo_webui/etc
git update-index --assume-unchanged packs_web/swish/examples/lps_corner
git update-index --assume-unchanged packs_web/swish/examples/pfc
git update-index --assume-unchanged packs_web/swish/web/node_modules/.bin/semver
git update-index --assume-unchanged packs_web/swish/web/node_modules/.bin/esparse
git update-index --assume-unchanged packs_web/swish/web/node_modules/.bin/html-beautify
git update-index --assume-unchanged packs_web/swish/web/node_modules/.bin/json2dsv
git update-index --assume-unchanged packs_web/swish/web/node_modules/.bin/editorconfig
git update-index --assume-unchanged packs_web/swish/web/node_modules/.bin/eslint
git update-index --assume-unchanged packs_web/swish/web/node_modules/.bin/nopt
git update-index --assume-unchanged packs_web/swish/web/node_modules/.bin/json2csv
git update-index --assume-unchanged packs_web/swish/web/node_modules/.bin/prettier
git update-index --assume-unchanged packs_web/swish/web/node_modules/.bin/opencollective-postinstall
git update-index --assume-unchanged packs_web/swish/web/node_modules/.bin/sparkline
git update-index --assume-unchanged packs_web/swish/web/node_modules/.bin/csv2json
git update-index --assume-unchanged packs_web/swish/web/node_modules/.bin/dsv2json
git update-index --assume-unchanged packs_web/swish/web/node_modules/.bin/json5
git update-index --assume-unchanged packs_web/swish/web/node_modules/.bin/ace
git update-index --assume-unchanged packs_web/swish/web/node_modules/.bin/json2tsv
git update-index --assume-unchanged packs_web/swish/web/node_modules/.bin/dsv2dsv
git update-index --assume-unchanged packs_web/swish/web/node_modules/.bin/tsv2csv
git update-index --assume-unchanged packs_web/swish/web/node_modules/.bin/css-beautify
git update-index --assume-unchanged packs_web/swish/web/node_modules/.bin/mkdirp
git update-index --assume-unchanged packs_web/swish/web/node_modules/.bin/gunzip-maybe
git update-index --assume-unchanged packs_web/swish/web/node_modules/.bin/uuid
git update-index --assume-unchanged packs_web/swish/web/node_modules/.bin/csv2tsv
git update-index --assume-unchanged packs_web/swish/web/node_modules/.bin/r.js
git update-index --assume-unchanged packs_web/swish/web/node_modules/.bin/acorn
git update-index --assume-unchanged packs_web/swish/web/node_modules/.bin/js-beautify
git update-index --assume-unchanged packs_web/swish/web/node_modules/.bin/rimraf
git update-index --assume-unchanged packs_web/swish/web/node_modules/.bin/js-yaml
git update-index --assume-unchanged packs_web/swish/web/node_modules/.bin/rc
git update-index --assume-unchanged packs_web/swish/web/node_modules/.bin/unibeautify
git update-index --assume-unchanged packs_web/swish/web/node_modules/.bin/r_js
git update-index --assume-unchanged packs_web/swish/web/node_modules/.bin/node-which
git update-index --assume-unchanged packs_web/swish/web/node_modules/.bin/tsv2json
git update-index --assume-unchanged packs_web/swish/web/node_modules/.bin/esvalidate
git update-index --assume-unchanged packs_web/swish/web/node_modules/editorconfig/node_modules/.bin/semver
git update-index --assume-unchanged packs_web/swish/web/node_modules/eslint/node_modules/.bin/semver
git update-index --assume-unchanged packs_web/swish/web/node_modules/eslint/node_modules/.bin/js-yaml
git update-index --assume-unchanged packs_web/swish/web/node_modules/eslint/node_modules/cross-spawn/node_modules/.bin/node-which
git update-index --assume-unchanged packs_web/swish/web/node_modules/espree/node_modules/.bin/acorn
git update-index --assume-unchanged packs_web/swish/web/node_modules/requireg/node_modules/.bin/rc
git update-index --assume-unchanged packs_web/swish/web/node_modules/request/node_modules/.bin/uuid
git update-index --assume-unchanged packs_web/swish/web/node_modules/sparkline/node_modules/.bin/nopt
git update-index --assume-unchanged packs_web/swish/web/node_modules/normalize-package-data/node_modules/.bin/semver
git update-index --assume-unchanged packs_web/swish/web/node_modules/init-package-json/node_modules/.bin/semver
git update-index --assume-unchanged packs_web/swish/web/node_modules/init-package-json/node_modules/npm-package-arg/node_modules/.bin/semver
git update-index --assume-unchanged packs_web/swish/web/node_modules/ts-node/node_modules/.bin/mkdirp
git update-index --assume-unchanged packs_web/swish/web/node_modules/flat-cache/node_modules/.bin/rimraf
git update-index --assume-unchanged packs_web/swish/web/node_modules/ace/node_modules/.bin/semver
git update-index --assume-unchanged packs_web/swish/web/node_modules/ace/node_modules/.bin/gunzip-maybe
git update-index --assume-unchanged packs_web/swish/web/node_modules/ace/node_modules/.bin/uuid
git update-index --assume-unchanged packs_web/swish/web/node_modules/mkdirp-then/node_modules/.bin/mkdirp
git update-index --assume-unchanged packs_web/swish/web/node_modules/unibeautify-cli/node_modules/unibeautify/node_modules/.bin/semver
git update-index --assume-unchanged packs_web/swish/web/node_modules/http-signature/node_modules/.bin/sshpk-conv
git update-index --assume-unchanged packs_web/swish/web/node_modules/http-signature/node_modules/.bin/sshpk-sign
git update-index --assume-unchanged packs_web/swish/web/node_modules/http-signature/node_modules/.bin/sshpk-verify
git update-index --assume-unchanged packs_web/swish/web/node_modules/npm-package-arg/node_modules/.bin/semver
git update-index --assume-unchanged packs_web/swish/web/node_modules/loader-utils/node_modules/.bin/json5
git update-index --assume-unchanged packs_web/swish/web/node_modules/@eslint/eslintrc/node_modules/.bin/js-yaml
git update-index --assume-unchanged packs_web/swish/web/node_modules/fs-extra/node_modules/.bin/rimraf
git update-index --assume-unchanged packs_web/swish/web/node_modules/acorn-jsx/node_modules/.bin/acorn
git update-index --assume-unchanged packs_web/swish/web/node_modules/d3-fetch/node_modules/.bin/json2dsv
git update-index --assume-unchanged packs_web/swish/web/node_modules/d3-fetch/node_modules/.bin/json2csv
git update-index --assume-unchanged packs_web/swish/web/node_modules/d3-fetch/node_modules/.bin/csv2json
git update-index --assume-unchanged packs_web/swish/web/node_modules/d3-fetch/node_modules/.bin/dsv2json
git update-index --assume-unchanged packs_web/swish/web/node_modules/d3-fetch/node_modules/.bin/json2tsv
git update-index --assume-unchanged packs_web/swish/web/node_modules/d3-fetch/node_modules/.bin/dsv2dsv
git update-index --assume-unchanged packs_web/swish/web/node_modules/d3-fetch/node_modules/.bin/tsv2csv
git update-index --assume-unchanged packs_web/swish/web/node_modules/d3-fetch/node_modules/.bin/csv2tsv
git update-index --assume-unchanged packs_web/swish/web/node_modules/d3-fetch/node_modules/.bin/tsv2json
git update-index --assume-unchanged packs_web/swish/web/node_modules/jsclass-serializer/node_modules/.bin/uuid
git update-index --assume-unchanged packs_web/swish/web/node_modules/js-beautify/node_modules/.bin/editorconfig
git update-index --assume-unchanged packs_web/swish/web/node_modules/js-beautify/node_modules/.bin/nopt
git update-index --assume-unchanged packs_web/swish/web/node_modules/agent-base/node_modules/.bin/semver
git update-index --assume-unchanged packs_web/swish/web/node_modules/js-yaml/node_modules/.bin/esparse
git update-index --assume-unchanged packs_web/swish/web/node_modules/js-yaml/node_modules/.bin/esvalidate
git update-index --assume-unchanged packs_web/swish/web/node_modules/d3/node_modules/.bin/json2dsv
git update-index --assume-unchanged packs_web/swish/web/node_modules/d3/node_modules/.bin/json2csv
git update-index --assume-unchanged packs_web/swish/web/node_modules/d3/node_modules/.bin/csv2json
git update-index --assume-unchanged packs_web/swish/web/node_modules/d3/node_modules/.bin/dsv2json
git update-index --assume-unchanged packs_web/swish/web/node_modules/d3/node_modules/.bin/json2tsv
git update-index --assume-unchanged packs_web/swish/web/node_modules/d3/node_modules/.bin/dsv2dsv
git update-index --assume-unchanged packs_web/swish/web/node_modules/d3/node_modules/.bin/tsv2csv
git update-index --assume-unchanged packs_web/swish/web/node_modules/d3/node_modules/.bin/csv2tsv
git update-index --assume-unchanged packs_web/swish/web/node_modules/d3/node_modules/.bin/tsv2json
git update-index --assume-unchanged packs_web/swish/web/node_modules/unibeautify/node_modules/.bin/semver
git update-index --assume-unchanged packs_web/swish/web/node_modules/unibeautify/node_modules/requireg/node_modules/.bin/rc
git update-index --assume-unchanged packs_web/swish/web/node_modules/find-global-packages/node_modules/.bin/which
git update-index --assume-unchanged packs_web/swish/web/node_modules/c3/node_modules/d3-fetch/node_modules/.bin/json2dsv
git update-index --assume-unchanged packs_web/swish/web/node_modules/c3/node_modules/d3-fetch/node_modules/.bin/json2csv
git update-index --assume-unchanged packs_web/swish/web/node_modules/c3/node_modules/d3-fetch/node_modules/.bin/csv2json
git update-index --assume-unchanged packs_web/swish/web/node_modules/c3/node_modules/d3-fetch/node_modules/.bin/dsv2json
git update-index --assume-unchanged packs_web/swish/web/node_modules/c3/node_modules/d3-fetch/node_modules/.bin/json2tsv
git update-index --assume-unchanged packs_web/swish/web/node_modules/c3/node_modules/d3-fetch/node_modules/.bin/dsv2dsv
git update-index --assume-unchanged packs_web/swish/web/node_modules/c3/node_modules/d3-fetch/node_modules/.bin/tsv2csv
git update-index --assume-unchanged packs_web/swish/web/node_modules/c3/node_modules/d3-fetch/node_modules/.bin/csv2tsv
git update-index --assume-unchanged packs_web/swish/web/node_modules/c3/node_modules/d3-fetch/node_modules/.bin/tsv2json
git update-index --assume-unchanged packs_web/swish/web/node_modules/c3/node_modules/d3/node_modules/.bin/json2dsv
git update-index --assume-unchanged packs_web/swish/web/node_modules/c3/node_modules/d3/node_modules/.bin/json2csv
git update-index --assume-unchanged packs_web/swish/web/node_modules/c3/node_modules/d3/node_modules/.bin/csv2json
git update-index --assume-unchanged packs_web/swish/web/node_modules/c3/node_modules/d3/node_modules/.bin/dsv2json
git update-index --assume-unchanged packs_web/swish/web/node_modules/c3/node_modules/d3/node_modules/.bin/json2tsv
git update-index --assume-unchanged packs_web/swish/web/node_modules/c3/node_modules/d3/node_modules/.bin/dsv2dsv
git update-index --assume-unchanged packs_web/swish/web/node_modules/c3/node_modules/d3/node_modules/.bin/tsv2csv
git update-index --assume-unchanged packs_web/swish/web/node_modules/c3/node_modules/d3/node_modules/.bin/csv2tsv
git update-index --assume-unchanged packs_web/swish/web/node_modules/c3/node_modules/d3/node_modules/.bin/tsv2json
git update-index --assume-unchanged packs_web/swish/web/node_modules/@unibeautify/beautifier-js-beautify/node_modules/.bin/html-beautify
git update-index --assume-unchanged packs_web/swish/web/node_modules/@unibeautify/beautifier-js-beautify/node_modules/.bin/css-beautify
git update-index --assume-unchanged packs_web/swish/web/node_modules/@unibeautify/beautifier-js-beautify/node_modules/.bin/js-beautify
git update-index --assume-unchanged packs_web/swish/web/node_modules/cross-spawn/node_modules/.bin/semver
git update-index --assume-unchanged packs_web/swish/web/node_modules/cross-spawn/node_modules/.bin/which
git update-index --assume-unchanged packs_web/swish/web/node_modules/fstream/node_modules/.bin/mkdirp
git update-index --assume-unchanged packs_web/swish/web/node_modules/fstream/node_modules/.bin/rimraf
git update-index --assume-unchanged packs_web/butterfly/scripts/b
git update-index --assume-unchanged packs_web/butterfly/lib64
git update-index --assume-unchanged packs_web/butterfly/bin/python
git update-index --assume-unchanged packs_web/butterfly/bin/python3
git update-index --assume-unchanged packs_web/butterfly/butterfly/static/main.min.js
git update-index --assume-unchanged packs_web/butterfly/butterfly/static/ext.min.js
git update-index --assume-unchanged packs_lib/cplint_r/doc/example_out.eps
git update-index --assume-unchanged packs_lib/bddem/cudd-3.0.0/cudd/.libs/libcudd.la
git update-index --assume-unchanged packs_lib/bddem/cudd-3.0.0/dddmp/.libs/libdddmp.la
git update-index --assume-unchanged packs_lib/bddem/cudd-3.0.0/cplusplus/.libs/libobj.la
git update-index --assume-unchanged docker/rootfs/usr/local/bin/swipl
git update-index --assume-unchanged docker/rootfs/usr/local/bin/swipl-ld
git update-index --assume-unchanged docker/rootfs/usr/local/bin/mkcert
git update-index --assume-unchanged docker/rootfs/usr/local/bin/swipl-prologmud
git update-index --assume-unchanged docker/rootfs/usr/local/bin/swipl-win
git update-index --assume-unchanged docker/rootfs/usr/local/lib/libswipl.so
git update-index --assume-unchanged docker/rootfs/usr/local/lib/libswipl.so.8
git update-index --assume-unchanged docker/rootfs/usr/local/lib/swipl/lib/amd64
git update-index --assume-unchanged docker/rootfs/usr/local/lib/swipl/lib/x86_64-linux/libswipl.so
git update-index --assume-unchanged docker/rootfs/usr/local/lib/swipl/lib/x86_64-linux/libswipl.so.8
git update-index --assume-unchanged docker/rootfs/var/www/html/ef/vendor
git update-index --assume-unchanged docker/rootfs/var/www/html/ef/php/vendor/google
git update-index --assume-unchanged docker/rootfs/var/www/html/hMUD
git update-index --assume-unchanged docker/rootfs/etc/letsencrypt/live/logicmoo.org-0002
git update-index --assume-unchanged docker/rootfs/etc/letsencrypt/live/logicmoo.org-0001
git update-index --assume-unchanged share

cd prologmud_server
git update-index --assume-unchanged completion_4001
git update-index --assume-unchanged __ontologyportal_sumo_Merge_kif.tmp
git update-index --assume-unchanged completion_4023
git update-index --assume-unchanged RDF-store
git update-index --assume-unchanged history_4001
git update-index --assume-unchanged data
git update-index --assume-unchanged completion_4004
git update-index --assume-unchanged openid.db
git update-index --assume-unchanged settings.db
git update-index --assume-unchanged history_4000
git update-index --assume-unchanged history_4003
git update-index --assume-unchanged history_4002
git update-index --assume-unchanged cache
git update-index --assume-unchanged completion_4002
git update-index --assume-unchanged .platformio/penv/lib64
git update-index --assume-unchanged .platformio/penv/bin/python
git update-index --assume-unchanged .platformio/penv/bin/python3
git update-index --assume-unchanged .platformio/penv/bin/python3.9
git update-index --assume-unchanged eclipse-workspace/AceWiki/gf_webxml.ent
git update-index --assume-unchanged eclipse-workspace/AceWiki/ape.exe
git update-index --assume-unchanged eclipse-workspace/AceWiki/war/WEB-INF/data
git update-index --assume-unchanged eclipse-workspace/AceWiki/war/WEB-INF/ape.exe
git update-index --assume-unchanged completion_4003
git update-index --assume-unchanged log
git update-index --assume-unchanged .config/pulse/99361aa4c52847c2a2c7bc1d9461f0f0-runtime
git update-index --assume-unchanged history_4025
git update-index --assume-unchanged pack
git update-index --assume-unchanged completion_4000
git update-index --assume-unchanged completion_4025
git update-index --assume-unchanged robots.txt
git update-index --assume-unchanged .local/share/swi-prolog/pack/xtools
git update-index --assume-unchanged .local/share/swi-prolog/pack/logicmoo_e2c.vpwhist
git update-index --assume-unchanged .local/share/swi-prolog/pack/genutils
git update-index --assume-unchanged .local/share/swi-prolog/pack/logicmoo_nlu
git update-index --assume-unchanged .local/share/swi-prolog/pack/slack_prolog
git update-index --assume-unchanged .local/share/swi-prolog/pack/regex
git update-index --assume-unchanged .local/share/swi-prolog/pack/logicmoo_ec
git update-index --assume-unchanged .local/share/swi-prolog/pack/matrix
git update-index --assume-unchanged .local/share/swi-prolog/pack/logicmoo_base
git update-index --assume-unchanged .local/share/swi-prolog/pack/prologmud_samples
git update-index --assume-unchanged .local/share/swi-prolog/pack/phil
git update-index --assume-unchanged .local/share/swi-prolog/pack/logicmoo_webui
git update-index --assume-unchanged .local/share/swi-prolog/pack/sldnfdraw
git update-index --assume-unchanged .local/share/swi-prolog/pack/swish
git update-index --assume-unchanged .local/share/swi-prolog/pack/predicate_streams
git update-index --assume-unchanged .local/share/swi-prolog/pack/trill
git update-index --assume-unchanged .local/share/swi-prolog/pack/butterfly
git update-index --assume-unchanged .local/share/swi-prolog/pack/cplint_r
git update-index --assume-unchanged .local/share/swi-prolog/pack/logicmoo_utils
git update-index --assume-unchanged .local/share/swi-prolog/pack/instant_prolog_docs
git update-index --assume-unchanged .local/share/swi-prolog/pack/wam_common_lisp
git update-index --assume-unchanged .local/share/swi-prolog/pack/bw_src
git update-index --assume-unchanged .local/share/swi-prolog/pack/New folder
git update-index --assume-unchanged .local/share/swi-prolog/pack/assertions
git update-index --assume-unchanged .local/share/swi-prolog/pack/MMORPG
git update-index --assume-unchanged .local/share/swi-prolog/pack/typedef
git update-index --assume-unchanged .local/share/swi-prolog/pack/ClioPatria
git update-index --assume-unchanged .local/share/swi-prolog/pack/lsp_server
git update-index --assume-unchanged .local/share/swi-prolog/pack/bddem
git update-index --assume-unchanged .local/share/swi-prolog/pack/logicmoo_agi
git update-index --assume-unchanged .local/share/swi-prolog/pack/dictoo
git update-index --assume-unchanged .local/share/swi-prolog/pack/pfc
git update-index --assume-unchanged .local/share/swi-prolog/pack/eggdrop
git update-index --assume-unchanged .local/share/swi-prolog/pack/xlibrary
git update-index --assume-unchanged .local/share/swi-prolog/pack/rocksdb
git update-index --assume-unchanged .local/share/swi-prolog/pack/logicmoo_lps
git update-index --assume-unchanged .local/share/swi-prolog/pack/Downloads
git update-index --assume-unchanged .local/share/swi-prolog/pack/aleph
git update-index --assume-unchanged .local/share/swi-prolog/pack/prologmud
git update-index --assume-unchanged .local/share/swi-prolog/pack/sparqlprog
git update-index --assume-unchanged .local/share/swi-prolog/pack/rtchecks
git update-index --assume-unchanged .local/share/swi-prolog/pack/auc
git update-index --assume-unchanged .local/share/swi-prolog/pack/shrdlu
git update-index --assume-unchanged .local/share/swi-prolog/pack/mpi
git update-index --assume-unchanged .local/share/swi-prolog/pack/lambda
git update-index --assume-unchanged .local/share/swi-prolog/pack/logicmoo_nars
git update-index --assume-unchanged .local/share/swi-prolog/pack/cplint
git update-index --assume-unchanged .local/share/swi-prolog/pack/README.md
git update-index --assume-unchanged .local/share/swi-prolog/pack/dcgutils
git update-index --assume-unchanged .local/share/swi-prolog/pack/swicli
git update-index --assume-unchanged .local/share/swi-prolog/pack/logicmoo_cg
git update-index --assume-unchanged tempDir/config-enabled-swish
git update-index --assume-unchanged logtalk-scratch
git update-index --assume-unchanged history_4004
git update-index --assume-unchanged passwd
git update-index --assume-unchanged history_4023
git update-index --assume-unchanged users.db
git update-index --assume-unchanged gv.git
cd ..

