(*
    Tests for: Daniel`ARC`ARCMappingsForGeneratedObject
    
    To run these tests:
    
        << DevTools`
        << Daniel`ARC`
        RunUnitTests[Daniel`ARC`ARCMappingsForGeneratedObject]
    
    Author: danielb
*)

Test[
    Utility`ReplaceAssociationsWithUnevaluatedAssociations[
        DevTools`TestingTools`SlowTest[
            res = ERPTesting`NormalizeOutput[
                Module[
                    {parsedScene, object},
                    parsedScene = Daniel`ARC`ARCParseScene[
                        Daniel`ARC`ARCParseFile["28e73c20"]["Train", 1, "Output"]
                    ];
                    object = parsedScene[["Objects", 1]];
                    Daniel`ARC`ARCMappingsForGeneratedObject[
                        Daniel`ARC`ARCPossiblyGeneratedObjectQ[object]["Line"],
                        object["Color"],
                        Replace[
                            parsedScene["Scene"],
                            parsedScene["Background"] -> Daniel`ARC`Private`$nonImageColor,
                            {3}
                        ]
                    ]
                ]
            ]
        ]
    ]
    ,
    {
        <|
            "UUID" -> 0,
            "Position" -> {1, 1},
            "Start" -> True,
            "DistanceSinceLastTurn" -> 1,
            "TotalDistanceSoFar" -> 1
        |> -> <|
            "OutgoingDirection" -> {0, 1},
            "OutgoingDirectionY" -> 0,
            "OutgoingDirectionX" -> 1
        |>,
        <|
            "UUID" -> 0,
            "Position" -> {1, 2},
            "PreviousPosition" -> {1, 1},
            "IncomingDirection" -> {0, 1},
            "IncomingDirectionY" -> 0,
            "IncomingDirectionX" -> 1,
            "ColorAhead" -> -1,
            "ColorAheadMatchesObject" -> False,
            "ColorAhead2" -> -1,
            "ColorAhead2MatchesObject" -> False,
            "ColorAhead3" -> -1,
            "ColorAhead3MatchesObject" -> False,
            "Color135Degrees" -> -1,
            "Color135DegreesMatchesObject" -> False,
            "Color90Degrees" -> -1,
            "Color90DegreesMatchesObject" -> False,
            "Color90Degrees2" -> -1,
            "Color90Degrees2MatchesObject" -> False,
            "Color45Degrees" -> -1,
            "Color45DegreesMatchesObject" -> False,
            "ColorNegative45Degrees" -> -2,
            "ColorNegative45DegreesMatchesObject" -> False,
            "ColorNegative90Degrees" -> -2,
            "ColorNegative90DegreesMatchesObject" -> False,
            "ColorNegative135Degrees" -> -2,
            "ColorNegative135DegreesMatchesObject" -> False,
            "DistanceSinceLastTurn" -> 2,
            "TotalDistanceSoFar" -> 2
        |> -> <|
            "OutgoingDirection" -> {0, 1},
            "OutgoingDirectionY" -> 0,
            "OutgoingDirectionX" -> 1,
            "TurnDegrees" -> 0
        |>,
        <|
            "UUID" -> 0,
            "Position" -> {1, 3},
            "PreviousPosition" -> {1, 2},
            "IncomingDirection" -> {0, 1},
            "IncomingDirectionY" -> 0,
            "IncomingDirectionX" -> 1,
            "PreviousIncomingDirection" -> {0, 1},
            "ColorAhead" -> -1,
            "ColorAheadMatchesObject" -> False,
            "ColorAhead2" -> -1,
            "ColorAhead2MatchesObject" -> False,
            "ColorAhead3" -> -1,
            "ColorAhead3MatchesObject" -> False,
            "Color135Degrees" -> -1,
            "Color135DegreesMatchesObject" -> False,
            "Color90Degrees" -> -1,
            "Color90DegreesMatchesObject" -> False,
            "Color90Degrees2" -> -1,
            "Color90Degrees2MatchesObject" -> False,
            "Color45Degrees" -> -1,
            "Color45DegreesMatchesObject" -> False,
            "ColorNegative45Degrees" -> -2,
            "ColorNegative45DegreesMatchesObject" -> False,
            "ColorNegative90Degrees" -> -2,
            "ColorNegative90DegreesMatchesObject" -> False,
            "ColorNegative135Degrees" -> -2,
            "ColorNegative135DegreesMatchesObject" -> False,
            "DistanceSinceLastTurn" -> 3,
            "TotalDistanceSoFar" -> 3
        |> -> <|
            "OutgoingDirection" -> {0, 1},
            "OutgoingDirectionY" -> 0,
            "OutgoingDirectionX" -> 1,
            "TurnDegrees" -> 0
        |>,
        <|
            "UUID" -> 0,
            "Position" -> {1, 4},
            "PreviousPosition" -> {1, 3},
            "IncomingDirection" -> {0, 1},
            "IncomingDirectionY" -> 0,
            "IncomingDirectionX" -> 1,
            "PreviousIncomingDirection" -> {0, 1},
            "ColorAhead" -> -1,
            "ColorAheadMatchesObject" -> False,
            "ColorAhead2" -> -1,
            "ColorAhead2MatchesObject" -> False,
            "ColorAhead3" -> -2,
            "ColorAhead3MatchesObject" -> False,
            "Color135Degrees" -> -1,
            "Color135DegreesMatchesObject" -> False,
            "Color90Degrees" -> -1,
            "Color90DegreesMatchesObject" -> False,
            "Color90Degrees2" -> -1,
            "Color90Degrees2MatchesObject" -> False,
            "Color45Degrees" -> -1,
            "Color45DegreesMatchesObject" -> False,
            "ColorNegative45Degrees" -> -2,
            "ColorNegative45DegreesMatchesObject" -> False,
            "ColorNegative90Degrees" -> -2,
            "ColorNegative90DegreesMatchesObject" -> False,
            "ColorNegative135Degrees" -> -2,
            "ColorNegative135DegreesMatchesObject" -> False,
            "DistanceSinceLastTurn" -> 4,
            "TotalDistanceSoFar" -> 4
        |> -> <|
            "OutgoingDirection" -> {0, 1},
            "OutgoingDirectionY" -> 0,
            "OutgoingDirectionX" -> 1,
            "TurnDegrees" -> 0
        |>,
        <|
            "UUID" -> 0,
            "Position" -> {1, 5},
            "PreviousPosition" -> {1, 4},
            "IncomingDirection" -> {0, 1},
            "IncomingDirectionY" -> 0,
            "IncomingDirectionX" -> 1,
            "PreviousIncomingDirection" -> {0, 1},
            "ColorAhead" -> -1,
            "ColorAheadMatchesObject" -> False,
            "ColorAhead2" -> -2,
            "ColorAhead2MatchesObject" -> False,
            "ColorAhead3" -> -2,
            "ColorAhead3MatchesObject" -> False,
            "Color135Degrees" -> -1,
            "Color135DegreesMatchesObject" -> False,
            "Color90Degrees" -> -1,
            "Color90DegreesMatchesObject" -> False,
            "Color90Degrees2" -> -1,
            "Color90Degrees2MatchesObject" -> False,
            "Color45Degrees" -> -1,
            "Color45DegreesMatchesObject" -> False,
            "ColorNegative45Degrees" -> -2,
            "ColorNegative45DegreesMatchesObject" -> False,
            "ColorNegative90Degrees" -> -2,
            "ColorNegative90DegreesMatchesObject" -> False,
            "ColorNegative135Degrees" -> -2,
            "ColorNegative135DegreesMatchesObject" -> False,
            "DistanceSinceLastTurn" -> 5,
            "TotalDistanceSoFar" -> 5
        |> -> <|
            "OutgoingDirection" -> {0, 1},
            "OutgoingDirectionY" -> 0,
            "OutgoingDirectionX" -> 1,
            "TurnDegrees" -> 0
        |>,
        <|
            "UUID" -> 0,
            "Position" -> {1, 6},
            "PreviousPosition" -> {1, 5},
            "IncomingDirection" -> {0, 1},
            "IncomingDirectionY" -> 0,
            "IncomingDirectionX" -> 1,
            "PreviousIncomingDirection" -> {0, 1},
            "ColorAhead" -> -2,
            "ColorAheadMatchesObject" -> False,
            "ColorAhead2" -> -2,
            "ColorAhead2MatchesObject" -> False,
            "ColorAhead3" -> -2,
            "ColorAhead3MatchesObject" -> False,
            "Color135Degrees" -> -1,
            "Color135DegreesMatchesObject" -> False,
            "Color90Degrees" -> -1,
            "Color90DegreesMatchesObject" -> False,
            "Color90Degrees2" -> -1,
            "Color90Degrees2MatchesObject" -> False,
            "Color45Degrees" -> -2,
            "Color45DegreesMatchesObject" -> False,
            "ColorNegative45Degrees" -> -2,
            "ColorNegative45DegreesMatchesObject" -> False,
            "ColorNegative90Degrees" -> -2,
            "ColorNegative90DegreesMatchesObject" -> False,
            "ColorNegative135Degrees" -> -2,
            "ColorNegative135DegreesMatchesObject" -> False,
            "DistanceSinceLastTurn" -> 6,
            "TotalDistanceSoFar" -> 6
        |> -> <|
            "OutgoingDirection" -> {1, 0},
            "OutgoingDirectionY" -> 1,
            "OutgoingDirectionX" -> 0,
            "TurnDegrees" -> 90
        |>,
        <|
            "UUID" -> 0,
            "Position" -> {2, 6},
            "PreviousPosition" -> {1, 6},
            "IncomingDirection" -> {1, 0},
            "IncomingDirectionY" -> 1,
            "IncomingDirectionX" -> 0,
            "PreviousIncomingDirection" -> {0, 1},
            "ColorAhead" -> -1,
            "ColorAheadMatchesObject" -> False,
            "ColorAhead2" -> -1,
            "ColorAhead2MatchesObject" -> False,
            "ColorAhead3" -> -1,
            "ColorAhead3MatchesObject" -> False,
            "Color135Degrees" -> 3,
            "Color135DegreesMatchesObject" -> True,
            "Color90Degrees" -> -1,
            "Color90DegreesMatchesObject" -> False,
            "Color90Degrees2" -> -1,
            "Color90Degrees2MatchesObject" -> False,
            "Color45Degrees" -> -1,
            "Color45DegreesMatchesObject" -> False,
            "ColorNegative45Degrees" -> -2,
            "ColorNegative45DegreesMatchesObject" -> False,
            "ColorNegative90Degrees" -> -2,
            "ColorNegative90DegreesMatchesObject" -> False,
            "ColorNegative135Degrees" -> -2,
            "ColorNegative135DegreesMatchesObject" -> False,
            "DistanceSinceLastTurn" -> 2,
            "TotalDistanceSoFar" -> 7
        |> -> <|
            "OutgoingDirection" -> {1, 0},
            "OutgoingDirectionY" -> 1,
            "OutgoingDirectionX" -> 0,
            "TurnDegrees" -> 0
        |>,
        <|
            "UUID" -> 0,
            "Position" -> {3, 6},
            "PreviousPosition" -> {2, 6},
            "IncomingDirection" -> {1, 0},
            "IncomingDirectionY" -> 1,
            "IncomingDirectionX" -> 0,
            "PreviousIncomingDirection" -> {1, 0},
            "ColorAhead" -> -1,
            "ColorAheadMatchesObject" -> False,
            "ColorAhead2" -> -1,
            "ColorAhead2MatchesObject" -> False,
            "ColorAhead3" -> -1,
            "ColorAhead3MatchesObject" -> False,
            "Color135Degrees" -> -1,
            "Color135DegreesMatchesObject" -> False,
            "Color90Degrees" -> -1,
            "Color90DegreesMatchesObject" -> False,
            "Color90Degrees2" -> -1,
            "Color90Degrees2MatchesObject" -> False,
            "Color45Degrees" -> -1,
            "Color45DegreesMatchesObject" -> False,
            "ColorNegative45Degrees" -> -2,
            "ColorNegative45DegreesMatchesObject" -> False,
            "ColorNegative90Degrees" -> -2,
            "ColorNegative90DegreesMatchesObject" -> False,
            "ColorNegative135Degrees" -> -2,
            "ColorNegative135DegreesMatchesObject" -> False,
            "DistanceSinceLastTurn" -> 3,
            "TotalDistanceSoFar" -> 8
        |> -> <|
            "OutgoingDirection" -> {1, 0},
            "OutgoingDirectionY" -> 1,
            "OutgoingDirectionX" -> 0,
            "TurnDegrees" -> 0
        |>,
        <|
            "UUID" -> 0,
            "Position" -> {4, 6},
            "PreviousPosition" -> {3, 6},
            "IncomingDirection" -> {1, 0},
            "IncomingDirectionY" -> 1,
            "IncomingDirectionX" -> 0,
            "PreviousIncomingDirection" -> {1, 0},
            "ColorAhead" -> -1,
            "ColorAheadMatchesObject" -> False,
            "ColorAhead2" -> -1,
            "ColorAhead2MatchesObject" -> False,
            "ColorAhead3" -> -2,
            "ColorAhead3MatchesObject" -> False,
            "Color135Degrees" -> -1,
            "Color135DegreesMatchesObject" -> False,
            "Color90Degrees" -> -1,
            "Color90DegreesMatchesObject" -> False,
            "Color90Degrees2" -> -1,
            "Color90Degrees2MatchesObject" -> False,
            "Color45Degrees" -> -1,
            "Color45DegreesMatchesObject" -> False,
            "ColorNegative45Degrees" -> -2,
            "ColorNegative45DegreesMatchesObject" -> False,
            "ColorNegative90Degrees" -> -2,
            "ColorNegative90DegreesMatchesObject" -> False,
            "ColorNegative135Degrees" -> -2,
            "ColorNegative135DegreesMatchesObject" -> False,
            "DistanceSinceLastTurn" -> 4,
            "TotalDistanceSoFar" -> 9
        |> -> <|
            "OutgoingDirection" -> {1, 0},
            "OutgoingDirectionY" -> 1,
            "OutgoingDirectionX" -> 0,
            "TurnDegrees" -> 0
        |>,
        <|
            "UUID" -> 0,
            "Position" -> {5, 6},
            "PreviousPosition" -> {4, 6},
            "IncomingDirection" -> {1, 0},
            "IncomingDirectionY" -> 1,
            "IncomingDirectionX" -> 0,
            "PreviousIncomingDirection" -> {1, 0},
            "ColorAhead" -> -1,
            "ColorAheadMatchesObject" -> False,
            "ColorAhead2" -> -2,
            "ColorAhead2MatchesObject" -> False,
            "ColorAhead3" -> -2,
            "ColorAhead3MatchesObject" -> False,
            "Color135Degrees" -> -1,
            "Color135DegreesMatchesObject" -> False,
            "Color90Degrees" -> -1,
            "Color90DegreesMatchesObject" -> False,
            "Color90Degrees2" -> -1,
            "Color90Degrees2MatchesObject" -> False,
            "Color45Degrees" -> -1,
            "Color45DegreesMatchesObject" -> False,
            "ColorNegative45Degrees" -> -2,
            "ColorNegative45DegreesMatchesObject" -> False,
            "ColorNegative90Degrees" -> -2,
            "ColorNegative90DegreesMatchesObject" -> False,
            "ColorNegative135Degrees" -> -2,
            "ColorNegative135DegreesMatchesObject" -> False,
            "DistanceSinceLastTurn" -> 5,
            "TotalDistanceSoFar" -> 10
        |> -> <|
            "OutgoingDirection" -> {1, 0},
            "OutgoingDirectionY" -> 1,
            "OutgoingDirectionX" -> 0,
            "TurnDegrees" -> 0
        |>,
        <|
            "UUID" -> 0,
            "Position" -> {6, 6},
            "PreviousPosition" -> {5, 6},
            "IncomingDirection" -> {1, 0},
            "IncomingDirectionY" -> 1,
            "IncomingDirectionX" -> 0,
            "PreviousIncomingDirection" -> {1, 0},
            "ColorAhead" -> -2,
            "ColorAheadMatchesObject" -> False,
            "ColorAhead2" -> -2,
            "ColorAhead2MatchesObject" -> False,
            "ColorAhead3" -> -2,
            "ColorAhead3MatchesObject" -> False,
            "Color135Degrees" -> -1,
            "Color135DegreesMatchesObject" -> False,
            "Color90Degrees" -> -1,
            "Color90DegreesMatchesObject" -> False,
            "Color90Degrees2" -> -1,
            "Color90Degrees2MatchesObject" -> False,
            "Color45Degrees" -> -2,
            "Color45DegreesMatchesObject" -> False,
            "ColorNegative45Degrees" -> -2,
            "ColorNegative45DegreesMatchesObject" -> False,
            "ColorNegative90Degrees" -> -2,
            "ColorNegative90DegreesMatchesObject" -> False,
            "ColorNegative135Degrees" -> -2,
            "ColorNegative135DegreesMatchesObject" -> False,
            "DistanceSinceLastTurn" -> 6,
            "TotalDistanceSoFar" -> 11
        |> -> <|
            "OutgoingDirection" -> {0, -1},
            "OutgoingDirectionY" -> 0,
            "OutgoingDirectionX" -> -1,
            "TurnDegrees" -> 90
        |>,
        <|
            "UUID" -> 0,
            "Position" -> {6, 5},
            "PreviousPosition" -> {6, 6},
            "IncomingDirection" -> {0, -1},
            "IncomingDirectionY" -> 0,
            "IncomingDirectionX" -> -1,
            "PreviousIncomingDirection" -> {1, 0},
            "ColorAhead" -> -1,
            "ColorAheadMatchesObject" -> False,
            "ColorAhead2" -> -1,
            "ColorAhead2MatchesObject" -> False,
            "ColorAhead3" -> -1,
            "ColorAhead3MatchesObject" -> False,
            "Color135Degrees" -> 3,
            "Color135DegreesMatchesObject" -> True,
            "Color90Degrees" -> -1,
            "Color90DegreesMatchesObject" -> False,
            "Color90Degrees2" -> -1,
            "Color90Degrees2MatchesObject" -> False,
            "Color45Degrees" -> -1,
            "Color45DegreesMatchesObject" -> False,
            "ColorNegative45Degrees" -> -2,
            "ColorNegative45DegreesMatchesObject" -> False,
            "ColorNegative90Degrees" -> -2,
            "ColorNegative90DegreesMatchesObject" -> False,
            "ColorNegative135Degrees" -> -2,
            "ColorNegative135DegreesMatchesObject" -> False,
            "DistanceSinceLastTurn" -> 2,
            "TotalDistanceSoFar" -> 12
        |> -> <|
            "OutgoingDirection" -> {0, -1},
            "OutgoingDirectionY" -> 0,
            "OutgoingDirectionX" -> -1,
            "TurnDegrees" -> 0
        |>,
        <|
            "UUID" -> 0,
            "Position" -> {6, 4},
            "PreviousPosition" -> {6, 5},
            "IncomingDirection" -> {0, -1},
            "IncomingDirectionY" -> 0,
            "IncomingDirectionX" -> -1,
            "PreviousIncomingDirection" -> {0, -1},
            "ColorAhead" -> -1,
            "ColorAheadMatchesObject" -> False,
            "ColorAhead2" -> -1,
            "ColorAhead2MatchesObject" -> False,
            "ColorAhead3" -> -1,
            "ColorAhead3MatchesObject" -> False,
            "Color135Degrees" -> -1,
            "Color135DegreesMatchesObject" -> False,
            "Color90Degrees" -> -1,
            "Color90DegreesMatchesObject" -> False,
            "Color90Degrees2" -> -1,
            "Color90Degrees2MatchesObject" -> False,
            "Color45Degrees" -> -1,
            "Color45DegreesMatchesObject" -> False,
            "ColorNegative45Degrees" -> -2,
            "ColorNegative45DegreesMatchesObject" -> False,
            "ColorNegative90Degrees" -> -2,
            "ColorNegative90DegreesMatchesObject" -> False,
            "ColorNegative135Degrees" -> -2,
            "ColorNegative135DegreesMatchesObject" -> False,
            "DistanceSinceLastTurn" -> 3,
            "TotalDistanceSoFar" -> 13
        |> -> <|
            "OutgoingDirection" -> {0, -1},
            "OutgoingDirectionY" -> 0,
            "OutgoingDirectionX" -> -1,
            "TurnDegrees" -> 0
        |>,
        <|
            "UUID" -> 0,
            "Position" -> {6, 3},
            "PreviousPosition" -> {6, 4},
            "IncomingDirection" -> {0, -1},
            "IncomingDirectionY" -> 0,
            "IncomingDirectionX" -> -1,
            "PreviousIncomingDirection" -> {0, -1},
            "ColorAhead" -> -1,
            "ColorAheadMatchesObject" -> False,
            "ColorAhead2" -> -1,
            "ColorAhead2MatchesObject" -> False,
            "ColorAhead3" -> -2,
            "ColorAhead3MatchesObject" -> False,
            "Color135Degrees" -> -1,
            "Color135DegreesMatchesObject" -> False,
            "Color90Degrees" -> -1,
            "Color90DegreesMatchesObject" -> False,
            "Color90Degrees2" -> -1,
            "Color90Degrees2MatchesObject" -> False,
            "Color45Degrees" -> -1,
            "Color45DegreesMatchesObject" -> False,
            "ColorNegative45Degrees" -> -2,
            "ColorNegative45DegreesMatchesObject" -> False,
            "ColorNegative90Degrees" -> -2,
            "ColorNegative90DegreesMatchesObject" -> False,
            "ColorNegative135Degrees" -> -2,
            "ColorNegative135DegreesMatchesObject" -> False,
            "DistanceSinceLastTurn" -> 4,
            "TotalDistanceSoFar" -> 14
        |> -> <|
            "OutgoingDirection" -> {0, -1},
            "OutgoingDirectionY" -> 0,
            "OutgoingDirectionX" -> -1,
            "TurnDegrees" -> 0
        |>,
        <|
            "UUID" -> 0,
            "Position" -> {6, 2},
            "PreviousPosition" -> {6, 3},
            "IncomingDirection" -> {0, -1},
            "IncomingDirectionY" -> 0,
            "IncomingDirectionX" -> -1,
            "PreviousIncomingDirection" -> {0, -1},
            "ColorAhead" -> -1,
            "ColorAheadMatchesObject" -> False,
            "ColorAhead2" -> -2,
            "ColorAhead2MatchesObject" -> False,
            "ColorAhead3" -> -2,
            "ColorAhead3MatchesObject" -> False,
            "Color135Degrees" -> -1,
            "Color135DegreesMatchesObject" -> False,
            "Color90Degrees" -> -1,
            "Color90DegreesMatchesObject" -> False,
            "Color90Degrees2" -> -1,
            "Color90Degrees2MatchesObject" -> False,
            "Color45Degrees" -> -1,
            "Color45DegreesMatchesObject" -> False,
            "ColorNegative45Degrees" -> -2,
            "ColorNegative45DegreesMatchesObject" -> False,
            "ColorNegative90Degrees" -> -2,
            "ColorNegative90DegreesMatchesObject" -> False,
            "ColorNegative135Degrees" -> -2,
            "ColorNegative135DegreesMatchesObject" -> False,
            "DistanceSinceLastTurn" -> 5,
            "TotalDistanceSoFar" -> 15
        |> -> <|
            "OutgoingDirection" -> {0, -1},
            "OutgoingDirectionY" -> 0,
            "OutgoingDirectionX" -> -1,
            "TurnDegrees" -> 0
        |>,
        <|
            "UUID" -> 0,
            "Position" -> {6, 1},
            "PreviousPosition" -> {6, 2},
            "IncomingDirection" -> {0, -1},
            "IncomingDirectionY" -> 0,
            "IncomingDirectionX" -> -1,
            "PreviousIncomingDirection" -> {0, -1},
            "ColorAhead" -> -2,
            "ColorAheadMatchesObject" -> False,
            "ColorAhead2" -> -2,
            "ColorAhead2MatchesObject" -> False,
            "ColorAhead3" -> -2,
            "ColorAhead3MatchesObject" -> False,
            "Color135Degrees" -> -1,
            "Color135DegreesMatchesObject" -> False,
            "Color90Degrees" -> -1,
            "Color90DegreesMatchesObject" -> False,
            "Color90Degrees2" -> -1,
            "Color90Degrees2MatchesObject" -> False,
            "Color45Degrees" -> -2,
            "Color45DegreesMatchesObject" -> False,
            "ColorNegative45Degrees" -> -2,
            "ColorNegative45DegreesMatchesObject" -> False,
            "ColorNegative90Degrees" -> -2,
            "ColorNegative90DegreesMatchesObject" -> False,
            "ColorNegative135Degrees" -> -2,
            "ColorNegative135DegreesMatchesObject" -> False,
            "DistanceSinceLastTurn" -> 6,
            "TotalDistanceSoFar" -> 16
        |> -> <|
            "OutgoingDirection" -> {-1, 0},
            "OutgoingDirectionY" -> -1,
            "OutgoingDirectionX" -> 0,
            "TurnDegrees" -> 90
        |>,
        <|
            "UUID" -> 0,
            "Position" -> {5, 1},
            "PreviousPosition" -> {6, 1},
            "IncomingDirection" -> {-1, 0},
            "IncomingDirectionY" -> -1,
            "IncomingDirectionX" -> 0,
            "PreviousIncomingDirection" -> {0, -1},
            "ColorAhead" -> -1,
            "ColorAheadMatchesObject" -> False,
            "ColorAhead2" -> -1,
            "ColorAhead2MatchesObject" -> False,
            "ColorAhead3" -> -1,
            "ColorAhead3MatchesObject" -> False,
            "Color135Degrees" -> 3,
            "Color135DegreesMatchesObject" -> True,
            "Color90Degrees" -> -1,
            "Color90DegreesMatchesObject" -> False,
            "Color90Degrees2" -> -1,
            "Color90Degrees2MatchesObject" -> False,
            "Color45Degrees" -> -1,
            "Color45DegreesMatchesObject" -> False,
            "ColorNegative45Degrees" -> -2,
            "ColorNegative45DegreesMatchesObject" -> False,
            "ColorNegative90Degrees" -> -2,
            "ColorNegative90DegreesMatchesObject" -> False,
            "ColorNegative135Degrees" -> -2,
            "ColorNegative135DegreesMatchesObject" -> False,
            "DistanceSinceLastTurn" -> 2,
            "TotalDistanceSoFar" -> 17
        |> -> <|
            "OutgoingDirection" -> {-1, 0},
            "OutgoingDirectionY" -> -1,
            "OutgoingDirectionX" -> 0,
            "TurnDegrees" -> 0
        |>,
        <|
            "UUID" -> 0,
            "Position" -> {4, 1},
            "PreviousPosition" -> {5, 1},
            "IncomingDirection" -> {-1, 0},
            "IncomingDirectionY" -> -1,
            "IncomingDirectionX" -> 0,
            "PreviousIncomingDirection" -> {-1, 0},
            "ColorAhead" -> -1,
            "ColorAheadMatchesObject" -> False,
            "ColorAhead2" -> -1,
            "ColorAhead2MatchesObject" -> False,
            "ColorAhead3" -> 3,
            "ColorAhead3MatchesObject" -> True,
            "Color135Degrees" -> -1,
            "Color135DegreesMatchesObject" -> False,
            "Color90Degrees" -> -1,
            "Color90DegreesMatchesObject" -> False,
            "Color90Degrees2" -> -1,
            "Color90Degrees2MatchesObject" -> False,
            "Color45Degrees" -> -1,
            "Color45DegreesMatchesObject" -> False,
            "ColorNegative45Degrees" -> -2,
            "ColorNegative45DegreesMatchesObject" -> False,
            "ColorNegative90Degrees" -> -2,
            "ColorNegative90DegreesMatchesObject" -> False,
            "ColorNegative135Degrees" -> -2,
            "ColorNegative135DegreesMatchesObject" -> False,
            "DistanceSinceLastTurn" -> 3,
            "TotalDistanceSoFar" -> 18
        |> -> <|
            "OutgoingDirection" -> {-1, 0},
            "OutgoingDirectionY" -> -1,
            "OutgoingDirectionX" -> 0,
            "TurnDegrees" -> 0
        |>,
        <|
            "UUID" -> 0,
            "Position" -> {3, 1},
            "PreviousPosition" -> {4, 1},
            "IncomingDirection" -> {-1, 0},
            "IncomingDirectionY" -> -1,
            "IncomingDirectionX" -> 0,
            "PreviousIncomingDirection" -> {-1, 0},
            "ColorAhead" -> -1,
            "ColorAheadMatchesObject" -> False,
            "ColorAhead2" -> 3,
            "ColorAhead2MatchesObject" -> True,
            "ColorAhead3" -> -2,
            "ColorAhead3MatchesObject" -> False,
            "Color135Degrees" -> -1,
            "Color135DegreesMatchesObject" -> False,
            "Color90Degrees" -> -1,
            "Color90DegreesMatchesObject" -> False,
            "Color90Degrees2" -> -1,
            "Color90Degrees2MatchesObject" -> False,
            "Color45Degrees" -> -1,
            "Color45DegreesMatchesObject" -> False,
            "ColorNegative45Degrees" -> -2,
            "ColorNegative45DegreesMatchesObject" -> False,
            "ColorNegative90Degrees" -> -2,
            "ColorNegative90DegreesMatchesObject" -> False,
            "ColorNegative135Degrees" -> -2,
            "ColorNegative135DegreesMatchesObject" -> False,
            "DistanceSinceLastTurn" -> 4,
            "TotalDistanceSoFar" -> 19
        |> -> <|
            "OutgoingDirection" -> {0, 1},
            "OutgoingDirectionY" -> 0,
            "OutgoingDirectionX" -> 1,
            "TurnDegrees" -> 90
        |>,
        <|
            "UUID" -> 0,
            "Position" -> {3, 2},
            "PreviousPosition" -> {3, 1},
            "IncomingDirection" -> {0, 1},
            "IncomingDirectionY" -> 0,
            "IncomingDirectionX" -> 1,
            "PreviousIncomingDirection" -> {-1, 0},
            "ColorAhead" -> -1,
            "ColorAheadMatchesObject" -> False,
            "ColorAhead2" -> -1,
            "ColorAhead2MatchesObject" -> False,
            "ColorAhead3" -> -1,
            "ColorAhead3MatchesObject" -> False,
            "Color135Degrees" -> 3,
            "Color135DegreesMatchesObject" -> True,
            "Color90Degrees" -> -1,
            "Color90DegreesMatchesObject" -> False,
            "Color90Degrees2" -> -1,
            "Color90Degrees2MatchesObject" -> False,
            "Color45Degrees" -> -1,
            "Color45DegreesMatchesObject" -> False,
            "ColorNegative45Degrees" -> -1,
            "ColorNegative45DegreesMatchesObject" -> False,
            "ColorNegative90Degrees" -> -1,
            "ColorNegative90DegreesMatchesObject" -> False,
            "ColorNegative135Degrees" -> -1,
            "ColorNegative135DegreesMatchesObject" -> False,
            "DistanceSinceLastTurn" -> 2,
            "TotalDistanceSoFar" -> 20
        |> -> <|
            "OutgoingDirection" -> {0, 1},
            "OutgoingDirectionY" -> 0,
            "OutgoingDirectionX" -> 1,
            "TurnDegrees" -> 0
        |>,
        <|
            "UUID" -> 0,
            "Position" -> {3, 3},
            "PreviousPosition" -> {3, 2},
            "IncomingDirection" -> {0, 1},
            "IncomingDirectionY" -> 0,
            "IncomingDirectionX" -> 1,
            "PreviousIncomingDirection" -> {0, 1},
            "ColorAhead" -> -1,
            "ColorAheadMatchesObject" -> False,
            "ColorAhead2" -> -1,
            "ColorAhead2MatchesObject" -> False,
            "ColorAhead3" -> 3,
            "ColorAhead3MatchesObject" -> True,
            "Color135Degrees" -> -1,
            "Color135DegreesMatchesObject" -> False,
            "Color90Degrees" -> -1,
            "Color90DegreesMatchesObject" -> False,
            "Color90Degrees2" -> -1,
            "Color90Degrees2MatchesObject" -> False,
            "Color45Degrees" -> -1,
            "Color45DegreesMatchesObject" -> False,
            "ColorNegative45Degrees" -> -1,
            "ColorNegative45DegreesMatchesObject" -> False,
            "ColorNegative90Degrees" -> -1,
            "ColorNegative90DegreesMatchesObject" -> False,
            "ColorNegative135Degrees" -> -1,
            "ColorNegative135DegreesMatchesObject" -> False,
            "DistanceSinceLastTurn" -> 3,
            "TotalDistanceSoFar" -> 21
        |> -> <|
            "OutgoingDirection" -> {0, 1},
            "OutgoingDirectionY" -> 0,
            "OutgoingDirectionX" -> 1,
            "TurnDegrees" -> 0
        |>,
        <|
            "UUID" -> 0,
            "Position" -> {3, 4},
            "PreviousPosition" -> {3, 3},
            "IncomingDirection" -> {0, 1},
            "IncomingDirectionY" -> 0,
            "IncomingDirectionX" -> 1,
            "PreviousIncomingDirection" -> {0, 1},
            "ColorAhead" -> -1,
            "ColorAheadMatchesObject" -> False,
            "ColorAhead2" -> 3,
            "ColorAhead2MatchesObject" -> True,
            "ColorAhead3" -> -2,
            "ColorAhead3MatchesObject" -> False,
            "Color135Degrees" -> -1,
            "Color135DegreesMatchesObject" -> False,
            "Color90Degrees" -> -1,
            "Color90DegreesMatchesObject" -> False,
            "Color90Degrees2" -> -1,
            "Color90Degrees2MatchesObject" -> False,
            "Color45Degrees" -> -1,
            "Color45DegreesMatchesObject" -> False,
            "ColorNegative45Degrees" -> -1,
            "ColorNegative45DegreesMatchesObject" -> False,
            "ColorNegative90Degrees" -> -1,
            "ColorNegative90DegreesMatchesObject" -> False,
            "ColorNegative135Degrees" -> -1,
            "ColorNegative135DegreesMatchesObject" -> False,
            "DistanceSinceLastTurn" -> 4,
            "TotalDistanceSoFar" -> 22
        |> -> <|
            "OutgoingDirection" -> {1, 0},
            "OutgoingDirectionY" -> 1,
            "OutgoingDirectionX" -> 0,
            "TurnDegrees" -> 90
        |>,
        <|
            "UUID" -> 0,
            "Position" -> {4, 4},
            "PreviousPosition" -> {3, 4},
            "IncomingDirection" -> {1, 0},
            "IncomingDirectionY" -> 1,
            "IncomingDirectionX" -> 0,
            "PreviousIncomingDirection" -> {0, 1},
            "ColorAhead" -> -1,
            "ColorAheadMatchesObject" -> False,
            "ColorAhead2" -> 3,
            "ColorAhead2MatchesObject" -> True,
            "ColorAhead3" -> -2,
            "ColorAhead3MatchesObject" -> False,
            "Color135Degrees" -> 3,
            "Color135DegreesMatchesObject" -> True,
            "Color90Degrees" -> -1,
            "Color90DegreesMatchesObject" -> False,
            "Color90Degrees2" -> -1,
            "Color90Degrees2MatchesObject" -> False,
            "Color45Degrees" -> -1,
            "Color45DegreesMatchesObject" -> False,
            "ColorNegative45Degrees" -> -1,
            "ColorNegative45DegreesMatchesObject" -> False,
            "ColorNegative90Degrees" -> -1,
            "ColorNegative90DegreesMatchesObject" -> False,
            "ColorNegative135Degrees" -> -1,
            "ColorNegative135DegreesMatchesObject" -> False,
            "DistanceSinceLastTurn" -> 2,
            "TotalDistanceSoFar" -> 23
        |> -> <|
            "OutgoingDirection" -> {0, -1},
            "OutgoingDirectionY" -> 0,
            "OutgoingDirectionX" -> -1,
            "TurnDegrees" -> 90
        |>,
        <|
            "UUID" -> 0,
            "Position" -> {4, 3},
            "PreviousPosition" -> {4, 4},
            "IncomingDirection" -> {0, -1},
            "IncomingDirectionY" -> 0,
            "IncomingDirectionX" -> -1,
            "PreviousIncomingDirection" -> {1, 0},
            "ColorAhead" -> -1,
            "ColorAheadMatchesObject" -> False,
            "ColorAhead2" -> 3,
            "ColorAhead2MatchesObject" -> True,
            "ColorAhead3" -> -2,
            "ColorAhead3MatchesObject" -> False,
            "Color135Degrees" -> 3,
            "Color135DegreesMatchesObject" -> True,
            "Color90Degrees" -> 3,
            "Color90DegreesMatchesObject" -> True,
            "Color90Degrees2" -> -1,
            "Color90Degrees2MatchesObject" -> False,
            "Color45Degrees" -> 3,
            "Color45DegreesMatchesObject" -> True,
            "ColorNegative45Degrees" -> -1,
            "ColorNegative45DegreesMatchesObject" -> False,
            "ColorNegative90Degrees" -> -1,
            "ColorNegative90DegreesMatchesObject" -> False,
            "ColorNegative135Degrees" -> -1,
            "ColorNegative135DegreesMatchesObject" -> False,
            "DistanceSinceLastTurn" -> 2,
            "TotalDistanceSoFar" -> 24
        |> -> <|
            "Stop" -> True
        |>
    }
    ,
    TestID -> "ARCMappingsForGeneratedObject-20220915-WTG4U0"
]