:- module( telephone_names, [ lex_name/1 ] ).

lex_name(alex).
lex_name(alida).
lex_name(anna).
lex_name(björn).
lex_name(bo).
lex_name(david).
lex_name(edith).
lex_name(elsa).
lex_name(erik).
lex_name(hildur).
lex_name(hugo).
lex_name(jan).
lex_name(john).
lex_name(kalle). 
lex_name(leif).
lex_name(lisa).
lex_name(maria).
lex_name(mia).
lex_name(olle).
lex_name(oscar).
lex_name(paul).
lex_name(pelle). 
lex_name(per).
lex_name(peter).
lex_name(robert).
lex_name(robin). 
lex_name(staffan). 
lex_name(stina).
lex_name(åsa).
