:- module(cycnl_iface,[]).

%:- nl_iface:rexport_qlf(cycnl_iface,ac_xnl_7166).

%:- reexport(ac_xnl_7166_nlkb).

end_of_file.

acnl('genTemplate','healedInjury',uU('xSentenceNpIsXpFn',uU('xParaphraseFnNp','ARG2'),uU('xConcatenatePhrasesFn',[uU('xPhraseFromStringFn',"healed"),uU('xPpPNpFn','xInTheWord',uU('xParaphraseFnNp','ARG1'))])),2884946).
acnl('genTemplate','hasArmorStatus',uU('xSentenceNpIsXpFn',uU('xParaphraseFnNp','ARG1'),uU('xParaphraseFnNp','ARG2')),2883838).
acnl('genTemplate','hasArticleTitlePubmed',uU('xConcatenatePhrasesFn',[uU('xParaphraseFnNp','ARG1'),uU('xHeadVerbForInitialSubjectFn','xHaveTheWord'),uU('xNpDetNbarFnDefinite',uU('xWordFormFnConstrained','singular','xTitleTheWord')),uU('xQuotedParaphraseFn','ARG2')]),3453203).
acnl('genTemplate','hasAsBoundary',uU('xSentenceNpIsXpFn',uU('xParaphraseFnNp','ARG1'),uU('xConcatenatePhrasesFn',[uU('xPhraseFromStringFn',s("a","boundary")),uU('xPpPNpFn','xOfTheWord',uU('xParaphraseFnNp','ARG2'))])),2884428).
acnl('genTemplate','hasAsCavity',uU('xConcatenatePhrasesFn',[uU('xParaphraseFnNp','ARG1'),uU('xHeadVerbForInitialSubjectFn','xHaveTheWord'),uU('xParaphraseFnNp','ARG2'),uU('xPhraseFromStringFn',"as"),uU('xPhraseFromStringFn',"a"),uU('xPhraseFromStringFn',"hole"),uU('xPhraseFromStringFn',"or"),uU('xPhraseFromStringFn',"cavity")]),822503).
acnl('genTemplate','hasAsChiefExecutiveOfGovernment',uU('xSentenceNpHasNpAsNbarFn',uU('xParaphraseFnNp','ARG1'),uU('xParaphraseFnNp','ARG2'),uU('xParaphraseFnConstrained',uR('xPhraseFnBar1','xtNoun'),'ARG0')),3926547).
acnl('genTemplate','hasAsChiefExecutiveOfGovernment',uU('xSentenceNpIsXpFn',uU('xNpDetNbarFn',uU('xParaphraseFnPossessive','ARG1'),uU('xParaphraseFn','ARG0')),uU('xParaphraseFn','ARG2')),1954907).
acnl('genTemplate','hasAsChiefExecutiveOfGovernment',uU('xSentenceNpIsXpFn',uU('xParaphraseFn','ARG2'),uU('xConcatenatePhrasesFn',[uU('xPhraseFromStringFn',s("the","chief","governmental","executive")),uU('xPpPNpFn','xOfTheWord',uU('xParaphraseFnNp','ARG1'))])),2884013).
acnl('genTemplate','hasAsChiefExecutiveOfGovernment',uU('xSentenceNpIsXpFn',uU('xParaphraseFnNp','ARG2'),uU('xConcatenatePhrasesFn',[uU('xPhraseFromStringFn',s("the","chief","governmental","executive","of")),uU('xParaphraseFnNp','ARG1')])),2885382).
acnl('genTemplate','hasAsChiefExecutiveOfGovernment',uU('xSentenceNpIsXpFn',uU('xParaphraseFnNp','ARG2'),uU('xNpDetNbarFnIndefinite',uU('xConcatenatePhrasesFn',[uU('xHeadWordOfPhraseFn',uU('xParaphraseFnConstrained',uR('xPhraseFnBar1','xtNoun'),'ARG0')),uU('xPpPNpFn','xOfTheWord',uU('xParaphraseFnNp','ARG1'))]))),3925859).
acnl('genTemplate','hasAsHeadOfGovernment',uU('xPhraseFnConstrained','xtNLSentence',uU('xConcatenatePhrasesFn',[uU('xParaphraseFn','ARG2'),uU('xHeadVerbForInitialSubjectFn','xHeadTheWord'),uU('xNpDetNPpFnDefinite','xGovernmentTheWord',"of",uU('xParaphraseFnNp','ARG1'))])),821412).
acnl('genTemplate','hasAsHeadOfGovernment',uU('xSentenceNpHasNpAsNbarFn',uU('xParaphraseFnNp','ARG1'),uU('xParaphraseFnNp','ARG2'),uU('xParaphraseFnConstrained',uR('xPhraseFnBar1','xtNoun'),'ARG0')),3926546).
acnl('genTemplate','hasAsHeadOfGovernment',uU('xSentenceNpIsXpFn',uU('xNpDetNbarFn',uU('xParaphraseFnPossessive','ARG1'),uU('xParaphraseFn','ARG0')),uU('xParaphraseFn','ARG2')),1954903).
acnl('genTemplateConstrained','vVoltFn','quotedFormulaArity'(uU('xQuoteFn','SELF'),2),uU('xNpDetNbarFn',uU('xConcatenatePhrasesFnNoSpaces',[uU('xParaphraseFnNp','ARG1'),uU('xSymbolPhraseFn','xEnDashTheSymbol'),uU('xParaphraseFnNp','ARG2')]),uU('xParaphraseFn','vVoltFn')),3874507).
acnl('genTemplateConstrained','vWattFn','quotedFormulaArity'(uU('xQuoteFn','SELF'),2),uU('xNpDetNbarFn',uU('xConcatenatePhrasesFnNoSpaces',[uU('xParaphraseFnNp','ARG1'),uU('xSymbolPhraseFn','xEnDashTheSymbol'),uU('xParaphraseFnNp','ARG2')]),uU('xParaphraseFn',nartR('cycPerFn',nartR('cycUnitProductFn','vKilogramFn','vSquareMeterFn'),nartR('cycUnitProductFn','vSecondsDurationFn',nartR('cycUnitProductFn','vSecondsDurationFn','vSecondsDurationFn'))))),3874274).
acnl('genTemplateConstrained','vWattFn','quotedFormulaArity'(uU('xQuoteFn','SELF'),2),uU('xNpDetNbarFn',uU('xConcatenatePhrasesFnNoSpaces',[uU('xParaphraseFnNp','ARG1'),uU('xSymbolPhraseFn','xEnDashTheSymbol'),uU('xParaphraseFnNp','ARG2')]),uU('xParaphraseFn',nartR('cycPerFn','vJouleFn','vSecondsDurationFn'))),3874267).
acnl('genTemplateConstrained','vWattFn','quotedFormulaArity'(uU('xQuoteFn','SELF'),2),uU('xNpDetNbarFn',uU('xConcatenatePhrasesFnNoSpaces',[uU('xParaphraseFnNp','ARG1'),uU('xSymbolPhraseFn','xEnDashTheSymbol'),uU('xParaphraseFnNp','ARG2')]),uU('xParaphraseFn',nartR('cycUnitProductFn','vAmpereFn','vVoltFn'))),3874340).
acnl('genTemplateConstrained','vWattFn','quotedFormulaArity'(uU('xQuoteFn','SELF'),2),uU('xNpDetNbarFn',uU('xConcatenatePhrasesFnNoSpaces',[uU('xParaphraseFnNp','ARG1'),uU('xSymbolPhraseFn','xEnDashTheSymbol'),uU('xParaphraseFnNp','ARG2')]),uU('xParaphraseFn','vWattFn')),3874165).
acnl('genTemplateConstrained','vWeeksDurationFn','quotedFormulaArity'(uU('xQuoteFn','SELF'),2),uU('xNpDetNbarFn',uU('xConcatenatePhrasesFnNoSpaces',[uU('xParaphraseFnNp','ARG1'),uU('xSymbolPhraseFn','xEnDashTheSymbol'),uU('xParaphraseFnNp','ARG2')]),uU('xParaphraseFn',nartR('cycDefiningTimeUnitForCalendarCoveringTypeFn','tClazzCalendarWeek'))),3874813).
acnl('genTemplateConstrained','vWeeksDurationFn','quotedFormulaArity'(uU('xQuoteFn','SELF'),2),uU('xNpDetNbarFn',uU('xConcatenatePhrasesFnNoSpaces',[uU('xParaphraseFnNp','ARG1'),uU('xSymbolPhraseFn','xEnDashTheSymbol'),uU('xParaphraseFnNp','ARG2')]),uU('xParaphraseFn','vWeeksDurationFn')),3874767).
acnl('genTemplateConstrained','vWonNorthKoreaFn','quotedFormulaArity'(uU('xQuoteFn','SELF'),2),uU('xNpDetNbarFn',uU('xConcatenatePhrasesFnNoSpaces',[uU('xParaphraseFnNp','ARG1'),uU('xSymbolPhraseFn','xEnDashTheSymbol'),uU('xParaphraseFnNp','ARG2')]),uU('xParaphraseFn','vWonNorthKoreaFn')),3874779).
acnl('genTemplateConstrained','vWonSouthKoreaFn','quotedFormulaArity'(uU('xQuoteFn','SELF'),2),uU('xNpDetNbarFn',uU('xConcatenatePhrasesFnNoSpaces',[uU('xParaphraseFnNp','ARG1'),uU('xSymbolPhraseFn','xEnDashTheSymbol'),uU('xParaphraseFnNp','ARG2')]),uU('xParaphraseFn','vWonSouthKoreaFn')),3874629).
acnl('genTemplateConstrained','vWordUnitOfComputerMemoryFn','quotedFormulaArity'(uU('xQuoteFn','SELF'),2),uU('xNpDetNbarFn',uU('xConcatenatePhrasesFnNoSpaces',[uU('xParaphraseFnNp','ARG1'),uU('xSymbolPhraseFn','xEnDashTheSymbol'),uU('xParaphraseFnNp','ARG2')]),uU('xParaphraseFn','vWordUnitOfComputerMemoryFn')),3874776).
acnl('genTemplateConstrained','vYardUnitOfDistanceFn','quotedFormulaArity'(uU('xQuoteFn','SELF'),2),uU('xNpDetNbarFn',uU('xConcatenatePhrasesFnNoSpaces',[uU('xParaphraseFnNp','ARG1'),uU('xSymbolPhraseFn','xEnDashTheSymbol'),uU('xParaphraseFnNp','ARG2')]),uU('xParaphraseFn','vYardUnitOfDistanceFn')),3874488).
acnl('genTemplateConstrained','vYearsDurationFn','quotedFormulaArity'(uU('xQuoteFn','SELF'),2),uU('xNpDetNbarFn',uU('xConcatenatePhrasesFnNoSpaces',[uU('xParaphraseFnNp','ARG1'),uU('xSymbolPhraseFn','xEnDashTheSymbol'),uU('xParaphraseFnNp','ARG2')]),uU('xParaphraseFn',nartR('cycDefiningTimeUnitForCalendarCoveringTypeFn','tClazzCalendarYear'))),3874819).
acnl('genTemplateConstrained','vYearsDurationFn','quotedFormulaArity'(uU('xQuoteFn','SELF'),2),uU('xNpDetNbarFn',uU('xConcatenatePhrasesFnNoSpaces',[uU('xParaphraseFnNp','ARG1'),uU('xSymbolPhraseFn','xEnDashTheSymbol'),uU('xParaphraseFnNp','ARG2')]),uU('xParaphraseFn','vYearsDurationFn')),3874737).
acnl('genTemplateConstrained','vYenJapanFn','quotedFormulaArity'(uU('xQuoteFn','SELF'),2),uU('xNpDetNbarFn',uU('xConcatenatePhrasesFnNoSpaces',[uU('xParaphraseFnNp','ARG1'),uU('xSymbolPhraseFn','xEnDashTheSymbol'),uU('xParaphraseFnNp','ARG2')]),uU('xParaphraseFn','vYenJapanFn')),3874682).
acnl('genTemplateConstrained','vYuanChinaFn','quotedFormulaArity'(uU('xQuoteFn','SELF'),2),uU('xNpDetNbarFn',uU('xConcatenatePhrasesFnNoSpaces',[uU('xParaphraseFnNp','ARG1'),uU('xSymbolPhraseFn','xEnDashTheSymbol'),uU('xParaphraseFnNp','ARG2')]),uU('xParaphraseFn','vYuanChinaFn')),3874685).
acnl('genTemplateConstrained','vZlotyPolandFn','quotedFormulaArity'(uU('xQuoteFn','SELF'),2),uU('xNpDetNbarFn',uU('xConcatenatePhrasesFnNoSpaces',[uU('xParaphraseFnNp','ARG1'),uU('xSymbolPhraseFn','xEnDashTheSymbol'),uU('xParaphraseFnNp','ARG2')]),uU('xParaphraseFn','vZlotyPolandFn')),3874725).
acnl('genTemplateConstrained','wantsToRelnA','equals'('buys','ARG3'),uU('xConcatenatePhrasesFn',[uU('xParaphraseFnNp','ARG1'),uU('xHeadVerbForInitialSubjectFn','xWantTheWord'),uU('xPhraseFromStringFn',s("to","buy")),uU('xParaphraseFnNp','ARG2')]),878129).
acnl('genTemplateConstrained','was','quotedIsa'('ARG1','ftSentence'),uU('xParaphraseFnConstrained','pastTenseGeneric','ARG1'),1783075).
acnl('genTemplateConstrained','waterSolubility','quotedIsa'('ARG2','ftAtomicTerm'),uU('xSentenceNpIsXpFn',uU('xParaphraseFn','ARG1'),uU('xConcatenatePhrasesFn',[uU('xParaphraseFn','ARG2'),uU('xPpPNpFn','xInTheWord',uU('xWordFormFnConstrained','xtMassNoun','xWaterTheWord'))])),1781957).
acnl('genTemplateConstrained','weaponPayloadMax','or'('isa'('ARG1','tObjectMissile'),'genls'('ARG1','tObjectMissile')),uU('xSentenceNpIsXpFn',uU('xParaphraseFn','ARG1'),uU('xConcatenatePhrasesFn',[uU('xWordFormFnConstrained','perfect','xLimitTheWord'),uU('xPpPNpFn','xToTheWord',uU('xNpDetNbarFnIndefinite',uU('xNbarHeadedByNounFormFn','xPayloadTheWord','xtCountNoun',uU('xParaphraseFnPp','xOfTheWord','ARG2'))))])),2883976).

acnl('nbarForArgOfPred','spouse',2,uU('xPhraseFnConstrained',uR('xPhraseFnBar1','xtNoun'),uU('xConcatenatePhrasesFn',[uU('xHeadWordOfPhraseFn',uU('xParaphraseFnConstrained','singularGeneric','spouse')),uU('xPpPNpFn','xOfTheWord',uU('xParaphraseFnNp','ARG1'))])),1644779).
acnl('nbarForArgOfPred','thicknessOfObject',2,uU('xPhraseFnConstrained',uR('xPhraseFnBar1','xtNoun'),uU('xConcatenatePhrasesFn',[uU('xHeadWordOfPhraseFn',uU('xParaphraseFnConstrained','singularGeneric','thicknessOfObject')),uU('xPpPNpFn','xOfTheWord',uU('xParaphraseFnNp','ARG1'))])),1644750).

acnl('nbarForArgOfPred','titleOfWork',2,uU('xPhraseFnConstrained',uR('xPhraseFnBar1','xtNoun'),uU('xConcatenatePhrasesFn',[uU('xHeadWordOfPhraseFn',uU('xParaphraseFnConstrained','singularGeneric','titleOfWork')),uU('xPpPNpFn','xOfTheWord',uU('xParaphraseFnNp','ARG1'))])),1644776).
acnl('nbarForArgOfPred','twins',2,uU('xPhraseFnConstrained',uR('xPhraseFnBar1','xtNoun'),uU('xConcatenatePhrasesFn',[uU('xHeadWordOfPhraseFn',uU('xParaphraseFnConstrained','singularGeneric','twins')),uU('xPpPNpFn','xOfTheWord',uU('xParaphraseFnNp','ARG1'))])),1644784).
acnl('nbarForArgOfPred','twinsFraternal',2,uU('xPhraseFnConstrained',uR('xPhraseFnBar1','xtNoun'),uU('xConcatenatePhrasesFn',[uU('xHeadWordOfPhraseFn',uU('xParaphraseFnConstrained','singularGeneric','twinsFraternal')),uU('xPpPNpFn','xOfTheWord',uU('xParaphraseFnNp','ARG1'))])),1644786).
acnl('nbarForArgOfPred','twinsIdentical',2,uU('xPhraseFnConstrained',uR('xPhraseFnBar1','xtNoun'),uU('xConcatenatePhrasesFn',[uU('xHeadWordOfPhraseFn',uU('xParaphraseFnConstrained','singularGeneric','twinsIdentical')),uU('xPpPNpFn','xOfTheWord',uU('xParaphraseFnNp','ARG1'))])),1644785).
acnl('nbarForArgOfPred','unitCommander',2,uU('xPhraseFnConstrained',nartR('xPhraseFnBar1','xtNoun'),uU('xConcatenatePhrasesFn',[uU('xHeadWordOfPhraseFn',uU('xParaphraseFnConstrained','singularGeneric','unitCommander')),uU('xPpPNpFn','xOfTheWord',uU('xParaphraseFnNp','ARG1'))])),1828320acnl('verbSemTrans','iInstitutionaliseTheWord',0,'xDitransitiveNPInfinitivePhraseFrame','and'('isa'('ACTION','actCommittingSomeoneToAnInstitution'),'performedBy'('ACTION','SUBJECT'),'recipientOfInfo'('ACTION','OBJECT'),'infoTransferred'('ACTION',PERMISSION),'istInformation'(PERMISSION,'performedBy'('INF-COMP','OBJECT'))),3308704).
acnl('verbSemTrans','iInstitutionalizeTheWord',0,'xDitransitiveNPInfinitivePhraseFrame','and'('isa'('ACTION','actCommittingSomeoneToAnInstitution'),'performedBy'('ACTION','SUBJECT'),'recipientOfInfo'('ACTION','OBJECT'),'infoTransferred'('ACTION',PERMISSION),'istInformation'(PERMISSION,'performedBy'('INF-COMP','OBJECT'))),3308703).
% From /opt/logicmoo_workspace/packs_sys/logicmoo_nlu/ext/pldata/ac_xnl/ac_xnl_7166_part_025800.nldata:1758
acnl('verbSemTrans','iLegaliseTheWord',0,'xDitransitiveNPInfinitivePhraseFrame','and'('isa'('ACTION','actLegalizingSomethingPreviouslyIllegal'),'performedBy'('ACTION','SUBJECT'),'recipientOfInfo'('ACTION','OBJECT'),'infoTransferred'('ACTION',PERMISSION),'istInformation'(PERMISSION,'performedBy'('INF-COMP','OBJECT'))),3308719).
acnl('verbSemTrans','iLegalizeTheWord',0,'xDitransitiveNPInfinitivePhraseFrame','and'('isa'('ACTION','actLegalizingSomethingPreviouslyIllegal'),'performedBy'('ACTION','SUBJECT'),'recipientOfInfo'('ACTION','OBJECT'),'infoTransferred'('ACTION',PERMISSION),'istInformation'(PERMISSION,'performedBy'('INF-COMP','OBJECT'))),3308720).
% From /opt/logicmoo_workspace/packs_sys/logicmoo_nlu/ext/pldata/ac_xnl/ac_xnl_7166_part_025200.nldata:4343
acnl('termTemplateReln','xtNPTemplate','or',uU('vNLPatternListFn',[uU('xNLPatternTemplateFn','xtNPTemplate','NP1'),'iTemplateCommaMarker',uU('xNLPatternTemplateFn','xtNPTemplate','NP2'),uU('tSetOfOptionalSomeFn',[","]),uU('tSetOfNLPatternExactFn',["or"]),uU('xNLPatternTemplateFn','xtNPTemplate','NP3')]),uU('uConjoinedPhrasesFn',uU('vTheListFn',["or"]),uU('vTheListFn',['NP1','NP2','NP3'])),1394910).
acnl('termTemplateReln','xtNPTemplate','or',uU('vNLPatternListFn',[uU('xNLPatternTemplateFn','xtNPTemplate','NP1'),uU('tSetOfNLPatternExactFn',["or"]),uU('xNLPatternTemplateFn','xtNPTemplate','NP2')]),uU('uConjoinedPhrasesFn',uU('vTheListFn',["or"]),uU('vTheListFn',['NP1','NP2'])),1394813).
% From /opt/logicmoo_workspace/packs_sys/logicmoo_nlu/ext/pldata/ac_xnl/ac_xnl_7166_part_025200.nldata:5703
acnl('termTemplateReln','xtNPTemplate','xBestStringOfNLPhraseFn',uU('vNLPatternListFn',[uU('tSetOfNLPatternExactFn',["the"]),uU('tSetOfNLPatternExactFn',["preferred"]),uU('tSetOfNLPatternWordFn','xStringTheWord','xtMassNoun'),uU('tSetOfNLPatternExactFn',["of"]),uU('xNLPatternTemplateFn','xtNPTemplate','ARG1')]),uU('xBestStringOfNLPhraseFn','ARG1'),1443719).
% From /opt/logicmoo_workspace/packs_sys/logicmoo_nlu/ext/pldata/ac_xnl/ac_xnl_7166_part_025200.nldata:5707
acnl('termTemplateReln','xtNPTemplate','xGeneratePhraseFn',uU('vNLPatternListFn',[uU('tSetOfOptionalOneFn',["the"]),uU('tSetOfRequireOneFn',[s("generation","string")]),uU('tSetOfRequireOneFn',["for",s("corresponding","to")]),uU('xNLPatternTemplateFn','xtNPTemplate','ARG')]),uU('xGeneratePhraseFn','ARG'),1389580).
% From /opt/logicmoo_workspace/packs_sys/logicmoo_nlu/ext/pldata/ac_xnl/ac_xnl_7166_part_025200.nldata:5710
acnl('termTemplateReln','xtNPTemplate','xPhraseFnBar1',uU('vNLPatternListFn',[uU('tSetOfNLPatternExactFn',["bar-1-level"]),uU('tSetOfNLPatternWordFn','xConstituentTheWord','xtCountNoun'),uU('tSetOfNLPatternExactFn',["headed","by","a"]),uU('xNLPatternTemplateFn','xtNPTemplate','ARG1')]),uR('xPhraseFnBar1','ARG1'),1387684).


