:- use_module(library(logicmoo_plarkc)).

:- set_prolog_flag(double_quotes, string).
:- install_constant_renamer_until_eof.
:- set_prolog_flag(do_renames_sumo,never).

dynamicCyc2( 'abbreviationForCompoundString'/6).
dynamicCyc2( 'abbreviationForLexicalWord'/5).
dynamicCyc2( 'abbreviationForMultiWordString'/6).
dynamicCyc2( 'abbreviationForString'/4).
dynamicCyc2( 'abbreviationString-PN'/4).
dynamicCyc2( 'abnormal'/4).
dynamicCyc2( 'acronymString'/4).
dynamicCyc2( 'actionExpressesFeelingToward'/5).
dynamicCyc2( 'actionViolatesObligation'/4).
dynamicCyc2( 'adjacentTo'/4).
dynamicCyc2( 'adjSemTrans'/6).
dynamicCyc2( 'adjSemTrans-Restricted'/7).
dynamicCyc2( 'adjSemTransTemplate'/5).
dynamicCyc2( 'affiliatedWith'/4).
dynamicCyc2( 'affixRuleArity'/4).
dynamicCyc2( 'affixRuleCategorialConstraint'/4).
dynamicCyc2( 'affixRuleTypeMorphemePosition'/5).
dynamicCyc2( 'affixSemantics'/4).
dynamicCyc2( 'agentive-Mass'/4).
dynamicCyc2( 'agentiveNounSemTrans'/6).
dynamicCyc2( 'agentive-Pl'/4).
dynamicCyc2( 'agentive-Sg'/4).
dynamicCyc2( 'agreeingAgents'/4).
dynamicCyc2( 'algorithmStartStep'/4).
dynamicCyc2( 'allies'/4).
dynamicCyc2( 'alternateRouteFromThrough'/6).
dynamicCyc2( 'altitudeAnglePredicate'/4).
dynamicCyc2( 'analogousFeelings'/4).
dynamicCyc2( 'anatomicalParts'/4).
dynamicCyc2( 'areaOfRegion'/4).
dynamicCyc2( 'arg1Format'/4).
dynamicCyc2( 'arg1Genl'/4).
dynamicCyc2( 'arg1Isa'/4).
dynamicCyc2( 'arg2Format'/4).
dynamicCyc2( 'arg2Genl'/4).
dynamicCyc2( 'arg2Isa'/4).
dynamicCyc2( 'arg3Format'/4).
dynamicCyc2( 'arg3Genl'/4).
dynamicCyc2( 'arg3Isa'/4).
dynamicCyc2( 'arg4Format'/4).
dynamicCyc2( 'arg4Genl'/4).
dynamicCyc2( 'arg4Isa'/4).
dynamicCyc2( 'arg5Format'/4).
dynamicCyc2( 'arg5Genl'/4).
dynamicCyc2( 'arg5Isa'/4).
dynamicCyc2( 'arg6Format'/4).
dynamicCyc2( 'arg6Isa'/4).
dynamicCyc2( 'argAdmittanceTestedDuringTransitiveViaInference'/6).
dynamicCyc2( 'argAndRestIsa'/5).
dynamicCyc2( 'argFormat'/5).
dynamicCyc2( 'argGenl'/5).
dynamicCyc2( 'argIsa'/5).
dynamicCyc2( 'argsIsa'/4).
dynamicCyc2( 'arity'/4).
dynamicCyc2( 'arityMax'/4).
dynamicCyc2( 'arityMin'/4).
dynamicCyc2( 'assertionTimeOfMicrotheory'/4).
dynamicCyc2( 'assertTemplate-Reln'/6).
dynamicCyc2( 'azimuthAnglePredicate'/4).
dynamicCyc2( 'backchainForbidden'/3).
dynamicCyc2( 'backchainRequired'/3).
dynamicCyc2( 'barLevelOfPhraseType'/4).
dynamicCyc2( 'baseForm'/4).
dynamicCyc2( 'basicSpeechPartPred'/4).
dynamicCyc2( 'behaviorCapable'/5).
dynamicCyc2( 'beliefs'/4).
dynamicCyc2( 'beneficiary'/4).
dynamicCyc2( 'betweenSpatially'/5).
dynamicCyc2( 'bogusSpeechPart'/3).
dynamicCyc2( 'bordersOn'/4).
dynamicCyc2( 'budgetExpenditureFractionOfGDP'/6).
dynamicCyc2( 'budgetExpenditures'/6).
dynamicCyc2( 'canBop'/4).
dynamicCyc2( 'capitalCity'/4).
dynamicCyc2( 'cardinality'/4).
dynamicCyc2( 'casualtyCount'/4).
dynamicCyc2( 'causes-PropProp'/4).
dynamicCyc2( 'causes-SitProp'/4).
dynamicCyc2( 'chiefPorts'/4).
dynamicCyc2( 'citizens'/4).
dynamicCyc2( 'coExtensional'/4).
dynamicCyc2( 'collectionBackchainEncouraged'/3).
dynamicCyc2( 'collectionIntersection'/4).
dynamicCyc2( 'collectionUnion'/4).
dynamicCyc2( 'comment'/4).
dynamicCyc2( 'commutativeInArgs'/5).
dynamicCyc2( 'commutativeInArgsAndRest'/4).
dynamicCyc2( 'comparativeAdverb'/4).
dynamicCyc2( 'comparativeDegree'/4).
dynamicCyc2( 'completeCollectionExtent'/3).
dynamicCyc2( 'completeExtentKnown'/3).
dynamicCyc2( 'compoundSemTrans'/7).
dynamicCyc2( 'compoundString'/6).
dynamicCyc2( 'compoundStringDenotesArgInReln'/7).
dynamicCyc2( 'compoundVerbSemTrans'/6).
dynamicCyc2( 'conceptuallyRelated'/4).
dynamicCyc2( 'conditionalProbability'/5).
dynamicCyc2( 'conditionalProbabilitySet'/5).
dynamicCyc2( 'considersAsEnemy'/4).
dynamicCyc2( 'constrainsArg'/4).
dynamicCyc2( 'consumptionAmountDuring'/6).
dynamicCyc2( 'consumptionCapacityDuring'/6).
dynamicCyc2( 'containsInformation'/4).
dynamicCyc2( 'contiguousAfter'/4).
dynamicCyc2( 'contradictoryPreds'/4).
dynamicCyc2( 'contraryFeelings'/4).
dynamicCyc2( 'contrastedFeelings'/4).
dynamicCyc2( 'controls'/4).
dynamicCyc2( 'correspondingPreds-Capability'/4).
dynamicCyc2( 'countryCodeDigraph'/4).
dynamicCyc2( 'countryName-LocalLongForm'/4).
dynamicCyc2( 'countryName-LocalShortForm'/4).
dynamicCyc2( 'countryName-LongForm'/4).
dynamicCyc2( 'countryName-ShortForm'/4).
dynamicCyc2( 'covering'/4).
dynamicCyc2( 'currencyOf'/4).
dynamicCyc2( 'currentAccountBalanceDuring'/5).
dynamicCyc2( 'customers'/4).
dynamicCyc2( 'cyclistNotes'/4).
dynamicCyc2( 'damages'/4).
dynamicCyc2( 'dateOfEvent'/4).
dynamicCyc2( 'deathToll'/5).
dynamicCyc2( 'decontextualizedCollection'/3).
dynamicCyc2( 'decontextualizedCollectionConventionMt'/4).
dynamicCyc2( 'decontextualizedPredicate'/3).
dynamicCyc2( 'decontextualizedPredicateConventionMt'/4).
dynamicCyc2( 'decreasesCausally'/5).
dynamicCyc2( 'defaultCorrespondingRoles'/4).
dynamicCyc2( 'defaultReformulationDirectionInModeForPred'/5).
dynamicCyc2( 'defenseBudgetExpenditures'/4).
dynamicCyc2( 'definingMt'/4).
dynamicCyc2( 'definingTimeUnit'/4).
dynamicCyc2( 'defnIff'/4).
dynamicCyc2( 'defnSufficient'/4).
dynamicCyc2( 'deliberateActors'/4).
dynamicCyc2( 'denotation'/6).
dynamicCyc2( 'denotationPlaceholder'/6).
dynamicCyc2( 'denotationRelatedTo'/6).
dynamicCyc2( 'denotatumArg'/4).
dynamicCyc2( 'denotesArgInReln'/6).
dynamicCyc2( 'derivationalAffixBasePOS'/4).
dynamicCyc2( 'derivationalAffixResultPOS'/4).
dynamicCyc2( 'derivedProbability'/4).
dynamicCyc2( 'derivedProbability-Range'/4).
dynamicCyc2( 'derivedUsingPrefix'/4).
dynamicCyc2( 'derivedUsingSuffix'/4).
dynamicCyc2( 'desires'/4).
dynamicCyc2( 'determinerAgreement'/4).
dynamicCyc2( 'deviceUsed'/4).
dynamicCyc2( 'different'/4).
dynamicCyc2( 'directingAgent'/4).
dynamicCyc2( 'disjointWith'/4).
dynamicCyc2( 'distanceAboveSeaLevel'/4).
dynamicCyc2( 'distanceBetween'/5).
dynamicCyc2( 'domainAssumptions'/4).
dynamicCyc2( 'doneBy'/4).
dynamicCyc2( 'driverActor'/4).
dynamicCyc2( 'duration'/4).
dynamicCyc2( 'eastOf'/4).
dynamicCyc2( 'elInverse'/4).
dynamicCyc2( 'emptiesInto'/4).
dynamicCyc2( 'endingDate'/4).
dynamicCyc2( 'endingPoint'/4).
dynamicCyc2( 'endsAfterEndingOf'/4).
dynamicCyc2( 'enforcingAgent'/4).
dynamicCyc2( 'englishGloss'/4).
dynamicCyc2( 'equals'/4).
dynamicCyc2( 'etymologicalVariantOfSuffix'/5).
dynamicCyc2( 'evaluate'/4).
dynamicCyc2( 'evaluationDefn'/4).
dynamicCyc2( 'eventOccursAt'/4).
dynamicCyc2( 'exceptFor'/4).
dynamicCyc2( 'exceptWhen'/4).
dynamicCyc2( 'exchangeRateDuring'/6).
dynamicCyc2( 'exchangeRateDuring-Market'/6).
dynamicCyc2( 'exchangeRateDuring-Official'/6).
dynamicCyc2( 'executableProgramName'/4).
dynamicCyc2( 'expansion'/4).
dynamicCyc2( 'expansionAxiom'/4).
dynamicCyc2( 'expansionDefn'/4).
dynamicCyc2( 'expertRegarding'/4).
dynamicCyc2( 'exportAmountDuring'/6).
dynamicCyc2( 'exportCapacityDuring'/6).
dynamicCyc2( 'exportDestinationFractionDuring'/6).
dynamicCyc2( 'exportRate'/5).
dynamicCyc2( 'exportRateThrough'/6).
dynamicCyc2( 'exportRevenueFractionDuring'/6).
dynamicCyc2( 'exports'/4).
dynamicCyc2( 'exportsThrough'/5).
dynamicCyc2( 'exportThroughAmountDuring'/7).
dynamicCyc2( 'extent'/4).
dynamicCyc2( 'facets-Generic'/4).
dynamicCyc2( 'facets-Partition'/4).
dynamicCyc2( 'facets-Strict'/4).
dynamicCyc2( 'fanOutArg'/4).
dynamicCyc2( 'fertilityRate'/4).
dynamicCyc2( 'firstPersonSg-Present'/4).
dynamicCyc2( 'firstSubEvents'/4).
dynamicCyc2( 'flowCapacity'/4).
dynamicCyc2( 'followingIntervalType'/4).
dynamicCyc2( 'followingValue'/4).
dynamicCyc2( 'formalityOfWS'/6).
dynamicCyc2( 'formalityOfWS-New'/4).
dynamicCyc2( 'formationAuthorizedBy'/4).
dynamicCyc2( 'formedByConfluenceOf'/4).
dynamicCyc2( 'formerName'/4).
dynamicCyc2( 'frequencyOfActionType'/6).
dynamicCyc2( 'functionalInArgs'/4).
dynamicCyc2( 'functionCommutesWith'/4).
dynamicCyc2( 'functionCorrespondingPredicate'/5).
dynamicCyc2( 'functionCorrespondingPredicate-Canonical'/5).
dynamicCyc2( 'functionCorrespondingPredicate-Generic'/5).
dynamicCyc2( 'genCodeSupport'/3).
dynamicCyc2( 'generalSemantics'/4).
dynamicCyc2( 'generateArgWithOutsideScope'/4).
dynamicCyc2( 'generateQuantOverArg'/5).
dynamicCyc2( 'genExpansion'/4).
dynamicCyc2( 'genFormat'/5).
dynamicCyc2( 'genFormat-ArgFixed'/7).
dynamicCyc2( 'genFormat-NP'/5).
dynamicCyc2( 'genFormat-Precise'/5).
dynamicCyc2( 'genKeyword'/4).
dynamicCyc2( 'genlAttributes'/4).
dynamicCyc2( 'genlFuncs'/4).
dynamicCyc2( 'genlInverse'/4).
dynamicCyc2( 'genlMt'/4).
dynamicCyc2( 'genlMt-Vocabulary'/4).
dynamicCyc2( 'genlPreds'/4).
dynamicCyc2( 'genls'/4).
dynamicCyc2( 'genMassNoun'/3).
dynamicCyc2( 'genNatTerm-ArgLast'/5).
dynamicCyc2( 'genNatTerm-compoundString'/7).
dynamicCyc2( 'genNatTerm-multiWordString'/7).
dynamicCyc2( 'genPhrase'/6).
dynamicCyc2( 'genPreferredKeyword'/4).
dynamicCyc2( 'genQuestion'/6).
dynamicCyc2( 'genStringAssertion'/4).
dynamicCyc2( 'genStringAssertion-Old'/3).
dynamicCyc2( 'genStringAssertion-Precise'/4).
dynamicCyc2( 'genTemplate'/4).
dynamicCyc2( 'genTemplate-Constrained'/5).
dynamicCyc2( 'genWithGloss'/3).
dynamicCyc2( 'geographicalSubRegions'/4).
dynamicCyc2( 'geopoliticalSubdivision'/4).
dynamicCyc2( 'givesSupportToAgent'/5).
dynamicCyc2( 'goalCategoryForAgent'/5).
dynamicCyc2( 'goals'/4).
dynamicCyc2( 'governmentType'/4).
dynamicCyc2( 'granuleOfStuff'/4).
dynamicCyc2( 'greaterThanOrEqualTo'/4).
dynamicCyc2( 'grossDomesticProduct'/5).
dynamicCyc2( 'grossDomesticProduct-Nominal'/5).
dynamicCyc2( 'grossDomesticProduct-Slot'/4).
dynamicCyc2( 'grossNationalProduct'/5).
dynamicCyc2( 'groupCardinality'/4).
dynamicCyc2( 'groupMembers'/4).
dynamicCyc2( 'groupMemberType'/4).
dynamicCyc2( 'hasAgents'/4).
dynamicCyc2( 'hasBeliefSystems'/4).
dynamicCyc2( 'hasClimateType'/4).
dynamicCyc2( 'hasHeadquartersInCountry'/4).
dynamicCyc2( 'hasLeaders'/4).
dynamicCyc2( 'hasMembers'/4).
dynamicCyc2( 'hasOwnershipIn'/4).
dynamicCyc2( 'hasSequentialProgramSteps'/5).
dynamicCyc2( 'hasStatusWithAgent'/5).
dynamicCyc2( 'headMedialString'/7).
dynamicCyc2( 'headsPhraseOfType'/4).
dynamicCyc2( 'holdsIn'/4).
dynamicCyc2( 'hyphenString'/6).
dynamicCyc2( 'implies'/4).
dynamicCyc2( 'importAmountDuring'/6).
dynamicCyc2( 'importanceOfThingInSet'/5).
dynamicCyc2( 'importCapacityDuring'/6).
dynamicCyc2( 'importExpenditureFractionDuring'/6).
dynamicCyc2( 'importFromAmountDuring'/7).
dynamicCyc2( 'importFromThroughAmountDuring'/8).
dynamicCyc2( 'importOriginFractionDuring'/6).
dynamicCyc2( 'importRate'/5).
dynamicCyc2( 'importRateFrom'/6).
dynamicCyc2( 'imports'/4).
dynamicCyc2( 'importsFrom'/5).
dynamicCyc2( 'importsThrough'/5).
dynamicCyc2( 'importThroughAmountDuring'/7).
dynamicCyc2( 'increasesCausally'/5).
dynamicCyc2( 'independentArg'/4).
dynamicCyc2( 'industryFacilities'/4).
dynamicCyc2( 'industryFractionOfGDP'/6).
dynamicCyc2( 'industryProduces'/4).
dynamicCyc2( 'infinitive'/4).
dynamicCyc2( 'inflationRateDuring'/5).
dynamicCyc2( 'infoTransferred'/4).
dynamicCyc2( 'inhabitantTypes'/4).
dynamicCyc2( 'initialismString'/4).
dynamicCyc2( 'initialParameterValue'/4).
dynamicCyc2( 'inputsDestroyed'/4).
dynamicCyc2( 'inReactionTo'/4).
dynamicCyc2( 'inRegion'/4).
dynamicCyc2( 'instanceElementType'/4).
dynamicCyc2( 'instancesDontNeedLexification'/3).
dynamicCyc2( 'instrument-Generic'/4).
dynamicCyc2( 'intangibleParts'/4).
dynamicCyc2( 'integerRange'/4).
dynamicCyc2( 'intendedBehaviorCapable'/5).
dynamicCyc2( 'interArg1ResultGenls'/5).
dynamicCyc2( 'interArg1ResultIsa'/5).
dynamicCyc2( 'interArg2ResultIsa'/5).
dynamicCyc2( 'interArgCardinality'/7).
dynamicCyc2( 'interArgDifferent'/5).
dynamicCyc2( 'interArgFormat1-1'/5).
dynamicCyc2( 'interArgFormat1-2'/5).
dynamicCyc2( 'interArgFormat2-2'/5).
dynamicCyc2( 'interArgGenl2-1'/5).
dynamicCyc2( 'interArgIsa1-2'/5).
dynamicCyc2( 'interArgIsa1-3'/5).
dynamicCyc2( 'interArgIsa2-1'/5).
dynamicCyc2( 'interArgIsa3-4'/5).
dynamicCyc2( 'interArgIsa4-5'/5).
dynamicCyc2( 'interArgReln1-2'/4).
dynamicCyc2( 'interArgReln1-3'/4).
dynamicCyc2( 'interArgReln1-4'/4).
dynamicCyc2( 'interArgReln2-1'/4).
dynamicCyc2( 'interArgReln2-3'/4).
dynamicCyc2( 'interArgReln2-4'/4).
dynamicCyc2( 'interArgReln3-1'/4).
dynamicCyc2( 'interArgReln3-2'/4).
dynamicCyc2( 'interArgReln3-4'/4).
dynamicCyc2( 'interArgReln'/6).
dynamicCyc2( 'interArgResultGenl'/6).
dynamicCyc2( 'interArgResultIsa'/6).
dynamicCyc2( 'interArgResultReln'/5).
dynamicCyc2( 'internationalMonetaryReservesDuring'/5).
dynamicCyc2( 'internationalOrg-MemberCountry'/4).
dynamicCyc2( 'interResultArgReln'/5).
dynamicCyc2( 'intersectsIntervalType'/4).
dynamicCyc2( 'intervalStartedBy'/4).
dynamicCyc2( 'inverseFunc'/4).
dynamicCyc2( 'isa'/4).
dynamicCyc2( 'jurisdictionRegion'/4).
dynamicCyc2( 'keClarifyingCollection'/3).
dynamicCyc2( 'keCommonQueryPredForInstances'/4).
dynamicCyc2( 'keConsiderationInverse'/4).
dynamicCyc2( 'keConsiderationPreds'/4).
dynamicCyc2( 'keGenlsConsiderationInverse'/4).
dynamicCyc2( 'keGenlsConsiderationPreds'/4).
dynamicCyc2( 'keGenlsStrongSuggestionPreds'/4).
dynamicCyc2( 'keGenlsWeakSuggestionInverse'/4).
dynamicCyc2( 'keGenlsWeakSuggestionPreds'/4).
dynamicCyc2( 'kePredArgStrongSuggestionPreds'/5).
dynamicCyc2( 'kePredArgWeakSuggestionPreds'/5).
dynamicCyc2( 'keRequirementPreds'/4).
dynamicCyc2( 'keStrongConsiderationInverse'/4).
dynamicCyc2( 'keStrongConsiderationPreds'/4).
dynamicCyc2( 'keStrongSuggestion'/4).
dynamicCyc2( 'keStrongSuggestionInverse'/4).
dynamicCyc2( 'keStrongSuggestionPreds'/4).
dynamicCyc2( 'keWeakSuggestionInverse'/4).
dynamicCyc2( 'keWeakSuggestionPreds'/4).
dynamicCyc2( 'knows'/4).
dynamicCyc2( 'laborForceDuring'/5).
dynamicCyc2( 'laborForceFractionDuring'/6).
dynamicCyc2( 'languageOfLexicon'/4).
dynamicCyc2( 'languagesSpokenHere'/4).
dynamicCyc2( 'laterThan'/4).
dynamicCyc2( 'latitude'/4).
dynamicCyc2( 'lengthOfObject'/4).
dynamicCyc2( 'lengthOfPathTypeInRegion'/5).
dynamicCyc2( 'lessLikelyThan-Prior'/4).
dynamicCyc2( 'lexicalWordTypeForLanguage'/4).
dynamicCyc2( 'lightVerb-TransitiveSemTrans'/5).
dynamicCyc2( 'linksOfCustomarySystem'/4).
dynamicCyc2( 'listSetMembers'/4).
dynamicCyc2( 'literacyRateForGroupInRegion'/5).
dynamicCyc2( 'longitude'/4).
dynamicCyc2( 'majorReligions'/4).
dynamicCyc2( 'maleficiary'/4).
dynamicCyc2( 'massNounSemTrans'/6).
dynamicCyc2( 'massNumber'/4).
dynamicCyc2( 'memberStatusInOrganization'/5).
dynamicCyc2( 'microtheoryDesignationArgnum'/4).
dynamicCyc2( 'minimize'/3).
dynamicCyc2( 'minimizeExtent'/3).
dynamicCyc2( 'modalInArg'/4).
dynamicCyc2( 'morphologicalComposition'/5).
dynamicCyc2( 'morphologicallyDerivedFrom'/4).
dynamicCyc2( 'mtInferenceFunction'/4).
dynamicCyc2( 'multiplicationUnits'/5).
dynamicCyc2( 'multiWordSemTrans'/7).
dynamicCyc2( 'multiWordString'/6).
dynamicCyc2( 'multiWordStringDenotesArgInReln'/7).
dynamicCyc2( 'nameOfAgent'/4).
dynamicCyc2( 'nameString'/4).
dynamicCyc2( 'nationalBudgetExpenditures'/4).
dynamicCyc2( 'nationalLanguage'/4).
dynamicCyc2( 'naturalResourcesInRegion'/4).
dynamicCyc2( 'ncRuleConstraint'/4).
dynamicCyc2( 'ncRuleLabel'/4).
dynamicCyc2( 'ncRuleTemplate'/4).
dynamicCyc2( 'near'/4).
dynamicCyc2( 'negationAttribute'/4).
dynamicCyc2( 'negationInverse'/4).
dynamicCyc2( 'negationPreds'/4).
dynamicCyc2( 'negativeVestedInterest'/4).
dynamicCyc2( 'nicknames'/4).
dynamicCyc2( 'nlPhraseTypeForTemplateCategory'/4).
dynamicCyc2( 'no-GenQuant'/4).
dynamicCyc2( 'nonCompositionalVerbSemTrans'/5).
dynamicCyc2( 'nonGradableAdjectiveForm'/4).
dynamicCyc2( 'nonThirdSg-Present'/4).
dynamicCyc2( 'northeastOf'/4).
dynamicCyc2( 'northOf'/4).
dynamicCyc2( 'northwestOf'/4).
dynamicCyc2( 'logicallyNot'/3).
dynamicCyc2( 'notAssertible'/3).
dynamicCyc2( 'notAssertibleCollection'/3).
dynamicCyc2( 'notAssertibleMt'/3).
dynamicCyc2( 'nounPrep'/5).
dynamicCyc2( 'nounSemTrans'/6).
dynamicCyc2( 'nthLargestElement'/6).
dynamicCyc2( 'numInhabitants'/4).
dynamicCyc2( 'objectActedOn'/4).
dynamicCyc2( 'objectFoundInLocation'/4).
dynamicCyc2( 'obligatedAgent'/4).
dynamicCyc2( 'obligationParts'/4).
dynamicCyc2( 'occurrencesPerPeriod'/5).
dynamicCyc2( 'officialArmedForces'/4).
dynamicCyc2( 'oldConstantName'/4).
dynamicCyc2( 'opaqueArgument'/4).
dynamicCyc2( 'opponents'/4).
dynamicCyc2( 'opponentsInConflict'/5).
dynamicCyc2( 'oppositeAttributeValue'/4).
dynamicCyc2( 'oppositeDirection-Precise'/4).
dynamicCyc2( 'or'/4).
dynamicCyc2( 'overrides'/4).
dynamicCyc2( 'owns'/4).
dynamicCyc2( 'paraphraseCoercionAllowedFrom'/4).
dynamicCyc2( 'partitionedInto'/4).
dynamicCyc2( 'partOfSpeech'/5).
dynamicCyc2( 'pastTense-Universal'/4).
dynamicCyc2( 'pathBetween'/5).
dynamicCyc2( 'pathConnects'/5).
dynamicCyc2( 'pathFromToInSystem'/6).
dynamicCyc2( 'pathTerminus'/4).
dynamicCyc2( 'perfect'/4).
dynamicCyc2( 'performedBy'/4).
dynamicCyc2( 'performsInsAtLocation'/5).
dynamicCyc2( 'perpendicularVectors'/4).
dynamicCyc2( 'phoneticVariantOfPrefix'/5).
dynamicCyc2( 'phoneticVariantOfSuffix'/5).
dynamicCyc2( 'phraseTemplateArg'/4).
dynamicCyc2( 'physicalPartTypes'/4).
dynamicCyc2( 'placeName-ShortForm'/4).
dynamicCyc2( 'plural'/4).
dynamicCyc2( 'pluralVerb-Present'/4).
dynamicCyc2( 'pnMassNumber'/4).
dynamicCyc2( 'pnPlural'/4).
dynamicCyc2( 'pnSingular'/4).
dynamicCyc2( 'politenessOfWS'/6).
dynamicCyc2( 'populationDuring'/5).
dynamicCyc2( 'populationGrowthRate'/4).
dynamicCyc2( 'posBaseForms'/4).
dynamicCyc2( 'posForms'/4).
dynamicCyc2( 'posForTemplateCategory'/4).
dynamicCyc2( 'positiveVestedInterest'/4).
dynamicCyc2( 'posOfPhraseType'/4).
dynamicCyc2( 'posPredForTemplateCategory'/4).
dynamicCyc2( 'power-Military'/4).
dynamicCyc2( 'predicateForAction'/4).
dynamicCyc2( 'preferredGenUnit'/5).
dynamicCyc2( 'preferredNameString'/4).
dynamicCyc2( 'preferredTermStrings'/4).
dynamicCyc2( 'prefixString'/4).
dynamicCyc2( 'prepCollocation'/5).
dynamicCyc2( 'prepReln-Action'/6).
dynamicCyc2( 'prepReln-Object'/6).
dynamicCyc2( 'prepSemTrans'/6).
dynamicCyc2( 'presentParticiple'/4).
dynamicCyc2( 'presentTense-Universal'/4).
dynamicCyc2( 'preservesGenlsInArg'/4).
dynamicCyc2( 'prettyName'/4).
dynamicCyc2( 'primaryFunction'/5).
dynamicCyc2( 'priorProbability'/4).
dynamicCyc2( 'priorProbability-Range'/4).
dynamicCyc2( 'productionAmountDuring'/6).
dynamicCyc2( 'productionCapacity'/5).
dynamicCyc2( 'productionCapacityDuring'/6).
dynamicCyc2( 'productionQuotaDuring'/6).
dynamicCyc2( 'productionRateOfRegion'/5).
dynamicCyc2( 'productionValueOfIndustryDuring'/6).
dynamicCyc2( 'programAlgorithmInputs'/4).
dynamicCyc2( 'programAlgorithmInputs'/5).
dynamicCyc2( 'programAlgorithmInternals'/4).
dynamicCyc2( 'programAlgorithmOutputs'/4).
dynamicCyc2( 'programExpressionHasType'/4).
dynamicCyc2( 'programFunctionArity'/4).
dynamicCyc2( 'programFunctionIdentifier'/4).
dynamicCyc2( 'programFunctionOperator'/4).
dynamicCyc2( 'programIfConditionThenElse'/6).
dynamicCyc2( 'programObjectTypeRepresents'/4).
dynamicCyc2( 'programStrings'/4).
dynamicCyc2( 'programTypeStrings'/4).
dynamicCyc2( 'programWhileConditionDo'/5).
dynamicCyc2( 'properNounSemTrans'/6).
dynamicCyc2( 'psRuleArity'/4).
dynamicCyc2( 'psRuleCategory'/4).
dynamicCyc2( 'psRuleConstraint'/4).
dynamicCyc2( 'psRuleExample'/4).
dynamicCyc2( 'psRuleSemanticsFromDtr'/4).
dynamicCyc2( 'psRuleSemanticsHandler'/4).
dynamicCyc2( 'psRuleSyntacticHeadDtr'/4).
dynamicCyc2( 'psRuleTemplateBindings'/4).
dynamicCyc2( 'psRuleTemplateDtr'/4).
dynamicCyc2( 'purchaseFromFractionDuring'/7).
dynamicCyc2( 'purposeInEvent'/5).
dynamicCyc2( 'quotedArgument'/4).
dynamicCyc2( 'quotedCollection'/3).
dynamicCyc2( 'realGDPGrowthRateDuring'/5).
dynamicCyc2( 'realGNPGrowthRateDuring'/5).
dynamicCyc2( 'recipientOfInfo'/4).
dynamicCyc2( 'reformulationPrecondition'/5).
dynamicCyc2( 'reformulatorEquals'/4).
dynamicCyc2( 'reformulatorEquiv'/4).
dynamicCyc2( 'regionHasTransportMeans'/4).
dynamicCyc2( 'regionLacksTransportMeans'/4).
dynamicCyc2( 'regularAdverb'/4).
dynamicCyc2( 'regularDegree'/4).
dynamicCyc2( 'regularSuffix'/5).
dynamicCyc2( 'relatedArgPositions'/5).
dynamicCyc2( 'relationAll'/4).
dynamicCyc2( 'relationAllExists'/5).
dynamicCyc2( 'relationAllExistsCount'/6).
dynamicCyc2( 'relationAllExistsMany'/5).
dynamicCyc2( 'relationAllExistsMax'/6).
dynamicCyc2( 'relationAllExistsMin'/6).
dynamicCyc2( 'relationAllInstance'/5).
dynamicCyc2( 'relationExistsAll'/5).
dynamicCyc2( 'relationExistsAllMany'/5).
dynamicCyc2( 'relationExistsCountAll'/6).
dynamicCyc2( 'relationExistsInstance'/5).
dynamicCyc2( 'relationExistsMaxAll'/6).
dynamicCyc2( 'relationIndicators'/5).
dynamicCyc2( 'relationIndicators-Strong'/5).
dynamicCyc2( 'relationInstanceAll'/5).
dynamicCyc2( 'relationInstanceExists'/5).
dynamicCyc2( 'relationInstanceExistsCount'/6).
dynamicCyc2( 'relationInstanceExistsMany'/5).
dynamicCyc2( 'relationInstanceExistsMax'/6).
dynamicCyc2( 'relationInstanceExistsMin'/6).
dynamicCyc2( 'reliabilityOfMicrotheory'/4).
dynamicCyc2( 'requiredActorSlots'/4).
dynamicCyc2( 'requiredArg1Pred'/4).
dynamicCyc2( 'requiredArg2Pred'/4).
dynamicCyc2( 'residenceOfOrganization'/4).
dynamicCyc2( 'resultGenl'/4).
dynamicCyc2( 'resultGenlArg'/4).
dynamicCyc2( 'resultIsa'/4).
dynamicCyc2( 'resultIsaArg'/4).
dynamicCyc2( 'resultIsaArgIsa'/4).
dynamicCyc2( 'revenueFromProduct'/5).
dynamicCyc2( 'rewriteOf'/4).
dynamicCyc2( 'rolesForEventType'/4).
dynamicCyc2( 'saleToFractionDuring'/7).
dynamicCyc2( 'salientAssertions'/4).
dynamicCyc2( 'scientificName'/4).
dynamicCyc2( 'scopingArg'/4).
dynamicCyc2( 'secondPersonSg-Present'/4).
dynamicCyc2( 'sellsProductType'/4).
dynamicCyc2( 'semTransArg'/4).
dynamicCyc2( 'semTransPredForPOS'/4).
dynamicCyc2( 'senderOfInfo'/4).
dynamicCyc2( 'sentenceDesignationArgnum'/4).
dynamicCyc2( 'sharedNotes'/4).
dynamicCyc2( 'shortTimeIntervalAfter'/4).
dynamicCyc2( 'siblingDisjointExceptions'/4).
dynamicCyc2( 'singular'/4).
dynamicCyc2( 'skillRequired'/6).
dynamicCyc2( 'socialParticipants'/4).
dynamicCyc2( 'softwareParameterDomain'/4).
dynamicCyc2( 'softwareParameterHasType'/4).
dynamicCyc2( 'spatiallyIntersects'/4).
dynamicCyc2( 'spatiallyIntrinsicArg'/4).
dynamicCyc2( 'spatiallySubsumes'/4).
dynamicCyc2( 'speechPartPreds'/4).
dynamicCyc2( 'startingDate'/4).
dynamicCyc2( 'startingPoint'/4).
dynamicCyc2( 'startsAfterEndingOf'/4).
dynamicCyc2( 'startsAfterStartingOf'/4).
dynamicCyc2( 'startsDuring'/4).
dynamicCyc2( 'statementOfPurpose'/4).
dynamicCyc2( 'subBeliefSystem'/4).
dynamicCyc2( 'subcatFrame'/6).
dynamicCyc2( 'subcatFrameArity'/4).
dynamicCyc2( 'subcatFrameDependentConstraint'/5).
dynamicCyc2( 'subcatFrameDependentKeyword'/5).
dynamicCyc2( 'subcatFrameExample'/4).
dynamicCyc2( 'subcatFrameKeywords'/4).
dynamicCyc2( 'subEvents'/4).
dynamicCyc2( 'subEventType'/4).
dynamicCyc2( 'subEventTypes'/4).
dynamicCyc2( 'subGroups'/4).
dynamicCyc2( 'subIndustries'/4).
dynamicCyc2( 'subjectRoles'/4).
dynamicCyc2( 'subOrganizations'/4).
dynamicCyc2( 'subsumesIntervalType'/4).
dynamicCyc2( 'suffixString'/4).
dynamicCyc2( 'suffrageAge'/4).
dynamicCyc2( 'superlativeAdverb'/4).
dynamicCyc2( 'superlativeDegree'/4).
dynamicCyc2( 'superTaxons'/4).
dynamicCyc2( 'suppliedWithFrom'/5).
dynamicCyc2( 'supplyFromThroughAmountDuring'/8).
dynamicCyc2( 'supplyThroughAmountDuring'/7).
dynamicCyc2( 'surroundsHorizontally'/4).
dynamicCyc2( 'synonymousExternalConcept'/5).
dynamicCyc2( 'temporalBoundsContain'/4).
dynamicCyc2( 'temporallyCooriginating'/4).
dynamicCyc2( 'temporallyCoterminal'/4).
dynamicCyc2( 'temporallyIntrinsicArg'/4).
dynamicCyc2( 'temporallyStartedBy'/4).
dynamicCyc2( 'temporallySubsumes'/4).
dynamicCyc2( 'termDoesntNeedLexification'/3).
dynamicCyc2( 'termPOS-Strings'/5).
dynamicCyc2( 'termStrings'/4).
dynamicCyc2( 'termStrings-GuessedFromName'/4).
dynamicCyc2( 'territoriesControlled'/4).
dynamicCyc2( 'thereExistAtLeast'/5).
dynamicCyc2( 'thereExistExactly'/5).
dynamicCyc2( 'thereExists'/4).
dynamicCyc2( 'thirdPersonSg-Present'/4).
dynamicCyc2( 'timeIntervalBetween'/5).
dynamicCyc2( 'toBeReviewedBy'/4).
dynamicCyc2( 'topicOfIndividual'/4).
dynamicCyc2( 'topicOfInfoTransfer'/4).
dynamicCyc2( 'totalBudgetExpenditures'/5).
dynamicCyc2( 'totalReserves'/5).
dynamicCyc2( 'tradeBalanceDuring'/6).
dynamicCyc2( 'transitiveViaArg'/5).
dynamicCyc2( 'transitiveViaArgInverse'/5).
dynamicCyc2( 'transportedInTypes'/4).
dynamicCyc2( 'transportees'/4).
dynamicCyc2( 'transportFacilityFor'/4).
dynamicCyc2( 'trueRule'/4).
dynamicCyc2( 'typeBehaviorCapable'/5).
dynamicCyc2( 'typedGenlInverse'/4).
dynamicCyc2( 'typedGenlPreds'/4).
dynamicCyc2( 'typeGenls'/4).
dynamicCyc2( 'typeLevelVersionInArg'/7).
dynamicCyc2( 'unemploymentRateDuring'/5).
dynamicCyc2( 'uniquePartTypes'/4).
dynamicCyc2( 'unitExpansions'/4).
dynamicCyc2( 'unitMultiplicationFactor'/5).
dynamicCyc2( 'unitOfMeasurePrefixString'/4).
dynamicCyc2( unk_comment/3).
dynamicCyc2( 'useReformulationRuleForQuantifierProcessing'/3).
dynamicCyc2( 'variantOfSuffix'/4).
dynamicCyc2( 'verbPrep-Passive'/5).
dynamicCyc2( 'verbPrep-Transitive'/5).
dynamicCyc2( 'verbPrep-TransitiveTemplate'/5).
dynamicCyc2( 'verbSemTrans'/6).
dynamicCyc2( 'verbSemTransPartial'/6).
dynamicCyc2( 'verbSemTransTemplate'/5).
dynamicCyc2( 'victim'/4).
dynamicCyc2( 'widthOfObject'/4).
dynamicCyc2( 'wnAdjectiveParticiple'/6).
dynamicCyc2( 'wnAdjectivePertains'/6).
dynamicCyc2( 'wnAntonymous'/6).
dynamicCyc2( 'wnAttribute'/4).
dynamicCyc2( 'wnCauses'/4).
dynamicCyc2( 'wnEntailment'/4).
dynamicCyc2( 'wnFollowsInMeaning'/6).
dynamicCyc2( 'wnHypernym'/4).
dynamicCyc2( 'wnMemberMeronym'/4).
dynamicCyc2( 'wnPartMeronym'/4).
dynamicCyc2( 'wnS'/8).
dynamicCyc2( 'wnSimilarInMeaning'/4).
dynamicCyc2( 'wnSubstanceMeronym'/4).
dynamicCyc2( 'wnVerbsSimilarInMeaning'/4).
dynamicCyc2( 'wordInLanguage'/4).
dynamicCyc2( 'wornOn-TypeType'/4).
