:- module(nldata_colloc_pdat,[mws/2]).
:- dynamic((mws/2)).
:- multifile((mws/2)).

mws(['\'s','gravenhage'],n).
mws(['11','november'],n).
mws(['12-tone','music'],n).
mws(['12-tone','system'],n).
mws(['14','july'],n).
mws(['15','august','1945'],n).
mws(['15','may','organization'],n).
mws(['15','minutes'],n).
mws(['16','pf'],n).
mws(['17','november'],n).
mws(['18-karat','gold'],n).
mws([('1'),'chronicles'],n).
mws([('1'),'esdras'],n).
mws([('1'),'kings'],n).
mws([('1'),'maccabees'],n).
mws([('1'),'samuel'],n).
mws(['1st-class','mail'],n).
mws(['1st','baron','beaverbrook'],n).
mws(['1st','baron','verulam'],n).
mws(['1st','class'],n).
mws(['1st','earl','attlee'],n).
mws(['1st','earl','baldwin','of','bewdley'],n).
mws(['1st','earl','of','balfour'],n).
mws(['1st','viscount','montgomery','of','alamein'],n).
mws(['2-hydroxybenzoic','acid'],n).
mws(['2-methylpropenoic','acid'],n).
mws(['22-karat','gold'],n).
mws(['24-hour','interval'],n).
mws(['24-karat','gold'],n).
mws([('2'),'chronicles'],n).
mws([('2'),'esdras'],n).
mws([('2'),'kings'],n).
mws([('2'),'maccabees'],n).
mws([('2'),'samuel'],n).
mws(['30','minutes'],n).
mws(['365','days'],n).
mws(['366','days'],n).
mws(['3d','radar'],n).
mws(['3rd','october','organization'],n).
mws(['401-k','plan'],n).
mws(['440','yards'],n).
mws(['5-hydroxy-3-methylglutaryl-coenzyme','a','reductase'],n).
mws(['60','minutes'],n).
mws([('6'),'june','1944'],n).
mws(['880','yards'],n).
mws([('8'),'may','1945'],n).
mws(['a.','a.','michelson'],n).
mws(['a.','a.','milne'],n).
mws(['a.','conan','doyle'],n).
mws(['a.','e.','burnside'],n).
mws(['a.','e.','housman'],n).
mws(['a.','e.','kennelly'],n).
mws(['a.','e.','w.','mason'],n).
mws(['a.','noam','chomsky'],n).
mws(['a.','testudineus'],n).
mws(['a','battery'],n).
mws(['a','capella','singing'],n).
mws(['a','cappella','singing'],n).
mws(['a','horizon'],n).
mws(['a','kempis'],n).
mws(['a','la','carte'],n).
mws(['a','level'],n).
mws(['aaland','islands'],n).
mws(['aare','river'],n).
mws(['aaron\'s','rod'],n).
mws(['aaron','burr'],n).
mws(['aaron','copland'],n).
mws(['aaron','montgomery','ward'],n).
mws(['aba','cloth'],n).
mws(['aba','transit','number'],n).
mws(['abandoned','infant'],n).
mws(['abandoned','person'],n).
mws(['abandoned','ship'],n).
mws(['abasia','trepidans'],n).
mws(['abatable','nuisance'],n).
mws(['abatement','of','a','nuisance'],n).
mws(['abbe','condenser'],n).
mws(['abbott','lawrence','lowell'],n).
mws(['abdominal','actinomycosis'],n).
mws(['abdominal','aorta'],n).
mws(['abdominal','aortic','aneurysm'],n).
mws(['abdominal','breathing'],n).
mws(['abdominal','cavity'],n).
mws(['abdominal','delivery'],n).
mws(['abdominal','external','oblique','muscle'],n).
mws(['abdominal','muscle'],n).
mws(['abdominal','nerve','plexus'],n).
mws(['abdominal','pregnancy'],n).
mws(['abdominal','wall'],n).
mws(['abducens','muscle'],n).
mws(['abducens','nerve'],n).
mws(['abducent','nerve'],n).
mws(['abductor','muscle'],n).
mws(['abel','janszoon','tasman'],n).
mws(['abel','tasman'],n).
mws(['abelian','group'],n).
mws(['abelmoschus','esculentus'],n).
mws(['abelmoschus','moschatus'],n).
mws(['aberdeen','angus'],n).
mws(['abies','alba'],n).
mws(['abies','amabilis'],n).
mws(['abies','balsamea'],n).
mws(['abies','bracteata'],n).
mws(['abies','concolor'],n).
mws(['abies','fraseri'],n).
mws(['abies','grandis'],n).
mws(['abies','lasiocarpa'],n).
mws(['abies','lowiana'],n).
mws(['abies','venusta'],n).
mws(['ablative','absolute'],n).
mws(['ablative','case'],n).
mws(['able-bodied','seaman'],n).
mws(['able','seaman'],n).
mws(['abney','level'],n).
mws(['abnormal','condition'],n).
mws(['abnormal','psychology'],n).
mws(['abo','antibodies'],n).
mws(['abo','blood','group','system'],n).
mws(['abo','group'],n).
mws(['abo','system'],n).
mws(['abominable','snowman'],n).
mws(['aboriginal','australian'],n).
mws(['abortion-inducing','drug'],n).
mws(['abortion','pill'],n).
mws(['about','turn'],n).
mws(['abrading','stone'],n).
mws(['abraham\'s','bosom'],n).
mws(['abraham','lincoln'],n).
mws(['abraham','stoker'],n).
mws(['abramis','brama'],n).
mws(['abrasive','material'],n).
mws(['abronia','elliptica'],n).
mws(['abronia','fragrans'],n).
mws(['abronia','latifolia'],n).
mws(['abronia','maritima'],n).
mws(['abronia','umbellata'],n).
mws(['abronia','villosa'],n).
mws(['abruptio','placentae'],n).
mws(['abruptly-pinnate','leaf'],n).
mws(['abruzzi','e','molise'],n).
mws(['abscessed','tooth'],n).
mws(['absence','without','leave'],n).
mws(['absentee','ballot'],n).
mws(['absentee','rate'],n).
mws(['absinthe','oil'],n).
mws(['absolute','alcohol'],n).
mws(['absolute','ceiling'],n).
mws(['absolute','frequency'],n).
mws(['absolute','magnitude'],n).
mws(['absolute','majority'],n).
mws(['absolute','pitch'],n).
mws(['absolute','scale'],n).
mws(['absolute','space'],n).
mws(['absolute','temperature'],n).
mws(['absolute','threshold'],n).
mws(['absolute','value'],n).
mws(['absolute','viscosity'],n).
mws(['absolute','zero'],n).
mws(['absorbent','cotton'],n).
mws(['absorbent','material'],n).
mws(['absorption','band'],n).
mws(['absorption','coefficient'],n).
mws(['absorption','factor'],n).
mws(['absorption','indicator'],n).
mws(['absorption','spectrum'],n).
mws(['absorption','unit'],n).
mws(['abstract','art'],n).
mws(['abstract','artist'],n).
mws(['abstract','entity'],n).
mws(['abstract','expressionism'],n).
mws(['abstract','thought'],n).
mws(['abu','ali','al-husain','ibn','abdallah','ibn','sina'],n).
mws(['abu','dhabi'],n).

:- include('nldata_colloc_pdat.nldata').

