%%% automatically generated by src/prolog/lib/verbnet2boxer.pl
%%%
:- module(verbnet,[verbnet/3,verbnet/4]).
:- use_module(boxer(slashes)).

%%% wrapper
%%%
verbnet(A,B,C):- verbnet(A,B,C,_).

%%% File:    ext/VerbNet/accept-77.xml
%%% Primary: NP V how S (accept-77)
%%% Syntax:  [np:Agent,v,s:Theme]
%%% CCG:     (s:_\np)/s:_
%%% Roles:   [Theme,Agent]
%%% Example: I accept how you do it.
%%%
verbnet(accept, (s:_\np)/s:_, ['Theme','Agent'], [77]).
verbnet(understand, (s:_\np)/s:_, ['Theme','Agent'], [77]).
verbnet(encourage, (s:_\np)/s:_, ['Theme','Agent'], [77]).
verbnet(discourage, (s:_\np)/s:_, ['Theme','Agent'], [77]).
verbnet(disprefer, (s:_\np)/s:_, ['Theme','Agent'], [77]).
verbnet(reject, (s:_\np)/s:_, ['Theme','Agent'], [77]).
verbnet(repent, (s:_\np)/s:_, ['Theme','Agent'], [77]).
verbnet(rue, (s:_\np)/s:_, ['Theme','Agent'], [77]).

%%% File:    ext/VerbNet/accept-77.xml
%%% Primary: NP V NP (accept-77)
%%% Syntax:  [np:Agent,v,np:Theme]
%%% CCG:     (s:_\np)/np
%%% Roles:   [Theme,Agent]
%%% Example: I accepted it.
%%%
verbnet(accept, (s:_\np)/np, ['Theme','Agent'], [77]).
verbnet(understand, (s:_\np)/np, ['Theme','Agent'], [77]).
verbnet(encourage, (s:_\np)/np, ['Theme','Agent'], [77]).
verbnet(discourage, (s:_\np)/np, ['Theme','Agent'], [77]).
verbnet(disprefer, (s:_\np)/np, ['Theme','Agent'], [77]).
verbnet(reject, (s:_\np)/np, ['Theme','Agent'], [77]).
verbnet(repent, (s:_\np)/np, ['Theme','Agent'], [77]).
verbnet(rue, (s:_\np)/np, ['Theme','Agent'], [77]).

%%% File:    ext/VerbNet/accept-77.xml
%%% Primary: NP V S_ING (accept-77)
%%% Syntax:  [np:Agent,v,np:Theme]
%%% CCG:     (s:_\np)/np
%%% Roles:   [Theme,Agent]
%%% Example: I accepted their writing novels.
%%%
verbnet(accept, (s:_\np)/np, ['Theme','Agent'], [77]).
verbnet(understand, (s:_\np)/np, ['Theme','Agent'], [77]).
verbnet(encourage, (s:_\np)/np, ['Theme','Agent'], [77]).
verbnet(discourage, (s:_\np)/np, ['Theme','Agent'], [77]).
verbnet(disprefer, (s:_\np)/np, ['Theme','Agent'], [77]).
verbnet(reject, (s:_\np)/np, ['Theme','Agent'], [77]).
verbnet(repent, (s:_\np)/np, ['Theme','Agent'], [77]).
verbnet(rue, (s:_\np)/np, ['Theme','Agent'], [77]).

%%% File:    ext/VerbNet/accept-77.xml
%%% Primary: NP V that S (accept-77)
%%% Syntax:  [np:Agent,v,s:Theme]
%%% CCG:     (s:_\np)/s:_
%%% Roles:   [Theme,Agent]
%%% Example: I accepted that they wrote novels.
%%%
verbnet(accept, (s:_\np)/s:_, ['Theme','Agent'], [77]).
verbnet(understand, (s:_\np)/s:_, ['Theme','Agent'], [77]).
verbnet(encourage, (s:_\np)/s:_, ['Theme','Agent'], [77]).
verbnet(discourage, (s:_\np)/s:_, ['Theme','Agent'], [77]).
verbnet(disprefer, (s:_\np)/s:_, ['Theme','Agent'], [77]).
verbnet(reject, (s:_\np)/s:_, ['Theme','Agent'], [77]).
verbnet(repent, (s:_\np)/s:_, ['Theme','Agent'], [77]).
verbnet(rue, (s:_\np)/s:_, ['Theme','Agent'], [77]).

%%% File:    ext/VerbNet/accept-77.xml
%%% Primary: NP V what S (accept-77)
%%% Syntax:  [np:Agent,v,s:Theme]
%%% CCG:     (s:_\np)/s:_
%%% Roles:   [Theme,Agent]
%%% Example: I accepted what they were doing.
%%%
verbnet(accept, (s:_\np)/s:_, ['Theme','Agent'], [77]).
verbnet(understand, (s:_\np)/s:_, ['Theme','Agent'], [77]).
verbnet(encourage, (s:_\np)/s:_, ['Theme','Agent'], [77]).
verbnet(discourage, (s:_\np)/s:_, ['Theme','Agent'], [77]).
verbnet(disprefer, (s:_\np)/s:_, ['Theme','Agent'], [77]).
verbnet(reject, (s:_\np)/s:_, ['Theme','Agent'], [77]).
verbnet(repent, (s:_\np)/s:_, ['Theme','Agent'], [77]).
verbnet(rue, (s:_\np)/s:_, ['Theme','Agent'], [77]).

%%% File:    ext/VerbNet/accompany-51.7.xml
%%% Primary: NP V NP (accompany-51.7)
%%% Syntax:  [np:Agent,v,np:Theme]
%%% CCG:     (s:_\np)/np
%%% Roles:   [Theme,Agent]
%%% Example: Jackie accompanied Rose.
%%%
verbnet(accompany, (s:_\np)/np, ['Theme','Agent'], [51,'.',7]).
verbnet(conduct, (s:_\np)/np, ['Theme','Agent'], [51,'.',7]).
verbnet(escort, (s:_\np)/np, ['Theme','Agent'], [51,'.',7]).
verbnet(guide, (s:_\np)/np, ['Theme','Agent'], [51,'.',7]).
verbnet(lead, (s:_\np)/np, ['Theme','Agent'], [51,'.',7]).
verbnet(misdirect, (s:_\np)/np, ['Theme','Agent'], [51,'.',7]).
verbnet(shepherd, (s:_\np)/np, ['Theme','Agent'], [51,'.',7]).
verbnet(steer, (s:_\np)/np, ['Theme','Agent'], [51,'.',7]).

%%% File:    ext/VerbNet/accompany-51.7.xml
%%% Primary: NP V NP PP.destination (accompany-51.7)
%%% Syntax:  [np:Agent,v,np:Theme,pp,np:Destination]
%%% CCG:     ((s:_\np)/pp)/np
%%% Roles:   [Theme,Agent]
%%% Example: Jackie accompanied Rose to the store.
%%%
verbnet(accompany, ((s:_\np)/pp)/np, ['Theme','Agent'], [51,'.',7]).
verbnet(conduct, ((s:_\np)/pp)/np, ['Theme','Agent'], [51,'.',7]).
verbnet(escort, ((s:_\np)/pp)/np, ['Theme','Agent'], [51,'.',7]).
verbnet(guide, ((s:_\np)/pp)/np, ['Theme','Agent'], [51,'.',7]).
verbnet(lead, ((s:_\np)/pp)/np, ['Theme','Agent'], [51,'.',7]).
verbnet(misdirect, ((s:_\np)/pp)/np, ['Theme','Agent'], [51,'.',7]).
verbnet(shepherd, ((s:_\np)/pp)/np, ['Theme','Agent'], [51,'.',7]).
verbnet(steer, ((s:_\np)/pp)/np, ['Theme','Agent'], [51,'.',7]).

%%% File:    ext/VerbNet/acquiesce-95.xml
%%% Primary: NP V PP.co-agent (acquiesce-95)
%%% Syntax:  [np:Agent,v,prep:to,np:Co-Agent]
%%% CCG:     (s:_\np)/pp
%%% Roles:   [Agent]
%%% Example: The enemy soldiers submitted to us.
%%%
verbnet(acquiesce, (s:_\np)/pp, ['Agent'], [95]).
verbnet(submit, (s:_\np)/pp, ['Agent'], [95]).
verbnet(give_in, (s:_\np)/pp, ['Agent'], [95]).
verbnet(bow, (s:_\np)/pp, ['Agent'], [95]).
verbnet(defer, (s:_\np)/pp, ['Agent'], [95]).
verbnet(accede, (s:_\np)/pp, ['Agent'], [95]).
verbnet(succumb, (s:_\np)/pp, ['Agent'], [95]).
verbnet(yield, (s:_\np)/pp, ['Agent'], [95]).
verbnet(capitulate, (s:_\np)/pp, ['Agent'], [95]).
verbnet(to, pp/np, ['Agent'], [95]).

%%% File:    ext/VerbNet/acquiesce-95.xml
%%% Primary: NP V S_INF (acquiesce-95)
%%% Syntax:  [np:Agent,v,vp_to:Theme]
%%% CCG:     (s:_\np)/ (s:ng\np)
%%% Roles:   [Theme,Agent]
%%% Example: The king acquiesced to be in the same room with the paupers
%%%
verbnet(acquiesce, (s:_\np)/ (s:ng\np), ['Theme','Agent'], [95]).
verbnet(submit, (s:_\np)/ (s:ng\np), ['Theme','Agent'], [95]).
verbnet(give_in, (s:_\np)/ (s:ng\np), ['Theme','Agent'], [95]).
verbnet(bow, (s:_\np)/ (s:ng\np), ['Theme','Agent'], [95]).
verbnet(defer, (s:_\np)/ (s:ng\np), ['Theme','Agent'], [95]).
verbnet(accede, (s:_\np)/ (s:ng\np), ['Theme','Agent'], [95]).
verbnet(succumb, (s:_\np)/ (s:ng\np), ['Theme','Agent'], [95]).
verbnet(yield, (s:_\np)/ (s:ng\np), ['Theme','Agent'], [95]).
verbnet(capitulate, (s:_\np)/ (s:ng\np), ['Theme','Agent'], [95]).

%%% File:    ext/VerbNet/acquiesce-95.xml
%%% Primary: NP V PP.theme (acquiesce-95)
%%% Syntax:  [np:Agent,v,prep:to,np:Theme]
%%% CCG:     (s:_\np)/pp
%%% Roles:   [Agent]
%%% Example: The enemy soldiers submitted to demands.
%%%
verbnet(acquiesce, (s:_\np)/pp, ['Agent'], [95]).
verbnet(submit, (s:_\np)/pp, ['Agent'], [95]).
verbnet(give_in, (s:_\np)/pp, ['Agent'], [95]).
verbnet(bow, (s:_\np)/pp, ['Agent'], [95]).
verbnet(defer, (s:_\np)/pp, ['Agent'], [95]).
verbnet(accede, (s:_\np)/pp, ['Agent'], [95]).
verbnet(succumb, (s:_\np)/pp, ['Agent'], [95]).
verbnet(yield, (s:_\np)/pp, ['Agent'], [95]).
verbnet(capitulate, (s:_\np)/pp, ['Agent'], [95]).
verbnet(to, pp/np, ['Theme'], [95]).

%%% File:    ext/VerbNet/addict-96.xml
%%% Primary: NP V NP PP.stimulus (addict-96)
%%% Syntax:  [np:Agent,v,np:Patient,prep:to,np:Stimulus]
%%% CCG:     ((s:_\np)/pp)/np
%%% Roles:   [Patient,Agent]
%%% Example: I addicted him to Douglas Adams.
%%%
verbnet(addict, ((s:_\np)/pp)/np, ['Patient','Agent'], [96]).
verbnet(bias, ((s:_\np)/pp)/np, ['Patient','Agent'], [96]).
verbnet(dispose, ((s:_\np)/pp)/np, ['Patient','Agent'], [96]).
verbnet(incline, ((s:_\np)/pp)/np, ['Patient','Agent'], [96]).
verbnet(predispose, ((s:_\np)/pp)/np, ['Patient','Agent'], [96]).
verbnet(woo, ((s:_\np)/pp)/np, ['Patient','Agent'], [96]).
verbnet(slant, ((s:_\np)/pp)/np, ['Patient','Agent'], [96]).
verbnet(to, pp/np, ['Stimulus'], [96]).

%%% File:    ext/VerbNet/addict-96.xml
%%% Primary: NP V NP S_ING (addict-96)
%%% Syntax:  [np:Agent,v,np:Patient,prep:to,np:Stimulus]
%%% CCG:     ((s:_\np)/pp)/np
%%% Roles:   [Patient,Agent]
%%% Example: Mary addicted him to going on long journeys.
%%%
verbnet(addict, ((s:_\np)/pp)/np, ['Patient','Agent'], [96]).
verbnet(bias, ((s:_\np)/pp)/np, ['Patient','Agent'], [96]).
verbnet(dispose, ((s:_\np)/pp)/np, ['Patient','Agent'], [96]).
verbnet(incline, ((s:_\np)/pp)/np, ['Patient','Agent'], [96]).
verbnet(predispose, ((s:_\np)/pp)/np, ['Patient','Agent'], [96]).
verbnet(woo, ((s:_\np)/pp)/np, ['Patient','Agent'], [96]).
verbnet(slant, ((s:_\np)/pp)/np, ['Patient','Agent'], [96]).
verbnet(to, pp/np, ['Stimulus'], [96]).

%%% File:    ext/VerbNet/adjust-26.9.xml
%%% Primary: NP V NP (adjust-26.9)
%%% Syntax:  [np:Agent,v,np:Patient]
%%% CCG:     (s:_\np)/np
%%% Roles:   [Patient,Agent]
%%% Example: He adapted himself.
%%%
verbnet(adapt, (s:_\np)/np, ['Patient','Agent'], [26,'.',9]).
verbnet(accommodate, (s:_\np)/np, ['Patient','Agent'], [26,'.',9]).
verbnet(conform, (s:_\np)/np, ['Patient','Agent'], [26,'.',9]).
verbnet(adjust, (s:_\np)/np, ['Patient','Agent'], [26,'.',9]).
verbnet(gear, (s:_\np)/np, ['Patient','Agent'], [26,'.',9]).
verbnet(fit, (s:_\np)/np, ['Patient','Agent'], [26,'.',9]).
verbnet(readjust, (s:_\np)/np, ['Patient','Agent'], [26,'.',9]).
verbnet(readapt, (s:_\np)/np, ['Patient','Agent'], [26,'.',9]).
verbnet(assimilate, (s:_\np)/np, ['Patient','Agent'], [26,'.',9]).

%%% File:    ext/VerbNet/adjust-26.9.xml
%%% Primary: NP V NP PP (adjust-26.9)
%%% Syntax:  [np:Agent,v,np:Patient,prep:to,np:Goal]
%%% CCG:     ((s:_\np)/pp)/np
%%% Roles:   [Patient,Agent]
%%% Example: He adapted himself to the situation.
%%%
verbnet(adapt, ((s:_\np)/pp)/np, ['Patient','Agent'], [26,'.',9]).
verbnet(accommodate, ((s:_\np)/pp)/np, ['Patient','Agent'], [26,'.',9]).
verbnet(conform, ((s:_\np)/pp)/np, ['Patient','Agent'], [26,'.',9]).
verbnet(adjust, ((s:_\np)/pp)/np, ['Patient','Agent'], [26,'.',9]).
verbnet(gear, ((s:_\np)/pp)/np, ['Patient','Agent'], [26,'.',9]).
verbnet(fit, ((s:_\np)/pp)/np, ['Patient','Agent'], [26,'.',9]).
verbnet(readjust, ((s:_\np)/pp)/np, ['Patient','Agent'], [26,'.',9]).
verbnet(readapt, ((s:_\np)/pp)/np, ['Patient','Agent'], [26,'.',9]).
verbnet(assimilate, ((s:_\np)/pp)/np, ['Patient','Agent'], [26,'.',9]).
verbnet(to, pp/np, ['Goal'], [26,.,9]).

%%% File:    ext/VerbNet/adjust-26.9.xml
%%% Primary: NP V NP S_ING (adjust-26.9)
%%% Syntax:  [np:Agent,v,np:Patient,prep:to,vp_ng:Goal]
%%% CCG:     ((s:_\np)/pp)/np
%%% Roles:   [Patient,Agent]
%%% Example: He adapted himself to waking up early.
%%%
verbnet(adapt, ((s:_\np)/pp)/np, ['Patient','Agent'], [26,'.',9]).
verbnet(accommodate, ((s:_\np)/pp)/np, ['Patient','Agent'], [26,'.',9]).
verbnet(conform, ((s:_\np)/pp)/np, ['Patient','Agent'], [26,'.',9]).
verbnet(adjust, ((s:_\np)/pp)/np, ['Patient','Agent'], [26,'.',9]).
verbnet(gear, ((s:_\np)/pp)/np, ['Patient','Agent'], [26,'.',9]).
verbnet(fit, ((s:_\np)/pp)/np, ['Patient','Agent'], [26,'.',9]).
verbnet(readjust, ((s:_\np)/pp)/np, ['Patient','Agent'], [26,'.',9]).
verbnet(readapt, ((s:_\np)/pp)/np, ['Patient','Agent'], [26,'.',9]).
verbnet(assimilate, ((s:_\np)/pp)/np, ['Patient','Agent'], [26,'.',9]).
verbnet(to, pp/(s:ng\np), ['Goal'], [26,.,9]).

%%% File:    ext/VerbNet/adjust-26.9.xml
%%% Primary: NP V S_ING (adjust-26.9)
%%% Syntax:  [np:Agent,v,prep:to,np:Goal]
%%% CCG:     (s:_\np)/pp
%%% Roles:   [Agent]
%%% Example: He adapted to waking up early.
%%%
verbnet(adapt, (s:_\np)/pp, ['Agent'], [26,'.',9]).
verbnet(accommodate, (s:_\np)/pp, ['Agent'], [26,'.',9]).
verbnet(conform, (s:_\np)/pp, ['Agent'], [26,'.',9]).
verbnet(adjust, (s:_\np)/pp, ['Agent'], [26,'.',9]).
verbnet(gear, (s:_\np)/pp, ['Agent'], [26,'.',9]).
verbnet(fit, (s:_\np)/pp, ['Agent'], [26,'.',9]).
verbnet(readjust, (s:_\np)/pp, ['Agent'], [26,'.',9]).
verbnet(readapt, (s:_\np)/pp, ['Agent'], [26,'.',9]).
verbnet(assimilate, (s:_\np)/pp, ['Agent'], [26,'.',9]).
verbnet(to, pp/np, ['Goal'], [26,.,9]).

%%% File:    ext/VerbNet/adjust-26.9.xml
%%% Primary: NP V PP (adjust-26.9)
%%% Syntax:  [np:Agent,v,prep:to,np:Goal]
%%% CCG:     (s:_\np)/pp
%%% Roles:   [Agent]
%%% Example: He adapted to the situation.
%%%
verbnet(adapt, (s:_\np)/pp, ['Agent'], [26,'.',9]).
verbnet(accommodate, (s:_\np)/pp, ['Agent'], [26,'.',9]).
verbnet(conform, (s:_\np)/pp, ['Agent'], [26,'.',9]).
verbnet(adjust, (s:_\np)/pp, ['Agent'], [26,'.',9]).
verbnet(gear, (s:_\np)/pp, ['Agent'], [26,'.',9]).
verbnet(fit, (s:_\np)/pp, ['Agent'], [26,'.',9]).
verbnet(readjust, (s:_\np)/pp, ['Agent'], [26,'.',9]).
verbnet(readapt, (s:_\np)/pp, ['Agent'], [26,'.',9]).
verbnet(assimilate, (s:_\np)/pp, ['Agent'], [26,'.',9]).
verbnet(to, pp/np, ['Goal'], [26,.,9]).

%%% File:    ext/VerbNet/admire-31.2.xml
%%% Primary: NP V S_INF (admire-31.2-1)
%%% Syntax:  [np:Experiencer,v,vp_to:Stimulus]
%%% CCG:     (s:_\np)/ (s:ng\np)
%%% Roles:   [Stimulus,Experiencer]
%%% Example: I loved to write.
%%%
verbnet(despise, (s:_\np)/ (s:ng\np), ['Stimulus','Experiencer'], [31,'.',2,-,1]).
verbnet(detest, (s:_\np)/ (s:ng\np), ['Stimulus','Experiencer'], [31,'.',2,-,1]).
verbnet(disdain, (s:_\np)/ (s:ng\np), ['Stimulus','Experiencer'], [31,'.',2,-,1]).
verbnet(dislike, (s:_\np)/ (s:ng\np), ['Stimulus','Experiencer'], [31,'.',2,-,1]).
verbnet(regret, (s:_\np)/ (s:ng\np), ['Stimulus','Experiencer'], [31,'.',2,-,1]).
verbnet(like, (s:_\np)/ (s:ng\np), ['Stimulus','Experiencer'], [31,'.',2,-,1]).
verbnet(love, (s:_\np)/ (s:ng\np), ['Stimulus','Experiencer'], [31,'.',2,-,1]).
verbnet(enjoy, (s:_\np)/ (s:ng\np), ['Stimulus','Experiencer'], [31,'.',2,-,1]).
verbnet(fear, (s:_\np)/ (s:ng\np), ['Stimulus','Experiencer'], [31,'.',2,-,1]).
verbnet(hate, (s:_\np)/ (s:ng\np), ['Stimulus','Experiencer'], [31,'.',2,-,1]).

%%% File:    ext/VerbNet/admire-31.2.xml
%%% Primary: NP V NP (admire-31.2)
%%% Syntax:  [np:Experiencer,v,np:Stimulus]
%%% CCG:     (s:_\np)/np
%%% Roles:   [Stimulus,Experiencer]
%%% Example: The tourists admired the paintings.
%%%
verbnet(despise, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(detest, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(disdain, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(dislike, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(regret, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(like, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(love, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(enjoy, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(fear, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(hate, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(admire, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(adore, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(appreciate, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(applaud, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(bear, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(bewail, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(cherish, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(deify, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(disbelieve, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(esteem, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(exalt, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(fancy, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(favor, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(grudge, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(idolize, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(miss, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(prefer, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(affirm, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(reaffirm, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(prize, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(respect, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(relish, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(revere, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(savor, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(stand, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(support, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(tolerate, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(treasure, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(trust, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(value, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(venerate, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(worship, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(abhor, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(deplore, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(distrust, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(dread, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(envy, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(execrate, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(lament, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(loathe, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(mourn, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(pity, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(resent, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(rue, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(believe, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(suffer, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).

%%% File:    ext/VerbNet/admire-31.2.xml
%%% Primary: NP V NP PP.attribute (admire-31.2)
%%% Syntax:  [np:Experiencer,v,np:Stimulus,prep:for,np:Attribute]
%%% CCG:     ((s:_\np)/pp)/np
%%% Roles:   [Stimulus,Experiencer]
%%% Example: I admired him for his honesty.
%%%
verbnet(despise, ((s:_\np)/pp)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(detest, ((s:_\np)/pp)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(disdain, ((s:_\np)/pp)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(dislike, ((s:_\np)/pp)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(regret, ((s:_\np)/pp)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(like, ((s:_\np)/pp)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(love, ((s:_\np)/pp)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(enjoy, ((s:_\np)/pp)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(fear, ((s:_\np)/pp)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(hate, ((s:_\np)/pp)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(admire, ((s:_\np)/pp)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(adore, ((s:_\np)/pp)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(appreciate, ((s:_\np)/pp)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(applaud, ((s:_\np)/pp)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(bear, ((s:_\np)/pp)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(bewail, ((s:_\np)/pp)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(cherish, ((s:_\np)/pp)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(deify, ((s:_\np)/pp)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(disbelieve, ((s:_\np)/pp)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(esteem, ((s:_\np)/pp)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(exalt, ((s:_\np)/pp)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(fancy, ((s:_\np)/pp)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(favor, ((s:_\np)/pp)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(grudge, ((s:_\np)/pp)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(idolize, ((s:_\np)/pp)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(miss, ((s:_\np)/pp)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(prefer, ((s:_\np)/pp)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(affirm, ((s:_\np)/pp)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(reaffirm, ((s:_\np)/pp)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(prize, ((s:_\np)/pp)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(respect, ((s:_\np)/pp)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(relish, ((s:_\np)/pp)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(revere, ((s:_\np)/pp)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(savor, ((s:_\np)/pp)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(stand, ((s:_\np)/pp)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(support, ((s:_\np)/pp)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(tolerate, ((s:_\np)/pp)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(treasure, ((s:_\np)/pp)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(trust, ((s:_\np)/pp)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(value, ((s:_\np)/pp)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(venerate, ((s:_\np)/pp)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(worship, ((s:_\np)/pp)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(abhor, ((s:_\np)/pp)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(deplore, ((s:_\np)/pp)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(distrust, ((s:_\np)/pp)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(dread, ((s:_\np)/pp)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(envy, ((s:_\np)/pp)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(execrate, ((s:_\np)/pp)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(lament, ((s:_\np)/pp)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(loathe, ((s:_\np)/pp)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(mourn, ((s:_\np)/pp)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(pity, ((s:_\np)/pp)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(resent, ((s:_\np)/pp)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(rue, ((s:_\np)/pp)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(believe, ((s:_\np)/pp)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(suffer, ((s:_\np)/pp)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(for, pp/np, ['Attribute'], [31,.,2]).

%%% File:    ext/VerbNet/admire-31.2.xml
%%% Primary: NP V NP.stimulus (admire-31.2)
%%% Syntax:  [np:Experiencer,v,np:Stimulus]
%%% CCG:     (s:_\np)/np
%%% Roles:   [Stimulus,Experiencer]
%%% Example: I admired the honesty in him.
%%%
verbnet(despise, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(detest, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(disdain, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(dislike, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(regret, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(like, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(love, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(enjoy, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(fear, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(hate, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(admire, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(adore, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(appreciate, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(applaud, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(bear, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(bewail, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(cherish, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(deify, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(disbelieve, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(esteem, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(exalt, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(fancy, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(favor, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(grudge, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(idolize, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(miss, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(prefer, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(affirm, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(reaffirm, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(prize, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(respect, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(relish, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(revere, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(savor, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(stand, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(support, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(tolerate, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(treasure, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(trust, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(value, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(venerate, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(worship, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(abhor, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(deplore, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(distrust, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(dread, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(envy, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(execrate, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(lament, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(loathe, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(mourn, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(pity, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(resent, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(rue, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(believe, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(suffer, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).

%%% File:    ext/VerbNet/admire-31.2.xml
%%% Primary: NP V that S (admire-31.2)
%%% Syntax:  [np:Experiencer,v,s:Stimulus]
%%% CCG:     (s:_\np)/s:_
%%% Roles:   [Stimulus,Experiencer]
%%% Example: The children liked that the clown had a red nose.
%%%
verbnet(despise, (s:_\np)/s:_, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(detest, (s:_\np)/s:_, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(disdain, (s:_\np)/s:_, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(dislike, (s:_\np)/s:_, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(regret, (s:_\np)/s:_, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(like, (s:_\np)/s:_, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(love, (s:_\np)/s:_, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(enjoy, (s:_\np)/s:_, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(fear, (s:_\np)/s:_, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(hate, (s:_\np)/s:_, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(admire, (s:_\np)/s:_, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(adore, (s:_\np)/s:_, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(appreciate, (s:_\np)/s:_, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(applaud, (s:_\np)/s:_, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(bear, (s:_\np)/s:_, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(bewail, (s:_\np)/s:_, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(cherish, (s:_\np)/s:_, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(deify, (s:_\np)/s:_, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(disbelieve, (s:_\np)/s:_, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(esteem, (s:_\np)/s:_, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(exalt, (s:_\np)/s:_, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(fancy, (s:_\np)/s:_, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(favor, (s:_\np)/s:_, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(grudge, (s:_\np)/s:_, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(idolize, (s:_\np)/s:_, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(miss, (s:_\np)/s:_, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(prefer, (s:_\np)/s:_, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(affirm, (s:_\np)/s:_, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(reaffirm, (s:_\np)/s:_, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(prize, (s:_\np)/s:_, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(respect, (s:_\np)/s:_, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(relish, (s:_\np)/s:_, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(revere, (s:_\np)/s:_, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(savor, (s:_\np)/s:_, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(stand, (s:_\np)/s:_, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(support, (s:_\np)/s:_, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(tolerate, (s:_\np)/s:_, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(treasure, (s:_\np)/s:_, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(trust, (s:_\np)/s:_, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(value, (s:_\np)/s:_, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(venerate, (s:_\np)/s:_, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(worship, (s:_\np)/s:_, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(abhor, (s:_\np)/s:_, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(deplore, (s:_\np)/s:_, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(distrust, (s:_\np)/s:_, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(dread, (s:_\np)/s:_, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(envy, (s:_\np)/s:_, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(execrate, (s:_\np)/s:_, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(lament, (s:_\np)/s:_, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(loathe, (s:_\np)/s:_, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(mourn, (s:_\np)/s:_, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(pity, (s:_\np)/s:_, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(resent, (s:_\np)/s:_, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(rue, (s:_\np)/s:_, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(believe, (s:_\np)/s:_, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(suffer, (s:_\np)/s:_, ['Stimulus','Experiencer'], [31,'.',2]).

%%% File:    ext/VerbNet/admire-31.2.xml
%%% Primary: NP V S_ING (admire-31.2)
%%% Syntax:  [np:Experiencer,v,vp_ng:Stimulus]
%%% CCG:     (s:_\np)/ (s:ng\np)
%%% Roles:   [Stimulus,Experiencer]
%%% Example: I loved writing.
%%%
verbnet(despise, (s:_\np)/ (s:ng\np), ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(detest, (s:_\np)/ (s:ng\np), ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(disdain, (s:_\np)/ (s:ng\np), ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(dislike, (s:_\np)/ (s:ng\np), ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(regret, (s:_\np)/ (s:ng\np), ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(like, (s:_\np)/ (s:ng\np), ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(love, (s:_\np)/ (s:ng\np), ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(enjoy, (s:_\np)/ (s:ng\np), ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(fear, (s:_\np)/ (s:ng\np), ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(hate, (s:_\np)/ (s:ng\np), ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(admire, (s:_\np)/ (s:ng\np), ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(adore, (s:_\np)/ (s:ng\np), ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(appreciate, (s:_\np)/ (s:ng\np), ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(applaud, (s:_\np)/ (s:ng\np), ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(bear, (s:_\np)/ (s:ng\np), ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(bewail, (s:_\np)/ (s:ng\np), ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(cherish, (s:_\np)/ (s:ng\np), ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(deify, (s:_\np)/ (s:ng\np), ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(disbelieve, (s:_\np)/ (s:ng\np), ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(esteem, (s:_\np)/ (s:ng\np), ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(exalt, (s:_\np)/ (s:ng\np), ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(fancy, (s:_\np)/ (s:ng\np), ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(favor, (s:_\np)/ (s:ng\np), ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(grudge, (s:_\np)/ (s:ng\np), ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(idolize, (s:_\np)/ (s:ng\np), ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(miss, (s:_\np)/ (s:ng\np), ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(prefer, (s:_\np)/ (s:ng\np), ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(affirm, (s:_\np)/ (s:ng\np), ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(reaffirm, (s:_\np)/ (s:ng\np), ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(prize, (s:_\np)/ (s:ng\np), ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(respect, (s:_\np)/ (s:ng\np), ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(relish, (s:_\np)/ (s:ng\np), ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(revere, (s:_\np)/ (s:ng\np), ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(savor, (s:_\np)/ (s:ng\np), ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(stand, (s:_\np)/ (s:ng\np), ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(support, (s:_\np)/ (s:ng\np), ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(tolerate, (s:_\np)/ (s:ng\np), ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(treasure, (s:_\np)/ (s:ng\np), ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(trust, (s:_\np)/ (s:ng\np), ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(value, (s:_\np)/ (s:ng\np), ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(venerate, (s:_\np)/ (s:ng\np), ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(worship, (s:_\np)/ (s:ng\np), ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(abhor, (s:_\np)/ (s:ng\np), ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(deplore, (s:_\np)/ (s:ng\np), ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(distrust, (s:_\np)/ (s:ng\np), ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(dread, (s:_\np)/ (s:ng\np), ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(envy, (s:_\np)/ (s:ng\np), ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(execrate, (s:_\np)/ (s:ng\np), ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(lament, (s:_\np)/ (s:ng\np), ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(loathe, (s:_\np)/ (s:ng\np), ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(mourn, (s:_\np)/ (s:ng\np), ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(pity, (s:_\np)/ (s:ng\np), ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(resent, (s:_\np)/ (s:ng\np), ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(rue, (s:_\np)/ (s:ng\np), ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(believe, (s:_\np)/ (s:ng\np), ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(suffer, (s:_\np)/ (s:ng\np), ['Stimulus','Experiencer'], [31,'.',2]).

%%% File:    ext/VerbNet/admire-31.2.xml
%%% Primary: NP V NP S_ING (admire-31.2)
%%% Syntax:  [np:Experiencer,v,np:Stimulus]
%%% CCG:     (s:_\np)/np
%%% Roles:   [Stimulus,Experiencer]
%%% Example: I loved him writing novels.
%%%
verbnet(despise, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(detest, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(disdain, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(dislike, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(regret, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(like, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(love, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(enjoy, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(fear, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(hate, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(admire, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(adore, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(appreciate, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(applaud, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(bear, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(bewail, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(cherish, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(deify, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(disbelieve, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(esteem, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(exalt, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(fancy, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(favor, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(grudge, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(idolize, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(miss, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(prefer, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(affirm, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(reaffirm, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(prize, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(respect, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(relish, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(revere, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(savor, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(stand, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(support, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(tolerate, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(treasure, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(trust, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(value, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(venerate, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(worship, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(abhor, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(deplore, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(distrust, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(dread, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(envy, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(execrate, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(lament, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(loathe, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(mourn, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(pity, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(resent, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(rue, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(believe, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).
verbnet(suffer, (s:_\np)/np, ['Stimulus','Experiencer'], [31,'.',2]).

%%% File:    ext/VerbNet/admit-65.xml
%%% Primary: NP V NP (admit-65)
%%% Syntax:  [np:Agent,v,np:Theme]
%%% CCG:     (s:_\np)/np
%%% Roles:   [Theme,Agent]
%%% Example: She admitted us.
%%%
verbnet(admit, (s:_\np)/np, ['Theme','Agent'], [65]).
verbnet(allow, (s:_\np)/np, ['Theme','Agent'], [65]).
verbnet(exclude, (s:_\np)/np, ['Theme','Agent'], [65]).
verbnet(include, (s:_\np)/np, ['Theme','Agent'], [65]).
verbnet(permit, (s:_\np)/np, ['Theme','Agent'], [65]).
verbnet(welcome, (s:_\np)/np, ['Theme','Agent'], [65]).

%%% File:    ext/VerbNet/admit-65.xml
%%% Primary: NP V NP ADV (admit-65)
%%% Syntax:  [np:Agent,v,np:Theme,np:Location]
%%% CCG:     ((s:_\np)/np)/np
%%% Roles:   [Theme,Location,Agent]
%%% Example: She admitted us here.
%%%
verbnet(admit, ((s:_\np)/np)/np, ['Theme','Location','Agent'], [65]).
verbnet(allow, ((s:_\np)/np)/np, ['Theme','Location','Agent'], [65]).
verbnet(exclude, ((s:_\np)/np)/np, ['Theme','Location','Agent'], [65]).
verbnet(include, ((s:_\np)/np)/np, ['Theme','Location','Agent'], [65]).
verbnet(permit, ((s:_\np)/np)/np, ['Theme','Location','Agent'], [65]).
verbnet(welcome, ((s:_\np)/np)/np, ['Theme','Location','Agent'], [65]).

%%% File:    ext/VerbNet/admit-65.xml
%%% Primary: NP V NP PP.location (admit-65)
%%% Syntax:  [np:Agent,v,np:Theme,pp,np:Location]
%%% CCG:     ((s:_\np)/pp)/np
%%% Roles:   [Theme,Agent]
%%% Example: She allowed us near the house.
%%%
verbnet(admit, ((s:_\np)/pp)/np, ['Theme','Agent'], [65]).
verbnet(allow, ((s:_\np)/pp)/np, ['Theme','Agent'], [65]).
verbnet(exclude, ((s:_\np)/pp)/np, ['Theme','Agent'], [65]).
verbnet(include, ((s:_\np)/pp)/np, ['Theme','Agent'], [65]).
verbnet(permit, ((s:_\np)/pp)/np, ['Theme','Agent'], [65]).
verbnet(welcome, ((s:_\np)/pp)/np, ['Theme','Agent'], [65]).

%%% File:    ext/VerbNet/adopt-93.xml
%%% Primary: NP V NP (adopt-93)
%%% Syntax:  [np:Agent,v,np:Theme]
%%% CCG:     (s:_\np)/np
%%% Roles:   [Theme,Agent]
%%% Example: Soon, the new President will assume office.
%%%
verbnet(assume, (s:_\np)/np, ['Theme','Agent'], [93]).
verbnet(adopt, (s:_\np)/np, ['Theme','Agent'], [93]).
verbnet(take_over, (s:_\np)/np, ['Theme','Agent'], [93]).
verbnet(take_on, (s:_\np)/np, ['Theme','Agent'], [93]).

%%% File:    ext/VerbNet/advise-37.9.xml
%%% Primary: NP V PP.topic (advise-37.9-1)
%%% Syntax:  [np:Agent,v,prep:against about concerning on regarding respecting,np:Topic]
%%% CCG:     (s:_\np)/pp
%%% Roles:   [Agent]
%%% Example: Ellen warned against skating on thin ice.
%%%
verbnet(admonish, (s:_\np)/pp, ['Agent'], [37,'.',9,-,1]).
verbnet(advise, (s:_\np)/pp, ['Agent'], [37,'.',9,-,1]).
verbnet(caution, (s:_\np)/pp, ['Agent'], [37,'.',9,-,1]).
verbnet(counsel, (s:_\np)/pp, ['Agent'], [37,'.',9,-,1]).
verbnet(instruct, (s:_\np)/pp, ['Agent'], [37,'.',9,-,1]).
verbnet(warn, (s:_\np)/pp, ['Agent'], [37,'.',9,-,1]).
verbnet(against, pp/np, ['Topic'], [37,.,9,-,1]).
verbnet(about, pp/np, ['Topic'], [37,.,9,-,1]).
verbnet(concerning, pp/np, ['Topic'], [37,.,9,-,1]).
verbnet(on, pp/np, ['Topic'], [37,.,9,-,1]).
verbnet(regarding, pp/np, ['Topic'], [37,.,9,-,1]).
verbnet(respecting, pp/np, ['Topic'], [37,.,9,-,1]).

%%% File:    ext/VerbNet/advise-37.9.xml
%%% Primary: NP V that S (advise-37.9-1)
%%% Syntax:  [np:Agent,v,s:Topic]
%%% CCG:     (s:_\np)/s:_
%%% Roles:   [Topic,Agent]
%%% Example: Ellen warned that the party would be tonight.
%%%
verbnet(admonish, (s:_\np)/s:_, ['Topic','Agent'], [37,'.',9,-,1]).
verbnet(advise, (s:_\np)/s:_, ['Topic','Agent'], [37,'.',9,-,1]).
verbnet(caution, (s:_\np)/s:_, ['Topic','Agent'], [37,'.',9,-,1]).
verbnet(counsel, (s:_\np)/s:_, ['Topic','Agent'], [37,'.',9,-,1]).
verbnet(instruct, (s:_\np)/s:_, ['Topic','Agent'], [37,'.',9,-,1]).
verbnet(warn, (s:_\np)/s:_, ['Topic','Agent'], [37,'.',9,-,1]).

%%% File:    ext/VerbNet/advise-37.9.xml
%%% Primary: NP V how S_INF (advise-37.9-1)
%%% Syntax:  [np:Agent,v,s:Topic]
%%% CCG:     (s:_\np)/s:_
%%% Roles:   [Topic,Agent]
%%% Example: Ellen warned how to avoid the crowd.
%%%
verbnet(admonish, (s:_\np)/s:_, ['Topic','Agent'], [37,'.',9,-,1]).
verbnet(advise, (s:_\np)/s:_, ['Topic','Agent'], [37,'.',9,-,1]).
verbnet(caution, (s:_\np)/s:_, ['Topic','Agent'], [37,'.',9,-,1]).
verbnet(counsel, (s:_\np)/s:_, ['Topic','Agent'], [37,'.',9,-,1]).
verbnet(instruct, (s:_\np)/s:_, ['Topic','Agent'], [37,'.',9,-,1]).
verbnet(warn, (s:_\np)/s:_, ['Topic','Agent'], [37,'.',9,-,1]).

%%% File:    ext/VerbNet/advise-37.9.xml
%%% Primary: NP V S-Quote (advise-37.9-1)
%%% Syntax:  [np:Agent,v,s:Topic]
%%% CCG:     (s:_\np)/s:_
%%% Roles:   [Topic,Agent]
%%% Example: Ellen warned, 'Avoid that hole in the sidewalk.'
%%%
verbnet(admonish, (s:_\np)/s:_, ['Topic','Agent'], [37,'.',9,-,1]).
verbnet(advise, (s:_\np)/s:_, ['Topic','Agent'], [37,'.',9,-,1]).
verbnet(caution, (s:_\np)/s:_, ['Topic','Agent'], [37,'.',9,-,1]).
verbnet(counsel, (s:_\np)/s:_, ['Topic','Agent'], [37,'.',9,-,1]).
verbnet(instruct, (s:_\np)/s:_, ['Topic','Agent'], [37,'.',9,-,1]).
verbnet(warn, (s:_\np)/s:_, ['Topic','Agent'], [37,'.',9,-,1]).

%%% File:    ext/VerbNet/advise-37.9.xml
%%% Primary: NP V NP.recipient (advise-37.9)
%%% Syntax:  [np:Agent,v,np:Recipient]
%%% CCG:     (s:_\np)/np
%%% Roles:   [Recipient,Agent]
%%% Example: Ellen alerted Helen.
%%%
verbnet(admonish, (s:_\np)/np, ['Recipient','Agent'], [37,'.',9]).
verbnet(advise, (s:_\np)/np, ['Recipient','Agent'], [37,'.',9]).
verbnet(caution, (s:_\np)/np, ['Recipient','Agent'], [37,'.',9]).
verbnet(counsel, (s:_\np)/np, ['Recipient','Agent'], [37,'.',9]).
verbnet(instruct, (s:_\np)/np, ['Recipient','Agent'], [37,'.',9]).
verbnet(warn, (s:_\np)/np, ['Recipient','Agent'], [37,'.',9]).
verbnet(alert, (s:_\np)/np, ['Recipient','Agent'], [37,'.',9]).
verbnet(assure, (s:_\np)/np, ['Recipient','Agent'], [37,'.',9]).
verbnet(brief, (s:_\np)/np, ['Recipient','Agent'], [37,'.',9]).
verbnet(encourage, (s:_\np)/np, ['Recipient','Agent'], [37,'.',9]).
verbnet(inform, (s:_\np)/np, ['Recipient','Agent'], [37,'.',9]).
verbnet(notify, (s:_\np)/np, ['Recipient','Agent'], [37,'.',9]).

%%% File:    ext/VerbNet/advise-37.9.xml
%%% Primary: NP V NP PP.topic (advise-37.9)
%%% Syntax:  [np:Agent,v,np:Recipient,prep:against about concerning on regarding respecting,np:Topic]
%%% CCG:     ((s:_\np)/pp)/np
%%% Roles:   [Recipient,Agent]
%%% Example: Ellen warned Helen against skating on thin ice.
%%%
verbnet(admonish, ((s:_\np)/pp)/np, ['Recipient','Agent'], [37,'.',9]).
verbnet(advise, ((s:_\np)/pp)/np, ['Recipient','Agent'], [37,'.',9]).
verbnet(caution, ((s:_\np)/pp)/np, ['Recipient','Agent'], [37,'.',9]).
verbnet(counsel, ((s:_\np)/pp)/np, ['Recipient','Agent'], [37,'.',9]).
verbnet(instruct, ((s:_\np)/pp)/np, ['Recipient','Agent'], [37,'.',9]).
verbnet(warn, ((s:_\np)/pp)/np, ['Recipient','Agent'], [37,'.',9]).
verbnet(alert, ((s:_\np)/pp)/np, ['Recipient','Agent'], [37,'.',9]).
verbnet(assure, ((s:_\np)/pp)/np, ['Recipient','Agent'], [37,'.',9]).
verbnet(brief, ((s:_\np)/pp)/np, ['Recipient','Agent'], [37,'.',9]).
verbnet(encourage, ((s:_\np)/pp)/np, ['Recipient','Agent'], [37,'.',9]).
verbnet(inform, ((s:_\np)/pp)/np, ['Recipient','Agent'], [37,'.',9]).
verbnet(notify, ((s:_\np)/pp)/np, ['Recipient','Agent'], [37,'.',9]).
verbnet(against, pp/np, ['Topic'], [37,.,9]).
verbnet(about, pp/np, ['Topic'], [37,.,9]).
verbnet(concerning, pp/np, ['Topic'], [37,.,9]).
verbnet(on, pp/np, ['Topic'], [37,.,9]).
verbnet(regarding, pp/np, ['Topic'], [37,.,9]).
verbnet(respecting, pp/np, ['Topic'], [37,.,9]).

%%% File:    ext/VerbNet/advise-37.9.xml
%%% Primary: NP V NP.recipient that S (advise-37.9)
%%% Syntax:  [np:Agent,v,np:Recipient,s:Topic]
%%% CCG:     ((s:_\np)/s:_)/np
%%% Roles:   [Recipient,Topic,Agent]
%%% Example: Ellen warned Helen that the party would be tonight.
%%%
verbnet(admonish, ((s:_\np)/s:_)/np, ['Recipient','Topic','Agent'], [37,'.',9]).
verbnet(advise, ((s:_\np)/s:_)/np, ['Recipient','Topic','Agent'], [37,'.',9]).
verbnet(caution, ((s:_\np)/s:_)/np, ['Recipient','Topic','Agent'], [37,'.',9]).
verbnet(counsel, ((s:_\np)/s:_)/np, ['Recipient','Topic','Agent'], [37,'.',9]).
verbnet(instruct, ((s:_\np)/s:_)/np, ['Recipient','Topic','Agent'], [37,'.',9]).
verbnet(warn, ((s:_\np)/s:_)/np, ['Recipient','Topic','Agent'], [37,'.',9]).
verbnet(alert, ((s:_\np)/s:_)/np, ['Recipient','Topic','Agent'], [37,'.',9]).
verbnet(assure, ((s:_\np)/s:_)/np, ['Recipient','Topic','Agent'], [37,'.',9]).
verbnet(brief, ((s:_\np)/s:_)/np, ['Recipient','Topic','Agent'], [37,'.',9]).
verbnet(encourage, ((s:_\np)/s:_)/np, ['Recipient','Topic','Agent'], [37,'.',9]).
verbnet(inform, ((s:_\np)/s:_)/np, ['Recipient','Topic','Agent'], [37,'.',9]).
verbnet(notify, ((s:_\np)/s:_)/np, ['Recipient','Topic','Agent'], [37,'.',9]).

%%% File:    ext/VerbNet/advise-37.9.xml
%%% Primary: NP V NP how S_INF (advise-37.9)
%%% Syntax:  [np:Agent,v,np:Recipient,s:Topic]
%%% CCG:     ((s:_\np)/s:_)/np
%%% Roles:   [Recipient,Topic,Agent]
%%% Example: Ellen warned Helen how to avoid the crowd.
%%%
verbnet(admonish, ((s:_\np)/s:_)/np, ['Recipient','Topic','Agent'], [37,'.',9]).
verbnet(advise, ((s:_\np)/s:_)/np, ['Recipient','Topic','Agent'], [37,'.',9]).
verbnet(caution, ((s:_\np)/s:_)/np, ['Recipient','Topic','Agent'], [37,'.',9]).
verbnet(counsel, ((s:_\np)/s:_)/np, ['Recipient','Topic','Agent'], [37,'.',9]).
verbnet(instruct, ((s:_\np)/s:_)/np, ['Recipient','Topic','Agent'], [37,'.',9]).
verbnet(warn, ((s:_\np)/s:_)/np, ['Recipient','Topic','Agent'], [37,'.',9]).
verbnet(alert, ((s:_\np)/s:_)/np, ['Recipient','Topic','Agent'], [37,'.',9]).
verbnet(assure, ((s:_\np)/s:_)/np, ['Recipient','Topic','Agent'], [37,'.',9]).
verbnet(brief, ((s:_\np)/s:_)/np, ['Recipient','Topic','Agent'], [37,'.',9]).
verbnet(encourage, ((s:_\np)/s:_)/np, ['Recipient','Topic','Agent'], [37,'.',9]).
verbnet(inform, ((s:_\np)/s:_)/np, ['Recipient','Topic','Agent'], [37,'.',9]).
verbnet(notify, ((s:_\np)/s:_)/np, ['Recipient','Topic','Agent'], [37,'.',9]).

%%% File:    ext/VerbNet/advise-37.9.xml
%%% Primary: NP V NP S-Quote (advise-37.9)
%%% Syntax:  [np:Agent,v,np:Recipient,s:Topic]
%%% CCG:     ((s:_\np)/s:_)/np
%%% Roles:   [Recipient,Topic,Agent]
%%% Example: Ellen warned Helen, 'Avoid that hole in the sidewalk.'
%%%
verbnet(admonish, ((s:_\np)/s:_)/np, ['Recipient','Topic','Agent'], [37,'.',9]).
verbnet(advise, ((s:_\np)/s:_)/np, ['Recipient','Topic','Agent'], [37,'.',9]).
verbnet(caution, ((s:_\np)/s:_)/np, ['Recipient','Topic','Agent'], [37,'.',9]).
verbnet(counsel, ((s:_\np)/s:_)/np, ['Recipient','Topic','Agent'], [37,'.',9]).
verbnet(instruct, ((s:_\np)/s:_)/np, ['Recipient','Topic','Agent'], [37,'.',9]).
verbnet(warn, ((s:_\np)/s:_)/np, ['Recipient','Topic','Agent'], [37,'.',9]).
verbnet(alert, ((s:_\np)/s:_)/np, ['Recipient','Topic','Agent'], [37,'.',9]).
verbnet(assure, ((s:_\np)/s:_)/np, ['Recipient','Topic','Agent'], [37,'.',9]).
verbnet(brief, ((s:_\np)/s:_)/np, ['Recipient','Topic','Agent'], [37,'.',9]).
verbnet(encourage, ((s:_\np)/s:_)/np, ['Recipient','Topic','Agent'], [37,'.',9]).
verbnet(inform, ((s:_\np)/s:_)/np, ['Recipient','Topic','Agent'], [37,'.',9]).
verbnet(notify, ((s:_\np)/s:_)/np, ['Recipient','Topic','Agent'], [37,'.',9]).

%%% File:    ext/VerbNet/advise-37.9.xml
%%% Primary: NP V NP PP.topic (advise-37.9)
%%% Syntax:  [np:Agent,v,np:Recipient,prep:of,np:Topic]
%%% CCG:     ((s:_\np)/pp)/np
%%% Roles:   [Recipient,Agent]
%%% Example: My accountant warned me of the new loopholes in the tax code.
%%%
verbnet(admonish, ((s:_\np)/pp)/np, ['Recipient','Agent'], [37,'.',9]).
verbnet(advise, ((s:_\np)/pp)/np, ['Recipient','Agent'], [37,'.',9]).
verbnet(caution, ((s:_\np)/pp)/np, ['Recipient','Agent'], [37,'.',9]).
verbnet(counsel, ((s:_\np)/pp)/np, ['Recipient','Agent'], [37,'.',9]).
verbnet(instruct, ((s:_\np)/pp)/np, ['Recipient','Agent'], [37,'.',9]).
verbnet(warn, ((s:_\np)/pp)/np, ['Recipient','Agent'], [37,'.',9]).
verbnet(alert, ((s:_\np)/pp)/np, ['Recipient','Agent'], [37,'.',9]).
verbnet(assure, ((s:_\np)/pp)/np, ['Recipient','Agent'], [37,'.',9]).
verbnet(brief, ((s:_\np)/pp)/np, ['Recipient','Agent'], [37,'.',9]).
verbnet(encourage, ((s:_\np)/pp)/np, ['Recipient','Agent'], [37,'.',9]).
verbnet(inform, ((s:_\np)/pp)/np, ['Recipient','Agent'], [37,'.',9]).
verbnet(notify, ((s:_\np)/pp)/np, ['Recipient','Agent'], [37,'.',9]).
verbnet(of, pp/np, ['Topic'], [37,.,9]).

:- include('verbnet_candc_boxer.nldata').
%%% File:    ext/VerbNet/allow-64.xml

