
Prefix(disponte:=<https://sites.google.com/a/unife.it/ml/disponte#>)
Prefix(owl:=<http://www.w3.org/2002/07/owl#>)

Ontology(<http://www.semanticweb.org/riccardo/ontologies/2019/10/untitled-ontology-10>

EquivalentClasses( <http://www.semanticweb.org/riccardo/ontologies/2019/10/untitled-ontology-10#class4> ObjectIntersectionOf( <http://www.semanticweb.org/riccardo/ontologies/2019/10/untitled-ontology-10#class1>  <http://www.semanticweb.org/riccardo/ontologies/2019/10/untitled-ontology-10#class3> ))
DisjointClasses( <http://ml.unife.it/disponte#class7> ObjectUnionOf( <http://ml.unife.it/disponte#class5>  <http://ml.unife.it/disponte#class6> ))
SubClassOf( <http://ml.unife.it/disponte#class11> ObjectMinCardinality(2 <http://www.semanticweb.org/riccardo/ontologies/2019/10/untitled-ontology-10#objprop1>  <http://ml.unife.it/disponte#class9> ))
SubClassOf( <http://ml.unife.it/disponte#class11> ObjectExactCardinality(3 <http://www.semanticweb.org/riccardo/ontologies/2019/10/untitled-ontology-10#objprop2>  <http://ml.unife.it/disponte#class9> ))
SubClassOf( <http://ml.unife.it/disponte#class11> ObjectMaxCardinality(4 <http://www.semanticweb.org/riccardo/ontologies/2019/10/untitled-ontology-10#objprop1>  <http://ml.unife.it/disponte#class9> ))
SubClassOf( <http://www.semanticweb.org/riccardo/ontologies/2019/10/untitled-ontology-10#class2>  <http://www.semanticweb.org/riccardo/ontologies/2019/10/untitled-ontology-10#class1> )
SymmetricObjectProperty( <http://ml.unife.it/disponte#objprop9> )
InverseFunctionalObjectProperty( <http://ml.unife.it/disponte#objprop10> )
TransitiveObjectProperty( <http://ml.unife.it/disponte#objprop9> )
AsymmetricObjectProperty( <http://ml.unife.it/disponte#objprop10> )
SubObjectPropertyOf( <http://www.semanticweb.org/riccardo/ontologies/2019/10/untitled-ontology-10#objprop3>  <http://www.semanticweb.org/riccardo/ontologies/2019/10/untitled-ontology-10#objprop1> )
FunctionalObjectProperty( <http://ml.unife.it/disponte#objprop9> )
IrreflexiveObjectProperty( <http://ml.unife.it/disponte#objprop10> )
ObjectPropertyDomain( <http://ml.unife.it/disponte#objprop5>  <http://ml.unife.it/disponte#class5> )
ObjectPropertyDomain( <http://ml.unife.it/disponte#objprop5>  <http://ml.unife.it/disponte#class6> )
ReflexiveObjectProperty( <http://ml.unife.it/disponte#objprop9> )
ObjectPropertyRange( <http://ml.unife.it/disponte#objprop5>  <http://ml.unife.it/disponte#class9> )
EquivalentObjectProperties( <http://ml.unife.it/disponte#objprop4>  <http://www.semanticweb.org/riccardo/ontologies/2019/10/untitled-ontology-10#objprop2> )
InverseObjectProperties( <http://ml.unife.it/disponte#objprop4>  <http://ml.unife.it/disponte#objprop5> )
ObjectPropertyAssertion( <http://www.semanticweb.org/riccardo/ontologies/2019/10/untitled-ontology-10#objprop1>  <http://ml.unife.it/disponte#ind1>  <http://ml.unife.it/disponte#ind2> )
SameIndividual( <http://ml.unife.it/disponte#ind1>  <http://ml.unife.it/disponte#ind2> )
ClassAssertion( <http://www.semanticweb.org/riccardo/ontologies/2019/10/untitled-ontology-10#class1>  <http://ml.unife.it/disponte#ind1> )
ClassAssertion(ObjectSomeValuesFrom( <http://ml.unife.it/disponte#class5>  <http://www.semanticweb.org/riccardo/ontologies/2019/10/untitled-ontology-10#objprop2> ) <http://ml.unife.it/disponte#ind1> )
Declaration(NamedIndividual( <http://ml.unife.it/disponte#ind1> ))
Declaration(NamedIndividual( <http://ml.unife.it/disponte#ind2> ))
Declaration(NamedIndividual( <http://ml.unife.it/disponte#ind3> ))
Declaration(ObjectProperty( <http://ml.unife.it/disponte#objprop10> ))
Declaration(ObjectProperty( <http://ml.unife.it/disponte#objprop4> ))
Declaration(ObjectProperty( <http://ml.unife.it/disponte#objprop5> ))
Declaration(ObjectProperty( <http://ml.unife.it/disponte#objprop6> ))
Declaration(ObjectProperty( <http://ml.unife.it/disponte#objprop7> ))
Declaration(ObjectProperty( <http://ml.unife.it/disponte#objprop8> ))
Declaration(ObjectProperty( <http://ml.unife.it/disponte#objprop9> ))
Declaration(ObjectProperty( <http://www.semanticweb.org/riccardo/ontologies/2019/10/untitled-ontology-10#objprop1> ))
Declaration(ObjectProperty( <http://www.semanticweb.org/riccardo/ontologies/2019/10/untitled-ontology-10#objprop2> ))
Declaration(ObjectProperty( <http://www.semanticweb.org/riccardo/ontologies/2019/10/untitled-ontology-10#objprop3> ))
Declaration(AnnotationProperty( <http://ml.unife.it/disponte#probability> ))
Declaration(Class( <http://ml.unife.it/disponte#class10> ))
Declaration(Class( <http://ml.unife.it/disponte#class11> ))
Declaration(Class( <http://ml.unife.it/disponte#class5> ))
Declaration(Class( <http://ml.unife.it/disponte#class6> ))
Declaration(Class( <http://ml.unife.it/disponte#class7> ))
Declaration(Class( <http://ml.unife.it/disponte#class8> ))
Declaration(Class( <http://ml.unife.it/disponte#class9> ))
Declaration(Class( <http://www.semanticweb.org/riccardo/ontologies/2019/10/untitled-ontology-10#class1> ))
Declaration(Class( <http://www.semanticweb.org/riccardo/ontologies/2019/10/untitled-ontology-10#class2> ))
Declaration(Class( <http://www.semanticweb.org/riccardo/ontologies/2019/10/untitled-ontology-10#class3> ))
Declaration(Class( <http://www.semanticweb.org/riccardo/ontologies/2019/10/untitled-ontology-10#class4> ))
)
