
clean:
	rm -f *.O *.xwam core *~ *.bak .#* *.dll *.obj *.lib *.def *.exp *.exe
	rm -f */*.O */*.xwam */core */*~ */*.bak */.#* */*.dll */*.obj */*.lib */*.def */*.exp */*.exe
	rm -f */*/*.O */*/*.xwam */*/core */*/*~ */*/*.bak */*/*/.#* */*/*.dll */*/*.obj */*/*.lib */*/*.def */*/*.exp */*/*.exe
