(define (problem fixb-strips)
    (:domain fridge-domain-strips)
  (:objects s1 s2 s3 s4 b1 c1 c2 f1)
  (:init (screw s1)
	 (screw s2) (screw s3) (screw s4) 
	 (backplane b1)
	 (compressor c1) (compressor c2) (fridge f1)
	 (covers b1 c1) (part-of b1 f1)
	 (holds s1 b1)  (holds s2 b1)  (holds s3 b1)
	 (holds s4 b1)
	 (ok c1) (ok c2) (fridge-on f1)
	 (screwed s1) (screwed s2) (screwed s3) (screwed s4)
	 (in-place b1) (attached c1))
  (:goal (AND (attached c2) (ok c2) (fridge-on f1)))
  (:length (:serial 13 ) (:parallel 6))
    )