% Copyright © 2002 Teknowledge Corporation
% This software released under the GNU Public License <http://www.gnu.org/copyleft/gpl.html>.

adjective_exception(after,after).
adjective_exception(airier,airy).
adjective_exception(airiest,airy).
adjective_exception(angrier,angry).
adjective_exception(angriest,angry).
adjective_exception(artier,arty).
adjective_exception(artiest,arty).
adjective_exception(ashier,ashy).
adjective_exception(ashiest,ashy).
adjective_exception(baggier,baggy).
adjective_exception(baggiest,baggy).
adjective_exception(balkier,balky).
adjective_exception(balkiest,balky).
adjective_exception(balmier,balmy).
adjective_exception(balmiest,balmy).
adjective_exception(bandier,bandy).
adjective_exception(bandiest,bandy).
adjective_exception(barmier,barmy).
adjective_exception(barmiest,barmy).
adjective_exception(battier,batty).
adjective_exception(battiest,batty).
adjective_exception(baulkier,baulky).
adjective_exception(baulkiest,baulky).
adjective_exception(bawdier,bawdy).
adjective_exception(bawdiest,bawdy).
adjective_exception(beadier,beady).
adjective_exception(beadiest,beady).
adjective_exception(beastlier,beastly).
adjective_exception(beastliest,beastly).
adjective_exception(beefier,beefy).
adjective_exception(beefiest,beefy).
adjective_exception(beerier,beery).
adjective_exception(beeriest,beery).
adjective_exception(bendier,bendy).
adjective_exception(bendiest,bendy).
adjective_exception(bigger,big).
adjective_exception(biggest,big).
adjective_exception(bitchier,bitchy).
adjective_exception(bitchiest,bitchy).
adjective_exception(bittier,bitty).
adjective_exception(bittiest,bitty).
adjective_exception(blearier,bleary).
adjective_exception(bleariest,bleary).
adjective_exception(bloodier,bloody).
adjective_exception(bloodiest,bloody).
adjective_exception(bloodthirstier,bloodthirsty).
adjective_exception(bloodthirstiest,bloodthirsty).
adjective_exception(blowier,blowy).
adjective_exception(blowiest,blowy).
adjective_exception(blowsier,blowsy).
adjective_exception(blowsiest,blowsy).
adjective_exception(blowzier,blowzy).
adjective_exception(blowziest,blowzy).
adjective_exception(bluer,blue).
adjective_exception(bluest,blue).
adjective_exception(bonier,bony).
adjective_exception(boniest,bony).
adjective_exception(bonnier,bonny).
adjective_exception(bonniest,bonny).
adjective_exception(boozier,boozy).
adjective_exception(booziest,boozy).
adjective_exception(boskier,bosky).
adjective_exception(boskiest,bosky).
adjective_exception(bossier,bossy).
adjective_exception(bossiest,bossy).
adjective_exception(botchier,botchy).
adjective_exception(botchiest,botchy).
adjective_exception(bother,bother).
adjective_exception(bouncier,bouncy).
adjective_exception(bounciest,bouncy).
adjective_exception(brainier,brainy).
adjective_exception(brainiest,brainy).
adjective_exception(brashier,brashy).
adjective_exception(brashiest,brashy).
adjective_exception(brassier,brassy).
adjective_exception(brassiest,brassy).
adjective_exception(brawnier,brawny).
adjective_exception(brawniest,brawny).
adjective_exception(breathier,breathy).
adjective_exception(breathiest,breathy).
adjective_exception(breezier,breezy).
adjective_exception(breeziest,breezy).
adjective_exception(brinier,briny).
adjective_exception(briniest,briny).
adjective_exception(broodier,broody).
adjective_exception(broodiest,broody).
adjective_exception(bubblier,bubbly).
adjective_exception(bubbliest,bubbly).
adjective_exception(buggier,buggy).
adjective_exception(buggiest,buggy).
adjective_exception(bulkier,bulky).
adjective_exception(bulkiest,bulky).
adjective_exception(bumpier,bumpy).
adjective_exception(bumpiest,bumpy).
adjective_exception(bunchier,bunchy).
adjective_exception(bunchiest,bunchy).
adjective_exception(burlier,burly).
adjective_exception(burliest,burly).
adjective_exception(burrier,burry).
adjective_exception(burriest,burry).
adjective_exception(bushier,bushy).
adjective_exception(bushiest,bushy).
adjective_exception(busier,busy).
adjective_exception(busiest,busy).
adjective_exception(bustier,busty).
adjective_exception(bustiest,busty).
adjective_exception(cagier,cagey).
adjective_exception(cagiest,cagey).
adjective_exception(cannier,canny).
adjective_exception(canniest,canny).
adjective_exception(cantier,canty).
adjective_exception(cantiest,canty).
adjective_exception(catchier,catchy).
adjective_exception(catchiest,catchy).
adjective_exception(cattier,catty).
adjective_exception(cattiest,catty).
adjective_exception(chancier,chancy).
adjective_exception(chanciest,chancy).
adjective_exception(charier,chary).
adjective_exception(chariest,chary).
adjective_exception(chattier,chatty).
adjective_exception(chattiest,chatty).
adjective_exception(cheekier,cheeky).
adjective_exception(cheekiest,cheeky).
adjective_exception(cheerier,cheery).
adjective_exception(cheeriest,cheery).
adjective_exception(cheesier,cheesy).
adjective_exception(cheesiest,cheesy).
adjective_exception(chestier,chesty).
adjective_exception(chestiest,chesty).
adjective_exception(chewier,chewy).
adjective_exception(chewiest,chewy).
adjective_exception(chillier,chilly).
adjective_exception(chilliest,chilly).
adjective_exception(chintzier,chintzy).
adjective_exception(chintziest,chintzy).
adjective_exception(chippier,chippy).
adjective_exception(chippiest,chippy).
adjective_exception(choosier,choosy).
adjective_exception(choosiest,choosy).
adjective_exception(choppier,choppy).
adjective_exception(choppiest,choppy).
adjective_exception(chubbier,chubby).
adjective_exception(chubbiest,chubby).
adjective_exception(chuffier,chuffy).
adjective_exception(chuffiest,chuffy).
adjective_exception(chummier,chummy).
adjective_exception(chummiest,chummy).
adjective_exception(chunkier,chunky).
adjective_exception(chunkiest,chunky).
adjective_exception(churchier,churchy).
adjective_exception(churchiest,churchy).
adjective_exception(clammier,clammy).
adjective_exception(clammiest,clammy).
adjective_exception(classier,classy).
adjective_exception(classiest,classy).
adjective_exception(cleanlier,cleanly).
adjective_exception(cleanliest,cleanly).
adjective_exception(clerklier,clerkly).
adjective_exception(clerkliest,clerkly).
adjective_exception(cloudier,cloudy).
adjective_exception(cloudiest,cloudy).
adjective_exception(clubbier,clubby).
adjective_exception(clubbiest,clubby).
adjective_exception(clumsier,clumsy).
adjective_exception(clumsiest,clumsy).
adjective_exception(cockier,cocky).
adjective_exception(cockiest,cocky).
adjective_exception(collier,colly).
adjective_exception(colliest,colly).
adjective_exception(comelier,comely).
adjective_exception(comeliest,comely).
adjective_exception(comfier,comfy).
adjective_exception(comfiest,comfy).
adjective_exception(cornier,corny).
adjective_exception(corniest,corny).
adjective_exception(cosier,cosy).
adjective_exception(cosiest,cosy).
adjective_exception(costlier,costly).
adjective_exception(costliest,costly).
adjective_exception(courtlier,courtly).
adjective_exception(courtliest,courtly).
adjective_exception(cozier,cozy).
adjective_exception(coziest,cozy).
adjective_exception(crabbier,crabby).
adjective_exception(crabbiest,crabby).
adjective_exception(craftier,crafty).
adjective_exception(craftiest,crafty).
adjective_exception(craggier,craggy).
adjective_exception(craggiest,craggy).
adjective_exception(crankier,cranky).
adjective_exception(crankiest,cranky).
adjective_exception(crawlier,crawly).
adjective_exception(crawliest,crawly).
adjective_exception(crazier,crazy).
adjective_exception(craziest,crazy).
adjective_exception(creamier,creamy).
adjective_exception(creamiest,creamy).
adjective_exception(creepier,creepy).
adjective_exception(creepiest,creepy).
adjective_exception(crispier,crispy).
adjective_exception(crispiest,crispy).
adjective_exception(crumbier,crumby).
adjective_exception(crumbiest,crumby).
adjective_exception(crumblier,crumbly).
adjective_exception(crumbliest,crumbly).
adjective_exception(crummier,crummy).
adjective_exception(crummiest,crummy).
adjective_exception(crustier,crusty).
adjective_exception(crustiest,crusty).
adjective_exception(curlier,curly).
adjective_exception(curliest,curly).
adjective_exception(daffier,daffy).
adjective_exception(daffiest,daffy).
adjective_exception(daintier,dainty).
adjective_exception(daintiest,dainty).
adjective_exception(dandier,dandy).
adjective_exception(dandiest,dandy).
adjective_exception(deadlier,deadly).
adjective_exception(deadliest,deadly).
adjective_exception(dewier,dewy).
adjective_exception(dewiest,dewy).
adjective_exception(dicier,dicey).
adjective_exception(diciest,dicey).
adjective_exception(dimmer,dim).
adjective_exception(dimmest,dim).
adjective_exception(dingier,dingy).
adjective_exception(dingiest,dingy).
adjective_exception(dinkier,dinky).
adjective_exception(dinkiest,dinky).
adjective_exception(dippier,dippy).
adjective_exception(dippiest,dippy).
adjective_exception(dirtier,dirty).
adjective_exception(dirtiest,dirty).
adjective_exception(dishier,dishy).
adjective_exception(dishiest,dishy).
adjective_exception(dizzier,dizzy).
adjective_exception(dizziest,dizzy).
adjective_exception(dodgier,dodgy).
adjective_exception(dodgiest,dodgy).
adjective_exception(dopier,dopey).
adjective_exception(dopiest,dopey).
adjective_exception(dottier,dotty).
adjective_exception(dottiest,dotty).
adjective_exception(doughier,doughy).
adjective_exception(doughiest,doughy).
adjective_exception(doughtier,doughty).
adjective_exception(doughtiest,doughty).
adjective_exception(dowdier,dowdy).
adjective_exception(dowdiest,dowdy).
adjective_exception(dowier,[dowie,dowy]).
adjective_exception(dowiest,[dowie,dowy]).
adjective_exception(downier,downy).
adjective_exception(downiest,downy).
adjective_exception(dozier,dozy).
adjective_exception(doziest,dozy).
adjective_exception(drabber,drab).
adjective_exception(drabbest,drab).
adjective_exception(draftier,drafty).
adjective_exception(draftiest,drafty).
adjective_exception(draggier,draggy).
adjective_exception(draggiest,draggy).
adjective_exception(draughtier,draughty).
adjective_exception(draughtiest,draughty).
adjective_exception(dreamier,dreamy).
adjective_exception(dreamiest,dreamy).
adjective_exception(drearier,dreary).
adjective_exception(dreariest,dreary).
adjective_exception(dreggier,dreggy).
adjective_exception(dreggiest,dreggy).
adjective_exception(dressier,dressy).
adjective_exception(dressiest,dressy).
adjective_exception(drier,dry).
adjective_exception(driest,dry).
adjective_exception(drippier,drippy).
adjective_exception(drippiest,drippy).
adjective_exception(drowsier,drowsy).
adjective_exception(drowsiest,drowsy).
adjective_exception(dryer,dry).
adjective_exception(dryest,dry).
adjective_exception(dumpier,dumpy).
adjective_exception(dumpiest,dumpy).
adjective_exception(dunner,dun).
adjective_exception(dunnest,dun).
adjective_exception(duskier,dusky).
adjective_exception(duskiest,dusky).
adjective_exception(dustier,dusty).
adjective_exception(dustiest,dusty).
adjective_exception(earlier,early).
adjective_exception(earliest,early).
adjective_exception(earthier,earthy).
adjective_exception(earthiest,earthy).
adjective_exception(earthlier,earthly).
adjective_exception(earthliest,earthly).
adjective_exception(easier,easy).
adjective_exception(easiest,easy).
adjective_exception(edgier,edgy).
adjective_exception(edgiest,edgy).
adjective_exception(eerier,eerie).
adjective_exception(eeriest,eerie).
adjective_exception(emptier,empty).
adjective_exception(emptiest,empty).
adjective_exception(fancier,fancy).
adjective_exception(fanciest,fancy).
adjective_exception(fatter,fat).
adjective_exception(fattest,fat).
adjective_exception(fattier,fatty).
adjective_exception(fattiest,fatty).
adjective_exception(faultier,faulty).
adjective_exception(faultiest,faulty).
adjective_exception(feistier,feisty).
adjective_exception(feistiest,feisty).
adjective_exception(fiddlier,fiddly).
adjective_exception(fiddliest,fiddly).
adjective_exception(filmier,filmy).
adjective_exception(filmiest,filmy).
adjective_exception(filthier,filthy).
adjective_exception(filthiest,filthy).
adjective_exception(finnier,finny).
adjective_exception(finniest,finny).
adjective_exception(fishier,fishy).
adjective_exception(fishiest,fishy).
adjective_exception(fitter,fit).
adjective_exception(fittest,fit).
adjective_exception(flabbier,flabby).
adjective_exception(flabbiest,flabby).
adjective_exception(flaggier,flaggy).
adjective_exception(flaggiest,flaggy).
adjective_exception(flakier,flaky).
adjective_exception(flakiest,flaky).
adjective_exception(flashier,flashy).
adjective_exception(flashiest,flashy).
adjective_exception(flatter,flat).
adjective_exception(flattest,flat).
adjective_exception(flauntier,flaunty).
adjective_exception(flauntiest,flaunty).
adjective_exception(fledgier,fledgy).
adjective_exception(fledgiest,fledgy).
adjective_exception(fleecier,fleecy).
adjective_exception(fleeciest,fleecy).
adjective_exception(fleshier,fleshy).
adjective_exception(fleshiest,fleshy).
adjective_exception(fleshlier,fleshly).
adjective_exception(fleshliest,fleshly).
adjective_exception(flightier,flighty).
adjective_exception(flightiest,flighty).
adjective_exception(flimsier,flimsy).
adjective_exception(flimsiest,flimsy).
adjective_exception(flintier,flinty).
adjective_exception(flintiest,flinty).
adjective_exception(floatier,floaty).
adjective_exception(floatiest,floaty).
adjective_exception(floppier,floppy).
adjective_exception(floppiest,floppy).
adjective_exception(flossier,flossy).
adjective_exception(flossiest,flossy).
adjective_exception(fluffier,fluffy).
adjective_exception(fluffiest,fluffy).
adjective_exception(flukier,fluky).
adjective_exception(flukiest,fluky).
adjective_exception(foamier,foamy).
adjective_exception(foamiest,foamy).
adjective_exception(foggier,foggy).
adjective_exception(foggiest,foggy).
adjective_exception(folksier,folksy).
adjective_exception(folksiest,folksy).
adjective_exception(foolhardier,foolhardy).
adjective_exception(foolhardiest,foolhardy).
adjective_exception(forest,forest).
adjective_exception(foxier,foxy).
adjective_exception(foxiest,foxy).
adjective_exception(fratchier,fratchy).
adjective_exception(fratchiest,fratchy).
adjective_exception(freakier,freaky).
adjective_exception(freakiest,freaky).
adjective_exception(freer,free).
adjective_exception(freest,free).
adjective_exception(frenchier,frenchy).
adjective_exception(frenchiest,frenchy).
adjective_exception(friendlier,friendly).
adjective_exception(friendliest,friendly).
adjective_exception(friskier,frisky).
adjective_exception(friskiest,frisky).
adjective_exception(frizzier,frizzy).
adjective_exception(frizziest,frizzy).
adjective_exception(frizzlier,frizzly).
adjective_exception(frizzliest,frizzly).
adjective_exception(frostier,frosty).
adjective_exception(frostiest,frosty).
adjective_exception(frouzier,frouzy).
adjective_exception(frouziest,frouzy).
adjective_exception(frowsier,frowsy).
adjective_exception(frowsiest,frowsy).
adjective_exception(frowzier,frowzy).
adjective_exception(frowziest,frowzy).
adjective_exception(fruitier,fruity).
adjective_exception(fruitiest,fruity).
adjective_exception(funkier,funky).
adjective_exception(funkiest,funky).
adjective_exception(funnier,funny).
adjective_exception(funniest,funny).
adjective_exception(furrier,furry).
adjective_exception(furriest,furry).
adjective_exception(fussier,fussy).
adjective_exception(fussiest,fussy).
adjective_exception(fustier,fusty).
adjective_exception(fustiest,fusty).
adjective_exception(fuzzier,fuzzy).
adjective_exception(fuzziest,fuzzy).
adjective_exception(gabbier,gabby).
adjective_exception(gabbiest,gabby).
adjective_exception(gamier,gamy).
adjective_exception(gamiest,gamy).
adjective_exception(gammier,gammy).
adjective_exception(gammiest,gammy).
adjective_exception(gassier,gassy).
adjective_exception(gassiest,gassy).
adjective_exception(gaudier,gaudy).
adjective_exception(gaudiest,gaudy).
adjective_exception(gauzier,gauzy).
adjective_exception(gauziest,gauzy).
adjective_exception(gawkier,gawky).
adjective_exception(gawkiest,gawky).
adjective_exception(ghastlier,ghastly).
adjective_exception(ghastliest,ghastly).
adjective_exception(ghostlier,ghostly).
adjective_exception(ghostliest,ghostly).
adjective_exception(giddier,giddy).
adjective_exception(giddiest,giddy).
adjective_exception(gladder,glad).
adjective_exception(gladdest,glad).
adjective_exception(glassier,glassy).
adjective_exception(glassiest,glassy).
adjective_exception(glibber,glib).
adjective_exception(glibbest,glib).
adjective_exception(gloomier,gloomy).
adjective_exception(gloomiest,gloomy).
adjective_exception(glossier,glossy).
adjective_exception(glossiest,glossy).
adjective_exception(glummer,glum).
adjective_exception(glummest,glum).
adjective_exception(godlier,godly).
adjective_exception(godliest,godly).
adjective_exception(goodlier,goodly).
adjective_exception(goodliest,goodly).
adjective_exception(goofier,goofy).
adjective_exception(goofiest,goofy).
adjective_exception(gooier,gooey).
adjective_exception(gooiest,gooey).
adjective_exception(goosier,goosy).
adjective_exception(goosiest,goosy).
adjective_exception(gorier,gory).
adjective_exception(goriest,gory).
adjective_exception(gradelier,gradely).
adjective_exception(gradeliest,gradely).
adjective_exception(grainier,grainy).
adjective_exception(grainiest,grainy).
adjective_exception(grassier,grassy).
adjective_exception(grassiest,grassy).
adjective_exception(greasier,greasy).
adjective_exception(greasiest,greasy).
adjective_exception(greedier,greedy).
adjective_exception(greediest,greedy).
adjective_exception(grimmer,grim).
adjective_exception(grimmest,grim).
adjective_exception(grislier,grisly).
adjective_exception(grisliest,grisly).
adjective_exception(grittier,gritty).
adjective_exception(grittiest,gritty).
adjective_exception(grizzlier,grizzly).
adjective_exception(grizzliest,grizzly).
adjective_exception(groggier,groggy).
adjective_exception(groggiest,groggy).
adjective_exception(groovier,groovy).
adjective_exception(grooviest,groovy).
adjective_exception(grottier,grotty).
adjective_exception(grottiest,grotty).
adjective_exception(groutier,grouty).
adjective_exception(groutiest,grouty).
adjective_exception(grubbier,grubby).
adjective_exception(grubbiest,grubby).
adjective_exception(grumpier,grumpy).
adjective_exception(grumpiest,grumpy).
adjective_exception(guiltier,guilty).
adjective_exception(guiltiest,guilty).
adjective_exception(gummier,gummy).
adjective_exception(gummiest,gummy).
adjective_exception(gushier,gushy).
adjective_exception(gushiest,gushy).
adjective_exception(gustier,gusty).
adjective_exception(gustiest,gusty).
adjective_exception(gutsier,gutsy).
adjective_exception(gutsiest,gutsy).
adjective_exception(hairier,hairy).
adjective_exception(hairiest,hairy).
adjective_exception(halfways,halfway).
adjective_exception(hammier,hammy).
adjective_exception(hammiest,hammy).
adjective_exception(handier,handy).
adjective_exception(handiest,handy).
adjective_exception(happier,happy).
adjective_exception(happiest,happy).
adjective_exception(hardier,hardy).
adjective_exception(hardiest,hardy).
adjective_exception(hastier,hasty).
adjective_exception(hastiest,hasty).
adjective_exception(haughtier,haughty).
adjective_exception(haughtiest,haughty).
adjective_exception(hazier,hazy).
adjective_exception(haziest,hazy).
adjective_exception(headier,heady).
adjective_exception(headiest,heady).
adjective_exception(healthier,healthy).
adjective_exception(healthiest,healthy).
adjective_exception(heartier,hearty).
adjective_exception(heartiest,hearty).
adjective_exception(heavier,heavy).
adjective_exception(heaviest,heavy).
adjective_exception(heftier,hefty).
adjective_exception(heftiest,hefty).
adjective_exception(hepper,hep).
adjective_exception(heppest,hep).
adjective_exception(herbier,herby).
adjective_exception(herbiest,herby).
adjective_exception(hinder,hind).
adjective_exception(hipper,hip).
adjective_exception(hippest,hip).
adjective_exception(hippier,hippy).
adjective_exception(hippiest,hippy).
adjective_exception(hoarier,hoary).
adjective_exception(hoariest,hoary).
adjective_exception(holier,holy).
adjective_exception(holiest,holy).
adjective_exception(homelier,homely).
adjective_exception(homeliest,homely).
adjective_exception(homier,homey).
adjective_exception(homiest,homey).
adjective_exception(hornier,horny).
adjective_exception(horniest,horny).
adjective_exception(horsier,horsy).
adjective_exception(horsiest,horsy).
adjective_exception(hotter,hot).
adjective_exception(hottest,hot).
adjective_exception(humpier,humpy).
adjective_exception(humpiest,humpy).
adjective_exception(hungrier,hungry).
adjective_exception(hungriest,hungry).
adjective_exception(huskier,husky).
adjective_exception(huskiest,husky).
adjective_exception(icier,icy).
adjective_exception(iciest,icy).
adjective_exception(inkier,inky).
adjective_exception(inkiest,inky).
adjective_exception(jaggier,jaggy).
adjective_exception(jaggiest,jaggy).
adjective_exception(jammier,jammy).
adjective_exception(jammiest,jammy).
adjective_exception(jauntier,jaunty).
adjective_exception(jauntiest,jaunty).
adjective_exception(jazzier,jazzy).
adjective_exception(jazziest,jazzy).
adjective_exception(jerkier,jerky).
adjective_exception(jerkiest,jerky).
adjective_exception(jollier,jolly).
adjective_exception(jolliest,jolly).
adjective_exception(juicier,juicy).
adjective_exception(juiciest,juicy).
adjective_exception(jumpier,jumpy).
adjective_exception(jumpiest,jumpy).
adjective_exception(kindlier,kindly).
adjective_exception(kindliest,kindly).
adjective_exception(kinkier,kinky).
adjective_exception(kinkiest,kinky).
adjective_exception(knottier,knotty).
adjective_exception(knottiest,knotty).
adjective_exception(knurlier,knurly).
adjective_exception(knurliest,knurly).
adjective_exception(kookier,kooky).
adjective_exception(kookiest,kooky).
adjective_exception(lacier,lacy).
adjective_exception(laciest,lacy).
adjective_exception(lairier,lairy).
adjective_exception(lairiest,lairy).
adjective_exception(lakier,laky).
adjective_exception(lakiest,laky).
adjective_exception(lankier,lanky).
adjective_exception(lankiest,lanky).
adjective_exception(lathier,lathy).
adjective_exception(lathiest,lathy).
adjective_exception(layer,layer).
adjective_exception(lazier,lazy).
adjective_exception(laziest,lazy).
adjective_exception(leafier,leafy).
adjective_exception(leafiest,leafy).
adjective_exception(leakier,leaky).
adjective_exception(leakiest,leaky).
adjective_exception(learier,leary).
adjective_exception(leariest,leary).
adjective_exception(leerier,leery).
adjective_exception(leeriest,leery).
adjective_exception(leggier,leggy).
adjective_exception(leggiest,leggy).
adjective_exception(lengthier,lengthy).
adjective_exception(lengthiest,lengthy).
adjective_exception(limier,limy).
adjective_exception(limiest,limy).
adjective_exception(lippier,lippy).
adjective_exception(lippiest,lippy).
adjective_exception(livelier,lively).
adjective_exception(liveliest,lively).
adjective_exception(loftier,lofty).
adjective_exception(loftiest,lofty).
adjective_exception(logier,logy).
adjective_exception(logiest,logy).
adjective_exception(lonelier,lonely).
adjective_exception(loneliest,lonely).
adjective_exception(loonier,loony).
adjective_exception(looniest,loony).
adjective_exception(loopier,loopy).
adjective_exception(loopiest,loopy).
adjective_exception(lordlier,lordly).
adjective_exception(lordliest,lordly).
adjective_exception(lousier,lousy).
adjective_exception(lousiest,lousy).
adjective_exception(lovelier,lovely).
adjective_exception(loveliest,lovely).
adjective_exception(lowlier,lowly).
adjective_exception(lowliest,lowly).
adjective_exception(luckier,lucky).
adjective_exception(luckiest,lucky).
adjective_exception(lumpier,lumpy).
adjective_exception(lumpiest,lumpy).
adjective_exception(lunier,luny).
adjective_exception(luniest,luny).
adjective_exception(lustier,lusty).
adjective_exception(lustiest,lusty).
adjective_exception(madder,mad).
adjective_exception(maddest,mad).
adjective_exception(maltier,malty).
adjective_exception(maltiest,malty).
adjective_exception(mangier,mangy).
adjective_exception(mangiest,mangy).
adjective_exception(mankier,manky).
adjective_exception(mankiest,manky).
adjective_exception(manlier,manly).
adjective_exception(manliest,manly).
adjective_exception(marshier,marshy).
adjective_exception(marshiest,marshy).
adjective_exception(massier,massy).
adjective_exception(massiest,massy).
adjective_exception(matter,matter).
adjective_exception(maungier,maungy).
adjective_exception(maungiest,maungy).
adjective_exception(mazier,mazy).
adjective_exception(maziest,mazy).
adjective_exception(mealier,mealy).
adjective_exception(mealiest,mealy).
adjective_exception(measlier,measly).
adjective_exception(measliest,measly).
adjective_exception(meatier,meaty).
adjective_exception(meatiest,meaty).
adjective_exception(merrier,merry).
adjective_exception(merriest,merry).
adjective_exception(messier,messy).
adjective_exception(messiest,messy).
adjective_exception(miffier,miffy).
adjective_exception(miffiest,miffy).
adjective_exception(mightier,mighty).
adjective_exception(mightiest,mighty).
adjective_exception(milkier,milky).
adjective_exception(milkiest,milky).
adjective_exception(mingier,mingy).
adjective_exception(mingiest,mingy).
adjective_exception(mirkier,mirky).
adjective_exception(mirkiest,mirky).
adjective_exception(mistier,misty).
adjective_exception(mistiest,misty).
adjective_exception(modest,modest).
adjective_exception(moldier,moldy).
adjective_exception(moldiest,moldy).
adjective_exception(moodier,moody).
adjective_exception(moodiest,moody).
adjective_exception(moonier,moony).
adjective_exception(mooniest,moony).
adjective_exception(mothier,mothy).
adjective_exception(mothiest,mothy).
adjective_exception(mouldier,mouldy).
adjective_exception(mouldiest,mouldy).
adjective_exception(mousier,mousy).
adjective_exception(mousiest,mousy).
adjective_exception(mouthier,mouthy).
adjective_exception(mouthiest,mouthy).
adjective_exception(muckier,mucky).
adjective_exception(muckiest,mucky).
adjective_exception(muddier,muddy).
adjective_exception(muddiest,muddy).
adjective_exception(muggier,muggy).
adjective_exception(muggiest,muggy).
adjective_exception(murkier,murky).
adjective_exception(murkiest,murky).
adjective_exception(mushier,mushy).
adjective_exception(mushiest,mushy).
adjective_exception(muskier,musky).
adjective_exception(muskiest,musky).
adjective_exception(mustier,musty).
adjective_exception(mustiest,musty).
adjective_exception(muzzier,muzzy).
adjective_exception(muzziest,muzzy).
adjective_exception(nappier,nappy).
adjective_exception(nappiest,nappy).
adjective_exception(nastier,nasty).
adjective_exception(nastiest,nasty).
adjective_exception(nattier,natty).
adjective_exception(nattiest,natty).
adjective_exception(naughtier,naughty).
adjective_exception(naughtiest,naughty).
adjective_exception(needier,needy).
adjective_exception(neediest,needy).
adjective_exception(nervier,nervy).
adjective_exception(nerviest,nervy).
adjective_exception(newsier,newsy).
adjective_exception(newsiest,newsy).
adjective_exception(niftier,nifty).
adjective_exception(niftiest,nifty).
adjective_exception(nippier,nippy).
adjective_exception(nippiest,nippy).
adjective_exception(nittier,nitty).
adjective_exception(nittiest,nitty).
adjective_exception(noisier,noisy).
adjective_exception(noisiest,noisy).
adjective_exception(nosier,nosy).
adjective_exception(nosiest,nosy).
adjective_exception(nuttier,nutty).
adjective_exception(nuttiest,nutty).
adjective_exception(oilier,oily).
adjective_exception(oiliest,oily).
adjective_exception(oozier,oozy).
adjective_exception(ooziest,oozy).
adjective_exception(pallier,pally).
adjective_exception(palliest,pally).
adjective_exception(palmier,palmy).
adjective_exception(palmiest,palmy).
adjective_exception(paltrier,paltry).
adjective_exception(paltriest,paltry).
adjective_exception(pappier,pappy).
adjective_exception(pappiest,pappy).
adjective_exception(parkier,parky).
adjective_exception(parkiest,parky).
adjective_exception(pastier,pasty).
adjective_exception(pastiest,pasty).
adjective_exception(patchier,patchy).
adjective_exception(patchiest,patchy).
adjective_exception(pawkier,pawky).
adjective_exception(pawkiest,pawky).
adjective_exception(peachier,peachy).
adjective_exception(peachiest,peachy).
adjective_exception(pearlier,pearly).
adjective_exception(pearliest,pearly).
adjective_exception(peppier,peppy).
adjective_exception(peppiest,peppy).
adjective_exception(perkier,perky).
adjective_exception(perkiest,perky).
adjective_exception(peskier,pesky).
adjective_exception(peskiest,pesky).
adjective_exception(pettier,petty).
adjective_exception(pettiest,petty).
adjective_exception(phonier,phony).
adjective_exception(phoniest,phony).
adjective_exception(pickier,picky).
adjective_exception(pickiest,picky).
adjective_exception(piggier,piggy).
adjective_exception(piggiest,piggy).
adjective_exception(pinier,piny).
adjective_exception(piniest,piny).
adjective_exception(pitchier,pitchy).
adjective_exception(pitchiest,pitchy).
adjective_exception(pithier,pithy).
adjective_exception(pithiest,pithy).
adjective_exception(plashier,plashy).
adjective_exception(plashiest,plashy).
adjective_exception(platier,platy).
adjective_exception(platiest,platy).
adjective_exception(pluckier,plucky).
adjective_exception(pluckiest,plucky).
adjective_exception(plumier,plumy).
adjective_exception(plumiest,plumy).
adjective_exception(plummier,plummy).
adjective_exception(plummiest,plummy).
adjective_exception(podgier,podgy).
adjective_exception(podgiest,podgy).
adjective_exception(pokier,poky).
adjective_exception(pokiest,poky).
adjective_exception(porkier,porky).
adjective_exception(porkiest,porky).
adjective_exception(portlier,portly).
adjective_exception(portliest,portly).
adjective_exception(pottier,potty).
adjective_exception(pottiest,potty).
adjective_exception(preachier,preachy).
adjective_exception(preachiest,preachy).
adjective_exception(prettier,pretty).
adjective_exception(prettiest,pretty).
adjective_exception(pricier,pricy).
adjective_exception(priciest,pricy).
adjective_exception(pricklier,prickly).
adjective_exception(prickliest,prickly).
adjective_exception(priestlier,priestly).
adjective_exception(priestliest,priestly).
adjective_exception(primmer,prim).
adjective_exception(primmest,prim).
adjective_exception(princelier,princely).
adjective_exception(princeliest,princely).
adjective_exception(prissier,prissy).
adjective_exception(prissiest,prissy).
adjective_exception(privier,privy).
adjective_exception(priviest,privy).
adjective_exception(prosier,prosy).
adjective_exception(prosiest,prosy).
adjective_exception(pudgier,pudgy).
adjective_exception(pudgiest,pudgy).
adjective_exception(puffier,puffy).
adjective_exception(puffiest,puffy).
adjective_exception(pulpier,pulpy).
adjective_exception(pulpiest,pulpy).
adjective_exception(punchier,punchy).
adjective_exception(punchiest,punchy).
adjective_exception(punier,puny).
adjective_exception(puniest,puny).
adjective_exception(pushier,pushy).
adjective_exception(pushiest,pushy).
adjective_exception(pussier,pussy).
adjective_exception(pussiest,pussy).
adjective_exception(quaggier,quaggy).
adjective_exception(quaggiest,quaggy).
adjective_exception(quakier,quaky).
adjective_exception(quakiest,quaky).
adjective_exception(queasier,queasy).
adjective_exception(queasiest,queasy).
adjective_exception(queenlier,queenly).
adjective_exception(queenliest,queenly).
adjective_exception(racier,racy).
adjective_exception(raciest,racy).
adjective_exception(rainier,rainy).
adjective_exception(rainiest,rainy).
adjective_exception(randier,randy).
adjective_exception(randiest,randy).
adjective_exception(rangier,rangy).
adjective_exception(rangiest,rangy).
adjective_exception(rattier,ratty).
adjective_exception(rattiest,ratty).
adjective_exception(rattlier,rattly).
adjective_exception(rattliest,rattly).
adjective_exception(raunchier,raunchy).
adjective_exception(raunchiest,raunchy).
adjective_exception(readier,ready).
adjective_exception(readiest,ready).
adjective_exception(redder,red).
adjective_exception(reddest,red).
adjective_exception(reedier,reedy).
adjective_exception(reediest,reedy).
adjective_exception(rimier,rimy).
adjective_exception(rimiest,rimy).
adjective_exception(riskier,risky).
adjective_exception(riskiest,risky).
adjective_exception(ritzier,ritzy).
adjective_exception(ritziest,ritzy).
adjective_exception(rockier,rocky).
adjective_exception(rockiest,rocky).
adjective_exception(roilier,roily).
adjective_exception(roiliest,roily).
adjective_exception(rookier,rooky).
adjective_exception(rookiest,rooky).
adjective_exception(roomier,roomy).
adjective_exception(roomiest,roomy).
adjective_exception(ropier,ropy).
adjective_exception(ropiest,ropy).
adjective_exception(rosier,rosy).
adjective_exception(rosiest,rosy).
adjective_exception(rowdier,rowdy).
adjective_exception(rowdiest,rowdy).
adjective_exception(ruddier,ruddy).
adjective_exception(ruddiest,ruddy).
adjective_exception(runnier,runny).
adjective_exception(runniest,runny).
adjective_exception(rushier,rushy).
adjective_exception(rushiest,rushy).
adjective_exception(rustier,rusty).
adjective_exception(rustiest,rusty).
adjective_exception(ruttier,rutty).
adjective_exception(ruttiest,rutty).
adjective_exception(sadder,sad).
adjective_exception(saddest,sad).
adjective_exception(saltier,salty).
adjective_exception(saltiest,salty).
adjective_exception(sandier,sandy).
adjective_exception(sandiest,sandy).
adjective_exception(sappier,sappy).
adjective_exception(sappiest,sappy).
adjective_exception(sassier,sassy).
adjective_exception(sassiest,sassy).
adjective_exception(sauccier,saucy).
adjective_exception(saucciest,saucy).
adjective_exception(savvier,savvy).
adjective_exception(savviest,savvy).
adjective_exception(scabbier,scabby).
adjective_exception(scabbiest,scabby).
adjective_exception(scalier,scaly).
adjective_exception(scaliest,scaly).
adjective_exception(scantier,scanty).
adjective_exception(scantiest,scanty).
adjective_exception(scarier,scary).
adjective_exception(scariest,scary).
adjective_exception(scraggier,scraggy).
adjective_exception(scraggiest,scraggy).
adjective_exception(scragglier,scraggly).
adjective_exception(scraggliest,scraggly).
adjective_exception(scrappier,scrappy).
adjective_exception(scrappiest,scrappy).
adjective_exception(scrawnier,scrawny).
adjective_exception(scrawniest,scrawny).
adjective_exception(screwier,screwy).
adjective_exception(screwiest,screwy).
adjective_exception(scrubbier,scrubby).
adjective_exception(scrubbiest,scrubby).
adjective_exception(scruffier,scruffy).
adjective_exception(scruffiest,scruffy).
adjective_exception(scungier,scungy).
adjective_exception(scungiest,scungy).
adjective_exception(scurvier,scurvy).
adjective_exception(scurviest,scurvy).
adjective_exception(seamier,seamy).
adjective_exception(seamiest,seamy).
adjective_exception(seedier,seedy).
adjective_exception(seediest,seedy).
adjective_exception(seemlier,seemly).
adjective_exception(seemliest,seemly).
adjective_exception(sexier,sexy).
adjective_exception(sexiest,sexy).
adjective_exception(shabbier,shabby).
adjective_exception(shabbiest,shabby).
adjective_exception(shadier,shady).
adjective_exception(shadiest,shady).
adjective_exception(shaggier,shaggy).
adjective_exception(shaggiest,shaggy).
adjective_exception(shakier,shaky).
adjective_exception(shakiest,shaky).
adjective_exception(shapelier,shapely).
adjective_exception(shapeliest,shapely).
adjective_exception(shier,shy).
adjective_exception(shiest,shy).
adjective_exception(shiftier,shifty).
adjective_exception(shiftiest,shifty).
adjective_exception(shinier,shiny).
adjective_exception(shiniest,shiny).
adjective_exception(shirtier,shirty).
adjective_exception(shirtiest,shirty).
adjective_exception(shoddier,shoddy).
adjective_exception(shoddiest,shoddy).
adjective_exception(showier,showy).
adjective_exception(showiest,showy).
adjective_exception(shrubbier,shrubby).
adjective_exception(shrubbiest,shrubby).
adjective_exception(shyer,shy).
adjective_exception(shyest,shy).
adjective_exception(sicklier,sickly).
adjective_exception(sickliest,sickly).
adjective_exception(sightlier,sightly).
adjective_exception(sightliest,sightly).
adjective_exception(silkier,silky).
adjective_exception(silkiest,silky).
adjective_exception(sillier,silly).
adjective_exception(silliest,silly).
adjective_exception(sketchier,sketchy).
adjective_exception(sketchiest,sketchy).
adjective_exception(skimpier,skimpy).
adjective_exception(skimpiest,skimpy).
adjective_exception(skinnier,skinny).
adjective_exception(skinniest,skinny).
adjective_exception(slaphappier,slaphappy).
adjective_exception(slaphappiest,slaphappy).
adjective_exception(slatier,slaty).
adjective_exception(slatiest,slaty).
adjective_exception(sleazier,sleazy).
adjective_exception(sleaziest,sleazy).
adjective_exception(sleepier,sleepy).
adjective_exception(sleepiest,sleepy).
adjective_exception(slier,sly).
adjective_exception(sliest,sly).
adjective_exception(slimier,slimy).
adjective_exception(slimiest,slimy).
adjective_exception(slimmer,slim).
adjective_exception(slimmest,slim).
adjective_exception(slimsier,slimsy).
adjective_exception(slimsiest,slimsy).
adjective_exception(slinkier,slinky).
adjective_exception(slinkiest,slinky).
adjective_exception(slippier,slippy).
adjective_exception(slippiest,slippy).
adjective_exception(sloppier,sloppy).
adjective_exception(sloppiest,sloppy).
adjective_exception(slyer,sly).
adjective_exception(slyest,sly).
adjective_exception(smarmier,smarmy).
adjective_exception(smarmiest,smarmy).
adjective_exception(smellier,smelly).
adjective_exception(smelliest,smelly).
adjective_exception(smokier,smoky).
adjective_exception(smokiest,smoky).
adjective_exception(smugger,smug).
adjective_exception(smuggest,smug).
adjective_exception(snakier,snaky).
adjective_exception(snakiest,snaky).
adjective_exception(snappier,snappy).
adjective_exception(snappiest,snappy).
adjective_exception(snatchier,snatchy).
adjective_exception(snatchiest,snatchy).
adjective_exception(snazzier,snazzy).
adjective_exception(snazziest,snazzy).
adjective_exception(sniffier,sniffy).
adjective_exception(sniffiest,sniffy).
adjective_exception(snootier,snooty).
adjective_exception(snootiest,snooty).
adjective_exception(snottier,snotty).
adjective_exception(snottiest,snotty).
adjective_exception(snowier,snowy).
adjective_exception(snowiest,snowy).
adjective_exception(snuffier,snuffy).
adjective_exception(snuffiest,snuffy).
adjective_exception(snugger,snug).
adjective_exception(snuggest,snug).
adjective_exception(soapier,soapy).
adjective_exception(soapiest,soapy).
adjective_exception(soggier,soggy).
adjective_exception(soggiest,soggy).
adjective_exception(sonsier,sonsy).
adjective_exception(sonsiest,sonsy).
adjective_exception(sootier,sooty).
adjective_exception(sootiest,sooty).
adjective_exception(soppier,soppy).
adjective_exception(soppiest,soppy).
adjective_exception(sorrier,sorry).
adjective_exception(sorriest,sorry).
adjective_exception(soupier,soupy).
adjective_exception(soupiest,soupy).
adjective_exception(speedier,speedy).
adjective_exception(speediest,speedy).
adjective_exception(spicier,spicy).
adjective_exception(spiciest,spicy).
adjective_exception(spiffier,spiffy).
adjective_exception(spiffiest,spiffy).
adjective_exception(spikier,spiky).
adjective_exception(spikiest,spiky).
adjective_exception(spindlier,spindly).
adjective_exception(spindliest,spindly).
adjective_exception(spinier,spiny).
adjective_exception(spiniest,spiny).
adjective_exception(splashier,splashy).
adjective_exception(splashiest,splashy).
adjective_exception(spongier,spongy).
adjective_exception(spongiest,spongy).
adjective_exception(spookier,spooky).
adjective_exception(spookiest,spooky).
adjective_exception(spoonier,spoony).
adjective_exception(spooniest,spoony).
adjective_exception(sportier,sporty).
adjective_exception(sportiest,sporty).
adjective_exception(spottier,spotty).
adjective_exception(spottiest,spotty).
adjective_exception(sprier,spry).
adjective_exception(spriest,spry).
adjective_exception(sprightlier,sprightly).
adjective_exception(sprightliest,sprightly).
adjective_exception(springier,springy).
adjective_exception(springiest,springy).
adjective_exception(squashier,squashy).
adjective_exception(squashiest,squashy).
adjective_exception(squiffier,squiffy).
adjective_exception(squiffiest,squiffy).
adjective_exception(stagier,stagy).
adjective_exception(stagiest,stagy).
adjective_exception(stalkier,stalky).
adjective_exception(stalkiest,stalky).
adjective_exception(starchier,starchy).
adjective_exception(starchiest,starchy).
adjective_exception(starrier,starry).
adjective_exception(starriest,starry).
adjective_exception(statelier,stately).
adjective_exception(stateliest,stately).
adjective_exception(steadier,steady).
adjective_exception(steadiest,steady).
adjective_exception(stealthier,stealthy).
adjective_exception(stealthiest,stealthy).
adjective_exception(steamier,steamy).
adjective_exception(steamiest,steamy).
adjective_exception(stingier,stingy).
adjective_exception(stingiest,stingy).
adjective_exception(stockier,stocky).
adjective_exception(stockiest,stocky).
adjective_exception(stodgier,stodgy).
adjective_exception(stodgiest,stodgy).
adjective_exception(stonier,stony).
adjective_exception(stoniest,stony).
adjective_exception(stormier,stormy).
adjective_exception(stormiest,stormy).
adjective_exception(streakier,streaky).
adjective_exception(streakiest,streaky).
adjective_exception(streamier,streamy).
adjective_exception(streamiest,streamy).
adjective_exception(stretchier,stretchy).
adjective_exception(stretchiest,stretchy).
adjective_exception(stringier,stringy).
adjective_exception(stringiest,stringy).
adjective_exception(stripier,stripy).
adjective_exception(stripiest,stripy).
adjective_exception(stronger,strong).
adjective_exception(strongest,strong).
adjective_exception(stroppier,stroppy).
adjective_exception(stroppiest,stroppy).
adjective_exception(stuffier,stuffy).
adjective_exception(stuffiest,stuffy).
adjective_exception(stumpier,stumpy).
adjective_exception(stumpiest,stumpy).
adjective_exception(sturdier,sturdy).
adjective_exception(sturdiest,sturdy).
adjective_exception(sulkier,sulky).
adjective_exception(sulkiest,sulky).
adjective_exception(sultrier,sultry).
adjective_exception(sultriest,sultry).
adjective_exception(sunnier,sunny).
adjective_exception(sunniest,sunny).
adjective_exception(surlier,surly).
adjective_exception(surliest,surly).
adjective_exception(swankier,swanky).
adjective_exception(swankiest,swanky).
adjective_exception(swarthier,swarthy).
adjective_exception(swarthiest,swarthy).
adjective_exception(sweatier,sweaty).
adjective_exception(sweatiest,sweaty).
adjective_exception(tackier,tacky).
adjective_exception(tackiest,tacky).
adjective_exception(talkier,talky).
adjective_exception(talkiest,talky).
adjective_exception(tangier,tangy).
adjective_exception(tangiest,tangy).
adjective_exception(tanner,tan).
adjective_exception(tannest,tan).
adjective_exception(tardier,tardy).
adjective_exception(tardiest,tardy).
adjective_exception(tastier,tasty).
adjective_exception(tastiest,tasty).
adjective_exception(tattier,tatty).
adjective_exception(tattiest,tatty).
adjective_exception(tawdrier,tawdry).
adjective_exception(tawdriest,tawdry).
adjective_exception(techier,techy).
adjective_exception(techiest,techy).
adjective_exception(teenier,teeny).
adjective_exception(teeniest,teeny).
adjective_exception(testier,testy).
adjective_exception(testiest,testy).
adjective_exception(tetchier,tetchy).
adjective_exception(tetchiest,tetchy).
adjective_exception(thinner,thin).
adjective_exception(thinnest,thin).
adjective_exception(thirstier,thirsty).
adjective_exception(thirstiest,thirsty).
adjective_exception(thornier,thorny).
adjective_exception(thorniest,thorny).
adjective_exception(threadier,thready).
adjective_exception(threadiest,thready).
adjective_exception(thriftier,thrifty).
adjective_exception(thriftiest,thrifty).
adjective_exception(throatier,throaty).
adjective_exception(throatiest,throaty).
adjective_exception(tidier,tidy).
adjective_exception(tidiest,tidy).
adjective_exception(timelier,timely).
adjective_exception(timeliest,timely).
adjective_exception(tinier,tiny).
adjective_exception(tiniest,tiny).
adjective_exception(tinnier,tinny).
adjective_exception(tinniest,tinny).
adjective_exception(tipsier,tipsy).
adjective_exception(tipsiest,tipsy).
adjective_exception(tonier,tony).
adjective_exception(toniest,tony).
adjective_exception(toothier,toothy).
adjective_exception(toothiest,toothy).
adjective_exception(touchier,touchy).
adjective_exception(touchiest,touchy).
adjective_exception(trashier,trashy).
adjective_exception(trashiest,trashy).
adjective_exception(trendier,trendy).
adjective_exception(trendiest,trendy).
adjective_exception(trickier,tricky).
adjective_exception(trickiest,tricky).
adjective_exception(tricksier,tricksy).
adjective_exception(tricksiest,tricksy).
adjective_exception(trimmer,trim).
adjective_exception(trimmest,trim).
adjective_exception(truer,true).
adjective_exception(truest,true).
adjective_exception(trustier,trusty).
adjective_exception(trustiest,trusty).
adjective_exception(tubbier,tubby).
adjective_exception(tubbiest,tubby).
adjective_exception(turfier,turfy).
adjective_exception(turfiest,turfy).
adjective_exception(tweedier,tweedy).
adjective_exception(tweediest,tweedy).
adjective_exception(twiggier,twiggy).
adjective_exception(twiggiest,twiggy).
adjective_exception(uglier,ugly).
adjective_exception(ugliest,ugly).
adjective_exception(unfriendlier,unfriendly).
adjective_exception(unfriendliest,unfriendly).
adjective_exception(ungainlier,ungainly).
adjective_exception(ungainliest,ungainly).
adjective_exception(ungodlier,ungodly).
adjective_exception(ungodliest,ungodly).
adjective_exception(unhappier,unhappy).
adjective_exception(unhappiest,unhappy).
adjective_exception(unhealthier,unhealthy).
adjective_exception(unhealthiest,unhealthy).
adjective_exception(unholier,unholy).
adjective_exception(unholiest,unholy).
adjective_exception(unrulier,unruly).
adjective_exception(unruliest,unruly).
adjective_exception(untidier,untidy).
adjective_exception(untidiest,untidy).
adjective_exception(vastier,vasty).
adjective_exception(vastiest,vasty).
adjective_exception(viewier,viewy).
adjective_exception(viewiest,viewy).
adjective_exception(wackier,wacky).
adjective_exception(wackiest,wacky).
adjective_exception(wanner,wan).
adjective_exception(wannest,wan).
adjective_exception(warier,wary).
adjective_exception(wariest,wary).
adjective_exception(washier,washy).
adjective_exception(washiest,washy).
adjective_exception(wavier,wavy).
adjective_exception(waviest,wavy).
adjective_exception(waxier,waxy).
adjective_exception(waxiest,waxy).
adjective_exception(weaklier,weakly).
adjective_exception(weakliest,weakly).
adjective_exception(wealthier,wealthy).
adjective_exception(wealthiest,wealthy).
adjective_exception(wearier,weary).
adjective_exception(weariest,weary).
adjective_exception(webbier,webby).
adjective_exception(webbiest,webby).
adjective_exception(weedier,weedy).
adjective_exception(weediest,weedy).
adjective_exception(weenier,weeny).
adjective_exception(weeniest,weeny).
adjective_exception(weensier,weensy).
adjective_exception(weensiest,weensy).
adjective_exception(weepier,weepy).
adjective_exception(weepiest,weepy).
adjective_exception(weightier,weighty).
adjective_exception(weightiest,weighty).
adjective_exception(wetter,wet).
adjective_exception(wettest,wet).
adjective_exception(whackier,whacky).
adjective_exception(whackiest,whacky).
adjective_exception(whimsier,whimsy).
adjective_exception(whimsiest,whimsy).
adjective_exception(wieldier,wieldy).
adjective_exception(wieldiest,wieldy).
adjective_exception(wilier,wily).
adjective_exception(wiliest,wily).
adjective_exception(windier,windy).
adjective_exception(windiest,windy).
adjective_exception(winier,winy).
adjective_exception(winiest,winy).
adjective_exception(winterier,wintery).
adjective_exception(winteriest,wintery).
adjective_exception(wintrier,wintry).
adjective_exception(wintriest,wintry).
adjective_exception(wirier,wiry).
adjective_exception(wiriest,wiry).
adjective_exception(wispier,wispy).
adjective_exception(wispiest,wispy).
adjective_exception(wittier,witty).
adjective_exception(wittiest,witty).
adjective_exception(wonkier,wonky).
adjective_exception(wonkiest,wonky).
adjective_exception(woodier,woody).
adjective_exception(woodiest,woody).
adjective_exception(woodsier,woodsy).
adjective_exception(woodsiest,woodsy).
adjective_exception(woollier,woolly).
adjective_exception(woolliest,woolly).
adjective_exception(woozier,woozy).
adjective_exception(wooziest,woozy).
adjective_exception(wordier,wordy).
adjective_exception(wordiest,wordy).
adjective_exception(worldlier,worldly).
adjective_exception(worldliest,worldly).
adjective_exception(wormier,wormy).
adjective_exception(wormiest,wormy).
adjective_exception(worthier,worthy).
adjective_exception(worthiest,worthy).
adjective_exception(wrier,wry).
adjective_exception(wriest,wry).
adjective_exception(wryer,wry).
adjective_exception(wryest,wry).
adjective_exception(yarer,yare).
adjective_exception(yarest,yare).
adjective_exception(yeastier,yeasty).
adjective_exception(yeastiest,yeasty).
adjective_exception(younger,young).
adjective_exception(youngest,young).
adjective_exception(yummier,yummy).
adjective_exception(yummiest,yummy).
adjective_exception(zanier,zany).
adjective_exception(zaniest,zany).
adjective_exception(zippier,zippy).
adjective_exception(zippiest,zippy).
