FROM logicmoo/logicmoo_workspace:latest
USER root
#COPY --from=synthillect/atomspace:latest / /
#COPY --from=synthillect/opencog-dev:latest / /
#COPY --from=synthillect/opencog-jupyter:latest / /
COPY --from=synthillect/opencog-minerl:latest / /
COPY --from=logicmoo/logicmoo_workspace:latest / /
COPY docker/rootfs /
RUN cp /dockerstartup/generate_container_user /generate_container_user

EXPOSE 8188 1800 8888 4081 4082 4083 4084 4085
ENTRYPOINT ["/startup_logicmoo.sh"]

