FROM logicmoo/logicmoo_workspace:latest
USER root
RUN ls -l /var/lib/apt/lists/
RUN apt update
RUN apt install -y apt
COPY --from=synthillect/opencog-minerl:latest / /
RUN apt install --reinstall -y apt
COPY docker/rootfs /
EXPOSE 8188 1800 8888
ENTRYPOINT ["/startup_logicmoo.sh"]

