# where the whole package is located
ROOT_DIR = /home/bthomas/HI-WORK/PETER/ProSpec
# sub dir where the sources are
SRC = src

SRC_DIR = $(ROOT_DIR)/$(SRC)

SRC_FILES = Makefile myread.pl prospec.pl misc.pl pl2tme_pro.pl parser.pl \
utils.pl skolem.pl spec.pl error.pl hierachy.pl

co: 
	co -l $(SRC_FILES)

ci: $(SRC_FILES)
	ci -u $(SRC_FILES)

