% This file is part of AceRules.
% Copyright 2008-2012, Tobias Kuhn, http://www.tkuhn.ch
%
% AceRules is free software: you can redistribute it and/or modify it under the terms of the GNU
% Lesser General Public License as published by the Free Software Foundation, either version 3 of
% the License, or (at your option) any later version.
%
% AceRules is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even
% the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser
% General Public License for more details.
%
% You should have received a copy of the GNU Lesser General Public License along with AceRules. If
% not, see http://www.gnu.org/licenses/.


:- module(op_defs, [
		     op(400, fy, -),
		     op(400, fy, ~),
		     op(500, xfx, =>),
		     op(500, xfx, v),
			 is_modal_operator/1  % -Op
		    ]).

/** <module> Operator definitions

This modules only defines the operators that are used in DRSes generated by APE.

@author Tobias Kuhn
@version 2007-02-06
*/

is_modal_operator(can).
is_modal_operator(must).
is_modal_operator(should).
is_modal_operator(may).
