(define (problem monkey-test3)
    (:domain monkey-domain)
  (:objects p1 p2 p3 p4 p5 p6)
  (:init (location p1) (location p2)
	 (location p3)(location p4)
	 (location p5) (location p6)
	 (at monkey p1)(on-floor)
	 (at box p2)
	 (at bananas p3)
	 (at knife p4)
	 (at waterfountain p5)(at glass p6))
  (:goal (and (hasbananas) (haswater)))
  (:length (:serial 10) (:parallel 10))
    )