(define (problem monkey-test2)
    (:domain monkey-domain)
  (:objects P1 P2 P3 P4 P6)
  (:init (location p1)
	 (location p2)(location p3)
	 (location p4)(location p6)
	 (at monkey p1)(on-floor)
	 (at box p2)
	 (at bananas p3)
	 (at knife p4)
	 (at waterfountain p3)(at glass p6))
  (:goal (and (hasbananas) (haswater)))
  (:length (:serial 9) (:parallel 9)))