# Build a SWISH image, using the SWISH_SHA1 below. This is a simple variation of
# https://github.com/SWI-Prolog/docker-swish
# Build with:
#	docker build -t logicalcontracts/swish-june2020 -f Dockerfile-SWISH-June2020 .
################
# If the version below is unavailable, probably use 'latest':
FROM swipl:8.2.0 as base

RUN apt-get update && apt-get install -y \
    git build-essential autoconf curl unzip \
    cleancss node-requirejs

RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -
RUN apt-get install -y nodejs npm
# RUN npm install -g clean-css clean-css-cli
# RUN echo '{ "allow_root": true }' > .bowerrc 
RUN npm i yarn -g

# We'll place this instead on a more "portable" location:
ENV SWISH_HOME /home/swish
# June 12, 2020:
ENV SWISH_SHA1 d3c6a784d4c9d6baca661ddc3a228ee42f9f34e9

RUN echo "At version ${SWISH_SHA1}"
RUN (cd /home && git clone https://github.com/SWI-Prolog/swish.git) && \
    (cd ${SWISH_HOME} && git checkout -q ${SWISH_SHA1} && make packs && yarn && make src)
# We don't need   git submodule update --init

FROM base
# adapted from... LABEL maintainer "Jan Wielemaker <jan@swi-prolog.org>"
LABEL maintainer "Miguel Calejo <mc@logicalcontracts.com>"

RUN apt-get update && apt-get install -y \
    graphviz imagemagick \
    git \
    wamerican && \
    rm -rf /var/lib/apt/lists/*

COPY --from=base ${SWISH_HOME} ${SWISH_HOME}
COPY ./entry.sh entry.sh

ENV SWISH_DATA /data
VOLUME ${SWISH_DATA}
WORKDIR ${SWISH_DATA}

ENTRYPOINT ["/entry.sh"]


