(define (problem get-paid2-strips)
  (:domain briefcase-strips)
  (:objects D P home office)
  (:init (at B home)
	 (at P home)
	 (at D home)
	 (in P B))
  (:goal (and (at B home)
	      (at D office)
	      (at P home)))
  (:length (:serial 4) (:parallel 4)))