(define (problem uget-paid3)
    (:domain uni-bw)
  (:objects P D home office bank)
  (:init (place home)(place office)(place bank)
	 (obj p)(obj d)(obj b)
	 (at B home) (at P home) (at D home) (in P))
  (:goal (and (at P bank) (at D office) (at B home)))
  (:length (:serial 6) (:parallel 6))
    )