(DEFINE (PROBLEM MOLGEN1-STRIPS) (:DOMAIN MOLGEN-STRIPS) 
  (:objects insulin-gene e-coli-exosome junk-exosome e-coli junk
	    antibiotic-1)
  
  (:init
 (MOLECULE INSULIN-GENE) (MOLECULE E-COLI-EXOSOME) (MOLECULE JUNK-EXOSOME)
  (MOLECULE LINKER) (BACTERIUM E-COLI) (BACTERIUM JUNK)
  (ANTIBIOTIC ANTIBIOTIC-1) (MRNA INSULIN-GENE) (CLEAVABLE E-COLI-EXOSOME)
  (CLEAVABLE JUNK-EXOSOME) (ACCEPTS JUNK-EXOSOME JUNK)
  (ACCEPTS E-COLI-EXOSOME E-COLI) (RESISTS ANTIBIOTIC-1 E-COLI-EXOSOME))
  (:GOAL
 (AND (EXISTS (?X ?Y)
  (AND (BACTERIUM ?Y) (MOLECULE ?X) (CONTAINS INSULIN-GENE ?X)
   (CONTAINS ?X ?Y) (PURE ?Y))))))