(define (problem med-bw1)
    (:domain snlp-bw1)
  (:objects a b c d e)
  (:init (on c a) (on-table b) (on-table a)
	 (on e c) (on d b)
	 (clear d) (clear e))
  (:goal (AND (on a b)
	      (on b c)
	      (on c d)
	      (on d e)))
  (:length (:serial 7) (:parallel 5)))