(define (problem small-bw2)
    (:domain snlp-bw2)
  (:objects a b c d)
  (:init (on c a) (on-table b) (on-table a)
	 (on d b)
	 (clear d) (clear c))
  (:goal (AND (on a b)
	      (on b c)
	      (on c d)
	      ))
  (:length (:serial 4) (:parallel 4)))