( define ( problem att-sussman ) 
    (:domain att-bw)
  (:objects A B C)
  (:init ( block a ) ( block b ) ( block c ) ( is-table table)
	 ( on a table)
	 ( on b table)
	 ( on c a )
	 ( clear b )
	 ( clear c ) )
  (:goal ( AND (on a b) (on b c) ))
  (:length (:serial 3) (:parallel 3))
  )