(define (problem small-bw1)
    (:domain snlp-bw1)
  (:objects a b c d)
  (:init (on c a) (on-table b) (on-table a)
	 (on d b)
	 (clear d) (clear c))
  (:goal (AND (on a b)
	      (on b c)
	      (on c d)))
  (:length (:serial 5) (:parallel 4)))