# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded hexrec 2.0 [list source [file join $dir hexrec.tcl]]
package ifneeded rcxComm 2.0 [list source [file join $dir rcxComm.tcl]]
package ifneeded rcxMacComm 2.0 [list source [file join $dir rcxmac.tcl]]
package ifneeded rcxOption 2.0 [list source [file join $dir rcxoption.tcl]]
package ifneeded rcxUnixComm 2.0 [list source [file join $dir rcxunix.tcl]]
package ifneeded rcxWinComm 2.0 [list source [file join $dir rcxwin.tcl]]
package ifneeded rcxWinCommSerial 2.0 [list source [file join $dir rcxwin-serial.tcl]]
package ifneeded rcxWinCommUSB 2.0 [list source [file join $dir rcxwin-usb.tcl]]
package ifneeded rcxfirm 2.0 [list source [file join $dir rcxfirm.tcl]]
package ifneeded rcxterm 2.0 [list source [file join $dir rcxterm.tcl]]
package ifneeded rcxutil 2.0 [list source [file join $dir rcxutil.tcl]]
package ifneeded xmodem 2.0 [list source [file join $dir xmodem.tcl]]
