(define (domain shuffling_domain)
(:requirements :strips)
(:predicates
    (at ?block ?position)
    (left ?position_left ?position_right)
)

(:action 2shuffle
:parameters (?block1 ?block2 ?pos1 ?pos2)
:precondition (and (at ?block1 ?pos1)
                   (at ?block2 ?pos2)
                   (left ?pos1 ?pos2))
:effect (and (at ?block1 ?pos2)
             (at ?block2 ?pos1)
             (not (at ?block1 ?pos1))
             (not (at ?block2 ?pos2))))

(:action 3shuffle_right
:parameters (?block1 ?block2 ?block3 ?pos1 ?pos2 ?pos3)
:precondition (and (at ?block1 ?pos1)
                   (at ?block2 ?pos2)
                   (at ?block3 ?pos3)
                   (left ?pos1 ?pos2)
                   (left ?pos2 ?pos3))
:effect (and (at ?block1 ?pos2)
             (at ?block2 ?pos3)
             (at ?block3 ?pos1)
             (not (at ?block1 ?pos1))
             (not (at ?block2 ?pos2))
             (not (at ?block3 ?pos3))))

(:action 3shuffle_left
:parameters (?block1 ?block2 ?block3 ?pos1 ?pos2 ?pos3)
:precondition (and (at ?block1 ?pos1)
                   (at ?block2 ?pos2)
                   (at ?block3 ?pos3)
                   (left ?pos1 ?pos2)
                   (left ?pos2 ?pos3))
:effect (and (at ?block1 ?pos3)
             (at ?block2 ?pos1)
             (at ?block3 ?pos2)
             (not (at ?block1 ?pos1))
             (not (at ?block2 ?pos2))
             (not (at ?block3 ?pos3))))
)
