(define (problem shuffling-9)
(:domain shuffling_domain)
(:objects block1 block2 block3 block4 block5 block6 block7 block8 block9
          pos1 pos2 pos3 pos4 pos5 pos6 pos7 pos8 pos9)

(:init
(at block1 pos3)
(at block2 pos6)
(at block3 pos4)
(at block4 pos9)
(at block5 pos1)
(at block6 pos8)
(at block7 pos7)
(at block8 pos2)
(at block9 pos5)

(left pos1 pos2)
(left pos2 pos3)
(left pos3 pos4)
(left pos4 pos5)
(left pos5 pos6)
(left pos6 pos7)
(left pos7 pos8)
(left pos8 pos9)
)
(:goal
    (and (at block1 pos1)
         (at block2 pos2)
         (at block3 pos3)
         (at block4 pos4)
         (at block5 pos5)
         (at block6 pos6)
         (at block7 pos7)
         (at block8 pos8)
         (at block9 pos9)))
)
