/* Generated By:JJTree: Do not edit this line. ASTFloat.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.cs3.prolog.connector.internal.cterm.parser;

public
class ASTFloat extends org.cs3.prolog.connector.internal.cterm.parser.ASTNode {
  public ASTFloat(int id) {
    super(id);
  }

  public ASTFloat(CanonicalTermParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  @Override
public Object jjtAccept(CanonicalTermParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=fc37cf9ee687b24eaad78e965ae1f463 (do not edit this line) */
