/* Generated By:JJTree: Do not edit this line. ASTNil.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.cs3.prolog.connector.internal.cterm.parser;

public
class ASTNil extends org.cs3.prolog.connector.internal.cterm.parser.ASTNode {
  public ASTNil(int id) {
    super(id);
  }

  public ASTNil(CanonicalTermParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  @Override
public Object jjtAccept(CanonicalTermParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ad6f1b685eed044c5bd263b45e63ac40 (do not edit this line) */
