/* Generated By:JavaCC: Do not edit this line. CanonicalTermParserTreeConstants.java Version 5.0 */
package org.cs3.prolog.connector.internal.cterm.parser;

public interface CanonicalTermParserTreeConstants
{
  public int JJTVOID = 0;
  public int JJTATOM = 1;
  public int JJTNIL = 2;
  public int JJTVARIABLE = 3;
  public int JJTCOMPOUND = 4;
  public int JJTINTEGER = 5;
  public int JJTFLOAT = 6;
  public int JJTSTRING = 7;


  public String[] jjtNodeName = {
    "void",
    "Atom",
    "Nil",
    "Variable",
    "Compound",
    "Integer",
    "Float",
    "String",
  };
}
/* JavaCC - OriginalChecksum=64039172a0cfffc49e33fd5a6f497e92 (do not edit this line) */
