/*

QUERY 1:
sub_class('Village','PopulatedPlace',LE).

EXPL:
LE = [(equivalentClasses(['#0_144_',intersectionOf(['PopulatedPlace','Place'])]),1),(subClassOf('Village','#0_144_'),1)] ? ;

LE = [(equivalentClasses(['#73_0_',intersectionOf(['Settlement','PopulatedPlace'])]),1),(subClassOf('Village','#73_0_'),1)] ? ;

LE = [(equivalentClasses(['#0_144_',intersectionOf(['PopulatedPlace','Place'])]),1),(subClassOf('Settlement','#0_144_'),1),(subClassOf('Village','Settlement'),1)] ? ;

LE = [(subClassOf('Settlement','PopulatedPlace'),1),(subClassOf('Village','Settlement'),1)] ? ;

LE = [(equivalentClasses(['#73_0_',intersectionOf(['Settlement','PopulatedPlace'])]),1),(subClassOf('Place','#73_0_'),1),(subClassOf('Settlement','Place'),1),(subClassOf('Village','Settlement'),1)] ? ;

LE = [(subClassOf('Place','PopulatedPlace'),1),(subClassOf('Settlement','Place'),1),(subClassOf('Village','Settlement'),1)] ? ;

LE = [(equivalentClasses(['#73_0_144_',intersectionOf(['Settlement','PopulatedPlace','Place'])]),1),(subClassOf('Village','#73_0_144_'),1)] ? ;

LE = [(subClassOf('Village','PopulatedPlace'),1)] ? ;

LE = [(equivalentClasses(['#73_0_',intersectionOf(['Settlement','PopulatedPlace'])]),1),(subClassOf('Place','#73_0_'),1),(subClassOf('Village','Place'),1)] ? ;

LE = [(equivalentClasses(['#0_144_',intersectionOf(['PopulatedPlace','Place'])]),1),(subClassOf('Settlement','#0_144_'),1),(subClassOf('Place','Settlement'),1),(subClassOf('Village','Place'),1)] ? ;

LE = [(subClassOf('Settlement','PopulatedPlace'),1),(subClassOf('Place','Settlement'),1),(subClassOf('Village','Place'),1)] ? ;

LE = [(subClassOf('Place','PopulatedPlace'),1),(subClassOf('Village','Place'),1)] ? ;

LE = [(equivalentClasses(['#73_0_',intersectionOf(['Settlement','PopulatedPlace'])]),1),(subClassOf('Place','#73_0_'),1),(equivalentClasses(['#73_144_',intersectionOf(['Settlement','Place'])]),1),(subClassOf('Village','#73_144_'),1)] ? ;

LE = [(subClassOf('Place','PopulatedPlace'),1),(equivalentClasses(['#73_144_',intersectionOf(['Settlement','Place'])]),1),(subClassOf('Village','#73_144_'),1)] ? ;

LE = [(equivalentClasses(['#0_144_',intersectionOf(['PopulatedPlace','Place'])]),1),(subClassOf('Settlement','#0_144_'),1),(equivalentClasses(['#73_144_',intersectionOf(['Settlement','Place'])]),1),(subClassOf('Village','#73_144_'),1)] ? ;

LE = [(subClassOf('Settlement','PopulatedPlace'),1),(equivalentClasses(['#73_144_',intersectionOf(['Settlement','Place'])]),1),(subClassOf('Village','#73_144_'),1)] 

*/

equivalentClasses(['#0_144_',intersectionOf(['PopulatedPlace','Place'])]).
equivalentClasses(['#73_0_',intersectionOf(['Settlement','PopulatedPlace'])]).
equivalentClasses(['#73_144_',intersectionOf(['Settlement','Place'])]).
equivalentClasses(['#73_0_144_',intersectionOf(['Settlement','PopulatedPlace','Place'])]).
subClassOf('ComicsCreator','Person').
subClassOf('Model','Person').
subClassOf('CollegeCoach','Person').
subClassOf('Continent','Place').
subClassOf('Continent','PopulatedPlace').
subClassOf('Continent','#0_144_').
subClassOf('Mountain','Place').
subClassOf('Lighthouse','Place').
subClassOf('MemberOfParliament','Person').
subClassOf('Country','Place').
subClassOf('Country','PopulatedPlace').
subClassOf('Country','#0_144_').
subClassOf('Book','Work').
subClassOf('SiteOfSpecialScientificInterest','Place').
subClassOf('Chancellor','Person').
subClassOf('FormulaOneRacer','Person').
subClassOf('Musical','Work').
subClassOf('Criminal','Person').
subClassOf('GridironFootballPlayer','Person').
subClassOf('Cyclist','Person').
subClassOf('AmericanFootballPlayer','Person').
subClassOf('Boxer','Person').
subClassOf('Skyscraper','Place').
subClassOf('FigureSkater','Person').
subClassOf('Comedian','Person').
subClassOf('Song','Work').
subClassOf('VideoGame','Work').
subClassOf('AdministrativeRegion','Place').
subClassOf('AdministrativeRegion','PopulatedPlace').
subClassOf('AdministrativeRegion','#0_144_').
subClassOf('FictionalCharacter','Person').
subClassOf('PopulatedPlace','#73_144_').
subClassOf('PopulatedPlace','Place').
subClassOf('PopulatedPlace','Settlement').
subClassOf('MountainRange','Place').
subClassOf('Congressman','Person').
subClassOf('Single','Work').
subClassOf('MilitaryPerson','Person').
subClassOf('Software','Work').
subClassOf('BodyOfWater','Place').
subClassOf('TelevisionEpisode','Work').
subClassOf('LunarCrater','Place').
subClassOf('Station','Place').
subClassOf('VoiceActor','Person').
subClassOf('BasketballPlayer','Person').
subClassOf('Building','Place').
subClassOf('Album','Work').
subClassOf('Airport','Place').
subClassOf('Cardinal','Person').
subClassOf('BadmintonPlayer','Person').
subClassOf('President','Person').
subClassOf('Wrestler','Person').
subClassOf('River','Place').
subClassOf('HistoricPlace','Place').
subClassOf('Cleric','Person').
subClassOf('SoccerPlayer','Person').
subClassOf('Architect','Person').
subClassOf('Judge','Person').
subClassOf('Lake','Place').
subClassOf('EurovisionSongContestEntry','Work').
subClassOf('ComicsCharacter','Person').
subClassOf('WorldHeritageSite','Place').
subClassOf('TelevisionShow','Work').
subClassOf('LaunchPad','Place').
subClassOf('BaseballPlayer','Person').
subClassOf('ChristianBishop','Person').
subClassOf('NationalCollegiateAthleticAssociationAthlete','Person').
subClassOf('Saint','Person').
subClassOf('Cricketer','Person').
subClassOf('Astronaut','Person').
subClassOf('Island','Place').
subClassOf('Island','PopulatedPlace').
subClassOf('Island','#0_144_').
subClassOf('IceHockeyPlayer','Person').
subClassOf('Stream','Place').
subClassOf('Governor','Person').
subClassOf('Newspaper','Work').
subClassOf('SoccerManager','Person').
subClassOf('BritishRoyalty','Person').
subClassOf('Hospital','Place').
subClassOf('Journalist','Person').
subClassOf('NascarDriver','Person').
subClassOf('Park','Place').
subClassOf('Bridge','Place').
subClassOf('Village','#73_144_').
subClassOf('Village','Place').
subClassOf('Village','PopulatedPlace').
subClassOf('Village','#73_0_144_').
subClassOf('Village','Settlement').
subClassOf('Village','#73_0_').
subClassOf('Village','#0_144_').
subClassOf('Senator','Person').
subClassOf('ProtectedArea','Place').
subClassOf('Stadium','Place').
subClassOf('Magazine','Work').
subClassOf('Canal','Place').
subClassOf('Politician','Person').
subClassOf('MusicalArtist','Person').
subClassOf('PrimeMinister','Person').
subClassOf('Town','#73_144_').
subClassOf('Town','Place').
subClassOf('Town','PopulatedPlace').
subClassOf('Town','#73_0_144_').
subClassOf('Town','Settlement').
subClassOf('Town','#73_0_').
subClassOf('Town','#0_144_').
subClassOf('OfficeHolder','Person').
subClassOf('Film','Work').
subClassOf('TennisPlayer','Person').
subClassOf('Athlete','Person').
subClassOf('Pope','Person').
subClassOf('Mayor','Person').
subClassOf('Cave','Place').
subClassOf('MusicalWork','Work').
subClassOf('PlayboyPlaymate','Person').
subClassOf('Monarch','Person').
subClassOf('Settlement','Place').
subClassOf('Settlement','PopulatedPlace').
subClassOf('Settlement','#0_144_').
subClassOf('City','#73_144_').
subClassOf('City','Place').
subClassOf('City','PopulatedPlace').
subClassOf('City','#73_0_144_').
subClassOf('City','Settlement').
subClassOf('City','#73_0_').
subClassOf('City','#0_144_').
subClassOf('ShoppingMall','Place').
subClassOf('SkiArea','Place').
subClassOf('Monument','Place').
subClassOf('WineRegion','Place').
subClassOf('GaelicGamesPlayer','Person').
subClassOf('PokerPlayer','Person').
subClassOf('AdultActor','Person').
subClassOf('Ambassador','Person').
subClassOf('Place','PopulatedPlace').
subClassOf('Place','Settlement').
subClassOf('Place','#73_0_').
subClassOf('Philosopher','Person').
subClassOf('Scientist','Person').
subClassOf('Artist','Person').
subClassOf('Actor','Person').
subClassOf('Valley','Place').
subClassOf('Writer','Person').
subClassOf('RugbyPlayer','Person').
annotationProperty('http://www.w3.org/2000/01/rdf-schema#label').
annotationProperty('http://www.w3.org/2000/01/rdf-schema#comment').
annotationProperty('https://sites.google.com/a/unife.it/ml/bundle#probability').
class('#0_144_').
class('#73_0_').
class('#73_144_').
class('#73_0_144_').
class('ComicsCreator').
class('Model').
class('CollegeCoach').
class('Continent').
class('Mountain').
class('Lighthouse').
class('MemberOfParliament').
class('Country').
class('Book').
class('SiteOfSpecialScientificInterest').
class('Chancellor').
class('FormulaOneRacer').
class('Musical').
class('Criminal').
class('GridironFootballPlayer').
class('Cyclist').
class('AmericanFootballPlayer').
class('Boxer').
class('Skyscraper').
class('FigureSkater').
class('Comedian').
class('Song').
class('VideoGame').
class('AdministrativeRegion').
class('FictionalCharacter').
class('PopulatedPlace').
class('MountainRange').
class('Congressman').
class('Single').
class('MilitaryPerson').
class('Software').
class('BodyOfWater').
class('TelevisionEpisode').
class('LunarCrater').
class('Station').
class('VoiceActor').
class('BasketballPlayer').
class('Building').
class('Album').
class('Airport').
class('Cardinal').
class('BadmintonPlayer').
class('President').
class('Wrestler').
class('River').
class('HistoricPlace').
class('Cleric').
class('SoccerPlayer').
class('Architect').
class('Judge').
class('Lake').
class('EurovisionSongContestEntry').
class('ComicsCharacter').
class('WorldHeritageSite').
class('TelevisionShow').
class('LaunchPad').
class('BaseballPlayer').
class('ChristianBishop').
class('NationalCollegiateAthleticAssociationAthlete').
class('Saint').
class('Cricketer').
class('Astronaut').
class('Island').
class('IceHockeyPlayer').
class('Stream').
class('Governor').
class('Newspaper').
class('SoccerManager').
class('BritishRoyalty').
class('Hospital').
class('Journalist').
class('NascarDriver').
class('Park').
class('Bridge').
class('Village').
class('Senator').
class('ProtectedArea').
class('Stadium').
class('Magazine').
class('Canal').
class('Politician').
class('MusicalArtist').
class('PrimeMinister').
class('Town').
class('OfficeHolder').
class('Film').
class('TennisPlayer').
class('Athlete').
class('Pope').
class('Mayor').
class('Cave').
class('MusicalWork').
class('PlayboyPlaymate').
class('Monarch').
class('Settlement').
class('City').
class('ShoppingMall').
class('SkiArea').
class('Monument').
class('WineRegion').
class('GaelicGamesPlayer').
class('PokerPlayer').
class('AdultActor').
class('Ambassador').
class('Place').
class('Philosopher').
class('Scientist').
class('Artist').
class('Actor').
class('Valley').
class('Writer').
class('RugbyPlayer').
ontology('').
ontologyAxiom('',ontologyVersionInfo('',literal(lang(en,'Version 3.5')))).
ontologyAxiom('',ontology('')).
ontologyAxiom('',annotationProperty('https://sites.google.com/a/unife.it/ml/bundle#probability')).
ontologyAxiom('',class('#0_144_')).
ontologyAxiom('',class('#73_0_')).
ontologyAxiom('',class('#73_144_')).
ontologyAxiom('',class('#73_0_144_')).
ontologyAxiom('',class('ComicsCreator')).
ontologyAxiom('',class('Model')).
ontologyAxiom('',class('CollegeCoach')).
ontologyAxiom('',class('Continent')).
ontologyAxiom('',class('Mountain')).
ontologyAxiom('',class('Lighthouse')).
ontologyAxiom('',class('MemberOfParliament')).
ontologyAxiom('',class('Country')).
ontologyAxiom('',class('Book')).
ontologyAxiom('',class('SiteOfSpecialScientificInterest')).
ontologyAxiom('',class('Chancellor')).
ontologyAxiom('',class('FormulaOneRacer')).
ontologyAxiom('',class('Musical')).
ontologyAxiom('',class('Criminal')).
ontologyAxiom('',class('GridironFootballPlayer')).
ontologyAxiom('',class('Cyclist')).
ontologyAxiom('',class('AmericanFootballPlayer')).
ontologyAxiom('',class('Boxer')).
ontologyAxiom('',class('Skyscraper')).
ontologyAxiom('',class('FigureSkater')).
ontologyAxiom('',class('Comedian')).
ontologyAxiom('',class('Song')).
ontologyAxiom('',class('VideoGame')).
ontologyAxiom('',class('AdministrativeRegion')).
ontologyAxiom('',class('FictionalCharacter')).
ontologyAxiom('',class('PopulatedPlace')).
ontologyAxiom('',class('MountainRange')).
ontologyAxiom('',class('Congressman')).
ontologyAxiom('',class('Single')).
ontologyAxiom('',class('MilitaryPerson')).
ontologyAxiom('',class('Software')).
ontologyAxiom('',class('BodyOfWater')).
ontologyAxiom('',class('TelevisionEpisode')).
ontologyAxiom('',class('LunarCrater')).
ontologyAxiom('',class('Station')).
ontologyAxiom('',class('VoiceActor')).
ontologyAxiom('',class('BasketballPlayer')).
ontologyAxiom('',class('Building')).
ontologyAxiom('',class('Album')).
ontologyAxiom('',class('Airport')).
ontologyAxiom('',class('Cardinal')).
ontologyAxiom('',class('BadmintonPlayer')).
ontologyAxiom('',class('President')).
ontologyAxiom('',class('Wrestler')).
ontologyAxiom('',class('River')).
ontologyAxiom('',class('HistoricPlace')).
ontologyAxiom('',class('Cleric')).
ontologyAxiom('',class('SoccerPlayer')).
ontologyAxiom('',class('Architect')).
ontologyAxiom('',class('Judge')).
ontologyAxiom('',class('Lake')).
ontologyAxiom('',class('EurovisionSongContestEntry')).
ontologyAxiom('',class('ComicsCharacter')).
ontologyAxiom('',class('WorldHeritageSite')).
ontologyAxiom('',class('TelevisionShow')).
ontologyAxiom('',class('LaunchPad')).
ontologyAxiom('',class('BaseballPlayer')).
ontologyAxiom('',class('ChristianBishop')).
ontologyAxiom('',class('NationalCollegiateAthleticAssociationAthlete')).
ontologyAxiom('',class('Saint')).
ontologyAxiom('',class('Cricketer')).
ontologyAxiom('',class('Astronaut')).
ontologyAxiom('',class('Island')).
ontologyAxiom('',class('IceHockeyPlayer')).
ontologyAxiom('',class('Stream')).
ontologyAxiom('',class('Governor')).
ontologyAxiom('',class('Newspaper')).
ontologyAxiom('',class('SoccerManager')).
ontologyAxiom('',class('BritishRoyalty')).
ontologyAxiom('',class('Hospital')).
ontologyAxiom('',class('Journalist')).
ontologyAxiom('',class('NascarDriver')).
ontologyAxiom('',class('Park')).
ontologyAxiom('',class('Bridge')).
ontologyAxiom('',class('Village')).
ontologyAxiom('',class('Senator')).
ontologyAxiom('',class('ProtectedArea')).
ontologyAxiom('',class('Stadium')).
ontologyAxiom('',class('Magazine')).
ontologyAxiom('',class('Canal')).
ontologyAxiom('',class('Politician')).
ontologyAxiom('',class('MusicalArtist')).
ontologyAxiom('',class('PrimeMinister')).
ontologyAxiom('',class('Town')).
ontologyAxiom('',class('OfficeHolder')).
ontologyAxiom('',class('Film')).
ontologyAxiom('',class('TennisPlayer')).
ontologyAxiom('',class('Athlete')).
ontologyAxiom('',class('Pope')).
ontologyAxiom('',class('Mayor')).
ontologyAxiom('',class('Cave')).
ontologyAxiom('',class('MusicalWork')).
ontologyAxiom('',class('PlayboyPlaymate')).
ontologyAxiom('',class('Monarch')).
ontologyAxiom('',class('Settlement')).
ontologyAxiom('',class('City')).
ontologyAxiom('',class('ShoppingMall')).
ontologyAxiom('',class('SkiArea')).
ontologyAxiom('',class('Monument')).
ontologyAxiom('',class('WineRegion')).
ontologyAxiom('',class('GaelicGamesPlayer')).
ontologyAxiom('',class('PokerPlayer')).
ontologyAxiom('',class('AdultActor')).
ontologyAxiom('',class('Ambassador')).
ontologyAxiom('',class('Place')).
ontologyAxiom('',class('Philosopher')).
ontologyAxiom('',class('Scientist')).
ontologyAxiom('',class('Artist')).
ontologyAxiom('',class('Actor')).
ontologyAxiom('',class('Valley')).
ontologyAxiom('',class('Writer')).
ontologyAxiom('',class('RugbyPlayer')).
ontologyAxiom('',subClassOf('ComicsCreator','Person')).
ontologyAxiom('',subClassOf('Model','Person')).
ontologyAxiom('',subClassOf('CollegeCoach','Person')).
ontologyAxiom('',subClassOf('Continent','Place')).
ontologyAxiom('',subClassOf('Continent','PopulatedPlace')).
ontologyAxiom('',subClassOf('Continent','#0_144_')).
ontologyAxiom('',subClassOf('Mountain','Place')).
ontologyAxiom('',subClassOf('Lighthouse','Place')).
ontologyAxiom('',subClassOf('MemberOfParliament','Person')).
ontologyAxiom('',subClassOf('Country','Place')).
ontologyAxiom('',subClassOf('Country','PopulatedPlace')).
ontologyAxiom('',subClassOf('Country','#0_144_')).
ontologyAxiom('',subClassOf('Book','Work')).
ontologyAxiom('',subClassOf('SiteOfSpecialScientificInterest','Place')).
ontologyAxiom('',subClassOf('Chancellor','Person')).
ontologyAxiom('',subClassOf('FormulaOneRacer','Person')).
ontologyAxiom('',subClassOf('Musical','Work')).
ontologyAxiom('',subClassOf('Criminal','Person')).
ontologyAxiom('',subClassOf('GridironFootballPlayer','Person')).
ontologyAxiom('',subClassOf('Cyclist','Person')).
ontologyAxiom('',subClassOf('AmericanFootballPlayer','Person')).
ontologyAxiom('',subClassOf('Boxer','Person')).
ontologyAxiom('',subClassOf('Skyscraper','Place')).
ontologyAxiom('',subClassOf('FigureSkater','Person')).
ontologyAxiom('',subClassOf('Comedian','Person')).
ontologyAxiom('',subClassOf('Song','Work')).
ontologyAxiom('',subClassOf('VideoGame','Work')).
ontologyAxiom('',subClassOf('AdministrativeRegion','Place')).
ontologyAxiom('',subClassOf('AdministrativeRegion','PopulatedPlace')).
ontologyAxiom('',subClassOf('AdministrativeRegion','#0_144_')).
ontologyAxiom('',subClassOf('FictionalCharacter','Person')).
ontologyAxiom('',subClassOf('PopulatedPlace','#73_144_')).
ontologyAxiom('',subClassOf('PopulatedPlace','Place')).
ontologyAxiom('',subClassOf('PopulatedPlace','Settlement')).
ontologyAxiom('',subClassOf('MountainRange','Place')).
ontologyAxiom('',subClassOf('Congressman','Person')).
ontologyAxiom('',subClassOf('Single','Work')).
ontologyAxiom('',subClassOf('MilitaryPerson','Person')).
ontologyAxiom('',subClassOf('Software','Work')).
ontologyAxiom('',subClassOf('BodyOfWater','Place')).
ontologyAxiom('',subClassOf('TelevisionEpisode','Work')).
ontologyAxiom('',subClassOf('LunarCrater','Place')).
ontologyAxiom('',subClassOf('Station','Place')).
ontologyAxiom('',subClassOf('VoiceActor','Person')).
ontologyAxiom('',subClassOf('BasketballPlayer','Person')).
ontologyAxiom('',subClassOf('Building','Place')).
ontologyAxiom('',subClassOf('Album','Work')).
ontologyAxiom('',subClassOf('Airport','Place')).
ontologyAxiom('',subClassOf('Cardinal','Person')).
ontologyAxiom('',subClassOf('BadmintonPlayer','Person')).
ontologyAxiom('',subClassOf('President','Person')).
ontologyAxiom('',subClassOf('Wrestler','Person')).
ontologyAxiom('',subClassOf('River','Place')).
ontologyAxiom('',subClassOf('HistoricPlace','Place')).
ontologyAxiom('',subClassOf('Cleric','Person')).
ontologyAxiom('',subClassOf('SoccerPlayer','Person')).
ontologyAxiom('',subClassOf('Architect','Person')).
ontologyAxiom('',subClassOf('Judge','Person')).
ontologyAxiom('',subClassOf('Lake','Place')).
ontologyAxiom('',subClassOf('EurovisionSongContestEntry','Work')).
ontologyAxiom('',subClassOf('ComicsCharacter','Person')).
ontologyAxiom('',subClassOf('WorldHeritageSite','Place')).
ontologyAxiom('',subClassOf('TelevisionShow','Work')).
ontologyAxiom('',subClassOf('LaunchPad','Place')).
ontologyAxiom('',subClassOf('BaseballPlayer','Person')).
ontologyAxiom('',subClassOf('ChristianBishop','Person')).
ontologyAxiom('',subClassOf('NationalCollegiateAthleticAssociationAthlete','Person')).
ontologyAxiom('',subClassOf('Saint','Person')).
ontologyAxiom('',subClassOf('Cricketer','Person')).
ontologyAxiom('',subClassOf('Astronaut','Person')).
ontologyAxiom('',subClassOf('Island','Place')).
ontologyAxiom('',subClassOf('Island','PopulatedPlace')).
ontologyAxiom('',subClassOf('Island','#0_144_')).
ontologyAxiom('',subClassOf('IceHockeyPlayer','Person')).
ontologyAxiom('',subClassOf('Stream','Place')).
ontologyAxiom('',subClassOf('Governor','Person')).
ontologyAxiom('',subClassOf('Newspaper','Work')).
ontologyAxiom('',subClassOf('SoccerManager','Person')).
ontologyAxiom('',subClassOf('BritishRoyalty','Person')).
ontologyAxiom('',subClassOf('Hospital','Place')).
ontologyAxiom('',subClassOf('Journalist','Person')).
ontologyAxiom('',subClassOf('NascarDriver','Person')).
ontologyAxiom('',subClassOf('Park','Place')).
ontologyAxiom('',subClassOf('Bridge','Place')).
ontologyAxiom('',subClassOf('Village','#73_144_')).
ontologyAxiom('',subClassOf('Village','Place')).
ontologyAxiom('',subClassOf('Village','PopulatedPlace')).
ontologyAxiom('',subClassOf('Village','#73_0_144_')).
ontologyAxiom('',subClassOf('Village','Settlement')).
ontologyAxiom('',subClassOf('Village','#73_0_')).
ontologyAxiom('',subClassOf('Village','#0_144_')).
ontologyAxiom('',subClassOf('Senator','Person')).
ontologyAxiom('',subClassOf('ProtectedArea','Place')).
ontologyAxiom('',subClassOf('Stadium','Place')).
ontologyAxiom('',subClassOf('Magazine','Work')).
ontologyAxiom('',subClassOf('Canal','Place')).
ontologyAxiom('',subClassOf('Politician','Person')).
ontologyAxiom('',subClassOf('MusicalArtist','Person')).
ontologyAxiom('',subClassOf('PrimeMinister','Person')).
ontologyAxiom('',subClassOf('Town','#73_144_')).
ontologyAxiom('',subClassOf('Town','Place')).
ontologyAxiom('',subClassOf('Town','PopulatedPlace')).
ontologyAxiom('',subClassOf('Town','#73_0_144_')).
ontologyAxiom('',subClassOf('Town','Settlement')).
ontologyAxiom('',subClassOf('Town','#73_0_')).
ontologyAxiom('',subClassOf('Town','#0_144_')).
ontologyAxiom('',subClassOf('OfficeHolder','Person')).
ontologyAxiom('',subClassOf('Film','Work')).
ontologyAxiom('',subClassOf('TennisPlayer','Person')).
ontologyAxiom('',subClassOf('Athlete','Person')).
ontologyAxiom('',subClassOf('Pope','Person')).
ontologyAxiom('',subClassOf('Mayor','Person')).
ontologyAxiom('',subClassOf('Cave','Place')).
ontologyAxiom('',subClassOf('MusicalWork','Work')).
ontologyAxiom('',subClassOf('PlayboyPlaymate','Person')).
ontologyAxiom('',subClassOf('Monarch','Person')).
ontologyAxiom('',subClassOf('Settlement','Place')).
ontologyAxiom('',subClassOf('Settlement','PopulatedPlace')).
ontologyAxiom('',subClassOf('Settlement','#0_144_')).
ontologyAxiom('',subClassOf('City','#73_144_')).
ontologyAxiom('',subClassOf('City','Place')).
ontologyAxiom('',subClassOf('City','PopulatedPlace')).
ontologyAxiom('',subClassOf('City','#73_0_144_')).
ontologyAxiom('',subClassOf('City','Settlement')).
ontologyAxiom('',subClassOf('City','#73_0_')).
ontologyAxiom('',subClassOf('City','#0_144_')).
ontologyAxiom('',subClassOf('ShoppingMall','Place')).
ontologyAxiom('',subClassOf('SkiArea','Place')).
ontologyAxiom('',subClassOf('Monument','Place')).
ontologyAxiom('',subClassOf('WineRegion','Place')).
ontologyAxiom('',subClassOf('GaelicGamesPlayer','Person')).
ontologyAxiom('',subClassOf('PokerPlayer','Person')).
ontologyAxiom('',subClassOf('AdultActor','Person')).
ontologyAxiom('',subClassOf('Ambassador','Person')).
ontologyAxiom('',subClassOf('Place','PopulatedPlace')).
ontologyAxiom('',subClassOf('Place','Settlement')).
ontologyAxiom('',subClassOf('Place','#73_0_')).
ontologyAxiom('',subClassOf('Philosopher','Person')).
ontologyAxiom('',subClassOf('Scientist','Person')).
ontologyAxiom('',subClassOf('Artist','Person')).
ontologyAxiom('',subClassOf('Actor','Person')).
ontologyAxiom('',subClassOf('Valley','Place')).
ontologyAxiom('',subClassOf('Writer','Person')).
ontologyAxiom('',subClassOf('RugbyPlayer','Person')).
ontologyAxiom('',equivalentClasses(['#0_144_',intersectionOf(['PopulatedPlace','Place'])])).
ontologyAxiom('',equivalentClasses(['#73_0_',intersectionOf(['Settlement','PopulatedPlace'])])).
ontologyAxiom('',equivalentClasses(['#73_144_',intersectionOf(['Settlement','Place'])])).
ontologyAxiom('',equivalentClasses(['#73_0_144_',intersectionOf(['Settlement','PopulatedPlace','Place'])])).


p(equivalentClasses(['#0_144_',intersectionOf(['PopulatedPlace','Place'])]),0.71).
p(subClassOf('Village','#0_144_'),0.9).
p(equivalentClasses(['#73_0_',intersectionOf(['Settlement','PopulatedPlace'])]),0.7).
p(subClassOf('Village','#73_0_'),0.3).
p(subClassOf('Settlement','#0_144_'),0.81).
p(subClassOf('Village','Settlement'),0.91).
p(subClassOf('Settlement','PopulatedPlace'),0.41).
p(subClassOf('Place','#73_0_'),0.31).
p(subClassOf('Settlement','Place'),0.11).
p(subClassOf('Place','PopulatedPlace'),0.71).
p(equivalentClasses(['#73_0_144_',intersectionOf(['Settlement','PopulatedPlace','Place'])]),0.81).
p(subClassOf('Village','#73_0_144_'),0.21).
p(subClassOf('Village','PopulatedPlace'),0.23).
p(subClassOf('Village','Place'),0.32).
p(subClassOf('Place','Settlement'),0.32).
p(equivalentClasses(['#73_144_',intersectionOf(['Settlement','Place'])]),0.51).
p(subClassOf('Village','#73_144_'),0.67).

