(DEFINE (PROBLEM LOGISTICS1)
   (:DOMAIN LOGISTICS-ADL)
   (:OBJECTS PACKAGE1 PACKAGE2 PACKAGE3 PACKAGE4 PACKAGE5 PACKAGE6
             - OBJ
             PGH-TRUCK BOS-TRUCK LA-TRUCK - TRUCK
             AIRPLANE1 AIRPLANE2 - AIRPLANE
             BOS-PO LA-PO PGH-PO - LOCATION
             BOS-AIRPORT PGH-AIRPORT LA-AIRPORT - AIRPORT
             PGH BOS LA - CITY)
   (:INIT (AT PACKAGE1 PGH-PO)
          (AT PACKAGE2 PGH-PO)
          (AT PACKAGE3 PGH-PO)
          (AT PACKAGE4 PGH-PO)
          (AT PACKAGE5 PGH-PO)
          (AT PACKAGE6 LA-PO)
          (AT AIRPLANE1 PGH-AIRPORT)
          (AT AIRPLANE2 PGH-AIRPORT)
          (AT BOS-TRUCK BOS-PO)
          (AT PGH-TRUCK PGH-PO)
          (AT LA-TRUCK LA-PO)
          (LOC-AT PGH-PO PGH)
          (LOC-AT PGH-AIRPORT PGH)
          (LOC-AT BOS-PO BOS)
          (LOC-AT BOS-AIRPORT BOS)
          (LOC-AT LA-PO LA)
          (LOC-AT LA-AIRPORT LA))
   (:GOAL (AND (AT PACKAGE1 BOS-PO)
               (AT PACKAGE2 LA-PO)
               (AT PACKAGE3 LA-PO)
               (AT PACKAGE4 LA-AIRPORT)
               (AT PACKAGE5 BOS-PO)
               (AT PACKAGE6 PGH-PO))))