(DEFINE (PROBLEM LOG12)
   (:DOMAIN LOGISTICS-STRIPS)
   (:OBJECTS PACKAGE1 PACKAGE2 PACKAGE3 PACKAGE4 PACKAGE5 PACKAGE6
             PACKAGE7 PACKAGE8 PACKAGE9 PLANE1 PLANE2 PLANE3 TRUCK1-1 LOC1-1
             LOC1-2 CITY1 TRUCK2-1 LOC2-1 LOC2-2 CITY2 TRUCK3-1 LOC3-1
             LOC3-2 CITY3 TRUCK4-1 LOC4-1 LOC4-2 CITY4)
   (:INIT (OBJ PACKAGE1)
          (OBJ PACKAGE2)
          (OBJ PACKAGE3)
          (OBJ PACKAGE4)
          (OBJ PACKAGE5)
          (OBJ PACKAGE6)
          (OBJ PACKAGE7)
          (OBJ PACKAGE8)
          (OBJ PACKAGE9)
          (AIRPLANE PLANE1)
          (AIRPLANE PLANE2)
          (AIRPLANE PLANE3)
          (TRUCK TRUCK1-1)
          (LOCATION LOC1-1)
          (LOCATION LOC1-2)
          (CITY CITY1)
          (AIRPORT LOC1-1)
          (TRUCK TRUCK2-1)
          (LOCATION LOC2-1)
          (LOCATION LOC2-2)
          (CITY CITY2)
          (AIRPORT LOC2-1)
          (TRUCK TRUCK3-1)
          (LOCATION LOC3-1)
          (LOCATION LOC3-2)
          (CITY CITY3)
          (AIRPORT LOC3-1)
          (TRUCK TRUCK4-1)
          (LOCATION LOC4-1)
          (LOCATION LOC4-2)
          (CITY CITY4)
          (AIRPORT LOC4-1)
          (IN-CITY LOC1-1 CITY1)
          (IN-CITY LOC1-2 CITY1)
          (IN-CITY LOC2-1 CITY2)
          (IN-CITY LOC2-2 CITY2)
          (IN-CITY LOC3-1 CITY3)
          (IN-CITY LOC3-2 CITY3)
          (IN-CITY LOC4-1 CITY4)
          (IN-CITY LOC4-2 CITY4)
          (AT PLANE1 LOC1-1)
          (AT PLANE2 LOC1-1)
          (AT PLANE3 LOC1-1)
          (AT TRUCK1-1 LOC1-1)
          (AT TRUCK2-1 LOC2-2)
          (AT TRUCK3-1 LOC3-1)
          (AT TRUCK4-1 LOC4-1)
          (AT PACKAGE1 LOC2-1)
          (AT PACKAGE2 LOC4-1)
          (AT PACKAGE3 LOC3-1)
          (AT PACKAGE4 LOC3-1)
          (AT PACKAGE5 LOC2-1)
          (AT PACKAGE6 LOC2-2)
          (AT PACKAGE7 LOC2-2)
          (AT PACKAGE8 LOC2-1)
          (AT PACKAGE9 LOC1-2))
   (:GOAL (AND (AT PACKAGE1 LOC2-1)
               (AT PACKAGE2 LOC1-1)
               (AT PACKAGE3 LOC2-2)
               (AT PACKAGE4 LOC1-2)
               (AT PACKAGE5 LOC1-2)
               (AT PACKAGE6 LOC4-1)
               (AT PACKAGE7 LOC2-1)
               (AT PACKAGE8 LOC3-1)
               (AT PACKAGE9 LOC1-1))))