#============================================================
#		   METAGAME Game-Playing Workbench
#		  Copyright (c) 1992 Barney D. Pell
#============================================================

# make			to build metagame, leaving in this directory
# make install		to build metagame, installing in the bin directory
# make arch		as above, but installs in a specific dir for
#			this architecture.

metagame: 
	(cd play; make metagame)

install:
	(cd play; make install)

arch:
	(cd play; make arch)

