/*

QUERY 1:
instanceOf('WomanUnderLifetimeBRCRisk','Helen',LE).

EXPL:
LE = [(subClassOf('Woman','WomanUnderLifetimeBRCRisk'),'Helen'),(equivalentClasses(['WomanUnderBRCRisk',intersectionOf(['Woman',someValuesFrom(hasRisk,'BRCRisk')])]),'Helen'),(equivalentClasses(['WomanUnderIncreasedBRCRisk',intersectionOf([someValuesFrom(hasRisk,'IncreasedBRCRisk'),'WomanUnderBRCRisk'])]),'Helen'),(equivalentClasses(['WomanUnderModeratelyIncreasedBRCRisk',intersectionOf(['WomanUnderIncreasedBRCRisk',someValuesFrom(hasRisk,'ModeratelyIncreasedBRCRisk')])]),'Helen'),(subClassOf('PostmenopausalWomanTakingEstrogen','WomanUnderModeratelyIncreasedBRCRisk'),'Helen'),(equivalentClasses(['PostmenopausalWomanTakingEstrogen',intersectionOf(['PostmenopausalWoman',someValuesFrom(hasRiskFactor,'Estrogen')])]),'Helen'),(equivalentClasses(['WomanTakingEstrogen',someValuesFrom(hasRiskFactor,'Estrogen')]),'Helen'),classAssertion('WomanTakingEstrogen','Helen'),classAssertion('PostmenopausalWoman','Helen')] ? ;

LE = [(subClassOf('Woman','WomanUnderLifetimeBRCRisk'),'Helen'),(equivalentClasses(['WomanUnderBRCRisk',intersectionOf(['Woman',someValuesFrom(hasRisk,'BRCRisk')])]),'Helen'),(equivalentClasses(['WomanUnderIncreasedBRCRisk',intersectionOf([someValuesFrom(hasRisk,'IncreasedBRCRisk'),'WomanUnderBRCRisk'])]),'Helen'),(subClassOf('WomanUnderModeratelyIncreasedBRCRisk','WomanUnderIncreasedBRCRisk'),'Helen'),(subClassOf('PostmenopausalWomanTakingEstrogen','WomanUnderModeratelyIncreasedBRCRisk'),'Helen'),(equivalentClasses(['PostmenopausalWomanTakingEstrogen',intersectionOf(['PostmenopausalWoman',someValuesFrom(hasRiskFactor,'Estrogen')])]),'Helen'),(equivalentClasses(['WomanTakingEstrogen',someValuesFrom(hasRiskFactor,'Estrogen')]),'Helen'),classAssertion('WomanTakingEstrogen','Helen'),classAssertion('PostmenopausalWoman','Helen')] ? ;

LE = [(subClassOf('Woman','WomanUnderLifetimeBRCRisk'),'Helen'),classAssertion('Woman','Helen')] ? ;

LE = [(subClassOf('Woman','WomanUnderLifetimeBRCRisk'),'Helen'),(subClassOf('WomanTakingEstrogen','Woman'),'Helen'),classAssertion('WomanTakingEstrogen','Helen')] ? ;

LE = [(subClassOf('Woman','WomanUnderLifetimeBRCRisk'),'Helen'),(equivalentClasses(['PostmenopausalWoman',intersectionOf(['Woman',someValuesFrom(hasRiskFactor,'AfterMenopause')])]),'Helen'),classAssertion('PostmenopausalWoman','Helen')] ? ;

LE = [(subClassOf('Woman','WomanUnderLifetimeBRCRisk'),'Helen'),(subClassOf('PostmenopausalWoman','Woman'),'Helen'),classAssertion('PostmenopausalWoman','Helen')] ? ;

LE = [(subClassOf('Woman','WomanUnderLifetimeBRCRisk'),'Helen'),(equivalentClasses(['WomanAged3040',intersectionOf(['Woman',someValuesFrom(hasAge,'Age3040')])]),'Helen'),classAssertion('WomanAged3040','Helen')] ? ;

LE = [(subClassOf('Woman','WomanUnderLifetimeBRCRisk'),'Helen'),(equivalentClasses(['WomanUnderShortTermBRCRisk',intersectionOf(['Woman',someValuesFrom(hasRisk,'ShortTermBRCRisk')])]),'Helen'),(subClassOf('WomanAged3040','WomanUnderShortTermBRCRisk'),'Helen'),classAssertion('WomanAged3040','Helen')] ? ;

LE = [(subClassOf('Woman','WomanUnderLifetimeBRCRisk'),'Helen'),(equivalentClasses(['WomanUnderAbsoluteBRCRisk',intersectionOf(['Woman',someValuesFrom(hasRisk,'AbsoluteBRCRisk')])]),'Helen'),(subClassOf('WomanUnderShortTermBRCRisk','WomanUnderAbsoluteBRCRisk'),'Helen'),(subClassOf('WomanAged3040','WomanUnderShortTermBRCRisk'),'Helen'),classAssertion('WomanAged3040','Helen')] ? ;

LE = [(subClassOf('Woman','WomanUnderLifetimeBRCRisk'),'Helen'),(subClassOf('WomanAged3040','Woman'),'Helen'),classAssertion('WomanAged3040','Helen')] ? ;

=================================

QUERY 2:
instanceOf('WomanUnderModeratelyIncreasedBRCRisk','Helen',LE).

EXPL
LE = [(subClassOf('PostmenopausalWomanTakingEstrogen','WomanUnderModeratelyIncreasedBRCRisk'),'Helen'),(equivalentClasses(['PostmenopausalWomanTakingEstrogen',intersectionOf(['PostmenopausalWoman',someValuesFrom(hasRiskFactor,'Estrogen')])]),'Helen'),(equivalentClasses(['WomanTakingEstrogen',someValuesFrom(hasRiskFactor,'Estrogen')]),'Helen'),classAssertion('WomanTakingEstrogen','Helen'),classAssertion('PostmenopausalWoman','Helen')] 
*/


equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#WomanTakingEstrogen',someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#hasRiskFactor','http://clarkparsia.com/pronto/cancer_ra.owl#Estrogen')]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#WomanTakingProgestin',someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#hasRiskFactor','http://clarkparsia.com/pronto/cancer_ra.owl#Progestin')]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#AbsoluteBRCRisk',intersectionOf(['http://clarkparsia.com/pronto/cancer_ra.owl#BRCRisk',allValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#riskCategory','http://clarkparsia.com/pronto/cancer_ra.owl#AbsoluteRiskCategory')])]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#AfricanAmericanWoman',intersectionOf(['http://clarkparsia.com/pronto/cancer_ra.owl#Woman',someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#hasRace','http://clarkparsia.com/pronto/cancer_ra.owl#AfricanAmerican')])]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#Age50Plus',unionOf(['http://clarkparsia.com/pronto/cancer_ra.owl#Age5060','http://clarkparsia.com/pronto/cancer_ra.owl#Age70Plus','http://clarkparsia.com/pronto/cancer_ra.owl#Age6070'])]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#AshkenaziJewishWoman',intersectionOf([someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#hasRace','http://clarkparsia.com/pronto/cancer_ra.owl#AshkenaziJew'),'http://clarkparsia.com/pronto/cancer_ra.owl#Woman'])]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#BRCRType',intersectionOf(['http://clarkparsia.com/pronto/cancer_ra.owl#RiskType',someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#riskOf','http://clarkparsia.com/pronto/cancer_ra.owl#BreastCancer')])]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#EstrogenProgestin',intersectionOf(['http://clarkparsia.com/pronto/cancer_ra.owl#Estrogen','http://clarkparsia.com/pronto/cancer_ra.owl#Progestin'])]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#EstrogenTestosterone',intersectionOf(['http://clarkparsia.com/pronto/cancer_ra.owl#Testosterone','http://clarkparsia.com/pronto/cancer_ra.owl#Estrogen'])]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#IncreasedBRCRisk',intersectionOf(['http://clarkparsia.com/pronto/cancer_ra.owl#RelativeBRCRisk',allValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#riskCategory','http://clarkparsia.com/pronto/cancer_ra.owl#IncreasedRiskCategory')])]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#ModeratelyIncreasedBRCRisk',intersectionOf([allValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#riskCategory','http://clarkparsia.com/pronto/cancer_ra.owl#ModerateIncrease'),'http://clarkparsia.com/pronto/cancer_ra.owl#IncreasedBRCRisk'])]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#ModeratelyReducedBRCRisk',allValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#riskCategory','http://clarkparsia.com/pronto/cancer_ra.owl#ModerateDecrease')]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#OverweightWoman',intersectionOf(['http://clarkparsia.com/pronto/cancer_ra.owl#Woman',someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#hasRiskFactor','http://clarkparsia.com/pronto/cancer_ra.owl#Overweight')])]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#PersonUnderRisk',intersectionOf(['http://clarkparsia.com/pronto/cancer_ra.owl#Person',someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#hasRisk','http://clarkparsia.com/pronto/cancer_ra.owl#Risk')])]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#PostmenopausalWoman',intersectionOf(['http://clarkparsia.com/pronto/cancer_ra.owl#Woman',someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#hasRiskFactor','http://clarkparsia.com/pronto/cancer_ra.owl#AfterMenopause')])]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#PostmenopausalWomanTakingEstrogen',intersectionOf(['http://clarkparsia.com/pronto/cancer_ra.owl#PostmenopausalWoman',someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#hasRiskFactor','http://clarkparsia.com/pronto/cancer_ra.owl#Estrogen')])]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#PostmenopausalWomanTakingEstrogenAndProgestin',intersectionOf([someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#hasRiskFactor','http://clarkparsia.com/pronto/cancer_ra.owl#Estrogen'),someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#hasRiskFactor','http://clarkparsia.com/pronto/cancer_ra.owl#Progestin')])]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#PostmenopausalWomanTakingEstrogenAndTestosterone',intersectionOf([someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#hasRiskFactor','http://clarkparsia.com/pronto/cancer_ra.owl#Testosterone'),someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#hasRiskFactor','http://clarkparsia.com/pronto/cancer_ra.owl#Estrogen'),'http://clarkparsia.com/pronto/cancer_ra.owl#PostmenopausalWoman'])]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#PostmenopausalWomanTakingProgestin',intersectionOf([someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#hasRiskFactor','http://clarkparsia.com/pronto/cancer_ra.owl#Progestin'),'http://clarkparsia.com/pronto/cancer_ra.owl#PostmenopausalWoman'])]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#PostmenopausalWomanTakingTestosterone',intersectionOf([someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#hasRiskFactor','http://clarkparsia.com/pronto/cancer_ra.owl#Testosterone'),'http://clarkparsia.com/pronto/cancer_ra.owl#PostmenopausalWoman'])]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#PostmenopausalWomanWithHighLevelOfEstrogen',intersectionOf(['http://clarkparsia.com/pronto/cancer_ra.owl#PostmenopausalWoman','http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithHighLevelOfEstrogen'])]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#PremenopausalWoman',intersectionOf([someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#hasRiskFactor','http://clarkparsia.com/pronto/cancer_ra.owl#BeforeMenopause'),'http://clarkparsia.com/pronto/cancer_ra.owl#Woman'])]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#ReducedBRCRisk',intersectionOf(['http://clarkparsia.com/pronto/cancer_ra.owl#RelativeBRCRisk',someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#riskCategory','http://clarkparsia.com/pronto/cancer_ra.owl#ReducedRiskCategory')])]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#RelativeBRCRisk',intersectionOf(['http://clarkparsia.com/pronto/cancer_ra.owl#BRCRisk',allValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#riskCategory','http://clarkparsia.com/pronto/cancer_ra.owl#RelativeRiskCategory')])]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#SeniorWomanWithMotherBRCAffected',intersectionOf([intersectionOf(['http://clarkparsia.com/pronto/cancer_ra.owl#Woman',someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#hasRiskFactor','http://clarkparsia.com/pronto/cancer_ra.owl#MotherAffected')]),someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#hasAge','http://clarkparsia.com/pronto/cancer_ra.owl#Age50Plus')])]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#StronglyIncreasedBRCRisk',intersectionOf(['http://clarkparsia.com/pronto/cancer_ra.owl#IncreasedBRCRisk',allValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#riskCategory','http://clarkparsia.com/pronto/cancer_ra.owl#StrongIncrease')])]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#StronglyReducedBRCRisk',allValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#riskCategory','http://clarkparsia.com/pronto/cancer_ra.owl#StrongDecrease')]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#WeakelyIncreasedBRCRisk',intersectionOf([allValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#riskCategory','http://clarkparsia.com/pronto/cancer_ra.owl#WeakIncrease'),'http://clarkparsia.com/pronto/cancer_ra.owl#IncreasedBRCRisk'])]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#WeakelyReducedBRCRisk',allValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#riskCategory','http://clarkparsia.com/pronto/cancer_ra.owl#WeakDecrease')]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#Woman',intersectionOf(['http://clarkparsia.com/pronto/cancer_ra.owl#Person',someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#hasGender','http://clarkparsia.com/pronto/cancer_ra.owl#Female')])]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#WomanAbusingAlcohol',intersectionOf(['http://clarkparsia.com/pronto/cancer_ra.owl#Woman',someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#hasRiskFactor','http://clarkparsia.com/pronto/cancer_ra.owl#Alcohol')])]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#WomanAged2030',someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#hasAge','http://clarkparsia.com/pronto/cancer_ra.owl#Age2030')]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#WomanAged3040',intersectionOf(['http://clarkparsia.com/pronto/cancer_ra.owl#Woman',someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#hasAge','http://clarkparsia.com/pronto/cancer_ra.owl#Age3040')])]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#WomanAged4050',someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#hasAge','http://clarkparsia.com/pronto/cancer_ra.owl#Age4050')]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#WomanAged5060',intersectionOf([someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#hasAge','http://clarkparsia.com/pronto/cancer_ra.owl#Age5060'),'http://clarkparsia.com/pronto/cancer_ra.owl#Woman'])]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#WomanAged50Plus',intersectionOf(['http://clarkparsia.com/pronto/cancer_ra.owl#Woman',someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#hasAge','http://clarkparsia.com/pronto/cancer_ra.owl#Age50Plus')])]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#WomanAged6070',someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#hasAge','http://clarkparsia.com/pronto/cancer_ra.owl#Age6070')]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#WomanAged70Plus',someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#hasAge','http://clarkparsia.com/pronto/cancer_ra.owl#Age70Plus')]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#WomanAgedUnder20',someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#hasAge','http://clarkparsia.com/pronto/cancer_ra.owl#AgeUnder20')]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#WomanAgedUnder50',intersectionOf(['http://clarkparsia.com/pronto/cancer_ra.owl#Woman',someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#hasAge','http://clarkparsia.com/pronto/cancer_ra.owl#AgeUnder50')])]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#WomanExposedToRadiationDuringYouth',someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#hasRiskFactor','http://clarkparsia.com/pronto/cancer_ra.owl#RadiationExposureDuringYouth')]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#WomanHavingFirstPeriodBefore12',intersectionOf(['http://clarkparsia.com/pronto/cancer_ra.owl#Woman',someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#hasRiskFactor','http://clarkparsia.com/pronto/cancer_ra.owl#FirstPeriodBefore12')])]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#WomanLackingExercise',intersectionOf([someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#hasRiskFactor','http://clarkparsia.com/pronto/cancer_ra.owl#LackOfExercise'),'http://clarkparsia.com/pronto/cancer_ra.owl#Woman'])]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#WomanTakingBirthControlPills',intersectionOf(['http://clarkparsia.com/pronto/cancer_ra.owl#Woman',someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#hasRiskFactor','http://clarkparsia.com/pronto/cancer_ra.owl#BirthControlPills')])]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#WomanTakingPostmenopausalHormones',intersectionOf([someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#hasRiskFactor','http://clarkparsia.com/pronto/cancer_ra.owl#PostmenopausalHormones'),'http://clarkparsia.com/pronto/cancer_ra.owl#Woman'])]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderAbsoluteBRCRisk',intersectionOf(['http://clarkparsia.com/pronto/cancer_ra.owl#Woman',someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#hasRisk','http://clarkparsia.com/pronto/cancer_ra.owl#AbsoluteBRCRisk')])]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderBRCRisk',intersectionOf(['http://clarkparsia.com/pronto/cancer_ra.owl#Woman',someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#hasRisk','http://clarkparsia.com/pronto/cancer_ra.owl#BRCRisk')])]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderIncreasedBRCRisk',intersectionOf([someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#hasRisk','http://clarkparsia.com/pronto/cancer_ra.owl#IncreasedBRCRisk'),'http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderBRCRisk'])]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderLifetimeBRCRisk',intersectionOf(['http://clarkparsia.com/pronto/cancer_ra.owl#Woman',someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#hasRisk','http://clarkparsia.com/pronto/cancer_ra.owl#LifetimeBRCRisk')])]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderModeratelyIncreasedBRCRisk',intersectionOf(['http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderIncreasedBRCRisk',someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#hasRisk','http://clarkparsia.com/pronto/cancer_ra.owl#ModeratelyIncreasedBRCRisk')])]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderModeratelyReducedBRCRisk',someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#hasRisk','http://clarkparsia.com/pronto/cancer_ra.owl#ModeratelyReducedBRCRisk')]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderReducedBRCRisk',intersectionOf(['http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderBRCRisk',someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#hasRisk','http://clarkparsia.com/pronto/cancer_ra.owl#ReducedBRCRisk')])]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderRelativeBRCRisk',intersectionOf([someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#hasRisk','http://clarkparsia.com/pronto/cancer_ra.owl#RelativeBRCRisk'),'http://clarkparsia.com/pronto/cancer_ra.owl#Woman'])]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderShortTermBRCRisk',intersectionOf(['http://clarkparsia.com/pronto/cancer_ra.owl#Woman',someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#hasRisk','http://clarkparsia.com/pronto/cancer_ra.owl#ShortTermBRCRisk')])]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderStronglyIncreasedBRCRisk',intersectionOf([someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#hasRisk','http://clarkparsia.com/pronto/cancer_ra.owl#StronglyIncreasedBRCRisk'),'http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderIncreasedBRCRisk'])]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderStronglyReducedBRCRisk',someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#hasRisk','http://clarkparsia.com/pronto/cancer_ra.owl#StronglyReducedBRCRisk')]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderWeakelyIncreasedBRCRisk',intersectionOf(['http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderIncreasedBRCRisk',someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#hasRisk','http://clarkparsia.com/pronto/cancer_ra.owl#WeakelyIncreasedBRCRisk')])]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderWeakelyReducedBRCRisk',someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#hasRisk','http://clarkparsia.com/pronto/cancer_ra.owl#WeakelyReducedBRCRisk')]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithAtypicalHyperplasia',intersectionOf(['http://clarkparsia.com/pronto/cancer_ra.owl#Woman',someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#hasRiskFactor','http://clarkparsia.com/pronto/cancer_ra.owl#AtypicalHyperplasia')])]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithBRCA1Mutation',intersectionOf(['http://clarkparsia.com/pronto/cancer_ra.owl#Woman',someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#hasRiskFactor','http://clarkparsia.com/pronto/cancer_ra.owl#BRCA1Mutation')])]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithBRCA2Mutation',intersectionOf([someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#hasRiskFactor','http://clarkparsia.com/pronto/cancer_ra.owl#BRCA2Mutation'),'http://clarkparsia.com/pronto/cancer_ra.owl#Woman'])]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithBRCAMutation',intersectionOf([someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#hasRiskFactor','http://clarkparsia.com/pronto/cancer_ra.owl#BRCAMutation'),'http://clarkparsia.com/pronto/cancer_ra.owl#Woman'])]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithCarcinomaInSitu',intersectionOf(['http://clarkparsia.com/pronto/cancer_ra.owl#Woman',someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#hasRiskFactor','http://clarkparsia.com/pronto/cancer_ra.owl#CarcinomaInSitu')])]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithEarlyFirstChild',intersectionOf(['http://clarkparsia.com/pronto/cancer_ra.owl#Woman',someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#hasRiskFactor','http://clarkparsia.com/pronto/cancer_ra.owl#EarlyFirstChild')])]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithEarlyFirstPeriodAndLateMenopause',intersectionOf(['http://clarkparsia.com/pronto/cancer_ra.owl#WomanHavingFirstPeriodBefore12','http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithLateMenopause'])]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithEarlyMenopause',intersectionOf(['http://clarkparsia.com/pronto/cancer_ra.owl#Woman',someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#hasRiskFactor','http://clarkparsia.com/pronto/cancer_ra.owl#EarlyMenopause')])]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithFamilyBRCHistory',intersectionOf(['http://clarkparsia.com/pronto/cancer_ra.owl#Woman',someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#hasRiskFactor','http://clarkparsia.com/pronto/cancer_ra.owl#FamilyCancerHistory')])]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithHighBoneDensity',intersectionOf([someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#hasRiskFactor','http://clarkparsia.com/pronto/cancer_ra.owl#HighBreastDensity'),'http://clarkparsia.com/pronto/cancer_ra.owl#Woman'])]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithHighBreastDensity',intersectionOf([someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#hasRiskFactor','http://clarkparsia.com/pronto/cancer_ra.owl#HighBreastDensity'),'http://clarkparsia.com/pronto/cancer_ra.owl#Woman'])]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithHighLevelOfEstrogen',intersectionOf(['http://clarkparsia.com/pronto/cancer_ra.owl#Woman',someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#hasRiskFactor','http://clarkparsia.com/pronto/cancer_ra.owl#HighLevelOfEstrogen')])]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithImmediateRelativesBRCAffected',intersectionOf(['http://clarkparsia.com/pronto/cancer_ra.owl#Woman',someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#hasRiskFactor','http://clarkparsia.com/pronto/cancer_ra.owl#TwoImmediateRelativesAffected')])]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithLateFirstChild',intersectionOf([someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#hasRiskFactor','http://clarkparsia.com/pronto/cancer_ra.owl#LateFirstChild'),'http://clarkparsia.com/pronto/cancer_ra.owl#Woman'])]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithLateMenopause',intersectionOf([someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#hasRiskFactor','http://clarkparsia.com/pronto/cancer_ra.owl#LateMenopause'),'http://clarkparsia.com/pronto/cancer_ra.owl#Woman'])]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithMotherAffectedAfterAge60',someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#hasRiskFactor','http://clarkparsia.com/pronto/cancer_ra.owl#MotherAffectedAfterAge60')]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithMotherAffectedBeforeAge60',someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#hasRiskFactor','http://clarkparsia.com/pronto/cancer_ra.owl#MotherAffectedBeforeAge60')]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithMotherBRCAffected',intersectionOf(['http://clarkparsia.com/pronto/cancer_ra.owl#Woman',someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#hasRiskFactor','http://clarkparsia.com/pronto/cancer_ra.owl#MotherAffected')])]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithPersonalBRCHistory',intersectionOf([someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#hasRiskFactor','http://clarkparsia.com/pronto/cancer_ra.owl#PersonalBRCHistory'),'http://clarkparsia.com/pronto/cancer_ra.owl#Woman'])]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithRiskFactors',intersectionOf(['http://clarkparsia.com/pronto/cancer_ra.owl#Woman',someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#hasRiskFactor','http://clarkparsia.com/pronto/cancer_ra.owl#RiskFactor')])]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithUsualHyperplasia',intersectionOf(['http://clarkparsia.com/pronto/cancer_ra.owl#Woman',someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#hasRiskFactor','http://clarkparsia.com/pronto/cancer_ra.owl#UsualHyperplasia')])]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithoutBreastfeeding',intersectionOf([someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#hasRiskFactor','http://clarkparsia.com/pronto/cancer_ra.owl#NoBreastfeeding'),'http://clarkparsia.com/pronto/cancer_ra.owl#Woman'])]).
equivalentClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithoutChildren',intersectionOf(['http://clarkparsia.com/pronto/cancer_ra.owl#Woman',someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#hasRiskFactor','http://clarkparsia.com/pronto/cancer_ra.owl#NoChildren'),someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#hasRiskFactor',unionOf(['http://clarkparsia.com/pronto/cancer_ra.owl#Age4050','http://clarkparsia.com/pronto/cancer_ra.owl#Age50Plus','http://clarkparsia.com/pronto/cancer_ra.owl#Age3040']))])]).

disjointClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#AfricanAmerican','http://clarkparsia.com/pronto/cancer_ra.owl#AshkenaziJew']).
disjointClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#Age2030','http://clarkparsia.com/pronto/cancer_ra.owl#Age3040']).
disjointClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#Age2030','http://clarkparsia.com/pronto/cancer_ra.owl#Age4050']).
disjointClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#Age2030','http://clarkparsia.com/pronto/cancer_ra.owl#Age5060']).
disjointClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#Age2030','http://clarkparsia.com/pronto/cancer_ra.owl#Age6070']).
disjointClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#Age2030','http://clarkparsia.com/pronto/cancer_ra.owl#Age70Plus']).
disjointClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#Age2030','http://clarkparsia.com/pronto/cancer_ra.owl#AgeUnder20']).
disjointClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#Age3040','http://clarkparsia.com/pronto/cancer_ra.owl#Age4050']).
disjointClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#Age3040','http://clarkparsia.com/pronto/cancer_ra.owl#Age6070']).
disjointClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#Age3040','http://clarkparsia.com/pronto/cancer_ra.owl#Age70Plus']).
disjointClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#Age3040','http://clarkparsia.com/pronto/cancer_ra.owl#AgeUnder20']).
disjointClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#Age4050','http://clarkparsia.com/pronto/cancer_ra.owl#Age70Plus']).
disjointClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#Age5060','http://clarkparsia.com/pronto/cancer_ra.owl#Age3040']).
disjointClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#Age5060','http://clarkparsia.com/pronto/cancer_ra.owl#Age4050']).
disjointClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#Age5060','http://clarkparsia.com/pronto/cancer_ra.owl#Age6070']).
disjointClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#Age5060','http://clarkparsia.com/pronto/cancer_ra.owl#Age70Plus']).
disjointClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#Age6070','http://clarkparsia.com/pronto/cancer_ra.owl#Age4050']).
disjointClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#Age6070','http://clarkparsia.com/pronto/cancer_ra.owl#Age70Plus']).
disjointClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#AgeUnder20','http://clarkparsia.com/pronto/cancer_ra.owl#Age4050']).
disjointClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#AgeUnder50','http://clarkparsia.com/pronto/cancer_ra.owl#Age50Plus']).
disjointClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#AtypicalHyperplasia','http://clarkparsia.com/pronto/cancer_ra.owl#UsualHyperplasia']).
disjointClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#BeforeMenopause','http://clarkparsia.com/pronto/cancer_ra.owl#AfterMenopause']).
disjointClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#BeforeMenopause','http://clarkparsia.com/pronto/cancer_ra.owl#LateMenopause']).
disjointClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#EarlyFirstChild','http://clarkparsia.com/pronto/cancer_ra.owl#LateFirstChild']).
disjointClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#LateMenopause','http://clarkparsia.com/pronto/cancer_ra.owl#EarlyMenopause']).
disjointClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#ModerateDecrease','http://clarkparsia.com/pronto/cancer_ra.owl#WeakDecrease']).
disjointClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#MotherAffectedBeforeAge60','http://clarkparsia.com/pronto/cancer_ra.owl#MotherAffectedAfterAge60']).
disjointClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#PostmenopausalWoman','http://clarkparsia.com/pronto/cancer_ra.owl#PremenopausalWoman']).
disjointClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#StrongDecrease','http://clarkparsia.com/pronto/cancer_ra.owl#ModerateDecrease']).
disjointClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#StrongDecrease','http://clarkparsia.com/pronto/cancer_ra.owl#WeakDecrease']).
disjointClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#StrongIncrease','http://clarkparsia.com/pronto/cancer_ra.owl#ModerateIncrease']).
disjointClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#StrongIncrease','http://clarkparsia.com/pronto/cancer_ra.owl#WeakIncrease']).
disjointClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#WeakIncrease','http://clarkparsia.com/pronto/cancer_ra.owl#ModerateIncrease']).
disjointClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderModeratelyIncreasedBRCRisk','http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderStronglyIncreasedBRCRisk']).
disjointClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderModeratelyReducedBRCRisk','http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderStronglyReducedBRCRisk']).
disjointClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderModeratelyReducedBRCRisk','http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderWeakelyReducedBRCRisk']).
disjointClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderReducedBRCRisk','http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderIncreasedBRCRisk']).
disjointClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderStronglyReducedBRCRisk','http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderWeakelyReducedBRCRisk']).
disjointClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderWeakelyIncreasedBRCRisk','http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderModeratelyIncreasedBRCRisk']).
disjointClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderWeakelyIncreasedBRCRisk','http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderStronglyIncreasedBRCRisk']).
disjointClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithLateFirstChild','http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithEarlyFirstChild']).
disjointClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithLateFirstChild','http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithoutChildren']).
disjointClasses(['http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithoutChildren','http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithEarlyFirstChild']).
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#WomanTakingEstrogen','http://clarkparsia.com/pronto/cancer_ra.owl#Woman').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#WomanTakingProgestin','http://clarkparsia.com/pronto/cancer_ra.owl#Woman').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#AbsoluteBRCRisk','http://clarkparsia.com/pronto/cancer_ra.owl#BRCRisk').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#AbsoluteRiskCategory','http://clarkparsia.com/pronto/cancer_ra.owl#RiskCategory').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#AfricanAmerican','http://clarkparsia.com/pronto/cancer_ra.owl#Ethnicity').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#AfricanAmericanWoman','http://clarkparsia.com/pronto/cancer_ra.owl#Woman').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#AfterMenopause','http://clarkparsia.com/pronto/cancer_ra.owl#KnownFactor').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#Age','http://clarkparsia.com/pronto/cancer_ra.owl#KnownFactor').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#Age2030','http://clarkparsia.com/pronto/cancer_ra.owl#AgeUnder50').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#Age3040','http://clarkparsia.com/pronto/cancer_ra.owl#AgeUnder50').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#Age4050','http://clarkparsia.com/pronto/cancer_ra.owl#AgeUnder50').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#Age5060','http://clarkparsia.com/pronto/cancer_ra.owl#Age').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#Age50Plus','http://clarkparsia.com/pronto/cancer_ra.owl#Age').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#Age6070','http://clarkparsia.com/pronto/cancer_ra.owl#Age').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#Age70Plus','http://clarkparsia.com/pronto/cancer_ra.owl#Age').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#AgeUnder20','http://clarkparsia.com/pronto/cancer_ra.owl#AgeUnder50').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#AgeUnder50','http://clarkparsia.com/pronto/cancer_ra.owl#Age').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#Alcohol','http://clarkparsia.com/pronto/cancer_ra.owl#KnownFactor').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#AshkenaziJew','http://clarkparsia.com/pronto/cancer_ra.owl#Ethnicity').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#AshkenaziJewishWoman','http://clarkparsia.com/pronto/cancer_ra.owl#Woman').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#AshkenaziJewishWoman','http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithBRCAMutation').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#AtypicalHyperplasia','http://clarkparsia.com/pronto/cancer_ra.owl#BenignBreastDisease').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#BRCA1Mutation','http://clarkparsia.com/pronto/cancer_ra.owl#BRCAMutation').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#BRCA2Mutation','http://clarkparsia.com/pronto/cancer_ra.owl#BRCAMutation').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#BRCAMutation','http://clarkparsia.com/pronto/cancer_ra.owl#InferredFactor').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#BRCRisk',intersectionOf([someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#riskType','http://clarkparsia.com/pronto/cancer_ra.owl#BRCRType'),'http://clarkparsia.com/pronto/cancer_ra.owl#Risk'])).
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#BeforeMenopause','http://clarkparsia.com/pronto/cancer_ra.owl#KnownFactor').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#BenignBreastDisease','http://clarkparsia.com/pronto/cancer_ra.owl#InferredFactor').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#BirthControlPills','http://clarkparsia.com/pronto/cancer_ra.owl#KnownFactor').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#BreastCancer','http://clarkparsia.com/pronto/cancer_ra.owl#Cancer').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#Cancer','http://clarkparsia.com/pronto/cancer_ra.owl#Disease').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#CarcinomaInSitu','http://clarkparsia.com/pronto/cancer_ra.owl#InferredFactor').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#Disease','http://www.w3.org/2002/07/owl#Thing').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#EarlyFirstChild','http://clarkparsia.com/pronto/cancer_ra.owl#KnownFactor').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#EarlyMenopause','http://clarkparsia.com/pronto/cancer_ra.owl#KnownFactor').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#Estrogen','http://clarkparsia.com/pronto/cancer_ra.owl#PostmenopausalHormones').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#EstrogenProgestin','http://clarkparsia.com/pronto/cancer_ra.owl#PostmenopausalHormones').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#EstrogenTestosterone','http://clarkparsia.com/pronto/cancer_ra.owl#PostmenopausalHormones').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#Ethnicity','http://www.w3.org/2002/07/owl#Thing').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#FamilyCancerHistory','http://clarkparsia.com/pronto/cancer_ra.owl#KnownFactor').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#Female','http://clarkparsia.com/pronto/cancer_ra.owl#Gender').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#FirstPeriodBefore12','http://clarkparsia.com/pronto/cancer_ra.owl#KnownFactor').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#Gender','http://www.w3.org/2002/07/owl#Thing').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#HighBoneDensity','http://clarkparsia.com/pronto/cancer_ra.owl#InferredFactor').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#HighBreastDensity','http://clarkparsia.com/pronto/cancer_ra.owl#InferredFactor').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#HighLevelOfEstrogen','http://clarkparsia.com/pronto/cancer_ra.owl#InferredFactor').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#IncreasedBRCRisk','http://clarkparsia.com/pronto/cancer_ra.owl#RelativeBRCRisk').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#IncreasedRiskCategory','http://clarkparsia.com/pronto/cancer_ra.owl#RelativeRiskCategory').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#InferredFactor','http://clarkparsia.com/pronto/cancer_ra.owl#RiskFactor').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#KnownFactor','http://clarkparsia.com/pronto/cancer_ra.owl#RiskFactor').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#LackOfExercise','http://clarkparsia.com/pronto/cancer_ra.owl#KnownFactor').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#LateFirstChild','http://clarkparsia.com/pronto/cancer_ra.owl#KnownFactor').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#LateMenopause','http://clarkparsia.com/pronto/cancer_ra.owl#KnownFactor').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#LifetimeBRCRisk','http://clarkparsia.com/pronto/cancer_ra.owl#AbsoluteBRCRisk').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#Male','http://clarkparsia.com/pronto/cancer_ra.owl#Gender').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#ModerateDecrease','http://clarkparsia.com/pronto/cancer_ra.owl#ReducedRiskCategory').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#ModerateIncrease','http://clarkparsia.com/pronto/cancer_ra.owl#IncreasedRiskCategory').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#ModeratelyIncreasedBRCRisk','http://clarkparsia.com/pronto/cancer_ra.owl#IncreasedBRCRisk').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#ModeratelyReducedBRCRisk','http://clarkparsia.com/pronto/cancer_ra.owl#ReducedBRCRisk').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#MotherAffected','http://clarkparsia.com/pronto/cancer_ra.owl#FamilyCancerHistory').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#MotherAffectedAfterAge60','http://clarkparsia.com/pronto/cancer_ra.owl#MotherAffected').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#MotherAffectedBeforeAge60','http://clarkparsia.com/pronto/cancer_ra.owl#MotherAffected').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#NoBreastfeeding','http://clarkparsia.com/pronto/cancer_ra.owl#KnownFactor').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#NoChildren','http://clarkparsia.com/pronto/cancer_ra.owl#NoBreastfeeding').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#Overweight','http://clarkparsia.com/pronto/cancer_ra.owl#KnownFactor').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#OverweightWoman','http://clarkparsia.com/pronto/cancer_ra.owl#Woman').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#Person','http://www.w3.org/2002/07/owl#Thing').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#Person',someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#hasGender','http://clarkparsia.com/pronto/cancer_ra.owl#Gender')).
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#PersonUnderRisk','http://clarkparsia.com/pronto/cancer_ra.owl#Person').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#PersonalBRCHistory','http://clarkparsia.com/pronto/cancer_ra.owl#KnownFactor').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#PostmenopausalHormones','http://clarkparsia.com/pronto/cancer_ra.owl#KnownFactor').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#PostmenopausalWoman','http://clarkparsia.com/pronto/cancer_ra.owl#Woman').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#PostmenopausalWomanTakingEstrogenAndProgestin','http://clarkparsia.com/pronto/cancer_ra.owl#PostmenopausalWoman').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#PostmenopausalWomanTakingEstrogenAndTestosterone','http://clarkparsia.com/pronto/cancer_ra.owl#PostmenopausalWoman').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#PostmenopausalWomanWithHighLevelOfEstrogen','http://clarkparsia.com/pronto/cancer_ra.owl#Woman').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#PremenopausalWoman','http://clarkparsia.com/pronto/cancer_ra.owl#Woman').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#Progestin','http://clarkparsia.com/pronto/cancer_ra.owl#PostmenopausalHormones').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#RadiationExposureDuringYouth','http://clarkparsia.com/pronto/cancer_ra.owl#KnownFactor').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#ReducedBRCRisk','http://clarkparsia.com/pronto/cancer_ra.owl#RelativeBRCRisk').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#ReducedRiskCategory','http://clarkparsia.com/pronto/cancer_ra.owl#RelativeRiskCategory').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#RelativeBRCRisk','http://clarkparsia.com/pronto/cancer_ra.owl#BRCRisk').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#RelativeRiskCategory','http://clarkparsia.com/pronto/cancer_ra.owl#RiskCategory').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#Risk','http://www.w3.org/2002/07/owl#Thing').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#RiskCategory','http://www.w3.org/2002/07/owl#Thing').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#RiskFactor','http://www.w3.org/2002/07/owl#Thing').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#RiskFactor',allValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#relatedToDisease','http://clarkparsia.com/pronto/cancer_ra.owl#Disease')).
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#RiskType',intersectionOf(['http://www.w3.org/2002/07/owl#Thing',someValuesFrom('http://clarkparsia.com/pronto/cancer_ra.owl#riskOf','http://clarkparsia.com/pronto/cancer_ra.owl#Disease')])).
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#SeniorWomanWithMotherBRCAffected','http://clarkparsia.com/pronto/cancer_ra.owl#Woman').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#ShortTermBRCRisk','http://clarkparsia.com/pronto/cancer_ra.owl#AbsoluteBRCRisk').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#StrongDecrease','http://clarkparsia.com/pronto/cancer_ra.owl#ReducedRiskCategory').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#StrongIncrease','http://clarkparsia.com/pronto/cancer_ra.owl#IncreasedRiskCategory').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#StronglyIncreasedBRCRisk','http://clarkparsia.com/pronto/cancer_ra.owl#IncreasedBRCRisk').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#StronglyReducedBRCRisk','http://clarkparsia.com/pronto/cancer_ra.owl#ReducedBRCRisk').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#Testosterone','http://clarkparsia.com/pronto/cancer_ra.owl#PostmenopausalHormones').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#TwoImmediateRelativesAffected','http://clarkparsia.com/pronto/cancer_ra.owl#FamilyCancerHistory').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#UsualHyperplasia','http://clarkparsia.com/pronto/cancer_ra.owl#BenignBreastDisease').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#WeakDecrease','http://clarkparsia.com/pronto/cancer_ra.owl#ReducedRiskCategory').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#WeakIncrease','http://clarkparsia.com/pronto/cancer_ra.owl#IncreasedRiskCategory').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#WeakelyIncreasedBRCRisk','http://clarkparsia.com/pronto/cancer_ra.owl#IncreasedBRCRisk').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#WeakelyReducedBRCRisk','http://clarkparsia.com/pronto/cancer_ra.owl#ReducedBRCRisk').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#Woman','http://www.w3.org/2002/07/owl#Thing').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#Woman','http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderLifetimeBRCRisk').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#WomanAbusingAlcohol','http://clarkparsia.com/pronto/cancer_ra.owl#Woman').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#WomanAged2030','http://clarkparsia.com/pronto/cancer_ra.owl#Woman').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#WomanAged3040','http://clarkparsia.com/pronto/cancer_ra.owl#Woman').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#WomanAged4050','http://clarkparsia.com/pronto/cancer_ra.owl#Woman').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#WomanAged5060','http://clarkparsia.com/pronto/cancer_ra.owl#Woman').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#WomanAged6070','http://clarkparsia.com/pronto/cancer_ra.owl#Woman').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#WomanAged70Plus','http://clarkparsia.com/pronto/cancer_ra.owl#Woman').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#WomanAgedUnder20','http://clarkparsia.com/pronto/cancer_ra.owl#Woman').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#WomanAgedUnder50','http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithRiskFactors').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#WomanExposedToRadiationDuringYouth','http://clarkparsia.com/pronto/cancer_ra.owl#Woman').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#WomanHavingFirstPeriodBefore12','http://clarkparsia.com/pronto/cancer_ra.owl#Woman').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#WomanLackingExercise','http://clarkparsia.com/pronto/cancer_ra.owl#Woman').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#WomanTakingBirthControlPills','http://clarkparsia.com/pronto/cancer_ra.owl#Woman').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#WomanTakingPostmenopausalHormones','http://clarkparsia.com/pronto/cancer_ra.owl#Woman').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderLifetimeBRCRisk','http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderAbsoluteBRCRisk').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderModeratelyIncreasedBRCRisk','http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderIncreasedBRCRisk').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderModeratelyReducedBRCRisk','http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderReducedBRCRisk').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderRelativeBRCRisk','http://clarkparsia.com/pronto/cancer_ra.owl#Woman').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderShortTermBRCRisk','http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderAbsoluteBRCRisk').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderStronglyIncreasedBRCRisk','http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderIncreasedBRCRisk').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderStronglyReducedBRCRisk','http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderReducedBRCRisk').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderWeakelyIncreasedBRCRisk','http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderIncreasedBRCRisk').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderWeakelyReducedBRCRisk','http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderReducedBRCRisk').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithAtypicalHyperplasia','http://clarkparsia.com/pronto/cancer_ra.owl#Woman').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithBRCA1Mutation','http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderLifetimeBRCRisk').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithBRCAMutation','http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithRiskFactors').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithBRCAMutation','http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderLifetimeBRCRisk').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithBRCAMutation','http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderLifetimeBRCRisk').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithCarcinomaInSitu','http://clarkparsia.com/pronto/cancer_ra.owl#Woman').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithEarlyFirstChild','http://clarkparsia.com/pronto/cancer_ra.owl#Woman').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithEarlyFirstPeriodAndLateMenopause','http://clarkparsia.com/pronto/cancer_ra.owl#Woman').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithEarlyMenopause','http://clarkparsia.com/pronto/cancer_ra.owl#PostmenopausalWoman').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithEarlyMenopause','http://clarkparsia.com/pronto/cancer_ra.owl#Woman').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithFamilyBRCHistory','http://clarkparsia.com/pronto/cancer_ra.owl#Woman').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithHighBoneDensity','http://clarkparsia.com/pronto/cancer_ra.owl#Woman').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithHighBreastDensity','http://clarkparsia.com/pronto/cancer_ra.owl#Woman').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithHighLevelOfEstrogen','http://clarkparsia.com/pronto/cancer_ra.owl#Woman').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithImmediateRelativesBRCAffected','http://clarkparsia.com/pronto/cancer_ra.owl#Woman').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithLateFirstChild','http://clarkparsia.com/pronto/cancer_ra.owl#Woman').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithLateMenopause','http://clarkparsia.com/pronto/cancer_ra.owl#PostmenopausalWoman').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithLateMenopause','http://clarkparsia.com/pronto/cancer_ra.owl#Woman').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithMotherAffectedAfterAge60','http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithMotherBRCAffected').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithMotherAffectedBeforeAge60','http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithMotherBRCAffected').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithMotherBRCAffected','http://clarkparsia.com/pronto/cancer_ra.owl#Woman').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithRiskFactors','http://clarkparsia.com/pronto/cancer_ra.owl#Woman').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithUsualHyperplasia','http://clarkparsia.com/pronto/cancer_ra.owl#Woman').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithoutBreastfeeding','http://clarkparsia.com/pronto/cancer_ra.owl#Woman').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithoutChildren','http://clarkparsia.com/pronto/cancer_ra.owl#Woman').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#WomanAgedUnder20','http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderShortTermBRCRisk').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#WomanAged3040','http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderShortTermBRCRisk').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#WomanAged6070','http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderShortTermBRCRisk').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithMotherAffectedBeforeAge60','http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderModeratelyIncreasedBRCRisk').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithLateMenopause','http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderModeratelyIncreasedBRCRisk').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#PostmenopausalWomanTakingEstrogen','http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderModeratelyIncreasedBRCRisk').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#PostmenopausalWomanTakingProgestin','http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderModeratelyIncreasedBRCRisk').
subClassOf('http://clarkparsia.com/pronto/cancer_ra.owl#WomanHavingFirstPeriodBefore12','http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithHighLevelOfEstrogen').
/*
subPropertyOf('http://clarkparsia.com/pronto/cancer_ra.owl#hasAge','http://clarkparsia.com/pronto/cancer_ra.owl#hasRiskFactor').
subPropertyOf('http://clarkparsia.com/pronto/cancer_ra.owl#willDevelopInLongTerm','http://clarkparsia.com/pronto/cancer_ra.owl#willDevelop').
subPropertyOf('http://clarkparsia.com/pronto/cancer_ra.owl#willDevelopInShortTerm','http://clarkparsia.com/pronto/cancer_ra.owl#willDevelop').
*/
/*
functionalProperty('http://clarkparsia.com/pronto/cancer_ra.owl#hasAge').
functionalProperty('http://clarkparsia.com/pronto/cancer_ra.owl#hasGender').
functionalProperty('http://clarkparsia.com/pronto/cancer_ra.owl#riskCategory').
functionalProperty('http://clarkparsia.com/pronto/cancer_ra.owl#riskOf').
functionalProperty('http://clarkparsia.com/pronto/cancer_ra.owl#riskType').
functionalProperty('http://clarkparsia.com/pronto/cancer_ra.owl#increaseFactor').
*/
propertyDomain('http://clarkparsia.com/pronto/cancer_ra.owl#hasAge','http://clarkparsia.com/pronto/cancer_ra.owl#Person').
propertyDomain('http://clarkparsia.com/pronto/cancer_ra.owl#hasGender','http://clarkparsia.com/pronto/cancer_ra.owl#Person').
propertyDomain('http://clarkparsia.com/pronto/cancer_ra.owl#hasRace','http://clarkparsia.com/pronto/cancer_ra.owl#Person').
propertyDomain('http://clarkparsia.com/pronto/cancer_ra.owl#hasRisk','http://clarkparsia.com/pronto/cancer_ra.owl#Person').
propertyDomain('http://clarkparsia.com/pronto/cancer_ra.owl#hasRiskFactor','http://clarkparsia.com/pronto/cancer_ra.owl#Person').
propertyDomain('http://clarkparsia.com/pronto/cancer_ra.owl#relatedToDisease','http://clarkparsia.com/pronto/cancer_ra.owl#RiskFactor').
propertyDomain('http://clarkparsia.com/pronto/cancer_ra.owl#riskCategory','http://clarkparsia.com/pronto/cancer_ra.owl#Risk').
propertyDomain('http://clarkparsia.com/pronto/cancer_ra.owl#riskOf','http://clarkparsia.com/pronto/cancer_ra.owl#RiskType').
propertyDomain('http://clarkparsia.com/pronto/cancer_ra.owl#riskType','http://clarkparsia.com/pronto/cancer_ra.owl#Risk').
propertyDomain('http://clarkparsia.com/pronto/cancer_ra.owl#willDevelop','http://clarkparsia.com/pronto/cancer_ra.owl#Person').
propertyDomain('http://clarkparsia.com/pronto/cancer_ra.owl#willDevelopInLongTerm','http://clarkparsia.com/pronto/cancer_ra.owl#Person').
propertyDomain('http://clarkparsia.com/pronto/cancer_ra.owl#willDevelopInShortTerm','http://clarkparsia.com/pronto/cancer_ra.owl#Person').
propertyDomain('http://clarkparsia.com/pronto/cancer_ra.owl#increaseFactor','http://clarkparsia.com/pronto/cancer_ra.owl#RelativeRiskCategory').
propertyRange('http://clarkparsia.com/pronto/cancer_ra.owl#hasAge','http://clarkparsia.com/pronto/cancer_ra.owl#Age').
propertyRange('http://clarkparsia.com/pronto/cancer_ra.owl#hasGender','http://clarkparsia.com/pronto/cancer_ra.owl#Gender').
propertyRange('http://clarkparsia.com/pronto/cancer_ra.owl#hasRace','http://clarkparsia.com/pronto/cancer_ra.owl#Ethnicity').
propertyRange('http://clarkparsia.com/pronto/cancer_ra.owl#hasRisk','http://clarkparsia.com/pronto/cancer_ra.owl#Risk').
propertyRange('http://clarkparsia.com/pronto/cancer_ra.owl#hasRiskFactor','http://clarkparsia.com/pronto/cancer_ra.owl#RiskFactor').
propertyRange('http://clarkparsia.com/pronto/cancer_ra.owl#relatedToDisease','http://clarkparsia.com/pronto/cancer_ra.owl#Disease').
propertyRange('http://clarkparsia.com/pronto/cancer_ra.owl#riskCategory','http://clarkparsia.com/pronto/cancer_ra.owl#RiskCategory').
propertyRange('http://clarkparsia.com/pronto/cancer_ra.owl#riskOf','http://clarkparsia.com/pronto/cancer_ra.owl#Disease').
propertyRange('http://clarkparsia.com/pronto/cancer_ra.owl#riskType','http://clarkparsia.com/pronto/cancer_ra.owl#RiskType').
propertyRange('http://clarkparsia.com/pronto/cancer_ra.owl#willDevelop','http://clarkparsia.com/pronto/cancer_ra.owl#Disease').
propertyRange('http://clarkparsia.com/pronto/cancer_ra.owl#willDevelopInLongTerm','http://clarkparsia.com/pronto/cancer_ra.owl#Disease').
propertyRange('http://clarkparsia.com/pronto/cancer_ra.owl#willDevelopInShortTerm','http://clarkparsia.com/pronto/cancer_ra.owl#Disease').
propertyRange('http://clarkparsia.com/pronto/cancer_ra.owl#increaseFactor','http://www.w3.org/2001/XMLSchema#decimal').
classAssertion('http://clarkparsia.com/pronto/cancer_ra.owl#Woman','http://clarkparsia.com/pronto/cancer_ra.owl#Helen').
classAssertion('http://clarkparsia.com/pronto/cancer_ra.owl#WomanTakingEstrogen','http://clarkparsia.com/pronto/cancer_ra.owl#Helen').
classAssertion('http://clarkparsia.com/pronto/cancer_ra.owl#PostmenopausalWoman','http://clarkparsia.com/pronto/cancer_ra.owl#Helen').
classAssertion('http://clarkparsia.com/pronto/cancer_ra.owl#WomanAged3040','http://clarkparsia.com/pronto/cancer_ra.owl#Helen').
/*
objectProperty('http://clarkparsia.com/pronto/cancer_ra.owl#hasAge').
objectProperty('http://clarkparsia.com/pronto/cancer_ra.owl#hasGender').
objectProperty('http://clarkparsia.com/pronto/cancer_ra.owl#hasRace').
objectProperty('http://clarkparsia.com/pronto/cancer_ra.owl#hasRisk').
objectProperty('http://clarkparsia.com/pronto/cancer_ra.owl#hasRiskFactor').
objectProperty('http://clarkparsia.com/pronto/cancer_ra.owl#relatedToDisease').
objectProperty('http://clarkparsia.com/pronto/cancer_ra.owl#riskCategory').
objectProperty('http://clarkparsia.com/pronto/cancer_ra.owl#riskOf').
objectProperty('http://clarkparsia.com/pronto/cancer_ra.owl#riskType').
objectProperty('http://clarkparsia.com/pronto/cancer_ra.owl#willDevelop').
objectProperty('http://clarkparsia.com/pronto/cancer_ra.owl#willDevelopInLongTerm').
objectProperty('http://clarkparsia.com/pronto/cancer_ra.owl#willDevelopInShortTerm').
dataProperty('http://clarkparsia.com/pronto/cancer_ra.owl#increaseFactor').
dataProperty('http://www.w3.org/2006/12/owl11#maxExclusive').
dataProperty('http://www.w3.org/2006/12/owl11#minExclusive').
annotationProperty('http://www.w3.org/2000/01/rdf-schema#label').
annotationProperty('http://www.w3.org/2000/01/rdf-schema#comment').
annotationProperty('https://sites.google.com/a/unife.it/ml/bundle#probability').
class('http://clarkparsia.com/pronto/cancer_ra.owl#WomanTakingEstrogen').
class('http://clarkparsia.com/pronto/cancer_ra.owl#WomanTakingProgestin').
class('http://clarkparsia.com/pronto/cancer_ra.owl#AbsoluteBRCRisk').
class('http://clarkparsia.com/pronto/cancer_ra.owl#AbsoluteRiskCategory').
class('http://clarkparsia.com/pronto/cancer_ra.owl#AfricanAmerican').
class('http://clarkparsia.com/pronto/cancer_ra.owl#AfricanAmericanWoman').
class('http://clarkparsia.com/pronto/cancer_ra.owl#AfterMenopause').
class('http://clarkparsia.com/pronto/cancer_ra.owl#Age').
class('http://clarkparsia.com/pronto/cancer_ra.owl#Age2030').
class('http://clarkparsia.com/pronto/cancer_ra.owl#Age3040').
class('http://clarkparsia.com/pronto/cancer_ra.owl#Age4050').
class('http://clarkparsia.com/pronto/cancer_ra.owl#Age5060').
class('http://clarkparsia.com/pronto/cancer_ra.owl#Age50Plus').
class('http://clarkparsia.com/pronto/cancer_ra.owl#Age6070').
class('http://clarkparsia.com/pronto/cancer_ra.owl#Age70Plus').
class('http://clarkparsia.com/pronto/cancer_ra.owl#AgeUnder20').
class('http://clarkparsia.com/pronto/cancer_ra.owl#AgeUnder50').
class('http://clarkparsia.com/pronto/cancer_ra.owl#Alcohol').
class('http://clarkparsia.com/pronto/cancer_ra.owl#AshkenaziJew').
class('http://clarkparsia.com/pronto/cancer_ra.owl#AshkenaziJewishWoman').
class('http://clarkparsia.com/pronto/cancer_ra.owl#AtypicalHyperplasia').
class('http://clarkparsia.com/pronto/cancer_ra.owl#BRCA1Mutation').
class('http://clarkparsia.com/pronto/cancer_ra.owl#BRCA2Mutation').
class('http://clarkparsia.com/pronto/cancer_ra.owl#BRCAMutation').
class('http://clarkparsia.com/pronto/cancer_ra.owl#BRCRType').
class('http://clarkparsia.com/pronto/cancer_ra.owl#BRCRisk').
class('http://clarkparsia.com/pronto/cancer_ra.owl#BeforeMenopause').
class('http://clarkparsia.com/pronto/cancer_ra.owl#BenignBreastDisease').
class('http://clarkparsia.com/pronto/cancer_ra.owl#BirthControlPills').
class('http://clarkparsia.com/pronto/cancer_ra.owl#BreastCancer').
class('http://clarkparsia.com/pronto/cancer_ra.owl#Cancer').
class('http://clarkparsia.com/pronto/cancer_ra.owl#CarcinomaInSitu').
class('http://clarkparsia.com/pronto/cancer_ra.owl#Disease').
class('http://clarkparsia.com/pronto/cancer_ra.owl#EarlyFirstChild').
class('http://clarkparsia.com/pronto/cancer_ra.owl#EarlyMenopause').
class('http://clarkparsia.com/pronto/cancer_ra.owl#Estrogen').
class('http://clarkparsia.com/pronto/cancer_ra.owl#EstrogenProgestin').
class('http://clarkparsia.com/pronto/cancer_ra.owl#EstrogenTestosterone').
class('http://clarkparsia.com/pronto/cancer_ra.owl#Ethnicity').
class('http://clarkparsia.com/pronto/cancer_ra.owl#FamilyCancerHistory').
class('http://clarkparsia.com/pronto/cancer_ra.owl#Female').
class('http://clarkparsia.com/pronto/cancer_ra.owl#FirstPeriodBefore12').
class('http://clarkparsia.com/pronto/cancer_ra.owl#Gender').
class('http://clarkparsia.com/pronto/cancer_ra.owl#HighBoneDensity').
class('http://clarkparsia.com/pronto/cancer_ra.owl#HighBreastDensity').
class('http://clarkparsia.com/pronto/cancer_ra.owl#HighLevelOfEstrogen').
class('http://clarkparsia.com/pronto/cancer_ra.owl#IncreasedBRCRisk').
class('http://clarkparsia.com/pronto/cancer_ra.owl#IncreasedRiskCategory').
class('http://clarkparsia.com/pronto/cancer_ra.owl#InferredFactor').
class('http://clarkparsia.com/pronto/cancer_ra.owl#KnownFactor').
class('http://clarkparsia.com/pronto/cancer_ra.owl#LackOfExercise').
class('http://clarkparsia.com/pronto/cancer_ra.owl#LateFirstChild').
class('http://clarkparsia.com/pronto/cancer_ra.owl#LateMenopause').
class('http://clarkparsia.com/pronto/cancer_ra.owl#LifetimeBRCRisk').
class('http://clarkparsia.com/pronto/cancer_ra.owl#Male').
class('http://clarkparsia.com/pronto/cancer_ra.owl#ModerateDecrease').
class('http://clarkparsia.com/pronto/cancer_ra.owl#ModerateIncrease').
class('http://clarkparsia.com/pronto/cancer_ra.owl#ModeratelyIncreasedBRCRisk').
class('http://clarkparsia.com/pronto/cancer_ra.owl#ModeratelyReducedBRCRisk').
class('http://clarkparsia.com/pronto/cancer_ra.owl#MotherAffected').
class('http://clarkparsia.com/pronto/cancer_ra.owl#MotherAffectedAfterAge60').
class('http://clarkparsia.com/pronto/cancer_ra.owl#MotherAffectedBeforeAge60').
class('http://clarkparsia.com/pronto/cancer_ra.owl#NoBreastfeeding').
class('http://clarkparsia.com/pronto/cancer_ra.owl#NoChildren').
class('http://clarkparsia.com/pronto/cancer_ra.owl#Overweight').
class('http://clarkparsia.com/pronto/cancer_ra.owl#OverweightWoman').
class('http://clarkparsia.com/pronto/cancer_ra.owl#Person').
class('http://clarkparsia.com/pronto/cancer_ra.owl#PersonUnderRisk').
class('http://clarkparsia.com/pronto/cancer_ra.owl#PersonalBRCHistory').
class('http://clarkparsia.com/pronto/cancer_ra.owl#PostmenopausalHormones').
class('http://clarkparsia.com/pronto/cancer_ra.owl#PostmenopausalWoman').
class('http://clarkparsia.com/pronto/cancer_ra.owl#PostmenopausalWomanTakingEstrogen').
class('http://clarkparsia.com/pronto/cancer_ra.owl#PostmenopausalWomanTakingEstrogenAndProgestin').
class('http://clarkparsia.com/pronto/cancer_ra.owl#PostmenopausalWomanTakingEstrogenAndTestosterone').
class('http://clarkparsia.com/pronto/cancer_ra.owl#PostmenopausalWomanTakingProgestin').
class('http://clarkparsia.com/pronto/cancer_ra.owl#PostmenopausalWomanTakingTestosterone').
class('http://clarkparsia.com/pronto/cancer_ra.owl#PostmenopausalWomanWithHighLevelOfEstrogen').
class('http://clarkparsia.com/pronto/cancer_ra.owl#PremenopausalWoman').
class('http://clarkparsia.com/pronto/cancer_ra.owl#Progestin').
class('http://clarkparsia.com/pronto/cancer_ra.owl#RadiationExposureDuringYouth').
class('http://clarkparsia.com/pronto/cancer_ra.owl#ReducedBRCRisk').
class('http://clarkparsia.com/pronto/cancer_ra.owl#ReducedRiskCategory').
class('http://clarkparsia.com/pronto/cancer_ra.owl#RelativeBRCRisk').
class('http://clarkparsia.com/pronto/cancer_ra.owl#RelativeRiskCategory').
class('http://clarkparsia.com/pronto/cancer_ra.owl#Risk').
class('http://clarkparsia.com/pronto/cancer_ra.owl#RiskCategory').
class('http://clarkparsia.com/pronto/cancer_ra.owl#RiskFactor').
class('http://clarkparsia.com/pronto/cancer_ra.owl#RiskType').
class('http://clarkparsia.com/pronto/cancer_ra.owl#SeniorWomanWithMotherBRCAffected').
class('http://clarkparsia.com/pronto/cancer_ra.owl#ShortTermBRCRisk').
class('http://clarkparsia.com/pronto/cancer_ra.owl#StrongDecrease').
class('http://clarkparsia.com/pronto/cancer_ra.owl#StrongIncrease').
class('http://clarkparsia.com/pronto/cancer_ra.owl#StronglyIncreasedBRCRisk').
class('http://clarkparsia.com/pronto/cancer_ra.owl#StronglyReducedBRCRisk').
class('http://clarkparsia.com/pronto/cancer_ra.owl#Testosterone').
class('http://clarkparsia.com/pronto/cancer_ra.owl#TwoImmediateRelativesAffected').
class('http://clarkparsia.com/pronto/cancer_ra.owl#UsualHyperplasia').
class('http://clarkparsia.com/pronto/cancer_ra.owl#WeakDecrease').
class('http://clarkparsia.com/pronto/cancer_ra.owl#WeakIncrease').
class('http://clarkparsia.com/pronto/cancer_ra.owl#WeakelyIncreasedBRCRisk').
class('http://clarkparsia.com/pronto/cancer_ra.owl#WeakelyReducedBRCRisk').
class('http://clarkparsia.com/pronto/cancer_ra.owl#Woman').
class('http://clarkparsia.com/pronto/cancer_ra.owl#WomanAbusingAlcohol').
class('http://clarkparsia.com/pronto/cancer_ra.owl#WomanAged2030').
class('http://clarkparsia.com/pronto/cancer_ra.owl#WomanAged3040').
class('http://clarkparsia.com/pronto/cancer_ra.owl#WomanAged4050').
class('http://clarkparsia.com/pronto/cancer_ra.owl#WomanAged5060').
class('http://clarkparsia.com/pronto/cancer_ra.owl#WomanAged50Plus').
class('http://clarkparsia.com/pronto/cancer_ra.owl#WomanAged6070').
class('http://clarkparsia.com/pronto/cancer_ra.owl#WomanAged70Plus').
class('http://clarkparsia.com/pronto/cancer_ra.owl#WomanAgedUnder20').
class('http://clarkparsia.com/pronto/cancer_ra.owl#WomanAgedUnder50').
class('http://clarkparsia.com/pronto/cancer_ra.owl#WomanExposedToRadiationDuringYouth').
class('http://clarkparsia.com/pronto/cancer_ra.owl#WomanHavingFirstPeriodBefore12').
class('http://clarkparsia.com/pronto/cancer_ra.owl#WomanLackingExercise').
class('http://clarkparsia.com/pronto/cancer_ra.owl#WomanTakingBirthControlPills').
class('http://clarkparsia.com/pronto/cancer_ra.owl#WomanTakingPostmenopausalHormones').
class('http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderAbsoluteBRCRisk').
class('http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderBRCRisk').
class('http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderIncreasedBRCRisk').
class('http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderLifetimeBRCRisk').
class('http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderModeratelyIncreasedBRCRisk').
class('http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderModeratelyReducedBRCRisk').
class('http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderReducedBRCRisk').
class('http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderRelativeBRCRisk').
class('http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderShortTermBRCRisk').
class('http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderStronglyIncreasedBRCRisk').
class('http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderStronglyReducedBRCRisk').
class('http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderWeakelyIncreasedBRCRisk').
class('http://clarkparsia.com/pronto/cancer_ra.owl#WomanUnderWeakelyReducedBRCRisk').
class('http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithAtypicalHyperplasia').
class('http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithBRCA1Mutation').
class('http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithBRCA2Mutation').
class('http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithBRCAMutation').
class('http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithCarcinomaInSitu').
class('http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithEarlyFirstChild').
class('http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithEarlyFirstPeriodAndLateMenopause').
class('http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithEarlyMenopause').
class('http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithFamilyBRCHistory').
class('http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithHighBoneDensity').
class('http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithHighBreastDensity').
class('http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithHighLevelOfEstrogen').
class('http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithImmediateRelativesBRCAffected').
class('http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithLateFirstChild').
class('http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithLateMenopause').
class('http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithMotherAffectedAfterAge60').
class('http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithMotherAffectedBeforeAge60').
class('http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithMotherBRCAffected').
class('http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithPersonalBRCHistory').
class('http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithRiskFactors').
class('http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithUsualHyperplasia').
class('http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithoutBreastfeeding').
class('http://clarkparsia.com/pronto/cancer_ra.owl#WomanWithoutChildren').
class('http://www.w3.org/2002/07/owl#Thing').
*/
