/*

QUERY 1:
sub_class('http://dbpedia.org/ontology/Village','http://dbpedia.org/ontology/PopulatedPlace',LE).

EXPL:
LE = [(equivalentClasses(['http://dbpedia.org/ontology/#0_144_',intersectionOf(['http://dbpedia.org/ontology/PopulatedPlace','http://dbpedia.org/ontology/Place'])]),1),(subClassOf('http://dbpedia.org/ontology/Village','http://dbpedia.org/ontology/#0_144_'),1)] ? ;

LE = [(equivalentClasses(['http://dbpedia.org/ontology/#73_0_',intersectionOf(['http://dbpedia.org/ontology/Settlement','http://dbpedia.org/ontology/PopulatedPlace'])]),1),(subClassOf('http://dbpedia.org/ontology/Village','http://dbpedia.org/ontology/#73_0_'),1)] ? ;

LE = [(equivalentClasses(['http://dbpedia.org/ontology/#0_144_',intersectionOf(['http://dbpedia.org/ontology/PopulatedPlace','http://dbpedia.org/ontology/Place'])]),1),(subClassOf('http://dbpedia.org/ontology/Settlement','http://dbpedia.org/ontology/#0_144_'),1),(subClassOf('http://dbpedia.org/ontology/Village','http://dbpedia.org/ontology/Settlement'),1)] ? ;

LE = [(subClassOf('http://dbpedia.org/ontology/Settlement','http://dbpedia.org/ontology/PopulatedPlace'),1),(subClassOf('http://dbpedia.org/ontology/Village','http://dbpedia.org/ontology/Settlement'),1)] ? ;

LE = [(equivalentClasses(['http://dbpedia.org/ontology/#73_0_',intersectionOf(['http://dbpedia.org/ontology/Settlement','http://dbpedia.org/ontology/PopulatedPlace'])]),1),(subClassOf('http://dbpedia.org/ontology/Place','http://dbpedia.org/ontology/#73_0_'),1),(subClassOf('http://dbpedia.org/ontology/Settlement','http://dbpedia.org/ontology/Place'),1),(subClassOf('http://dbpedia.org/ontology/Village','http://dbpedia.org/ontology/Settlement'),1)] ? ;

LE = [(subClassOf('http://dbpedia.org/ontology/Place','http://dbpedia.org/ontology/PopulatedPlace'),1),(subClassOf('http://dbpedia.org/ontology/Settlement','http://dbpedia.org/ontology/Place'),1),(subClassOf('http://dbpedia.org/ontology/Village','http://dbpedia.org/ontology/Settlement'),1)] ? ;

LE = [(equivalentClasses(['http://dbpedia.org/ontology/#73_0_144_',intersectionOf(['http://dbpedia.org/ontology/Settlement','http://dbpedia.org/ontology/PopulatedPlace','http://dbpedia.org/ontology/Place'])]),1),(subClassOf('http://dbpedia.org/ontology/Village','http://dbpedia.org/ontology/#73_0_144_'),1)] ? ;

LE = [(subClassOf('http://dbpedia.org/ontology/Village','http://dbpedia.org/ontology/PopulatedPlace'),1)] ? ;

LE = [(equivalentClasses(['http://dbpedia.org/ontology/#73_0_',intersectionOf(['http://dbpedia.org/ontology/Settlement','http://dbpedia.org/ontology/PopulatedPlace'])]),1),(subClassOf('http://dbpedia.org/ontology/Place','http://dbpedia.org/ontology/#73_0_'),1),(subClassOf('http://dbpedia.org/ontology/Village','http://dbpedia.org/ontology/Place'),1)] ? ;

LE = [(equivalentClasses(['http://dbpedia.org/ontology/#0_144_',intersectionOf(['http://dbpedia.org/ontology/PopulatedPlace','http://dbpedia.org/ontology/Place'])]),1),(subClassOf('http://dbpedia.org/ontology/Settlement','http://dbpedia.org/ontology/#0_144_'),1),(subClassOf('http://dbpedia.org/ontology/Place','http://dbpedia.org/ontology/Settlement'),1),(subClassOf('http://dbpedia.org/ontology/Village','http://dbpedia.org/ontology/Place'),1)] ? ;

LE = [(subClassOf('http://dbpedia.org/ontology/Settlement','http://dbpedia.org/ontology/PopulatedPlace'),1),(subClassOf('http://dbpedia.org/ontology/Place','http://dbpedia.org/ontology/Settlement'),1),(subClassOf('http://dbpedia.org/ontology/Village','http://dbpedia.org/ontology/Place'),1)] ? ;

LE = [(subClassOf('http://dbpedia.org/ontology/Place','http://dbpedia.org/ontology/PopulatedPlace'),1),(subClassOf('http://dbpedia.org/ontology/Village','http://dbpedia.org/ontology/Place'),1)] ? ;

LE = [(equivalentClasses(['http://dbpedia.org/ontology/#73_0_',intersectionOf(['http://dbpedia.org/ontology/Settlement','http://dbpedia.org/ontology/PopulatedPlace'])]),1),(subClassOf('http://dbpedia.org/ontology/Place','http://dbpedia.org/ontology/#73_0_'),1),(equivalentClasses(['http://dbpedia.org/ontology/#73_144_',intersectionOf(['http://dbpedia.org/ontology/Settlement','http://dbpedia.org/ontology/Place'])]),1),(subClassOf('http://dbpedia.org/ontology/Village','http://dbpedia.org/ontology/#73_144_'),1)] ? ;

LE = [(subClassOf('http://dbpedia.org/ontology/Place','http://dbpedia.org/ontology/PopulatedPlace'),1),(equivalentClasses(['http://dbpedia.org/ontology/#73_144_',intersectionOf(['http://dbpedia.org/ontology/Settlement','http://dbpedia.org/ontology/Place'])]),1),(subClassOf('http://dbpedia.org/ontology/Village','http://dbpedia.org/ontology/#73_144_'),1)] ? ;

LE = [(equivalentClasses(['http://dbpedia.org/ontology/#0_144_',intersectionOf(['http://dbpedia.org/ontology/PopulatedPlace','http://dbpedia.org/ontology/Place'])]),1),(subClassOf('http://dbpedia.org/ontology/Settlement','http://dbpedia.org/ontology/#0_144_'),1),(equivalentClasses(['http://dbpedia.org/ontology/#73_144_',intersectionOf(['http://dbpedia.org/ontology/Settlement','http://dbpedia.org/ontology/Place'])]),1),(subClassOf('http://dbpedia.org/ontology/Village','http://dbpedia.org/ontology/#73_144_'),1)] ? ;

LE = [(subClassOf('http://dbpedia.org/ontology/Settlement','http://dbpedia.org/ontology/PopulatedPlace'),1),(equivalentClasses(['http://dbpedia.org/ontology/#73_144_',intersectionOf(['http://dbpedia.org/ontology/Settlement','http://dbpedia.org/ontology/Place'])]),1),(subClassOf('http://dbpedia.org/ontology/Village','http://dbpedia.org/ontology/#73_144_'),1)] 

*/

equivalentClasses(['http://dbpedia.org/ontology/#0_144_',intersectionOf(['http://dbpedia.org/ontology/PopulatedPlace','http://dbpedia.org/ontology/Place'])]).
equivalentClasses(['http://dbpedia.org/ontology/#73_0_',intersectionOf(['http://dbpedia.org/ontology/Settlement','http://dbpedia.org/ontology/PopulatedPlace'])]).
equivalentClasses(['http://dbpedia.org/ontology/#73_144_',intersectionOf(['http://dbpedia.org/ontology/Settlement','http://dbpedia.org/ontology/Place'])]).
equivalentClasses(['http://dbpedia.org/ontology/#73_0_144_',intersectionOf(['http://dbpedia.org/ontology/Settlement','http://dbpedia.org/ontology/PopulatedPlace','http://dbpedia.org/ontology/Place'])]).
subClassOf('http://dbpedia.org/ontology/ComicsCreator','http://dbpedia.org/ontology/Person').
subClassOf('http://dbpedia.org/ontology/Model','http://dbpedia.org/ontology/Person').
subClassOf('http://dbpedia.org/ontology/CollegeCoach','http://dbpedia.org/ontology/Person').
subClassOf('http://dbpedia.org/ontology/Continent','http://dbpedia.org/ontology/Place').
subClassOf('http://dbpedia.org/ontology/Continent','http://dbpedia.org/ontology/PopulatedPlace').
subClassOf('http://dbpedia.org/ontology/Continent','http://dbpedia.org/ontology/#0_144_').
subClassOf('http://dbpedia.org/ontology/Mountain','http://dbpedia.org/ontology/Place').
subClassOf('http://dbpedia.org/ontology/Lighthouse','http://dbpedia.org/ontology/Place').
subClassOf('http://dbpedia.org/ontology/MemberOfParliament','http://dbpedia.org/ontology/Person').
subClassOf('http://dbpedia.org/ontology/Country','http://dbpedia.org/ontology/Place').
subClassOf('http://dbpedia.org/ontology/Country','http://dbpedia.org/ontology/PopulatedPlace').
subClassOf('http://dbpedia.org/ontology/Country','http://dbpedia.org/ontology/#0_144_').
subClassOf('http://dbpedia.org/ontology/Book','http://dbpedia.org/ontology/Work').
subClassOf('http://dbpedia.org/ontology/SiteOfSpecialScientificInterest','http://dbpedia.org/ontology/Place').
subClassOf('http://dbpedia.org/ontology/Chancellor','http://dbpedia.org/ontology/Person').
subClassOf('http://dbpedia.org/ontology/FormulaOneRacer','http://dbpedia.org/ontology/Person').
subClassOf('http://dbpedia.org/ontology/Musical','http://dbpedia.org/ontology/Work').
subClassOf('http://dbpedia.org/ontology/Criminal','http://dbpedia.org/ontology/Person').
subClassOf('http://dbpedia.org/ontology/GridironFootballPlayer','http://dbpedia.org/ontology/Person').
subClassOf('http://dbpedia.org/ontology/Cyclist','http://dbpedia.org/ontology/Person').
subClassOf('http://dbpedia.org/ontology/AmericanFootballPlayer','http://dbpedia.org/ontology/Person').
subClassOf('http://dbpedia.org/ontology/Boxer','http://dbpedia.org/ontology/Person').
subClassOf('http://dbpedia.org/ontology/Skyscraper','http://dbpedia.org/ontology/Place').
subClassOf('http://dbpedia.org/ontology/FigureSkater','http://dbpedia.org/ontology/Person').
subClassOf('http://dbpedia.org/ontology/Comedian','http://dbpedia.org/ontology/Person').
subClassOf('http://dbpedia.org/ontology/Song','http://dbpedia.org/ontology/Work').
subClassOf('http://dbpedia.org/ontology/VideoGame','http://dbpedia.org/ontology/Work').
subClassOf('http://dbpedia.org/ontology/AdministrativeRegion','http://dbpedia.org/ontology/Place').
subClassOf('http://dbpedia.org/ontology/AdministrativeRegion','http://dbpedia.org/ontology/PopulatedPlace').
subClassOf('http://dbpedia.org/ontology/AdministrativeRegion','http://dbpedia.org/ontology/#0_144_').
subClassOf('http://dbpedia.org/ontology/FictionalCharacter','http://dbpedia.org/ontology/Person').
subClassOf('http://dbpedia.org/ontology/PopulatedPlace','http://dbpedia.org/ontology/#73_144_').
subClassOf('http://dbpedia.org/ontology/PopulatedPlace','http://dbpedia.org/ontology/Place').
subClassOf('http://dbpedia.org/ontology/PopulatedPlace','http://dbpedia.org/ontology/Settlement').
subClassOf('http://dbpedia.org/ontology/MountainRange','http://dbpedia.org/ontology/Place').
subClassOf('http://dbpedia.org/ontology/Congressman','http://dbpedia.org/ontology/Person').
subClassOf('http://dbpedia.org/ontology/Single','http://dbpedia.org/ontology/Work').
subClassOf('http://dbpedia.org/ontology/MilitaryPerson','http://dbpedia.org/ontology/Person').
subClassOf('http://dbpedia.org/ontology/Software','http://dbpedia.org/ontology/Work').
subClassOf('http://dbpedia.org/ontology/BodyOfWater','http://dbpedia.org/ontology/Place').
subClassOf('http://dbpedia.org/ontology/TelevisionEpisode','http://dbpedia.org/ontology/Work').
subClassOf('http://dbpedia.org/ontology/LunarCrater','http://dbpedia.org/ontology/Place').
subClassOf('http://dbpedia.org/ontology/Station','http://dbpedia.org/ontology/Place').
subClassOf('http://dbpedia.org/ontology/VoiceActor','http://dbpedia.org/ontology/Person').
subClassOf('http://dbpedia.org/ontology/BasketballPlayer','http://dbpedia.org/ontology/Person').
subClassOf('http://dbpedia.org/ontology/Building','http://dbpedia.org/ontology/Place').
subClassOf('http://dbpedia.org/ontology/Album','http://dbpedia.org/ontology/Work').
subClassOf('http://dbpedia.org/ontology/Airport','http://dbpedia.org/ontology/Place').
subClassOf('http://dbpedia.org/ontology/Cardinal','http://dbpedia.org/ontology/Person').
subClassOf('http://dbpedia.org/ontology/BadmintonPlayer','http://dbpedia.org/ontology/Person').
subClassOf('http://dbpedia.org/ontology/President','http://dbpedia.org/ontology/Person').
subClassOf('http://dbpedia.org/ontology/Wrestler','http://dbpedia.org/ontology/Person').
subClassOf('http://dbpedia.org/ontology/River','http://dbpedia.org/ontology/Place').
subClassOf('http://dbpedia.org/ontology/HistoricPlace','http://dbpedia.org/ontology/Place').
subClassOf('http://dbpedia.org/ontology/Cleric','http://dbpedia.org/ontology/Person').
subClassOf('http://dbpedia.org/ontology/SoccerPlayer','http://dbpedia.org/ontology/Person').
subClassOf('http://dbpedia.org/ontology/Architect','http://dbpedia.org/ontology/Person').
subClassOf('http://dbpedia.org/ontology/Judge','http://dbpedia.org/ontology/Person').
subClassOf('http://dbpedia.org/ontology/Lake','http://dbpedia.org/ontology/Place').
subClassOf('http://dbpedia.org/ontology/EurovisionSongContestEntry','http://dbpedia.org/ontology/Work').
subClassOf('http://dbpedia.org/ontology/ComicsCharacter','http://dbpedia.org/ontology/Person').
subClassOf('http://dbpedia.org/ontology/WorldHeritageSite','http://dbpedia.org/ontology/Place').
subClassOf('http://dbpedia.org/ontology/TelevisionShow','http://dbpedia.org/ontology/Work').
subClassOf('http://dbpedia.org/ontology/LaunchPad','http://dbpedia.org/ontology/Place').
subClassOf('http://dbpedia.org/ontology/BaseballPlayer','http://dbpedia.org/ontology/Person').
subClassOf('http://dbpedia.org/ontology/ChristianBishop','http://dbpedia.org/ontology/Person').
subClassOf('http://dbpedia.org/ontology/NationalCollegiateAthleticAssociationAthlete','http://dbpedia.org/ontology/Person').
subClassOf('http://dbpedia.org/ontology/Saint','http://dbpedia.org/ontology/Person').
subClassOf('http://dbpedia.org/ontology/Cricketer','http://dbpedia.org/ontology/Person').
subClassOf('http://dbpedia.org/ontology/Astronaut','http://dbpedia.org/ontology/Person').
subClassOf('http://dbpedia.org/ontology/Island','http://dbpedia.org/ontology/Place').
subClassOf('http://dbpedia.org/ontology/Island','http://dbpedia.org/ontology/PopulatedPlace').
subClassOf('http://dbpedia.org/ontology/Island','http://dbpedia.org/ontology/#0_144_').
subClassOf('http://dbpedia.org/ontology/IceHockeyPlayer','http://dbpedia.org/ontology/Person').
subClassOf('http://dbpedia.org/ontology/Stream','http://dbpedia.org/ontology/Place').
subClassOf('http://dbpedia.org/ontology/Governor','http://dbpedia.org/ontology/Person').
subClassOf('http://dbpedia.org/ontology/Newspaper','http://dbpedia.org/ontology/Work').
subClassOf('http://dbpedia.org/ontology/SoccerManager','http://dbpedia.org/ontology/Person').
subClassOf('http://dbpedia.org/ontology/BritishRoyalty','http://dbpedia.org/ontology/Person').
subClassOf('http://dbpedia.org/ontology/Hospital','http://dbpedia.org/ontology/Place').
subClassOf('http://dbpedia.org/ontology/Journalist','http://dbpedia.org/ontology/Person').
subClassOf('http://dbpedia.org/ontology/NascarDriver','http://dbpedia.org/ontology/Person').
subClassOf('http://dbpedia.org/ontology/Park','http://dbpedia.org/ontology/Place').
subClassOf('http://dbpedia.org/ontology/Bridge','http://dbpedia.org/ontology/Place').
subClassOf('http://dbpedia.org/ontology/Village','http://dbpedia.org/ontology/#73_144_').
subClassOf('http://dbpedia.org/ontology/Village','http://dbpedia.org/ontology/Place').
subClassOf('http://dbpedia.org/ontology/Village','http://dbpedia.org/ontology/PopulatedPlace').
subClassOf('http://dbpedia.org/ontology/Village','http://dbpedia.org/ontology/#73_0_144_').
subClassOf('http://dbpedia.org/ontology/Village','http://dbpedia.org/ontology/Settlement').
subClassOf('http://dbpedia.org/ontology/Village','http://dbpedia.org/ontology/#73_0_').
subClassOf('http://dbpedia.org/ontology/Village','http://dbpedia.org/ontology/#0_144_').
subClassOf('http://dbpedia.org/ontology/Senator','http://dbpedia.org/ontology/Person').
subClassOf('http://dbpedia.org/ontology/ProtectedArea','http://dbpedia.org/ontology/Place').
subClassOf('http://dbpedia.org/ontology/Stadium','http://dbpedia.org/ontology/Place').
subClassOf('http://dbpedia.org/ontology/Magazine','http://dbpedia.org/ontology/Work').
subClassOf('http://dbpedia.org/ontology/Canal','http://dbpedia.org/ontology/Place').
subClassOf('http://dbpedia.org/ontology/Politician','http://dbpedia.org/ontology/Person').
subClassOf('http://dbpedia.org/ontology/MusicalArtist','http://dbpedia.org/ontology/Person').
subClassOf('http://dbpedia.org/ontology/PrimeMinister','http://dbpedia.org/ontology/Person').
subClassOf('http://dbpedia.org/ontology/Town','http://dbpedia.org/ontology/#73_144_').
subClassOf('http://dbpedia.org/ontology/Town','http://dbpedia.org/ontology/Place').
subClassOf('http://dbpedia.org/ontology/Town','http://dbpedia.org/ontology/PopulatedPlace').
subClassOf('http://dbpedia.org/ontology/Town','http://dbpedia.org/ontology/#73_0_144_').
subClassOf('http://dbpedia.org/ontology/Town','http://dbpedia.org/ontology/Settlement').
subClassOf('http://dbpedia.org/ontology/Town','http://dbpedia.org/ontology/#73_0_').
subClassOf('http://dbpedia.org/ontology/Town','http://dbpedia.org/ontology/#0_144_').
subClassOf('http://dbpedia.org/ontology/OfficeHolder','http://dbpedia.org/ontology/Person').
subClassOf('http://dbpedia.org/ontology/Film','http://dbpedia.org/ontology/Work').
subClassOf('http://dbpedia.org/ontology/TennisPlayer','http://dbpedia.org/ontology/Person').
subClassOf('http://dbpedia.org/ontology/Athlete','http://dbpedia.org/ontology/Person').
subClassOf('http://dbpedia.org/ontology/Pope','http://dbpedia.org/ontology/Person').
subClassOf('http://dbpedia.org/ontology/Mayor','http://dbpedia.org/ontology/Person').
subClassOf('http://dbpedia.org/ontology/Cave','http://dbpedia.org/ontology/Place').
subClassOf('http://dbpedia.org/ontology/MusicalWork','http://dbpedia.org/ontology/Work').
subClassOf('http://dbpedia.org/ontology/PlayboyPlaymate','http://dbpedia.org/ontology/Person').
subClassOf('http://dbpedia.org/ontology/Monarch','http://dbpedia.org/ontology/Person').
subClassOf('http://dbpedia.org/ontology/Settlement','http://dbpedia.org/ontology/Place').
subClassOf('http://dbpedia.org/ontology/Settlement','http://dbpedia.org/ontology/PopulatedPlace').
subClassOf('http://dbpedia.org/ontology/Settlement','http://dbpedia.org/ontology/#0_144_').
subClassOf('http://dbpedia.org/ontology/City','http://dbpedia.org/ontology/#73_144_').
subClassOf('http://dbpedia.org/ontology/City','http://dbpedia.org/ontology/Place').
subClassOf('http://dbpedia.org/ontology/City','http://dbpedia.org/ontology/PopulatedPlace').
subClassOf('http://dbpedia.org/ontology/City','http://dbpedia.org/ontology/#73_0_144_').
subClassOf('http://dbpedia.org/ontology/City','http://dbpedia.org/ontology/Settlement').
subClassOf('http://dbpedia.org/ontology/City','http://dbpedia.org/ontology/#73_0_').
subClassOf('http://dbpedia.org/ontology/City','http://dbpedia.org/ontology/#0_144_').
subClassOf('http://dbpedia.org/ontology/ShoppingMall','http://dbpedia.org/ontology/Place').
subClassOf('http://dbpedia.org/ontology/SkiArea','http://dbpedia.org/ontology/Place').
subClassOf('http://dbpedia.org/ontology/Monument','http://dbpedia.org/ontology/Place').
subClassOf('http://dbpedia.org/ontology/WineRegion','http://dbpedia.org/ontology/Place').
subClassOf('http://dbpedia.org/ontology/GaelicGamesPlayer','http://dbpedia.org/ontology/Person').
subClassOf('http://dbpedia.org/ontology/PokerPlayer','http://dbpedia.org/ontology/Person').
subClassOf('http://dbpedia.org/ontology/AdultActor','http://dbpedia.org/ontology/Person').
subClassOf('http://dbpedia.org/ontology/Ambassador','http://dbpedia.org/ontology/Person').
subClassOf('http://dbpedia.org/ontology/Place','http://dbpedia.org/ontology/PopulatedPlace').
subClassOf('http://dbpedia.org/ontology/Place','http://dbpedia.org/ontology/Settlement').
subClassOf('http://dbpedia.org/ontology/Place','http://dbpedia.org/ontology/#73_0_').
subClassOf('http://dbpedia.org/ontology/Philosopher','http://dbpedia.org/ontology/Person').
subClassOf('http://dbpedia.org/ontology/Scientist','http://dbpedia.org/ontology/Person').
subClassOf('http://dbpedia.org/ontology/Artist','http://dbpedia.org/ontology/Person').
subClassOf('http://dbpedia.org/ontology/Actor','http://dbpedia.org/ontology/Person').
subClassOf('http://dbpedia.org/ontology/Valley','http://dbpedia.org/ontology/Place').
subClassOf('http://dbpedia.org/ontology/Writer','http://dbpedia.org/ontology/Person').
subClassOf('http://dbpedia.org/ontology/RugbyPlayer','http://dbpedia.org/ontology/Person').
annotationProperty('http://www.w3.org/2000/01/rdf-schema#label').
annotationProperty('http://www.w3.org/2000/01/rdf-schema#comment').
annotationProperty('https://sites.google.com/a/unife.it/ml/bundle#probability').
class('http://dbpedia.org/ontology/#0_144_').
class('http://dbpedia.org/ontology/#73_0_').
class('http://dbpedia.org/ontology/#73_144_').
class('http://dbpedia.org/ontology/#73_0_144_').
class('http://dbpedia.org/ontology/ComicsCreator').
class('http://dbpedia.org/ontology/Model').
class('http://dbpedia.org/ontology/CollegeCoach').
class('http://dbpedia.org/ontology/Continent').
class('http://dbpedia.org/ontology/Mountain').
class('http://dbpedia.org/ontology/Lighthouse').
class('http://dbpedia.org/ontology/MemberOfParliament').
class('http://dbpedia.org/ontology/Country').
class('http://dbpedia.org/ontology/Book').
class('http://dbpedia.org/ontology/SiteOfSpecialScientificInterest').
class('http://dbpedia.org/ontology/Chancellor').
class('http://dbpedia.org/ontology/FormulaOneRacer').
class('http://dbpedia.org/ontology/Musical').
class('http://dbpedia.org/ontology/Criminal').
class('http://dbpedia.org/ontology/GridironFootballPlayer').
class('http://dbpedia.org/ontology/Cyclist').
class('http://dbpedia.org/ontology/AmericanFootballPlayer').
class('http://dbpedia.org/ontology/Boxer').
class('http://dbpedia.org/ontology/Skyscraper').
class('http://dbpedia.org/ontology/FigureSkater').
class('http://dbpedia.org/ontology/Comedian').
class('http://dbpedia.org/ontology/Song').
class('http://dbpedia.org/ontology/VideoGame').
class('http://dbpedia.org/ontology/AdministrativeRegion').
class('http://dbpedia.org/ontology/FictionalCharacter').
class('http://dbpedia.org/ontology/PopulatedPlace').
class('http://dbpedia.org/ontology/MountainRange').
class('http://dbpedia.org/ontology/Congressman').
class('http://dbpedia.org/ontology/Single').
class('http://dbpedia.org/ontology/MilitaryPerson').
class('http://dbpedia.org/ontology/Software').
class('http://dbpedia.org/ontology/BodyOfWater').
class('http://dbpedia.org/ontology/TelevisionEpisode').
class('http://dbpedia.org/ontology/LunarCrater').
class('http://dbpedia.org/ontology/Station').
class('http://dbpedia.org/ontology/VoiceActor').
class('http://dbpedia.org/ontology/BasketballPlayer').
class('http://dbpedia.org/ontology/Building').
class('http://dbpedia.org/ontology/Album').
class('http://dbpedia.org/ontology/Airport').
class('http://dbpedia.org/ontology/Cardinal').
class('http://dbpedia.org/ontology/BadmintonPlayer').
class('http://dbpedia.org/ontology/President').
class('http://dbpedia.org/ontology/Wrestler').
class('http://dbpedia.org/ontology/River').
class('http://dbpedia.org/ontology/HistoricPlace').
class('http://dbpedia.org/ontology/Cleric').
class('http://dbpedia.org/ontology/SoccerPlayer').
class('http://dbpedia.org/ontology/Architect').
class('http://dbpedia.org/ontology/Judge').
class('http://dbpedia.org/ontology/Lake').
class('http://dbpedia.org/ontology/EurovisionSongContestEntry').
class('http://dbpedia.org/ontology/ComicsCharacter').
class('http://dbpedia.org/ontology/WorldHeritageSite').
class('http://dbpedia.org/ontology/TelevisionShow').
class('http://dbpedia.org/ontology/LaunchPad').
class('http://dbpedia.org/ontology/BaseballPlayer').
class('http://dbpedia.org/ontology/ChristianBishop').
class('http://dbpedia.org/ontology/NationalCollegiateAthleticAssociationAthlete').
class('http://dbpedia.org/ontology/Saint').
class('http://dbpedia.org/ontology/Cricketer').
class('http://dbpedia.org/ontology/Astronaut').
class('http://dbpedia.org/ontology/Island').
class('http://dbpedia.org/ontology/IceHockeyPlayer').
class('http://dbpedia.org/ontology/Stream').
class('http://dbpedia.org/ontology/Governor').
class('http://dbpedia.org/ontology/Newspaper').
class('http://dbpedia.org/ontology/SoccerManager').
class('http://dbpedia.org/ontology/BritishRoyalty').
class('http://dbpedia.org/ontology/Hospital').
class('http://dbpedia.org/ontology/Journalist').
class('http://dbpedia.org/ontology/NascarDriver').
class('http://dbpedia.org/ontology/Park').
class('http://dbpedia.org/ontology/Bridge').
class('http://dbpedia.org/ontology/Village').
class('http://dbpedia.org/ontology/Senator').
class('http://dbpedia.org/ontology/ProtectedArea').
class('http://dbpedia.org/ontology/Stadium').
class('http://dbpedia.org/ontology/Magazine').
class('http://dbpedia.org/ontology/Canal').
class('http://dbpedia.org/ontology/Politician').
class('http://dbpedia.org/ontology/MusicalArtist').
class('http://dbpedia.org/ontology/PrimeMinister').
class('http://dbpedia.org/ontology/Town').
class('http://dbpedia.org/ontology/OfficeHolder').
class('http://dbpedia.org/ontology/Film').
class('http://dbpedia.org/ontology/TennisPlayer').
class('http://dbpedia.org/ontology/Athlete').
class('http://dbpedia.org/ontology/Pope').
class('http://dbpedia.org/ontology/Mayor').
class('http://dbpedia.org/ontology/Cave').
class('http://dbpedia.org/ontology/MusicalWork').
class('http://dbpedia.org/ontology/PlayboyPlaymate').
class('http://dbpedia.org/ontology/Monarch').
class('http://dbpedia.org/ontology/Settlement').
class('http://dbpedia.org/ontology/City').
class('http://dbpedia.org/ontology/ShoppingMall').
class('http://dbpedia.org/ontology/SkiArea').
class('http://dbpedia.org/ontology/Monument').
class('http://dbpedia.org/ontology/WineRegion').
class('http://dbpedia.org/ontology/GaelicGamesPlayer').
class('http://dbpedia.org/ontology/PokerPlayer').
class('http://dbpedia.org/ontology/AdultActor').
class('http://dbpedia.org/ontology/Ambassador').
class('http://dbpedia.org/ontology/Place').
class('http://dbpedia.org/ontology/Philosopher').
class('http://dbpedia.org/ontology/Scientist').
class('http://dbpedia.org/ontology/Artist').
class('http://dbpedia.org/ontology/Actor').
class('http://dbpedia.org/ontology/Valley').
class('http://dbpedia.org/ontology/Writer').
class('http://dbpedia.org/ontology/RugbyPlayer').
ontology('http://dbpedia.org/ontology/').
ontologyAxiom('http://dbpedia.org/ontology/',ontologyVersionInfo('http://dbpedia.org/ontology/',literal(lang(en,'Version 3.5')))).
ontologyAxiom('http://dbpedia.org/ontology/',ontology('http://dbpedia.org/ontology/')).
ontologyAxiom('http://dbpedia.org/ontology/',annotationProperty('https://sites.google.com/a/unife.it/ml/bundle#probability')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/#0_144_')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/#73_0_')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/#73_144_')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/#73_0_144_')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/ComicsCreator')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/Model')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/CollegeCoach')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/Continent')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/Mountain')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/Lighthouse')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/MemberOfParliament')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/Country')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/Book')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/SiteOfSpecialScientificInterest')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/Chancellor')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/FormulaOneRacer')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/Musical')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/Criminal')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/GridironFootballPlayer')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/Cyclist')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/AmericanFootballPlayer')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/Boxer')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/Skyscraper')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/FigureSkater')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/Comedian')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/Song')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/VideoGame')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/AdministrativeRegion')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/FictionalCharacter')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/PopulatedPlace')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/MountainRange')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/Congressman')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/Single')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/MilitaryPerson')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/Software')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/BodyOfWater')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/TelevisionEpisode')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/LunarCrater')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/Station')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/VoiceActor')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/BasketballPlayer')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/Building')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/Album')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/Airport')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/Cardinal')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/BadmintonPlayer')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/President')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/Wrestler')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/River')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/HistoricPlace')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/Cleric')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/SoccerPlayer')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/Architect')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/Judge')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/Lake')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/EurovisionSongContestEntry')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/ComicsCharacter')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/WorldHeritageSite')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/TelevisionShow')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/LaunchPad')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/BaseballPlayer')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/ChristianBishop')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/NationalCollegiateAthleticAssociationAthlete')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/Saint')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/Cricketer')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/Astronaut')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/Island')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/IceHockeyPlayer')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/Stream')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/Governor')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/Newspaper')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/SoccerManager')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/BritishRoyalty')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/Hospital')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/Journalist')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/NascarDriver')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/Park')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/Bridge')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/Village')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/Senator')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/ProtectedArea')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/Stadium')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/Magazine')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/Canal')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/Politician')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/MusicalArtist')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/PrimeMinister')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/Town')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/OfficeHolder')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/Film')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/TennisPlayer')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/Athlete')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/Pope')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/Mayor')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/Cave')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/MusicalWork')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/PlayboyPlaymate')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/Monarch')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/Settlement')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/City')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/ShoppingMall')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/SkiArea')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/Monument')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/WineRegion')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/GaelicGamesPlayer')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/PokerPlayer')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/AdultActor')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/Ambassador')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/Place')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/Philosopher')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/Scientist')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/Artist')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/Actor')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/Valley')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/Writer')).
ontologyAxiom('http://dbpedia.org/ontology/',class('http://dbpedia.org/ontology/RugbyPlayer')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/ComicsCreator','http://dbpedia.org/ontology/Person')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Model','http://dbpedia.org/ontology/Person')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/CollegeCoach','http://dbpedia.org/ontology/Person')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Continent','http://dbpedia.org/ontology/Place')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Continent','http://dbpedia.org/ontology/PopulatedPlace')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Continent','http://dbpedia.org/ontology/#0_144_')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Mountain','http://dbpedia.org/ontology/Place')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Lighthouse','http://dbpedia.org/ontology/Place')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/MemberOfParliament','http://dbpedia.org/ontology/Person')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Country','http://dbpedia.org/ontology/Place')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Country','http://dbpedia.org/ontology/PopulatedPlace')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Country','http://dbpedia.org/ontology/#0_144_')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Book','http://dbpedia.org/ontology/Work')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/SiteOfSpecialScientificInterest','http://dbpedia.org/ontology/Place')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Chancellor','http://dbpedia.org/ontology/Person')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/FormulaOneRacer','http://dbpedia.org/ontology/Person')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Musical','http://dbpedia.org/ontology/Work')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Criminal','http://dbpedia.org/ontology/Person')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/GridironFootballPlayer','http://dbpedia.org/ontology/Person')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Cyclist','http://dbpedia.org/ontology/Person')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/AmericanFootballPlayer','http://dbpedia.org/ontology/Person')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Boxer','http://dbpedia.org/ontology/Person')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Skyscraper','http://dbpedia.org/ontology/Place')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/FigureSkater','http://dbpedia.org/ontology/Person')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Comedian','http://dbpedia.org/ontology/Person')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Song','http://dbpedia.org/ontology/Work')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/VideoGame','http://dbpedia.org/ontology/Work')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/AdministrativeRegion','http://dbpedia.org/ontology/Place')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/AdministrativeRegion','http://dbpedia.org/ontology/PopulatedPlace')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/AdministrativeRegion','http://dbpedia.org/ontology/#0_144_')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/FictionalCharacter','http://dbpedia.org/ontology/Person')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/PopulatedPlace','http://dbpedia.org/ontology/#73_144_')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/PopulatedPlace','http://dbpedia.org/ontology/Place')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/PopulatedPlace','http://dbpedia.org/ontology/Settlement')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/MountainRange','http://dbpedia.org/ontology/Place')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Congressman','http://dbpedia.org/ontology/Person')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Single','http://dbpedia.org/ontology/Work')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/MilitaryPerson','http://dbpedia.org/ontology/Person')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Software','http://dbpedia.org/ontology/Work')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/BodyOfWater','http://dbpedia.org/ontology/Place')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/TelevisionEpisode','http://dbpedia.org/ontology/Work')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/LunarCrater','http://dbpedia.org/ontology/Place')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Station','http://dbpedia.org/ontology/Place')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/VoiceActor','http://dbpedia.org/ontology/Person')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/BasketballPlayer','http://dbpedia.org/ontology/Person')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Building','http://dbpedia.org/ontology/Place')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Album','http://dbpedia.org/ontology/Work')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Airport','http://dbpedia.org/ontology/Place')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Cardinal','http://dbpedia.org/ontology/Person')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/BadmintonPlayer','http://dbpedia.org/ontology/Person')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/President','http://dbpedia.org/ontology/Person')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Wrestler','http://dbpedia.org/ontology/Person')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/River','http://dbpedia.org/ontology/Place')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/HistoricPlace','http://dbpedia.org/ontology/Place')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Cleric','http://dbpedia.org/ontology/Person')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/SoccerPlayer','http://dbpedia.org/ontology/Person')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Architect','http://dbpedia.org/ontology/Person')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Judge','http://dbpedia.org/ontology/Person')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Lake','http://dbpedia.org/ontology/Place')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/EurovisionSongContestEntry','http://dbpedia.org/ontology/Work')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/ComicsCharacter','http://dbpedia.org/ontology/Person')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/WorldHeritageSite','http://dbpedia.org/ontology/Place')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/TelevisionShow','http://dbpedia.org/ontology/Work')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/LaunchPad','http://dbpedia.org/ontology/Place')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/BaseballPlayer','http://dbpedia.org/ontology/Person')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/ChristianBishop','http://dbpedia.org/ontology/Person')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/NationalCollegiateAthleticAssociationAthlete','http://dbpedia.org/ontology/Person')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Saint','http://dbpedia.org/ontology/Person')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Cricketer','http://dbpedia.org/ontology/Person')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Astronaut','http://dbpedia.org/ontology/Person')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Island','http://dbpedia.org/ontology/Place')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Island','http://dbpedia.org/ontology/PopulatedPlace')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Island','http://dbpedia.org/ontology/#0_144_')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/IceHockeyPlayer','http://dbpedia.org/ontology/Person')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Stream','http://dbpedia.org/ontology/Place')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Governor','http://dbpedia.org/ontology/Person')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Newspaper','http://dbpedia.org/ontology/Work')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/SoccerManager','http://dbpedia.org/ontology/Person')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/BritishRoyalty','http://dbpedia.org/ontology/Person')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Hospital','http://dbpedia.org/ontology/Place')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Journalist','http://dbpedia.org/ontology/Person')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/NascarDriver','http://dbpedia.org/ontology/Person')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Park','http://dbpedia.org/ontology/Place')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Bridge','http://dbpedia.org/ontology/Place')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Village','http://dbpedia.org/ontology/#73_144_')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Village','http://dbpedia.org/ontology/Place')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Village','http://dbpedia.org/ontology/PopulatedPlace')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Village','http://dbpedia.org/ontology/#73_0_144_')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Village','http://dbpedia.org/ontology/Settlement')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Village','http://dbpedia.org/ontology/#73_0_')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Village','http://dbpedia.org/ontology/#0_144_')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Senator','http://dbpedia.org/ontology/Person')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/ProtectedArea','http://dbpedia.org/ontology/Place')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Stadium','http://dbpedia.org/ontology/Place')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Magazine','http://dbpedia.org/ontology/Work')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Canal','http://dbpedia.org/ontology/Place')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Politician','http://dbpedia.org/ontology/Person')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/MusicalArtist','http://dbpedia.org/ontology/Person')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/PrimeMinister','http://dbpedia.org/ontology/Person')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Town','http://dbpedia.org/ontology/#73_144_')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Town','http://dbpedia.org/ontology/Place')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Town','http://dbpedia.org/ontology/PopulatedPlace')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Town','http://dbpedia.org/ontology/#73_0_144_')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Town','http://dbpedia.org/ontology/Settlement')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Town','http://dbpedia.org/ontology/#73_0_')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Town','http://dbpedia.org/ontology/#0_144_')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/OfficeHolder','http://dbpedia.org/ontology/Person')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Film','http://dbpedia.org/ontology/Work')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/TennisPlayer','http://dbpedia.org/ontology/Person')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Athlete','http://dbpedia.org/ontology/Person')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Pope','http://dbpedia.org/ontology/Person')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Mayor','http://dbpedia.org/ontology/Person')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Cave','http://dbpedia.org/ontology/Place')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/MusicalWork','http://dbpedia.org/ontology/Work')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/PlayboyPlaymate','http://dbpedia.org/ontology/Person')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Monarch','http://dbpedia.org/ontology/Person')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Settlement','http://dbpedia.org/ontology/Place')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Settlement','http://dbpedia.org/ontology/PopulatedPlace')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Settlement','http://dbpedia.org/ontology/#0_144_')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/City','http://dbpedia.org/ontology/#73_144_')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/City','http://dbpedia.org/ontology/Place')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/City','http://dbpedia.org/ontology/PopulatedPlace')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/City','http://dbpedia.org/ontology/#73_0_144_')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/City','http://dbpedia.org/ontology/Settlement')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/City','http://dbpedia.org/ontology/#73_0_')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/City','http://dbpedia.org/ontology/#0_144_')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/ShoppingMall','http://dbpedia.org/ontology/Place')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/SkiArea','http://dbpedia.org/ontology/Place')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Monument','http://dbpedia.org/ontology/Place')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/WineRegion','http://dbpedia.org/ontology/Place')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/GaelicGamesPlayer','http://dbpedia.org/ontology/Person')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/PokerPlayer','http://dbpedia.org/ontology/Person')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/AdultActor','http://dbpedia.org/ontology/Person')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Ambassador','http://dbpedia.org/ontology/Person')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Place','http://dbpedia.org/ontology/PopulatedPlace')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Place','http://dbpedia.org/ontology/Settlement')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Place','http://dbpedia.org/ontology/#73_0_')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Philosopher','http://dbpedia.org/ontology/Person')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Scientist','http://dbpedia.org/ontology/Person')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Artist','http://dbpedia.org/ontology/Person')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Actor','http://dbpedia.org/ontology/Person')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Valley','http://dbpedia.org/ontology/Place')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/Writer','http://dbpedia.org/ontology/Person')).
ontologyAxiom('http://dbpedia.org/ontology/',subClassOf('http://dbpedia.org/ontology/RugbyPlayer','http://dbpedia.org/ontology/Person')).
ontologyAxiom('http://dbpedia.org/ontology/',equivalentClasses(['http://dbpedia.org/ontology/#0_144_',intersectionOf(['http://dbpedia.org/ontology/PopulatedPlace','http://dbpedia.org/ontology/Place'])])).
ontologyAxiom('http://dbpedia.org/ontology/',equivalentClasses(['http://dbpedia.org/ontology/#73_0_',intersectionOf(['http://dbpedia.org/ontology/Settlement','http://dbpedia.org/ontology/PopulatedPlace'])])).
ontologyAxiom('http://dbpedia.org/ontology/',equivalentClasses(['http://dbpedia.org/ontology/#73_144_',intersectionOf(['http://dbpedia.org/ontology/Settlement','http://dbpedia.org/ontology/Place'])])).
ontologyAxiom('http://dbpedia.org/ontology/',equivalentClasses(['http://dbpedia.org/ontology/#73_0_144_',intersectionOf(['http://dbpedia.org/ontology/Settlement','http://dbpedia.org/ontology/PopulatedPlace','http://dbpedia.org/ontology/Place'])])).
