/*

QUERY 1:
sub_class('http://swat.cse.lehigh.edu/onto/univ-bench.owl#Chair','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Person',LE).

EXPL:
LE = [(equivalentClasses(['http://swat.cse.lehigh.edu/onto/univ-bench.owl#Chair',intersectionOf(['http://swat.cse.lehigh.edu/onto/univ-bench.owl#Person',someValuesFrom('http://swat.cse.lehigh.edu/onto/univ-bench.owl#headOf','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Department')])]),1)] ? ;

LE = [(equivalentClasses(['http://swat.cse.lehigh.edu/onto/univ-bench.owl#Employee',intersectionOf(['http://swat.cse.lehigh.edu/onto/univ-bench.owl#Person',someValuesFrom('http://swat.cse.lehigh.edu/onto/univ-bench.owl#worksFor','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Organization')])]),1),(subClassOf('http://swat.cse.lehigh.edu/onto/univ-bench.owl#Faculty','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Employee'),1),(subClassOf('http://swat.cse.lehigh.edu/onto/univ-bench.owl#Professor','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Faculty'),1),(subClassOf('http://swat.cse.lehigh.edu/onto/univ-bench.owl#Chair','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Professor'),1)] 

*/

equivalentClasses(['http://swat.cse.lehigh.edu/onto/univ-bench.owl#Chair',intersectionOf(['http://swat.cse.lehigh.edu/onto/univ-bench.owl#Person',someValuesFrom('http://swat.cse.lehigh.edu/onto/univ-bench.owl#headOf','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Department')])]).
equivalentClasses(['http://swat.cse.lehigh.edu/onto/univ-bench.owl#Dean',intersectionOf([someValuesFrom('http://swat.cse.lehigh.edu/onto/univ-bench.owl#headOf','http://swat.cse.lehigh.edu/onto/univ-bench.owl#College')])]).
equivalentClasses(['http://swat.cse.lehigh.edu/onto/univ-bench.owl#Director',intersectionOf(['http://swat.cse.lehigh.edu/onto/univ-bench.owl#Person',someValuesFrom('http://swat.cse.lehigh.edu/onto/univ-bench.owl#headOf','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Program')])]).
equivalentClasses(['http://swat.cse.lehigh.edu/onto/univ-bench.owl#Employee',intersectionOf(['http://swat.cse.lehigh.edu/onto/univ-bench.owl#Person',someValuesFrom('http://swat.cse.lehigh.edu/onto/univ-bench.owl#worksFor','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Organization')])]).
equivalentClasses(['http://swat.cse.lehigh.edu/onto/univ-bench.owl#Student',intersectionOf(['http://swat.cse.lehigh.edu/onto/univ-bench.owl#Person',someValuesFrom('http://swat.cse.lehigh.edu/onto/univ-bench.owl#takesCourse','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Course')])]).
equivalentClasses(['http://swat.cse.lehigh.edu/onto/univ-bench.owl#TeachingAssistant',intersectionOf(['http://swat.cse.lehigh.edu/onto/univ-bench.owl#Person',someValuesFrom('http://swat.cse.lehigh.edu/onto/univ-bench.owl#teachingAssistantOf','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Course')])]).
subClassOf('http://swat.cse.lehigh.edu/onto/univ-bench.owl#AdministrativeStaff','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Employee').
subClassOf('http://swat.cse.lehigh.edu/onto/univ-bench.owl#Article','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Publication').
subClassOf('http://swat.cse.lehigh.edu/onto/univ-bench.owl#AssistantProfessor','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Professor').
subClassOf('http://swat.cse.lehigh.edu/onto/univ-bench.owl#AssociateProfessor','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Professor').
subClassOf('http://swat.cse.lehigh.edu/onto/univ-bench.owl#Book','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Publication').
subClassOf('http://swat.cse.lehigh.edu/onto/univ-bench.owl#Chair','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Professor').
subClassOf('http://swat.cse.lehigh.edu/onto/univ-bench.owl#ClericalStaff','http://swat.cse.lehigh.edu/onto/univ-bench.owl#AdministrativeStaff').
subClassOf('http://swat.cse.lehigh.edu/onto/univ-bench.owl#College','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Organization').
subClassOf('http://swat.cse.lehigh.edu/onto/univ-bench.owl#ConferencePaper','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Article').
subClassOf('http://swat.cse.lehigh.edu/onto/univ-bench.owl#Course','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Work').
subClassOf('http://swat.cse.lehigh.edu/onto/univ-bench.owl#Dean','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Professor').
subClassOf('http://swat.cse.lehigh.edu/onto/univ-bench.owl#Department','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Organization').
subClassOf('http://swat.cse.lehigh.edu/onto/univ-bench.owl#Faculty','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Employee').
subClassOf('http://swat.cse.lehigh.edu/onto/univ-bench.owl#FullProfessor','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Professor').
subClassOf('http://swat.cse.lehigh.edu/onto/univ-bench.owl#GraduateCourse','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Course').
subClassOf('http://swat.cse.lehigh.edu/onto/univ-bench.owl#GraduateStudent','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Person').
subClassOf('http://swat.cse.lehigh.edu/onto/univ-bench.owl#GraduateStudent',someValuesFrom('http://swat.cse.lehigh.edu/onto/univ-bench.owl#takesCourse','http://swat.cse.lehigh.edu/onto/univ-bench.owl#GraduateCourse')).
subClassOf('http://swat.cse.lehigh.edu/onto/univ-bench.owl#Institute','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Organization').
subClassOf('http://swat.cse.lehigh.edu/onto/univ-bench.owl#JournalArticle','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Article').
subClassOf('http://swat.cse.lehigh.edu/onto/univ-bench.owl#Lecturer','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Faculty').
subClassOf('http://swat.cse.lehigh.edu/onto/univ-bench.owl#Manual','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Publication').
subClassOf('http://swat.cse.lehigh.edu/onto/univ-bench.owl#PostDoc','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Faculty').
subClassOf('http://swat.cse.lehigh.edu/onto/univ-bench.owl#Professor','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Faculty').
subClassOf('http://swat.cse.lehigh.edu/onto/univ-bench.owl#Program','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Organization').
subClassOf('http://swat.cse.lehigh.edu/onto/univ-bench.owl#Research','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Work').
subClassOf('http://swat.cse.lehigh.edu/onto/univ-bench.owl#ResearchAssistant','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Person').
subClassOf('http://swat.cse.lehigh.edu/onto/univ-bench.owl#ResearchAssistant',someValuesFrom('http://swat.cse.lehigh.edu/onto/univ-bench.owl#worksFor','http://swat.cse.lehigh.edu/onto/univ-bench.owl#ResearchGroup')).
subClassOf('http://swat.cse.lehigh.edu/onto/univ-bench.owl#ResearchGroup','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Organization').
subClassOf('http://swat.cse.lehigh.edu/onto/univ-bench.owl#Software','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Publication').
subClassOf('http://swat.cse.lehigh.edu/onto/univ-bench.owl#Specification','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Publication').
subClassOf('http://swat.cse.lehigh.edu/onto/univ-bench.owl#SystemsStaff','http://swat.cse.lehigh.edu/onto/univ-bench.owl#AdministrativeStaff').
subClassOf('http://swat.cse.lehigh.edu/onto/univ-bench.owl#TechnicalReport','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Article').
subClassOf('http://swat.cse.lehigh.edu/onto/univ-bench.owl#UndergraduateStudent','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Student').
subClassOf('http://swat.cse.lehigh.edu/onto/univ-bench.owl#University','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Organization').
subClassOf('http://swat.cse.lehigh.edu/onto/univ-bench.owl#UnofficialPublication','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Publication').
subClassOf('http://swat.cse.lehigh.edu/onto/univ-bench.owl#VisitingProfessor','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Professor').
transitiveProperty('http://swat.cse.lehigh.edu/onto/univ-bench.owl#subOrganizationOf').
subPropertyOf('http://swat.cse.lehigh.edu/onto/univ-bench.owl#doctoralDegreeFrom','http://swat.cse.lehigh.edu/onto/univ-bench.owl#degreeFrom').
subPropertyOf('http://swat.cse.lehigh.edu/onto/univ-bench.owl#headOf','http://swat.cse.lehigh.edu/onto/univ-bench.owl#worksFor').
subPropertyOf('http://swat.cse.lehigh.edu/onto/univ-bench.owl#mastersDegreeFrom','http://swat.cse.lehigh.edu/onto/univ-bench.owl#degreeFrom').
subPropertyOf('http://swat.cse.lehigh.edu/onto/univ-bench.owl#undergraduateDegreeFrom','http://swat.cse.lehigh.edu/onto/univ-bench.owl#degreeFrom').
subPropertyOf('http://swat.cse.lehigh.edu/onto/univ-bench.owl#worksFor','http://swat.cse.lehigh.edu/onto/univ-bench.owl#memberOf').
propertyDomain('http://swat.cse.lehigh.edu/onto/univ-bench.owl#advisor','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Person').
propertyDomain('http://swat.cse.lehigh.edu/onto/univ-bench.owl#affiliateOf','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Organization').
propertyDomain('http://swat.cse.lehigh.edu/onto/univ-bench.owl#affiliatedOrganizationOf','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Organization').
propertyDomain('http://swat.cse.lehigh.edu/onto/univ-bench.owl#degreeFrom','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Person').
propertyDomain('http://swat.cse.lehigh.edu/onto/univ-bench.owl#doctoralDegreeFrom','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Person').
propertyDomain('http://swat.cse.lehigh.edu/onto/univ-bench.owl#hasAlumnus','http://swat.cse.lehigh.edu/onto/univ-bench.owl#University').
propertyDomain('http://swat.cse.lehigh.edu/onto/univ-bench.owl#listedCourse','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Schedule').
propertyDomain('http://swat.cse.lehigh.edu/onto/univ-bench.owl#mastersDegreeFrom','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Person').
propertyDomain('http://swat.cse.lehigh.edu/onto/univ-bench.owl#member','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Organization').
propertyDomain('http://swat.cse.lehigh.edu/onto/univ-bench.owl#orgPublication','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Organization').
propertyDomain('http://swat.cse.lehigh.edu/onto/univ-bench.owl#publicationAuthor','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Publication').
propertyDomain('http://swat.cse.lehigh.edu/onto/univ-bench.owl#publicationDate','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Publication').
propertyDomain('http://swat.cse.lehigh.edu/onto/univ-bench.owl#publicationResearch','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Publication').
propertyDomain('http://swat.cse.lehigh.edu/onto/univ-bench.owl#researchProject','http://swat.cse.lehigh.edu/onto/univ-bench.owl#ResearchGroup').
propertyDomain('http://swat.cse.lehigh.edu/onto/univ-bench.owl#softwareDocumentation','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Software').
propertyDomain('http://swat.cse.lehigh.edu/onto/univ-bench.owl#softwareVersion','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Software').
propertyDomain('http://swat.cse.lehigh.edu/onto/univ-bench.owl#subOrganizationOf','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Organization').
propertyDomain('http://swat.cse.lehigh.edu/onto/univ-bench.owl#teacherOf','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Faculty').
propertyDomain('http://swat.cse.lehigh.edu/onto/univ-bench.owl#teachingAssistantOf','http://swat.cse.lehigh.edu/onto/univ-bench.owl#TeachingAssistant').
propertyDomain('http://swat.cse.lehigh.edu/onto/univ-bench.owl#tenured','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Professor').
propertyDomain('http://swat.cse.lehigh.edu/onto/univ-bench.owl#undergraduateDegreeFrom','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Person').
propertyDomain('http://swat.cse.lehigh.edu/onto/univ-bench.owl#age','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Person').
propertyDomain('http://swat.cse.lehigh.edu/onto/univ-bench.owl#emailAddress','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Person').
propertyDomain('http://swat.cse.lehigh.edu/onto/univ-bench.owl#telephone','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Person').
propertyDomain('http://swat.cse.lehigh.edu/onto/univ-bench.owl#title','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Person').
propertyRange('http://swat.cse.lehigh.edu/onto/univ-bench.owl#advisor','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Professor').
propertyRange('http://swat.cse.lehigh.edu/onto/univ-bench.owl#affiliateOf','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Person').
propertyRange('http://swat.cse.lehigh.edu/onto/univ-bench.owl#affiliatedOrganizationOf','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Organization').
propertyRange('http://swat.cse.lehigh.edu/onto/univ-bench.owl#degreeFrom','http://swat.cse.lehigh.edu/onto/univ-bench.owl#University').
propertyRange('http://swat.cse.lehigh.edu/onto/univ-bench.owl#doctoralDegreeFrom','http://swat.cse.lehigh.edu/onto/univ-bench.owl#University').
propertyRange('http://swat.cse.lehigh.edu/onto/univ-bench.owl#hasAlumnus','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Person').
propertyRange('http://swat.cse.lehigh.edu/onto/univ-bench.owl#listedCourse','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Course').
propertyRange('http://swat.cse.lehigh.edu/onto/univ-bench.owl#mastersDegreeFrom','http://swat.cse.lehigh.edu/onto/univ-bench.owl#University').
propertyRange('http://swat.cse.lehigh.edu/onto/univ-bench.owl#member','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Person').
propertyRange('http://swat.cse.lehigh.edu/onto/univ-bench.owl#orgPublication','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Publication').
propertyRange('http://swat.cse.lehigh.edu/onto/univ-bench.owl#publicationAuthor','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Person').
propertyRange('http://swat.cse.lehigh.edu/onto/univ-bench.owl#publicationResearch','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Research').
propertyRange('http://swat.cse.lehigh.edu/onto/univ-bench.owl#researchProject','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Research').
propertyRange('http://swat.cse.lehigh.edu/onto/univ-bench.owl#softwareDocumentation','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Publication').
propertyRange('http://swat.cse.lehigh.edu/onto/univ-bench.owl#subOrganizationOf','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Organization').
propertyRange('http://swat.cse.lehigh.edu/onto/univ-bench.owl#teacherOf','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Course').
propertyRange('http://swat.cse.lehigh.edu/onto/univ-bench.owl#teachingAssistantOf','http://swat.cse.lehigh.edu/onto/univ-bench.owl#Course').
propertyRange('http://swat.cse.lehigh.edu/onto/univ-bench.owl#undergraduateDegreeFrom','http://swat.cse.lehigh.edu/onto/univ-bench.owl#University').
inverseProperties('http://swat.cse.lehigh.edu/onto/univ-bench.owl#degreeFrom','http://swat.cse.lehigh.edu/onto/univ-bench.owl#hasAlumnus').
inverseProperties('http://swat.cse.lehigh.edu/onto/univ-bench.owl#memberOf','http://swat.cse.lehigh.edu/onto/univ-bench.owl#member').
propertyAssertion('http://swat.cse.lehigh.edu/onto/univ-bench.owl#headOf','http://swat.cse.lehigh.edu/onto/univ-bench.owl#PersonA','http://swat.cse.lehigh.edu/onto/univ-bench.owl#DepA').
classAssertion('http://swat.cse.lehigh.edu/onto/univ-bench.owl#Department','http://swat.cse.lehigh.edu/onto/univ-bench.owl#DepA').
classAssertion('http://swat.cse.lehigh.edu/onto/univ-bench.owl#Person','http://swat.cse.lehigh.edu/onto/univ-bench.owl#PersonA').
classAssertion('http://swat.cse.lehigh.edu/onto/univ-bench.owl#Chair','http://swat.cse.lehigh.edu/onto/univ-bench.owl#chairA').
namedIndividual('http://swat.cse.lehigh.edu/onto/univ-bench.owl#DepA').
namedIndividual('http://swat.cse.lehigh.edu/onto/univ-bench.owl#PersonA').
namedIndividual('http://swat.cse.lehigh.edu/onto/univ-bench.owl#chairA').
objectProperty('http://swat.cse.lehigh.edu/onto/univ-bench.owl#advisor').
objectProperty('http://swat.cse.lehigh.edu/onto/univ-bench.owl#affiliateOf').
objectProperty('http://swat.cse.lehigh.edu/onto/univ-bench.owl#affiliatedOrganizationOf').
objectProperty('http://swat.cse.lehigh.edu/onto/univ-bench.owl#degreeFrom').
objectProperty('http://swat.cse.lehigh.edu/onto/univ-bench.owl#doctoralDegreeFrom').
objectProperty('http://swat.cse.lehigh.edu/onto/univ-bench.owl#hasAlumnus').
objectProperty('http://swat.cse.lehigh.edu/onto/univ-bench.owl#headOf').
objectProperty('http://swat.cse.lehigh.edu/onto/univ-bench.owl#listedCourse').
objectProperty('http://swat.cse.lehigh.edu/onto/univ-bench.owl#mastersDegreeFrom').
objectProperty('http://swat.cse.lehigh.edu/onto/univ-bench.owl#member').
objectProperty('http://swat.cse.lehigh.edu/onto/univ-bench.owl#memberOf').
objectProperty('http://swat.cse.lehigh.edu/onto/univ-bench.owl#orgPublication').
objectProperty('http://swat.cse.lehigh.edu/onto/univ-bench.owl#publicationAuthor').
objectProperty('http://swat.cse.lehigh.edu/onto/univ-bench.owl#publicationDate').
objectProperty('http://swat.cse.lehigh.edu/onto/univ-bench.owl#publicationResearch').
objectProperty('http://swat.cse.lehigh.edu/onto/univ-bench.owl#researchProject').
objectProperty('http://swat.cse.lehigh.edu/onto/univ-bench.owl#softwareDocumentation').
objectProperty('http://swat.cse.lehigh.edu/onto/univ-bench.owl#softwareVersion').
objectProperty('http://swat.cse.lehigh.edu/onto/univ-bench.owl#subOrganizationOf').
objectProperty('http://swat.cse.lehigh.edu/onto/univ-bench.owl#takesCourse').
objectProperty('http://swat.cse.lehigh.edu/onto/univ-bench.owl#teacherOf').
objectProperty('http://swat.cse.lehigh.edu/onto/univ-bench.owl#teachingAssistantOf').
objectProperty('http://swat.cse.lehigh.edu/onto/univ-bench.owl#tenured').
objectProperty('http://swat.cse.lehigh.edu/onto/univ-bench.owl#undergraduateDegreeFrom').
objectProperty('http://swat.cse.lehigh.edu/onto/univ-bench.owl#worksFor').
dataProperty('http://swat.cse.lehigh.edu/onto/univ-bench.owl#age').
dataProperty('http://swat.cse.lehigh.edu/onto/univ-bench.owl#emailAddress').
dataProperty('http://swat.cse.lehigh.edu/onto/univ-bench.owl#name').
dataProperty('http://swat.cse.lehigh.edu/onto/univ-bench.owl#officeNumber').
dataProperty('http://swat.cse.lehigh.edu/onto/univ-bench.owl#researchInterest').
dataProperty('http://swat.cse.lehigh.edu/onto/univ-bench.owl#telephone').
dataProperty('http://swat.cse.lehigh.edu/onto/univ-bench.owl#title').
class('http://swat.cse.lehigh.edu/onto/univ-bench.owl#AdministrativeStaff').
class('http://swat.cse.lehigh.edu/onto/univ-bench.owl#Article').
class('http://swat.cse.lehigh.edu/onto/univ-bench.owl#AssistantProfessor').
class('http://swat.cse.lehigh.edu/onto/univ-bench.owl#AssociateProfessor').
class('http://swat.cse.lehigh.edu/onto/univ-bench.owl#Book').
class('http://swat.cse.lehigh.edu/onto/univ-bench.owl#Chair').
class('http://swat.cse.lehigh.edu/onto/univ-bench.owl#ClericalStaff').
class('http://swat.cse.lehigh.edu/onto/univ-bench.owl#College').
class('http://swat.cse.lehigh.edu/onto/univ-bench.owl#ConferencePaper').
class('http://swat.cse.lehigh.edu/onto/univ-bench.owl#Course').
class('http://swat.cse.lehigh.edu/onto/univ-bench.owl#Dean').
class('http://swat.cse.lehigh.edu/onto/univ-bench.owl#Department').
class('http://swat.cse.lehigh.edu/onto/univ-bench.owl#Director').
class('http://swat.cse.lehigh.edu/onto/univ-bench.owl#Employee').
class('http://swat.cse.lehigh.edu/onto/univ-bench.owl#Faculty').
class('http://swat.cse.lehigh.edu/onto/univ-bench.owl#FullProfessor').
class('http://swat.cse.lehigh.edu/onto/univ-bench.owl#GraduateCourse').
class('http://swat.cse.lehigh.edu/onto/univ-bench.owl#GraduateStudent').
class('http://swat.cse.lehigh.edu/onto/univ-bench.owl#Institute').
class('http://swat.cse.lehigh.edu/onto/univ-bench.owl#JournalArticle').
class('http://swat.cse.lehigh.edu/onto/univ-bench.owl#Lecturer').
class('http://swat.cse.lehigh.edu/onto/univ-bench.owl#Manual').
class('http://swat.cse.lehigh.edu/onto/univ-bench.owl#Organization').
class('http://swat.cse.lehigh.edu/onto/univ-bench.owl#Person').
class('http://swat.cse.lehigh.edu/onto/univ-bench.owl#PostDoc').
class('http://swat.cse.lehigh.edu/onto/univ-bench.owl#Professor').
class('http://swat.cse.lehigh.edu/onto/univ-bench.owl#Program').
class('http://swat.cse.lehigh.edu/onto/univ-bench.owl#Publication').
class('http://swat.cse.lehigh.edu/onto/univ-bench.owl#Research').
class('http://swat.cse.lehigh.edu/onto/univ-bench.owl#ResearchAssistant').
class('http://swat.cse.lehigh.edu/onto/univ-bench.owl#ResearchGroup').
class('http://swat.cse.lehigh.edu/onto/univ-bench.owl#Schedule').
class('http://swat.cse.lehigh.edu/onto/univ-bench.owl#Software').
class('http://swat.cse.lehigh.edu/onto/univ-bench.owl#Specification').
class('http://swat.cse.lehigh.edu/onto/univ-bench.owl#Student').
class('http://swat.cse.lehigh.edu/onto/univ-bench.owl#SystemsStaff').
class('http://swat.cse.lehigh.edu/onto/univ-bench.owl#TeachingAssistant').
class('http://swat.cse.lehigh.edu/onto/univ-bench.owl#TechnicalReport').
class('http://swat.cse.lehigh.edu/onto/univ-bench.owl#UndergraduateStudent').
class('http://swat.cse.lehigh.edu/onto/univ-bench.owl#University').
class('http://swat.cse.lehigh.edu/onto/univ-bench.owl#UnofficialPublication').
class('http://swat.cse.lehigh.edu/onto/univ-bench.owl#VisitingProfessor').
class('http://swat.cse.lehigh.edu/onto/univ-bench.owl#Work').
