(DEFINE (PROBLEM GRIPPER4)
   (:DOMAIN GRIPPER-TYPED)
   (:OBJECTS ROOMA ROOMB - ROOM
             BALL1 BALL2 BALL3 BALL4 - BALL)
   (:INIT (AT-ROBBY ROOMA)
          (FREE LEFT)
          (FREE RIGHT)
          (AT BALL1 ROOMA)
          (AT BALL2 ROOMA)
          (AT BALL3 ROOMA)
          (AT BALL4 ROOMA))
   (:GOAL (AND (AT BALL1 ROOMB)
               (AT BALL2 ROOMB)
               (AT BALL3 ROOMB)
               (AT BALL4 ROOMB))))