/*
get_forms_with_atom(A,TNs)
keep_forms_with_atom(TNsIn,A,TNsOut)
remove_forms_with_atom(TNsIn,A,TNsOut)
get_forms_with_structure(S,TNs)
keep_forms_with_structure(TNsIn,S,TNsOut)
remove_forms_with_structure(TNsIn,S,TNsOut)
return_forms(TNs)
return_forms_to_html(TNs)
*/
