#!/usr/bin/env swipl

:- consult('abc_01.pfc').


:- consult('bc_01a.pfc').
:- consult('bc_01b.pfc').
:- consult('bc_01c.pfc').
:- consult('bc_01d.pfc').
:- consult('bc_01.pfc').
:- consult('bc_02.pfc').
:- consult('df_01.pfc').
:- consult('df_02.pfc').
:- consult('df_03.pfc').
:- consult('df_04.pfc').
:- consult('df_05.pfc').
:- consult('df_06.pfc').
:- consult('df_07.pfc').
:- consult('dl_01.pfc').
:- consult('dmost_01.pfc').
:- consult('dmost_02.pfc').
:- consult('fc_01.pfc').
:- consult('fc_01r.pfc').
:- consult('fc_01s.pfc').
:- consult('fc_02.pfc').
:- consult('fc_03a.pfc').
:- consult('fc_03.pfc').
:- consult('fc_04.pfc').
:- consult('fc_04_user.pfc').
:- consult('fc_05a.pfc').
:- consult('fc_05.pfc').
:- consult('fc_06.pfc').
:- consult('fc_07.pfc').
:- consult('fc_08.pfc').
:- consult('fc_09.pfc').
:- consult('fc_10.pfc').
:- consult('if_missing_01a.pfc').
:- consult('if_missing_01b.pfc').
:- consult('if_missing_01c.pfc').
:- consult('if_missing_01.pfc').
:- consult('if_missing_02.pfc').
:- consult('if_missing_03.pfc').
:- consult('if_missing_04.pfc').
:- consult('if_missing_05.pfc').
:- consult('load_time_01.pfc').
:- consult('mdefault_01a.pfc').
:- consult('mdefault_01b.pfc').
:- consult('mpred_pfc_test_01.pl').
:- consult('nd_01.pl').
:- consult('nd_02a.pfc').
:- consult('nd_02.pfc').
:- consult('nd_09_rule.pfc').
:- consult('nd_cut_01.pfc').
:- consult('neg_01.pfc').
:- consult('never_retract_01b.pfc').
:- consult('pl_01.pfc').
:- consult('ppdb_01.pl').
:- consult('reset_db_01.pfc.pl').
:- consult('reset_db_01_user.pfc.pl').
:- consult('retract_01a.pfc').
:- consult('retract_01.pfc').
:- consult('shift_01.pl').
:- consult('shift_02.pl').
:- consult('sv_default_01.pfc').
:- consult('sv_in_arg_01d.pfc').
:- consult('sv_in_arg_01.pfc').
:- consult('tms_01.pfc').
:- consult('undo_01a.pfc').
:- consult('undo_01b.pfc').
:- consult('undo_01.pfc').
:- consult('undo_02a.pfc').
:- consult('update_list_01.pfc').
:- consult('update_number_01.pfc').
:- consult('verbatums_01.pfc').

end_of_file.

:- consult('reset_db_02.pfc.pl').


% Test that need a fresh VM to be fair

%:- consult('file_01.pfc').
%:- consult('file_02.pfc').
%:- consult('file_03.pfc').
:- consult('hard_mt_04a.pfc').
%:- consult('hard_mt_f01.pfc').
:- consult('hybrid_01a.pfc').
:- consult('hybrid_01.pfc').
:- consult('hybrid_02a.pfc').
:- consult('hybrid_02.pfc').
:- consult('hybrid_03a.pfc').
:- consult('hybrid_03.pfc').
:- consult('hybrid_04a.pfc').
:- consult('hybrid_04.pfc').
:- consult('hybrid_05a.pfc').
:- consult('hybrid_05.pfc').
:- consult('attvar_01.pl').
:- consult('attvar_02_in_user.pfc').
:- consult('attvar_02.pfc').
:- consult('attvar_03.pfc').
:- consult('attvar_04.pl').
:- consult('attvar_05.pfc').
:- consult('attvar_06.pfc').
:- consult('attvar_07.pfc').
:- consult('attvar_08a.pfc').
:- consult('attvar_08b.pfc').
:- consult('attvar_08.pfc').
:- consult('attvar_09.pfc').
:- consult('attvar_10.pfc').

:- consult('birds_01a.pfc').
:- consult('birds_01b_01_in_user.pfc').
:- consult('birds_01b_in_user_iza.pfc').
:- consult('birds_01b_in_user.pfc').
:- consult('birds_01b_not_in_user.pfc').
:- consult('birds_01b.pfc').
:- consult('birds_01c.pfc').
:- consult('birds_01d.pfc').
:- consult('circle_01a.pfc').
:- consult('circle_01b.pfc').
:- consult('circle_01c.pfc').
:- consult('circle_01d.pfc').
:- consult('clause_fwd_01a.pfc.pl').
:- consult('clause_fwd_01b.pfc.pl').
:- consult('clause_fwd_01c.pfc.pl').
:- consult('clause_fwd_02.pfc.pl').
:- consult('conan_01.pfc.pl').
:- consult('retry_inheritance_01.pfc').
:- consult('retry_inheritance_02.pfc').
:- consult('retry_inheritance_03.pfc').
:- consult('retry_inheritance_04.pfc').
:- consult('retry_inheritance_05.pfc').
:- consult('retry_inheritance_06.pfc').
:- consult('retry_inheritance_07.pfc').
:- consult('retry_inheritance_08.pfc').
:- consult('retry_inheritance_09.pfc').
:- consult('retry_undefined_01.pfc').
:- consult('retry_undefined_02.pfc').
:- consult('retry_undefined_03.pfc').
:- consult('retry_undefined_04.pfc').
:- consult('retry_undefined_05.pfc').
:- consult('retry_undefined_06.pfc').
:- consult('retry_undefined_07.pfc').
:- consult('retry_undefined_08.pfc').
:- consult('retry_undefined_09.pfc').
:- consult('mt_01a_0a.pl').
:- consult('mt_01a.pl').
:- consult('mt_01b.pl').
:- consult('mt_01c_0a.pl').
:- consult('mt_01c_0b.pl').
:- consult('mt_01c.pl').
:- consult('mt_01d.pl').
:- consult('mt_01e.pl').
:- consult('mt_01.pl').
:- consult('mt_02a_0c.pfc').
:- consult('mt_02.pl').
:- consult('mt_03.pl').
:- consult('mt_04.pl').
:- consult('mt_05.pl').
:- consult('mt_06_a.pfc').
:- consult('mt_06.pl').
:- consult('mt_07a.pl').
:- consult('mt_07.pl').
:- consult('mt_09.pl').
:- consult('mpred_pfc_test_02.pl').
:- consult('mpred_pfc_test_03.pl').
:- consult('mpred_pfc_test_04.pl').
:- consult('mdefault_01c.pfc').
:- consult('mdefault_01d.pfc').
:- consult('mdefault_01e.pfc').
:- consult('mdefault_01.pfc').
:- consult('list_01a.pfc').
:- consult('list_01.pfc').
:- consult('list_02a.pfc').
:- consult('list_02.pfc').
:- consult('list_03a.pfc').
:- consult('list_03.pfc').
:- consult('predmt_01a.pl').
:- consult('predmt_01b.pl').
:- consult('predmt_01.pfc').
:- consult('verbatums_02.pfc').
:- consult('verbatums_03.pfc').
:- consult('verbatums_04.pfc').
:- consult('verbatums_05.pfc').
:- consult('nd_03.pfc').
:- consult('nd_04.pfc').
:- consult('nd_05.pfc').
:- consult('nd_06.pfc').
:- consult('nd_07.pfc').
:- consult('nd_08.pfc').

