(define (problem woodshop-adl-2)
    (:domain woodshop-adl)
  (:objects o green plain three-eighths smooth)
  (:init  (physobj o) (not (in-spray-hood o)) (shape O round)
	  (color green) (color plain) 
	  (painted O plain) (surface O ROUGH))
  (:goal   (and (has-hole O three-eighths)
		(painted O GREEN)
		(surface O SMOOTH)
		(shape O round)
		(not (dusty O)) (boxed O))))