(define (problem woodshop-adl-1)
    (:domain woodshop-adl)
  (:objects o blob green plain three-eighths smooth square)
  (:init  (physobj o) (not (in-spray-hood o)) (shape O BLOB)
	  (color green) (color plain)
	  (painted O plain)
	  (surface O ROUGH))
  (:goal   (and (has-hole O three-eighths)
		(painted O GREEN)
		(surface O SMOOTH)
		(shape O SQUARE)
		(not (dusty O)) (boxed O))))