'use strict';var fh=function(a,b,c){a.timeOfStartCall=(new Date).getTime();var d=c||Ha,e=d.document,f=a.nonce||Ka(d);f&&!a.nonce&&(a.nonce=f);if("help"==a.flow){var g=Ma("document.location.href",d);!a.helpCenterContext&&g&&(a.helpCenterContext=g.substring(0,1200));g=!0;if(b&&JSON&&JSON.stringify){var h=JSON.stringify(b);(g=1200>=h.length)&&(a.psdJson=h)}g||(b={invalidPsd:!0})}b=[a,b,c];d.GOOGLE_FEEDBACK_START_ARGUMENTS=b;c=a.serverUri||"//www.google.com/tools/feedback";if(g=d.GOOGLE_FEEDBACK_START)g.apply(d,b);
else{d=c+"/load.js?";for(var n in a)b=a[n],null==b||Sa(b)||(d+=encodeURIComponent(n)+"="+encodeURIComponent(b)+"&");a=dg(Uf(e),"SCRIPT");f&&a.setAttribute("nonce",f);Xe(a,fg(d));e.body.appendChild(a)}};w("userfeedback.api.startFeedback",fh);var gh=function(){this.j=this.h=this.u=this.modelName=this.l=this.g=this.hd="";this.C=this.o=this.m=!1};var hh=chrome.i18n.getMessage("4163185390680253103"),ih=chrome.i18n.getMessage("492097680647953484"),jh=chrome.i18n.getMessage("2575016469622936324"),lh=chrome.i18n.getMessage("128276876460319075"),mh=chrome.i18n.getMessage("3326722026796849289"),nh=chrome.i18n.getMessage("1018984561488520517"),oh=chrome.i18n.getMessage("8205999658352447129"),ph=chrome.i18n.getMessage("5723583529370342957"),qh=chrome.i18n.getMessage("1550904064710828958"),rh=chrome.i18n.getMessage("5014364904504073524"),sh=chrome.i18n.getMessage("2194670894476780934"),
th=chrome.i18n.getMessage("6614468912728530636"),uh=chrome.i18n.getMessage("5910595154486533449"),vh=chrome.i18n.getMessage("5363086287710390513"),wh=chrome.i18n.getMessage("244647017322945605"),xh=chrome.i18n.getMessage("5375576275991472719"),yh=chrome.i18n.getMessage("4592127349908255218"),zh=chrome.i18n.getMessage("843316808366399491"),Ah=chrome.i18n.getMessage("5699813974548050528"),Bh=chrome.i18n.getMessage("8515148417333877999"),Ch=chrome.i18n.getMessage("1636686747687494376"),Dh=chrome.i18n.getMessage("4148300086676792937"),
Eh=chrome.i18n.getMessage("3219866268410307919"),Fh=chrome.i18n.getMessage("9211708838274008657"),Gh=chrome.i18n.getMessage("8706273405040403641"),Hh=chrome.i18n.getMessage("4756056595565370923"),Ih=chrome.i18n.getMessage("7876724262035435114"),Jh=chrome.i18n.getMessage("5485620192329479690"),Kh=chrome.i18n.getMessage("6963873398546068901"),Lh=chrome.i18n.getMessage("3567591856726172993"),Mh=chrome.i18n.getMessage("3239956785410157548");/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var Nh={"* ARIA-CHECKED":!0,"* ARIA-COLCOUNT":!0,"* ARIA-COLINDEX":!0,"* ARIA-CONTROLS":!0,"* ARIA-DESCRIBEDBY":!0,"* ARIA-DISABLED":!0,"* ARIA-EXPANDED":!0,"* ARIA-GOOG-EDITABLE":!0,"* ARIA-HASPOPUP":!0,"* ARIA-HIDDEN":!0,"* ARIA-LABEL":!0,"* ARIA-LABELLEDBY":!0,"* ARIA-MULTILINE":!0,"* ARIA-MULTISELECTABLE":!0,"* ARIA-ORIENTATION":!0,"* ARIA-PLACEHOLDER":!0,"* ARIA-READONLY":!0,"* ARIA-REQUIRED":!0,"* ARIA-ROLEDESCRIPTION":!0,"* ARIA-ROWCOUNT":!0,"* ARIA-ROWINDEX":!0,"* ARIA-SELECTED":!0,"* ABBR":!0,
"* ACCEPT":!0,"* ACCESSKEY":!0,"* ALIGN":!0,"* ALT":!0,"* AUTOCOMPLETE":!0,"* AXIS":!0,"* BGCOLOR":!0,"* BORDER":!0,"* CELLPADDING":!0,"* CELLSPACING":!0,"* CHAROFF":!0,"* CHAR":!0,"* CHECKED":!0,"* CLEAR":!0,"* COLOR":!0,"* COLSPAN":!0,"* COLS":!0,"* COMPACT":!0,"* COORDS":!0,"* DATETIME":!0,"* DIR":!0,"* DISABLED":!0,"* ENCTYPE":!0,"* FACE":!0,"* FRAME":!0,"* HEIGHT":!0,"* HREFLANG":!0,"* HSPACE":!0,"* ISMAP":!0,"* LABEL":!0,"* LANG":!0,"* MAX":!0,"* MAXLENGTH":!0,"* METHOD":!0,"* MULTIPLE":!0,
"* NOHREF":!0,"* NOSHADE":!0,"* NOWRAP":!0,"* OPEN":!0,"* READONLY":!0,"* REQUIRED":!0,"* REL":!0,"* REV":!0,"* ROLE":!0,"* ROWSPAN":!0,"* ROWS":!0,"* RULES":!0,"* SCOPE":!0,"* SELECTED":!0,"* SHAPE":!0,"* SIZE":!0,"* SPAN":!0,"* START":!0,"* SUMMARY":!0,"* TABINDEX":!0,"* TITLE":!0,"* TYPE":!0,"* VALIGN":!0,"* VALUE":!0,"* VSPACE":!0,"* WIDTH":!0},Oh={"* USEMAP":!0,"* ACTION":!0,"* CITE":!0,"* HREF":!0,"* LONGDESC":!0,"* SRC":!0,"LINK HREF":!0,"* FOR":!0,"* HEADERS":!0,"* NAME":!0,"A TARGET":!0,
"* CLASS":!0,"* ID":!0,"* STYLE":!0};var Ph={};
function Qh(a){if(nf&&!Kf(9))return[0,0,0,0];var b=Ph.hasOwnProperty(a)?Ph[a]:null;if(b)return b;65536<Object.keys(Ph).length&&(Ph={});var c=[0,0,0,0];b=Rh(a,/\\[0-9A-Fa-f]{6}\s?/g);b=Rh(b,/\\[0-9A-Fa-f]{1,5}\s/g);b=Rh(b,/\\./g);b=b.replace(/:not\(([^\)]*)\)/g,"     $1 ");b=b.replace(/{[^]*/gm,"");b=Sh(b,c,/(\[[^\]]+\])/g,2);b=Sh(b,c,/(#[^\#\s\+>~\.\[:]+)/g,1);b=Sh(b,c,/(\.[^\s\+>~\.\[:]+)/g,2);b=Sh(b,c,/(::[^\s\+>~\.\[:]+|:first-line|:first-letter|:before|:after)/gi,3);b=Sh(b,c,/(:[\w-]+\([^\)]*\))/gi,2);
b=Sh(b,c,/(:[^\s\+>~\.\[:]+)/g,2);b=b.replace(/[\*\s\+>~]/g," ");b=b.replace(/[#\.]/g," ");Sh(b,c,/([^\s\+>~\.\[:]+)/g,3);b=c;return Ph[a]=b}function Sh(a,b,c,d){return a.replace(c,function(e){b[d]+=1;return Array(e.length+1).join(" ")})}function Rh(a,b){return a.replace(b,function(c){return Array(c.length+1).join("A")})};var Th={rgb:!0,rgba:!0,alpha:!0,rect:!0,image:!0,"linear-gradient":!0,"radial-gradient":!0,"repeating-linear-gradient":!0,"repeating-radial-gradient":!0,"cubic-bezier":!0,matrix:!0,perspective:!0,rotate:!0,rotate3d:!0,rotatex:!0,rotatey:!0,steps:!0,rotatez:!0,scale:!0,scale3d:!0,scalex:!0,scaley:!0,scalez:!0,skew:!0,skewx:!0,skewy:!0,translate:!0,translate3d:!0,translatex:!0,translatey:!0,translatez:!0},Uh=/[\n\f\r"'()*<>]/g,Vh={"\n":"%0a","\f":"%0c","\r":"%0d",'"':"%22","'":"%27","(":"%28",")":"%29",
"*":"%2a","<":"%3c",">":"%3e"};function Wh(a){return Vh[a]}
var Xh=function(a,b,c){b=Tc(b);if(""==b)return null;if(0==Uc("url(",b.substr(0,4))){if(!b.endsWith(")")||1<(b?b.split("(").length-1:0)||1<(b?b.split(")").length-1:0)||!c)a=null;else{a:{b=b.substring(4,b.length-1);for(var d=0;2>d;d++){var e="\"'".charAt(d);if(b.charAt(0)==e&&b.charAt(b.length-1)==e){b=b.substring(1,b.length-1);break a}}}a=c?(a=c(b,a))&&"about:invalid#zClosurez"!=pe(a)?'url("'+pe(a).replace(Uh,Wh)+'")':null:null}return a}if(0<b.indexOf("(")){if(/"|'/.test(b))return null;for(a=/([\-\w]+)\(/g;c=
a.exec(b);)if(!(c[1].toLowerCase()in Th))return null}return b};function Yh(a,b){a=Ha[a];return a&&a.prototype?(b=Object.getOwnPropertyDescriptor(a.prototype,b))&&b.get||null:null}function Zh(a,b){return(a=Ha[a])&&a.prototype&&a.prototype[b]||null}
var $h=Yh("Element","attributes")||Yh("Node","attributes"),ai=Zh("Element","hasAttribute"),bi=Zh("Element","getAttribute"),ci=Zh("Element","setAttribute"),di=Zh("Element","removeAttribute"),ei=Zh("Element","getElementsByTagName"),fi=Zh("Element","matches")||Zh("Element","msMatchesSelector"),gi=Yh("Node","nodeName"),hi=Yh("Node","nodeType"),ii=Yh("Node","parentNode"),ji=Yh("HTMLElement","style")||Yh("Element","style"),ki=Yh("HTMLStyleElement","sheet"),li=Zh("CSSStyleDeclaration","getPropertyValue"),
mi=Zh("CSSStyleDeclaration","setProperty");function ni(a,b,c,d){if(a)return a.apply(b);a=b[c];if(!d(a))throw Error("Clobbering detected");return a}function oi(a,b,c,d){if(a)return a.apply(b,d);if(nf&&10>document.documentMode){if(!b[c].call)throw Error("IE Clobbering detected");}else if("function"!=typeof b[c])throw Error("Clobbering detected");return b[c].apply(b,d)}function pi(a){return ni($h,a,"attributes",function(b){return b instanceof NamedNodeMap})}
function qi(a,b,c){try{oi(ci,a,"setAttribute",[b,c])}catch(d){if(-1==d.message.indexOf("A security problem occurred"))throw d;}}function ri(a){si(a);return ni(ji,a,"style",function(b){return b instanceof CSSStyleDeclaration})}function si(a){if(!(a instanceof HTMLElement))throw Error("Not an HTMLElement");}function ti(a){si(a);return ni(ki,a,"sheet",function(b){return b instanceof CSSStyleSheet})}function ui(a){return ni(gi,a,"nodeName",function(b){return"string"==typeof b})}
function vi(a){return ni(hi,a,"nodeType",function(b){return"number"==typeof b})}function wi(a){return ni(ii,a,"parentNode",function(b){return!(b&&"string"==typeof b.name&&b.name&&"parentnode"==b.name.toLowerCase())})}function xi(a,b){return oi(li,a,a.getPropertyValue?"getPropertyValue":"getAttribute",[b])||""}function yi(a,b,c){oi(mi,a,a.setProperty?"setProperty":"setAttribute",[b,c])};var zi=nf&&10>document.documentMode?null:/\s*([^\s'",]+[^'",]*(('([^'\r\n\f\\]|\\[^])*')|("([^"\r\n\f\\]|\\[^])*")|[^'",])*)/g,Ai={"-webkit-border-horizontal-spacing":!0,"-webkit-border-vertical-spacing":!0},Ii=function(a,b,c){var d=[];a=Gi(yc(a.cssRules));$b(a,function(e){if(b&&!/[a-zA-Z][\w-:\.]*/.test(b))throw Error("Invalid container id");if(!(b&&nf&&10==document.documentMode&&/\\['"]/.test(e.selectorText))){var f=b?e.selectorText.replace(zi,"#"+b+" $1"):e.selectorText,g=d.push;e=Hi(e.style,c);
if(-1!=f.indexOf("<"))throw Error("Selector does not allow '<', got: "+f);var h=f.replace(/('|")((?!\1)[^\r\n\f\\]|\\[\s\S])*\1/g,"");if(!/^[-_a-zA-Z0-9#.:* ,>+~[\]()=^$|]+$/.test(h))throw Error("Selector allows only [-_a-zA-Z0-9#.:* ,>+~[\\]()=^$|] and strings, got: "+f);a:{for(var n={"(":")","[":"]"},p=[],r=0;r<h.length;r++){var y=h[r];if(n[y])p.push(n[y]);else if(td(n,y)&&p.pop()!=y){h=!1;break a}}h=0==p.length}if(!h)throw Error("() and [] in selector must be balanced, got: "+f);if(!(e instanceof
we)){h="";for(var A in e)if(Object.prototype.hasOwnProperty.call(e,A)){if(!/^[-_a-zA-Z0-9]+$/.test(A))throw Error("Name allows only [-_a-zA-Z0-9], got: "+A);n=e[A];null!=n&&(n=Array.isArray(n)?dc(n,Ae).join(" "):Ae(n),h+=A+":"+n+";")}e=h?new we(h,ve):ye}f=f+"{"+xe(e).replace(/</g,"\\3C ")+"}";g.call(d,new Ie(f,He))}});return Ke(d)},Gi=function(a){return cc(a,function(b){return b instanceof CSSStyleRule||b.type==CSSRule.STYLE_RULE})},Ki=function(a,b,c){a=Ji("<style>"+a+"</style>");return null==a||
null==a.sheet?Le:Ii(a.sheet,void 0!=b?b:null,c)},Ji=function(a){if(nf&&!Kf(10)||"function"!=typeof Ha.DOMParser)return null;a=Qe("<html><head></head><body>"+a+"</body></html>",null);return(new DOMParser).parseFromString(Oe(a),"text/html").body.children[0]},Hi=function(a,b){if(!a)return ye;var c=document.createElement("div").style,d=Li(a);$b(d,function(e){var f=sf&&e in Ai?e:e.replace(/^-(?:apple|css|epub|khtml|moz|mso?|o|rim|wap|webkit|xv)-(?=[a-z])/i,"");Qc(f,"--")||Qc(f,"var")||(e=xi(a,e),e=Xh(f,
e,b),null!=e&&yi(c,f,e))});return new we(c.cssText||"",ve)},Ni=function(a){var b=Array.from(oi(ei,a,"getElementsByTagName",["STYLE"])),c=Pc(b,function(e){return yc(ti(e).cssRules)});c=Gi(c);c.sort(function(e,f){e=Qh(e.selectorText);a:{f=Qh(f.selectorText);for(var g=Gc,h=Math.min(e.length,f.length),n=0;n<h;n++){var p=g(e[n],f[n]);if(0!=p){e=p;break a}}e=Gc(e.length,f.length)}return-e});a=document.createTreeWalker(a,NodeFilter.SHOW_ELEMENT,null,!1);for(var d;d=a.nextNode();)$b(c,function(e){oi(fi,d,
d.matches?"matches":"msMatchesSelector",[e.selectorText])&&e.style&&Mi(d,e.style)});$b(b,bg)},Mi=function(a,b){var c=Li(a.style),d=Li(b);$b(d,function(e){if(!(0<=c.indexOf(e))){var f=xi(b,e);yi(a.style,e,f)}})},Li=function(a){Ra(a)?a=yc(a):(a=rd(a),rc(a,"cssText"));return a};var Oi="undefined"!=typeof WeakMap&&-1!=WeakMap.toString().indexOf("[native code]"),Pi=0,Qi=function(){this.j=[];this.h=[];this.g="data-elementweakmap-index-"+Pi++};Qi.prototype.set=function(a,b){if(oi(ai,a,"hasAttribute",[this.g])){var c=parseInt(oi(bi,a,"getAttribute",[this.g])||null,10);this.h[c]=b}else c=this.h.push(b)-1,qi(a,this.g,c.toString()),this.j.push(a);return this};
Qi.prototype.get=function(a){if(oi(ai,a,"hasAttribute",[this.g]))return a=parseInt(oi(bi,a,"getAttribute",[this.g])||null,10),this.h[a]};Qi.prototype.clear=function(){this.j.forEach(function(a){oi(di,a,"removeAttribute",[this.g])},this);this.j=[];this.h=[]};var Ri=Wg("goog.html.sanitizer.SafeDomTreeProcessor"),Si=!nf||10<=Number(Nf),Ti=!nf||null==document.documentMode,Ui=function(){};var Vi={APPLET:!0,AUDIO:!0,BASE:!0,BGSOUND:!0,EMBED:!0,FORM:!0,IFRAME:!0,ISINDEX:!0,KEYGEN:!0,LAYER:!0,LINK:!0,META:!0,OBJECT:!0,SCRIPT:!0,SVG:!0,STYLE:!0,TEMPLATE:!0,VIDEO:!0};var Wi={A:!0,ABBR:!0,ACRONYM:!0,ADDRESS:!0,AREA:!0,ARTICLE:!0,ASIDE:!0,B:!0,BDI:!0,BDO:!0,BIG:!0,BLOCKQUOTE:!0,BR:!0,BUTTON:!0,CAPTION:!0,CENTER:!0,CITE:!0,CODE:!0,COL:!0,COLGROUP:!0,DATA:!0,DATALIST:!0,DD:!0,DEL:!0,DETAILS:!0,DFN:!0,DIALOG:!0,DIR:!0,DIV:!0,DL:!0,DT:!0,EM:!0,FIELDSET:!0,FIGCAPTION:!0,FIGURE:!0,FONT:!0,FOOTER:!0,FORM:!0,H1:!0,H2:!0,H3:!0,H4:!0,H5:!0,H6:!0,HEADER:!0,HGROUP:!0,HR:!0,I:!0,IMG:!0,INPUT:!0,INS:!0,KBD:!0,LABEL:!0,LEGEND:!0,LI:!0,MAIN:!0,MAP:!0,MARK:!0,MENU:!0,METER:!0,NAV:!0,
NOSCRIPT:!0,OL:!0,OPTGROUP:!0,OPTION:!0,OUTPUT:!0,P:!0,PRE:!0,PROGRESS:!0,Q:!0,S:!0,SAMP:!0,SECTION:!0,SELECT:!0,SMALL:!0,SOURCE:!0,SPAN:!0,STRIKE:!0,STRONG:!0,STYLE:!0,SUB:!0,SUMMARY:!0,SUP:!0,TABLE:!0,TBODY:!0,TD:!0,TEXTAREA:!0,TFOOT:!0,TH:!0,THEAD:!0,TIME:!0,TR:!0,TT:!0,U:!0,UL:!0,VAR:!0,WBR:!0};var Xi={"ANNOTATION-XML":!0,"COLOR-PROFILE":!0,"FONT-FACE":!0,"FONT-FACE-SRC":!0,"FONT-FACE-URI":!0,"FONT-FACE-FORMAT":!0,"FONT-FACE-NAME":!0,"MISSING-GLYPH":!0},aj=function(a){a=a||new Yi;Zi(a);this.g=wd(a.g);this.m=wd(a.D);this.h=wd(a.F);this.u=a.C;$b(a.H,function(b){if(!Qc(b,"data-"))throw new Vb('Only "data-" attributes allowed, got: %s.',[b]);if(Qc(b,"data-sanitizer-"))throw new Vb('Attributes with "%s" prefix are not allowed, got: %s.',["data-sanitizer-",b]);this.g["* "+b.toUpperCase()]=$i},
this);$b(a.G,function(b){b=b.toUpperCase();if(-1==b.indexOf("-")||Xi[b])throw new Vb("Only valid custom element tag names allowed, got: %s.",[b]);this.h[b]=!0},this);this.C=a.j;this.l=a.u;this.j=null;this.o=a.o};x(aj,Ui);
var bj=function(a){return function(b,c){return(b=a(Tc(b),c))&&"about:invalid#zClosurez"!=pe(b)?pe(b):null}},Yi=function(){this.g={};$b([Nh,Oh],function(a){$b(rd(a),function(b){this.g[b]=$i},this)},this);this.h={};this.H=[];this.G=[];this.D=wd(Vi);this.F=wd(Wi);this.C=!1;this.O=ue;this.L=this.m=this.J=this.j=Kd;this.u=null;this.l=this.o=!1},cj=function(a,b){return function(c,d,e,f){c=a(c,d,e,f);return null==c?null:b(c,d,e,f)}},dj=function(a,b,c,d){a[c]&&!b[c]&&(a[c]=cj(a[c],d))};Yi.prototype.da=function(){return new aj(this)};
var Zi=function(a){if(a.l)throw Error("HtmlSanitizer.Builder.build() can only be used once.");dj(a.g,a.h,"* USEMAP",ej);var b=bj(a.O);$b(["* ACTION","* CITE","* HREF"],function(d){dj(this.g,this.h,d,b)},a);var c=bj(a.j);$b(["* LONGDESC","* SRC","LINK HREF"],function(d){dj(this.g,this.h,d,c)},a);$b(["* FOR","* HEADERS","* NAME"],function(d){dj(this.g,this.h,d,$a(fj,this.J))},a);dj(a.g,a.h,"A TARGET",$a(gj,["_blank","_self"]));dj(a.g,a.h,"* CLASS",$a(hj,a.m));dj(a.g,a.h,"* ID",$a(ij,a.m));dj(a.g,a.h,
"* STYLE",$a(a.L,c));a.l=!0},jj=function(a,b){a||(a="*");return(a+" "+b).toUpperCase()},$i=function(a){return Tc(a)},gj=function(a,b){b=Tc(b);return lc(a,b.toLowerCase())?b:null},ej=function(a){return(a=Tc(a))&&"#"==a.charAt(0)?a:null},fj=function(a,b,c){return a(Tc(b),c)},hj=function(a,b,c){b=b.split(/(?:\s+)/);for(var d=[],e=0;e<b.length;e++){var f=a(b[e],c);f&&d.push(f)}return 0==d.length?null:d.join(" ")},ij=function(a,b,c){return a(Tc(b),c)},kj=function(a,b){var c=b.data;(b=wi(b))&&"style"==
ui(b).toLowerCase()&&!("STYLE"in a.m)&&"STYLE"in a.h&&(c=Je(Ki(c,a.j,Za(function(d,e){return this.C(d,{oT:e})},a))));return document.createTextNode(c)},lj=function(a){var b=(new Yi).da();var c=!("STYLE"in b.m)&&"STYLE"in b.h;c="*"==b.l&&c?"sanitizer-"+af():b.l;b.j=c;if(Si){c=a;if(Si){a=$f(document,"SPAN");b.j&&"*"==b.l&&(a.id=b.j);b.o&&(c=Ji("<div>"+c+"</div>"),Ni(c),c=c.innerHTML);c=Qe(c,null);var d=document.createElement("template");if(Ti&&"content"in d)Ve(d,c),d=d.content;else{var e=document.implementation.createHTMLDocument("x");
d=e.body;Ve(e.body,c)}c=document.createTreeWalker(d,NodeFilter.SHOW_ELEMENT|NodeFilter.SHOW_TEXT,null,!1);for(d=Oi?new WeakMap:new Qi;e=c.nextNode();){c:{var f=b;var g=e;var h=vi(g);switch(h){case 3:g=kj(f,g);break c;case 1:h=g;1==vi(h)||Wb("Expected Node of type Element but got Node of type %s",vi(h));g=f;f=h;if("TEMPLATE"==ui(f).toUpperCase())g=null;else{h=ui(f).toUpperCase();if(h in g.m)var n=null;else g.h[h]?n=document.createElement(h):(n=$f(document,"SPAN"),g.u&&qi(n,"data-sanitizer-original-tag",
h.toLowerCase()));if(n){var p=n,r=pi(f);if(null!=r)for(var y=0;h=r[y];y++)if(h.specified){var A=g;var B=f,K=h,S=K.name;if(Qc(S,"data-sanitizer-"))A=null;else{var ja=ui(B);K=K.value;var gb={tagName:Tc(ja).toLowerCase(),attributeName:Tc(S).toLowerCase()},ec={tw:void 0};"style"==gb.attributeName&&(ec.tw=ri(B));B=jj(ja,S);B in A.g?(A=A.g[B],A=A(K,gb,ec)):(S=jj(null,S),S in A.g?(A=A.g[S],A=A(K,gb,ec)):A=null)}null!==A&&qi(p,h.name,A)}g=n}else g=null}break c;default:Zg(Ri,"Dropping unknown node type: "+
h),g=null}}if(g){if(1==vi(g)&&d.set(e,g),e=wi(e),f=!1,e)h=vi(e),n=ui(e).toLowerCase(),p=wi(e),11!=h||p?"body"==n&&p&&(h=wi(p))&&!wi(h)&&(f=!0):f=!0,h=null,f||!e?h=a:1==vi(e)&&(h=d.get(e)),h.content&&(h=h.content),h.appendChild(g)}else ag(e)}d.clear&&d.clear();b=a}else b=$f(document,"SPAN");0<pi(b).length&&(a=$f(document,"SPAN"),a.appendChild(b),b=a);b=(new XMLSerializer).serializeToString(b);b=b.slice(b.indexOf(">")+1,b.lastIndexOf("</"))}else b="";return Qe(b,null)};if("undefined"!=typeof angular){var mj=angular.module("chrome_18n",[]);chrome.runtime&&chrome.runtime.getManifest&&chrome.runtime.getManifest().default_locale&&mj.directive("angularMessage",function(){return{restrict:"E",replace:!0,controller:["$scope",function(a){var b=this;this.Rk=this.wh=null;a.dirForText=function(c){b.wh||(b.wh=chrome.i18n.getMessage("@@bidi_dir")||"ltr");b.Rk||(b.Rk=new bh("rtl"==b.wh));var d=b.Rk,e,f=e=0,g=!1;c=(c||"").split(ae);for(var h=0;h<c.length;h++){var n=c[h];Zd.test(n)?
(e++,f++):$d.test(n)?g=!0:Yd.test(n)?f++:fe.test(n)&&(g=!0)}e=0==f?g?1:0:.4<e/f?-1:1;return-1==(0==e?d.g:e)?"rtl":"ltr"}}],compile:function(a,b){b=b.key;var c=null,d=document.createElement("amr");b&&!b.match(/^\d+$/)&&(b=chrome.i18n.getMessage(b),null==b&&d.setAttribute("id","missing"));if(b){var e=chrome.i18n.getMessage(b+"_ph");c=[];if(null!=e)for(c=e.split("\ue000"),e=0;e<c.length;++e)c[e]=c[e].replace(/^{{(.*)}}$/,'<amrp dir="{{dirForText($1)}}">{{$1}}</amrp>');c=chrome.i18n.getMessage(b,c)}else d.setAttribute("r",
"nokey");c?We(d,lj(c)):(d.setAttribute("tl","false"),We(d,lj(a.html())));a.replaceWith(d)}}})};var oj=function(a,b){var c=this;this.o=b;this.g=a;this.g.top=a;this.C=[];this.l=!1;this.h=new gh;this.g.videoSmoothnessRatings=this.Jm(sh,nh,oh,ph,qh,rh);this.g.videoQualityRatings=this.Jm(sh,th,uh,vh,wh,xh);this.g.audioQualityRatings=this.Jm(sh,yh,zh,Ah,Bh,Ch);this.C=[{value:"Bug",desc:hh},{value:"FeatureRequest",desc:ih},{value:"MirroringQuality",desc:jh},{value:"Discovery",desc:lh},{value:"Other",desc:mh}];this.g.feedbackTypes=this.C;this.g.includeFineLogs=!0;this.g.feedbackType="Bug";this.g.sendFeedback=
this.iC.bind(this);this.g.cancel=this.kw.bind(this);this.g.attachLogsClick=this.m.bind(this);this.g.viewLogs=this.F.bind(this);this.g.$watchGroup("videoSmoothness videoQuality audioQuality feedbackDescription comments feedbackType".split(" "),this.nw.bind(this));this.g.sufficientFeedback=!1;this.g.$watch("attachLogs",this.m.bind(this));this.g.attachLogs=!0;this.u=af();this.g.userEmail="";chrome.identity.getProfileUserInfo(function(d){c.g.userEmail=d.email;nj(c)});this.g.yourAnswerText=Mh;this.g.language=
chrome.i18n&&chrome.i18n.getUILanguage?chrome.i18n.getUILanguage():chrome.runtime.getManifest().default_locale;this.g.requestLogsInProgress=!1;this.g.mrVersion=chrome.runtime.getManifest().version};k=oj.prototype;k.Jm=function(a){for(var b=[],c=1;c<arguments.length;c++)b.push(new pj(c,arguments[c]));b.push(new pj(0,arguments[0]));return b};k.kw=function(){this.g.feedbackDescription&&!confirm(Dh)||window.close()};
k.nw=function(){var a=this.g.feedbackType;this.g.sufficientFeedback="MirroringQuality"==a?this.g.videoSmoothness||this.g.videoQuality||this.g.audioQuality||this.g.comments:"Discovery"==a?this.g.visibleInSetup||this.g.comments:!!this.g.feedbackDescription};
k.iC=function(){if(this.g.sufficientFeedback){var a=this.g.feedbackType,b="";"MirroringQuality"==a?(this.g.videoSmoothness&&(b+="\nVideo Smoothness: "+this.g.videoSmoothness),this.g.videoQuality&&(b+="\nVideo Quality: "+this.g.videoQuality),this.g.audioQuality&&(b+="\nAudio: "+this.g.audioQuality),this.g.projectedContentUrl&&(b+="\nProjected Content/URL: "+this.g.projectedContentUrl),this.g.comments&&(b+="\nComments: "+this.g.comments)):"Discovery"==a?(this.g.visibleInSetup&&(b+="\nChromecast Visible in Setup: "+
this.g.visibleInSetup),this.g.hasNetworkSoftware&&(b+="\nUsing VPN/proxy/firewall/NAS Software: "+this.g.hasNetworkSoftware),this.g.networkDescription&&(b+="\nNetwork Description: "+this.g.networkDescription),this.g.comments&&(b+="\nComments: "+this.g.comments)):b=this.g.feedbackDescription;a="Type: "+a+"\n\n"+b;this.g.sendDialogText=Eh;this.g.okButton=Lh;this.g.feedbackSent=!1;this.o.show({locals:{JT:this.g.feedbackSent,yV:this.g.sendDialogText,YA:this.g.okButton},scope:this.g,preserveScope:!0,bindToController:!0,
template:'<md-dialog id="feedback-confirmation"><md-dialog-content><div id="send-feedback-text">{{sendDialogText}}</div><md-dialog-actions><md-button class="md-raised md-primary"ng-disabled="!feedbackSent" ng-click="closeWindow()">{{okButton}}</md-button></md-dialog-actions></md-dialog-content></md-dialog>',controller:this.j});this.gr(a,Date.now())}};k.gr=function(a,b){var c=Date.now();!this.g.requestLogsInProgress||5E3<c-b?qj(this,a):setTimeout(this.gr.bind(this),1E3,a,b)};
var qj=function(a,b){var c=0,d=function(f,g,h){h?f(!0):(a.g.sendDialogText=Hh,nj(a),g(Error("Failed to send")))},e=chrome.declarativeWebRequest?"MrTeamfood":"MRStable";(new dh(function(){c++;return new Promise(function(f,g){var h=a.g.userEmail,n=a.h;f=d.bind(null,f,g);g=chrome.runtime.getManifest();fh({productId:85561,bucket:e,flow:"submit",serverUri:"https://www.google.com/tools/feedback",allowNonLoggedInFeedback:!0,locale:g.default_locale,enableAnonymousFeedback:!h,report:{description:b},callback:f},
{version:g.version,description:g.description,user_email:h||"NA",logs:n.hd||"NA",external_logs:n.g||"NA",device_model:n.modelName||"NA",receiver_version:n.u||"NA",dash_report_url:n.l||"NA",cast_device_counts:n.h,dial_device_counts:n.j,mirroring_service_enabled:n.m,native_cast_mrp_enabled:n.o,native_dial_mrp_enabled:n.C})})},1E4,4)).start().then(function(){Nb("MediaRouter.Ui.Action.Feedback");a.g.sendDialogText=Gh;a.g.feedbackSent=!0;nj(a)},function(){a.g.sendDialogText=Fh;a.g.feedbackSent=!0;nj(a)})};
oj.prototype.m=function(){var a=this;this.h=new gh;this.g.attachLogs&&(this.g.requestLogsInProgress=!0,chrome.runtime.sendMessage(new ch(this.u,"retrieve_log_data"),function(b){a.g.requestLogsInProgress=!1;a.h.hd=b.logs||"no extension";a.h.hd+="\n";a.h.hd+=b.mediaSinkServiceStatus||"no media sink service status from browser";a.h.hd+="\n";a.h.hd+=b.mediaRouterLogs||"no Media Router logs from the browser";b.castStreamingLogs&&(a.h.l=b.castStreamingLogs);b.castDeviceCounts&&(a.h.h=b.castDeviceCounts);
b.dialDeviceCounts&&(a.h.j=b.dialDeviceCounts);a.h.m=!!b.mirroringServiceEnabled;a.h.o=!!b.nativeCastMrpEnabled;a.h.C=!!b.nativeDialMrpEnabled;if(b=b.device)if(b.model&&(a.h.modelName=b.model),b.version&&(a.h.u=b.version),!a.l){var c=af();a.l=!0;a.h.g=zb(b.ip,c,a.D.bind(a))}}))};
oj.prototype.F=function(){this.g.logs=this.h.hd;this.g.logsHeader=Ih;this.g.sendLogs=Jh;this.g.fineLogsWarning=Kh;this.g.okButton=Lh;this.o.show({locals:{XS:this.g.attachLogs,hd:this.g.logs,eU:this.g.includeFineLogs,GU:this.g.logsHeader,zV:this.g.sendLogs,KT:this.g.fineLogsWarning,YA:this.g.okButton},scope:this.g,preserveScope:!0,bindToController:!0,clickOutsideToClose:!0,template:'<md-dialog><md-dialog-content id="logs-dialog"><div class="subheading">{{logsHeader}}</div><div ng-show="includeFineLogs && attachLogs"id="feedback-fine-log-warning" class="informative">{{fineLogsWarning}}</div><pre>{{logs}}</pre><div class="send-logs"><md-checkbox type="checkbox" ng-model="attachLogs"ng-change="attachLogsClick()"><span>{{sendLogs}}</span></md-checkbox></div><md-dialog-actions><md-button class="md-raised md-primary"ng-click="closeDialog()">{{okButton}}</md-button></md-dialog-actions></md-dialog-content></md-dialog>',
controller:this.j})};oj.prototype.D=function(a,b){this.l=!1;this.h.g="error"==a?"":b;this.g.attachLogs||(this.h.g="");nj(this)};var nj=function(a){a.g.$$phase||a.g.$apply()};oj.prototype.j=function(a,b){a.closeWindow=function(){window.close()};a.closeDialog=function(){b.hide()}};oj.prototype.j.$inject=["$scope","$mdDialog"];var pj=function(a,b){this.id=a;this.desc=b;this.text=0==a?b:a+" ("+b+")"};
angular.module("feedbackApp","chrome_18n material.components.button material.components.checkbox material.components.dialog material.components.input material.components.radioButton".split(" ")).controller("FeedbackCtrl",["$scope","$mdDialog",oj]);w("ng.safehtml.googSceHelper.isGoogHtmlType",function(a){return a&&a.ke?!0:!1});w("ng.safehtml.googSceHelper.isCOMPILED",function(){return!0});w("ng.safehtml.googSceHelper.unwrapAny",function(a){if(a instanceof he)return ie(a).toString();if(a instanceof Ne)return Oe(a).toString();if(a instanceof oe)return pe(a);if(a instanceof we)return xe(a);if(a instanceof Wd)return Xd(a).toString();throw Error();});
w("ng.safehtml.googSceHelper.unwrapGivenContext",function(a,b){if("html"==a)return Oe(b).toString();if("resourceUrl"==a||"templateUrl"==a)return ie(b).toString();if("url"==a)return b instanceof he?ie(b).toString():pe(b);if("css"==a)return xe(b);if("js"==a)return Xd(b).toString();throw Error();});
