'use strict';var vy={TAB:0,Um:1,Hu:2},wy=function(){return new Db("MediaRouter.CastStreaming.Session.Launch")},xy=function(){return new Kb("MediaRouter.CastStreaming.Session.Length")},yy=function(a){Ob("MediaRouter.CastStreaming.Start.Success",a,vy)};var zy=hb("mr.mirror.cast.LogUploader");function Ay(a,b,c){By("raw_events.log.gz",a,b,c);return b?"https://crash.corp.google.com/samples?reportid=&q="+encodeURIComponent("UserComments='"+b+"'"):""}
function By(a,b,c,d){if(0==b.size)zy.info("Trying to upload an empty file to Crash"),d&&d(null);else{var e=new FormData;e.append("prod","Cast");e.append("ver",chrome.runtime.getManifest().version);e.append(a,b);c&&e.append("comments",c);cy("https://clients2.google.com/cr/report",function(f){f=f.target;var g=null;my(f)?(g=oy(f),zy.info("Upload to Crash succeeded: "+g)):zy.info("Upload to Crash failed. HTTP status: "+f.za());d&&d(g)},"POST",e,void 0,3E4)}};var Cy=function(){this.g=0;Vm(this)},Ey=function(){Dy||(Dy=new Cy);return Dy},Fy=function(){var a=Ey(),b={fraction:.01,autoSubmitTimeLimitMillis:6048E5},c=b.autoSubmitTimeLimitMillis,d=Date.now();return a.g&&c&&d-a.g<c?!1:Math.random()<b.fraction};Cy.prototype.fb=function(){return"mirror.cast.LogUtils"};Cy.prototype.bc=function(){return[void 0,{lastAutoSubmitMillis:this.g}]};Cy.prototype.hc=function(){var a=Tm(this);this.g=a&&a.lastAutoSubmitMillis||0};var Dy=null;hb("mr.mirror.cast.LogUtils");var Gy={WL:"OFFER",QD:"ANSWER",cN:"PRESENTATION",cI:"GET_STATUS",WP:"STATUS_RESPONSE",XH:"GET_CAPABILITIES",tF:"CAPABILITIES_RESPONSE",VO:"RPC"};var Hy=function(){this.capabilities=this.status=this.g=this.error=this.rpc=this.result=this.type=this.h=this.sessionId=null},Ky=function(a){try{if("string"!==typeof a)throw SyntaxError("Cannot parse non-string as JSON");var b;Iy(JSON.parse(a),function(d){b=Jy(d)},function(){throw Error("non-Object result from JSON parse");});return b}catch(d){var c=d instanceof SyntaxError?"JSON parse error: "+d.message:"Type coercion error: "+d.message}"string"==typeof a?a="a string: "+a:a instanceof ArrayBuffer?
(a=new Uint8Array(a),a="an ArrayBuffer whose base64 is "+btoa(String.fromCharCode.apply(null,a))):a="of invalid data type "+typeof a;throw Error(c+". Input was "+a);},Jy=function(a){var b=new Hy;null!=a.sessionId&&(b.sessionId=String(a.sessionId));Ly(a.seqNum,function(f){b.h=f},function(){throw Error('"seqNum" must be a number');});if("type"in a){for(var c=String(a.type).toUpperCase(),d=m(Object.keys(Gy)),e=d.next();!e.done;e=d.next())if(Gy[e.value]==c){b.type=c;break}if(!b.type)throw Error('not a known message "type"');
}"result"in a&&(b.result=String(a.result));if("rpc"in a){if("string"!==typeof a.rpc)throw Error('"rpc" must be a String containing a base64 payload');b.rpc=new Uint8Array([].concat(q(atob(a.rpc))).map(function(f){return f.charCodeAt(0)}))}Iy(a.error,function(f){b.error=My(f)},function(){throw Error('"error" must be an Object');});Iy(a.answer,function(f){b.g=Ny(f)},function(){throw Error('"answer" must be an Object');});Iy(a.status,function(f){b.status=Oy(f)},function(){throw Error('"status" must be an Object');
});Iy(a.capabilities,function(f){b.capabilities=Py(f)},function(){throw Error('"capabilities" must be an Object');});return b},Iy=function(a,b,c){void 0!==a&&(a instanceof Object?b(a):c())},Ly=function(a,b,c){void 0!==a&&("number"!==typeof a?c():b(a))},Qy=function(a,b,c){void 0!==a&&(a instanceof Array&&a.every(function(d){return"number"===typeof d})?b(a):c())},Ry=function(a,b,c){void 0!==a&&(a instanceof Array?b(a.map(function(d){return String(d)})):c())},Sy=function(){this.m=null;this.g=[];this.h=
[];this.j=this.l=this.o=null},Ny=function(a){var b=new Sy;Ly(a.udpPort,function(c){b.m=c},function(){throw Error('"answer.udpPort" must be a number');});Qy(a.sendIndexes,function(c){b.g=c},function(){throw Error('"answer.sendIndexes" must be an array of numbers');});Qy(a.ssrcs,function(c){b.h=c},function(){throw Error('"answer.ssrcs" must be an array of numbers');});"IV"in a&&(b.o=String(a.IV));"receiverGetStatus"in a&&(b.l="true"==String(a.receiverGetStatus).toLowerCase());"castMode"in a&&(b.j=String(a.castMode));
return b},Ty=function(){this.details=this.description=this.code=null},My=function(a){var b=new Ty;Ly(a.code,function(c){b.code=c},function(){throw Error('"error.code" must be a number');});"description"in a&&(b.description=String(a.description));Iy(a.details,function(c){b.details=c},function(){throw Error('"error.details" must be an Object');});return b},Uy=function(){this.h=this.g=null},Oy=function(a){var b=new Uy;Ly(a.wifiSnr,function(c){b.g=c},function(){throw Error('"status.wifiSnr" must be a number');
});Qy(a.wifiSpeed,function(c){b.h=c},function(){throw Error('"status.wifiSpeed" must be an array of numbers');});return b},Vy=function(){this.h=this.g=null},Py=function(a){var b=new Vy;Ry(a.mediaCaps,function(c){b.g=c},function(){throw Error('"capabilities.mediaCaps" must be an array');});if("keySystems"in a){a=a.keySystems;if(!(a instanceof Array))throw Error('"capabilities.keySystems" must be an array');b.h=a.map(function(c){var d;Iy(c,function(e){d=Wy(e)},function(){throw Error('"capabilities.keySystems" entries must be *Objects');
});return d})}return b},Xy=function(){this.h=this.o=this.m=this.l=this.u=this.g=this.C=this.codecs=this.initDataTypes=this.j=null},Wy=function(a){var b=new Xy;"keySystemName"in a&&(b.j=String(a.keySystemName));Ry(a.initDataTypes,function(c){b.initDataTypes=c},function(){throw Error('"capabilities.initDataTypes" must be an array');});Ry(a.codecs,function(c){b.codecs=c},function(){throw Error('"capabilities.codecs" must be an array');});Ry(a.secureCodecs,function(c){b.C=c},function(){throw Error('"capabilities.secureCodecs" must be an array');
});Ry(a.audioRobustness,function(c){b.g=c},function(){throw Error('"capabilities.audioRobustness" must be an array');});Ry(a.videoRobustness,function(c){b.u=c},function(){throw Error('"capabilities.videoRobustness" must be an array');});"persistentLicenseSessionSupport"in a&&(b.l=String(a.persistentLicenseSessionSupport));"persistentReleaseMessageSessionSupport"in a&&(b.m=String(a.persistentReleaseMessageSessionSupport));"persistentStateSupport"in a&&(b.o=String(a.persistentStateSupport));"distinctiveIdentifierSupport"in
a&&(b.h=String(a.distinctiveIdentifierSupport));return b};var Yy=function(a){this.s=hb("mr.mirror.cast.MessageDispatcher");this.l=a;this.g=null;this.h=new Map;this.j=0},Zy=function(a,b,c){if(a.h.has(b))throw Error("Attempt to multiple-subscribe to the same response type: "+b);a.h.set(b,c);a.j=0;a.s.ua("Added subscriber for "+b+"-type messages.");a.g||(a.g=Ow(a.l),a.g.onMessage=a.m.bind(a))},$y=function(a,b){a.h.delete(b)&&a.s.ua(function(){return"Removed subscriber of "+b+"-type messages."});0==a.h.size&&a.g&&(a.g.dispose(),a.g=null)};
Yy.prototype.sendMessage=function(a){return this.g?"RPC"==a.type?this.g.sendMessage(a,{namespace:"urn:x-cast:com.google.cast.remoting"}):this.g.sendMessage(a,{namespace:"urn:x-cast:com.google.cast.webrtc"}):Promise.reject(Error("Require at least one subscriber before sending messages."))};
var az=function(a,b,c,d,e){var f=null,g=function(){$y(a,c);null!=f&&(clearTimeout(f),f=null)};try{Zy(a,c,function(h){e(h)&&g()})}catch(h){e(null,h);return}f=setTimeout(function(){g();e(null,Error("timeout"))},d);a.sendMessage(b).catch(function(h){g();e(null,h)})};
Yy.prototype.m=function(a){if(a&&"string"===typeof a.namespace_&&a.namespace_.startsWith("urn:x-cast:com.google.cast.")){do{var b=void 0;try{b=Ky(a.data)}catch(d){b=d.message;break}if(b.type){var c=this.h.get(b.type);if(c)try{c(b);return}catch(d){b="Error thrown during delivery. Response was: "+(JSON.stringify(b)+". Error from subscriber callback was: ")+(d.message+".")}else b="Message was ignored: "+JSON.stringify(b)}else b="Message did not include response type: "+JSON.stringify(b)}while(0);10>
this.j?this.s.K(b):this.s.ua(b);++this.j}};var bz=function(){this.g=Promise.resolve(1)},dz=function(a,b,c){return cz(a,function(d){return d==b},c)},ez=function(a,b){var c=[3,4];return cz(a,function(d){return-1!=c.indexOf(d)},b)},fz=function(a,b){a.g=a.g.catch(function(){return 1});return cz(a,function(){return!0},b)},cz=function(a,b,c){var d,e,f=new Promise(function(g,h){d=g;e=h});a.g=a.g.then(function(g){if(!b(g))return e(Error("Operation requires a different starting checkpoint than "+g)),Promise.resolve(g);var h=new gz(g);try{var n=c(h)}catch(p){n=
Promise.reject(p)}return n.then(function(p){return d(p)},function(p){return e(p)}).then(function(){if(null===h.g)throw Error("A prior operation that started at "+(g+" did not complete."));return h.g})},function(g){e(g);throw g;});return f},gz=function(a){this.h=a;this.g=null},hz=function(a,b){a.g="number"===typeof b?b:a.h};var iz=chrome.cast.streaming,jz=hb("mr.mirror.cast.StreamingLaunchWorkflow"),lz=function(a,b,c,d,e){this.L=a.sessionId;this.D=a.ii;this.W=a.mf;this.j=b;this.J=c;this.H=d;this.X=kz(e,"onAnswer",this.D);this.lb=kz(e,"onSessionStop",this.D);this.s=jz;this.F=new bz;this.C=this.G=this.u=this.h=this.g=this.o=this.m=this.l=null};
lz.prototype.start=function(a,b,c){var d=this;if(!a&&!b)return Promise.reject(Error("No tracks to stream"));var e=a instanceof mz,f=b instanceof mz;(e&&b&&!f||f&&a&&!e)&&Wb("Mixing remoting and non-remoting tracks");return dz(this.F,1,function(g){d.l=a;d.m=b;d.o=c;d.s.info(function(){return"Launching streaming for "+nz(d)+" to a "+(d.W+".")});return aaa(d).then(d.O.bind(d)).then(function(h){return baa(d,h).then(function(n){d.X();var p=caa(d,n,h);d.g=oz(d,d.g,p);d.h=oz(d,d.h,p);if(!d.g&&!d.h)throw Error("Receiver did not select any offers from: "+
JSON.stringify(h));d.G=!!n.l;d.C=function(r,y){r==d.g?d.o.Zf("Audio stream (id="+r+") error: "+y):r==d.h&&d.o.Zf("Video stream (id="+r+") error: "+y)};iz.rtpStream.onError.addListener(d.C);return daa(d,n,p)})}).then(function(){d.s.info(function(){return"Launched streaming for "+nz(d)});d.o.vh(d);hz(g,2);return{Xv:d.g,kD:d.h}})})};
lz.prototype.stop=function(){var a=this;return fz(this.F,function(b){if(!a.l&&!a.m)return hz(b,1),Promise.resolve();a.s.info(function(){return"Stopping streaming for "+nz(a)+"."});a.C&&(iz.rtpStream.onError.removeListener(a.C),a.C=null);if(a.o){var c=a.o.mi();a.o=null}else c=Promise.resolve();return c.then(function(){a.g&&(iz.rtpStream.stop(a.g),iz.rtpStream.destroy(a.g),a.g=null);a.h&&(iz.rtpStream.stop(a.h),iz.rtpStream.destroy(a.h),a.h=null);a.u&&(iz.udpTransport.destroy(a.u),a.u=null);a.lb();
a.s.info(function(){return"Stopped streaming for "+nz(a)+"."});a.l=null;a.m=null;hz(b,1)})})};
var eaa=function(a,b){var c=JSON.stringify(b);return Promise.all([a.g&&new Promise(function(d){return iz.rtpStream.getRawEvents(a.g,c,d)}),a.h&&new Promise(function(d){return iz.rtpStream.getRawEvents(a.h,c,d)})]).catch(function(d){a.s.error("Unexpected error when calling getRawEvents()",d);return[]}).then(function(d){return new Blob(d.filter(function(e){return!!e}),{type:"application/gzip"})})},faa=function(a){return Promise.all([a.g&&new Promise(function(b){return iz.rtpStream.getStats(a.g,b)}),
a.h&&new Promise(function(b){return iz.rtpStream.getStats(a.h,b)})]).catch(function(b){a.s.error("Unexpected error when calling getStats()",b);return[]}).then(function(b){return Object.assign.apply(Object,[{}].concat(q(b.filter(function(c){return!!c}))))})},nz=function(a){if(a.l&&a.m)var b="audio+video ";else if(a.l)b="audio-only ";else if(a.m)b="video-only ";else return"stopped";return a.l instanceof mz||a.m instanceof mz?b+"remoting":b+"streaming"},aaa=function(a){return new Promise(function(b){var c=
function(d,e,f){d&&!a.l&&(iz.rtpStream.destroy(d),d=null);e&&!a.m&&(iz.rtpStream.destroy(e),e=null);a.s.info(function(){return"Created Cast Streaming session: audioStreamId="+d+", videoStreamId="+e+"."});a.g=d;a.h=e;a.u=f;b()};a.l instanceof mz||a.m instanceof mz?iz.session.create(null,null,c):iz.session.create(a.l,a.m,c)})};
lz.prototype.O=function(){for(var a=Ak(),b=Ak(),c=[],d=m([this.g,this.h]),e=d.next();!e.done;e=d.next())if(e=e.value)for(var f=e==this.g,g=f?127:96,h=f?Math.floor(499999*Math.random())+1:Math.floor(499999*Math.random())+500001,n=f?48E3:9E4,p=m(iz.rtpStream.getSupportedParams(e)),r=p.next();!r.done;r=p.next())r=r.value,r.payload.payloadType=g,r.payload.maxLatency=this.j.maxLatencyMillis,r.payload.minLatency=this.j.minLatencyMillis,r.payload.animatedLatency=this.j.animatedLatencyMillis,r.payload.ssrc=
h,r.payload.clockRate=n,r.payload.aesKey=a,r.payload.aesIvMask=b,f?(r.payload.channels=2,r.payload.maxBitrate=this.j.audioBitrate,r.payload.maxFrameRate=100):(r.payload.minBitrate=this.j.minVideoBitrate,r.payload.maxBitrate=this.j.maxVideoBitrate,r.payload.maxFrameRate=this.j.maxFrameRate),c.push(new gaa(e,r));return c};
var oz=function(a,b,c){b&&!c.some(function(d){return d.Xg==b})&&(a.s.K("Destroying RTP stream not selected by the receiver: id="+b),iz.rtpStream.destroy(b),b=null);return b},baa=function(a,b){return new Promise(function(c,d){for(var e=[],f=0;f<b.length;++f){var g=b[f].params,h={index:f,codecName:g.payload.codecName.toLowerCase(),rtpProfile:"cast",rtpPayloadType:g.payload.payloadType,ssrc:g.payload.ssrc,targetDelay:g.payload.animatedLatency,aesKey:g.payload.aesKey,aesIvMask:g.payload.aesIvMask,timeBase:"1/"+
g.payload.clockRate,receiverRtcpEventLog:a.j.enableLogging,rtpExtensions:["adaptive_playout_delay"]};a.j.dscpEnabled&&(h.receiverRtcpDscp=46);127==g.payload.payloadType?Object.assign(h,{type:"audio_source",bitRate:0<g.payload.maxBitrate?1E3*g.payload.maxBitrate:60*g.payload.maxFrameRate+g.payload.clockRate*g.payload.channels,sampleRate:g.payload.clockRate,channels:g.payload.channels}):Object.assign(h,{type:"video_source",renderMode:"video",maxFrameRate:Math.round(1E3*g.payload.maxFrameRate)+"/1000",
maxBitRate:1E3*g.payload.maxBitrate,resolutions:[{width:a.j.maxWidth,height:a.j.maxHeight}]});e.push(h)}var n=a.l instanceof mz||a.m instanceof mz?"remoting":"mirroring",p={type:"OFFER",sessionId:a.L,seqNum:fo(a.J),offer:{castMode:n,receiverGetStatus:!0,supportedStreams:e}};a.s.info(function(){return"Sending OFFER message: "+JSON.stringify(p)});az(a.H,p,"ANSWER",1E4,function(r,y){if(null==r)d(y);else if("ok"==r.result&&r.g){if(r.h!=p.seqNum)return a.s.K("Ignoring ANSWER for OFFER with different seqNum: "+
JSON.stringify(r)),!1;((y=r.g.j)&&y!=n||!y&&"mirroring"!=n)&&a.s.error("Expected receiver to ANSWER with castMode="+n+", but got: "+y);a.s.ua(function(){return"Received ANSWER: "+JSON.stringify(r)});c(r.g)}else d(Error("Non-OK ANSWER received: "+JSON.stringify(r)));return!0})})},caa=function(a,b,c){if(b.g.length!=b.h.length)return a.s.error("sendIndexes.length != ssrcs.length in ANSWER: "+JSON.stringify(b)),[];for(var d=[],e={},f=0;f<b.g.length;e={mg:e.mg},++f){var g=b.g[f];if(0>g||g>=c.length)return a.s.error("Receiver selected invalid index ("+
g+" < "+c.length+") in ANSWER: "+JSON.stringify(b)),[];e.mg=c[g];if(d.some(function(h){return function(n){return n.Xg==h.mg.Xg}}(e)))return a.s.error("Receiver selected same RTP stream twice in ANSWER: "+JSON.stringify(b)),[];e.mg.params.payload.feedbackSsrc=b.h[g];if(d.some(function(h){return function(n){return n.params.payload.feedbackSsrc==h.mg.params.payload.feedbackSsrc}}(e)))return a.s.error("Receiver provided same SSRC for two different RTP streams in ANSWER: "+JSON.stringify(b)),[];d.push(e.mg)}return d},
daa=function(a,b,c){var d=null,e=function(){d&&(iz.rtpStream.onStarted.removeListener(d),d=null)};return(new Promise(function(f,g){var h=b.m||2344;a.s.info(function(){return"Starting RTP streams to receiver at "+(a.D+":"+h)+(" for selected offers: "+JSON.stringify(c))});var n=a.u||-1;a.j.dscpEnabled&&(a.s.info("Enabled DSCP in sender."),iz.udpTransport.setOptions(n,{DSCP:!0}));iz.udpTransport.setDestination(n,{address:a.D,port:h});var p=new Set(c.map(function(y){return y.Xg}));d=function(y){p.delete(y);
0==p.size&&f()};iz.rtpStream.onStarted.addListener(d);n=m(c);for(var r=n.next();!r.done;r=n.next())r=r.value,iz.rtpStream.toggleLogging(r.Xg,a.j.enableLogging),iz.rtpStream.start(r.Xg,r.params);setTimeout(function(){g(Error("Timeout: RTP streams failed to start."))},1E4)})).then(e).catch(function(f){e();throw f;})},kz=function(a,b,c){return a&&b in a?function(){try{a[b](c)}catch(d){jz.error("Error from testHooks."+b,d)}}:function(){}},gaa=function(a,b){this.Xg=a;this.params=b},mz=function(){};var pz=hb("mr.mirror.cast.MediaRemoter"),qz=function(a,b,c,d,e,f){this.C=a;this.J=haa(b,this.C.Qb);this.L=new lz(this.C.Qb,c,d,e,f);this.F=e;this.m=new bz;this.j=new iaa;this.D=new mojo.Binding(mojo.MirrorServiceRemoter,this,null);this.s=pz;this.G=this.g=this.o=this.l=this.H=null;this.h=!0;this.u=this.O.bind(this)};
qz.prototype.initialize=function(a,b){var c=this;return dz(this.m,1,function(d){c.H=a;c.l=b;var e=c.D.createInterfacePtrAndBind();c.D.setConnectionErrorHandler(function(){c.s.info("Remoter mojo pipe connection error.");rz(c)});c.g=new mojo.MirrorServiceRemotingSourcePtr;var f=mk(c.C.mediaSource||"");if(!f)throw Error("Failed to parse tab ID from source:\n          "+c.C.mediaSource);c.s.info("Connecting remoter to browser: tabId="+f);(Vj.get("mr.ProviderManager")||null).onMediaRemoterCreated(f,e,
mojo.makeRequest(c.g));c.g.ptr.setConnectionErrorHandler(function(){c.s.info("RemotingSource mojo pipe connection error.");rz(c)});return jaa(c).then(function(){if(c.h)c.g.onSinkAvailable(c.J);hz(d,2)})})};
var rz=function(a){return fz(a.m,function(b){a.g&&(a.g.ptr.reset(),a.g=null);var c=a.o;a.o=null;a.l=null;a.H=null;a.D.close();chrome.settingsPrivate.onPrefsChanged.hasListener(a.u)&&chrome.settingsPrivate.onPrefsChanged.removeListener(a.u);return new Promise(function(d){window.setTimeout(function(){sz(a).then(function(){hz(b,1);d();c&&c()})},250)})})};k=qz.prototype;k.jC=function(a){tz(this.j,a)};k.vh=function(a){this.l&&this.l.vh(a)};k.mi=function(){return this.l?this.l.mi():Promise.resolve()};
k.Zf=function(a,b){this.s.error("Error during streaming: "+a,b);if(this.g)this.g.onError();rz(this)};
k.start=function(){var a=this,b=!1;this.s.info(function(){b=!0;return"Starting next media remoting session."});b&&kaa(this.j,function(c){return a.s.info(c)});laa(this.j);dz(this.m,2,function(c){return(0,a.H)().then(function(d){a.o=d;Zy(a.F,"RPC",function(e){if(e.rpc){var f=a.j;e=e.rpc;f.o&&(++f.C,f.h+=e.length,f.o(e))}});hz(c,3)}).catch(function(d){return sz(a).then(function(){hz(c);throw d;})})}).then(function(){a.s.info("Remoting started successfully.")}).catch(function(c){a.s.error("Failed to start remoting",c);
a.g.onError()})};k.KC=function(a,b){var c=this;return dz(this.m,3,function(d){return c.L.start(a?new mz:null,b?new mz:null,c).then(function(e){maa(c.j,function(f){return c.F.sendMessage(f)},function(f){c.g.onMessageFromSink(f)});hz(d,4);return{audio_stream_id:e.Xv||-1,video_stream_id:e.kD||-1}}).catch(function(e){return sz(c).then(function(){hz(d);throw e;})})}).catch(function(d){c.s.error("Failed to start remoting streams",d);rz(c);return{audio_stream_id:-1,video_stream_id:-1}})};
k.stop=function(a){var b=this;ez(this.m,function(c){b.g.onStopped(a);return sz(b).then(function(){b.s.info("Remoting stopped.");hz(c,5);(0,b.o)().then(function(){return dz(b.m,5,function(d){if(b.g&&b.h)b.g.onSinkAvailable(b.J);hz(d,2);return Promise.resolve()})}).catch(function(d){throw d;});b.o=null})}).catch(function(c){b.s.error("Failed to stop remoting: ",c);rz(b)})};
k.Bw=function(){null===this.G&&(this.G=Cb(this.C.Qb.ii).then(function(a){return a.g||!1}));return this.G.then(function(a){return{rate:(a?1E7:5E6)/8}})};
var sz=function(a){return a.L.stop().then(function(){$y(a.F,"RPC");naa(a.j);uz(a.j)})},jaa=function(a){return new Promise(function(b){chrome.settingsPrivate.getPref("media_router.media_remoting.enabled",function(c){chrome.runtime.lastError?a.s.error("Encountered error getting media remoting pref: "+JSON.stringify(chrome.runtime.lastError)):c.type!=chrome.settingsPrivate.PrefType.BOOLEAN?a.s.error("Pref value not a boolean: "+JSON.stringify(c)):(a.h=!!c.value,a.s.info("Initializing mediaRemotingEnabled_ with value read from pref: "+
a.h));chrome.settingsPrivate.onPrefsChanged.hasListener(a.u)||chrome.settingsPrivate.onPrefsChanged.addListener(a.u);b()})})};
qz.prototype.O=function(a){if(this.g){a=m(a);for(var b=a.next();!b.done;b=a.next())if(b=b.value,"media_router.media_remoting.enabled"==b.key){if(b.type!=chrome.settingsPrivate.PrefType.BOOLEAN){this.s.error("Pref value not a boolean: "+JSON.stringify(b));break}a=!!b.value;if(this.h==a)break;this.h=a;this.s.info("mediaRemotingEnabled_ changed to: "+this.h);if(this.h)this.g.onSinkAvailable(this.J);else this.g.onStopped(mojo.RemotingStopReason.USER_DISABLED);break}}};
var haa=function(a,b){var c=new mojo.RemotingSinkMetadata;c.features=[];c.friendly_name=b.GC||"";c.audio_capabilities=[];c.video_capabilities=[];var d=mojo.RemotingSinkAudioCapability,e=mojo.RemotingSinkVideoCapability,f=c.audio_capabilities,g=c.video_capabilities,h=b.mf||"";(a.g||[]).forEach(function(n){switch(n){case "audio":f.push(d.CODEC_BASELINE_SET);break;case "aac":f.push(d.CODEC_AAC);break;case "opus":f.push(d.CODEC_OPUS);break;case "video":g.push(e.CODEC_BASELINE_SET);break;case "4k":g.push(e.SUPPORT_4K);
break;case "h264":g.push(e.CODEC_H264);break;case "vp8":g.push(e.CODEC_VP8);break;case "vp9":h.startsWith("Chromecast Ultra")&&g.push(e.CODEC_VP9);break;case "hevc":h.startsWith("Chromecast Ultra")&&g.push(e.CODEC_HEVC);break;default:pz.info("Unknown mediaCap name: "+n)}});b.mf&&"Chromecast Ultra"==b.mf&&g.push(e.SUPPORT_4K);return c};qz.prototype.estimateTransmissionCapacity=qz.prototype.Bw;qz.prototype.stop=qz.prototype.stop;qz.prototype.startDataStreams=qz.prototype.KC;qz.prototype.start=qz.prototype.start;
qz.prototype.sendMessageToSink=qz.prototype.jC;
var iaa=function(){this.o=this.m=this.g=null;this.D=this.h=this.C=this.j=this.u=0;this.l=null},laa=function(a){a.g=[];vz(a,performance.now())},maa=function(a,b,c){a.m=b;a.o=c;a.g?(b=a.g,a.g=null,b.forEach(function(d){return tz(a,d.data).then(d.lC,d.hr)})):vz(a,performance.now())},naa=function(a){if(a.g){var b=Error("Stop before delivering pending message");a.g.forEach(function(c){return c.hr(b)});a.g=null}a.m=null;a.o=null},tz=function(a,b){if(a.m){var c=btoa(String.fromCharCode.apply(null,b));++a.u;
a.j+=b.length;return a.m({type:"RPC",rpc:c})}return a.g?new Promise(function(d,e){a.g.push({data:b,lC:d,hr:e})}):Promise.reject(Error("RPC pipe not started"))},kaa=function(a,b){uz(a);a.l=setInterval(function(){if(a.g)var c=a.g.length+" messages are waiting to send.";else{c=performance.now();var d=(c-a.D)/1E3;d="Over the past "+d.toFixed(1)+" seconds, sent "+(a.u+" messages ("+Math.round(a.j/d)+" bytes/sec) and received ")+(a.C+" messages ("+Math.round(a.h/d)+" bytes/sec).");vz(a,c);c=d}b(c)},3E4)},
uz=function(a){null!=a.l&&(clearInterval(a.l),a.l=null)},vz=function(a,b){a.u=0;a.j=0;a.C=0;a.h=0;a.D=b};function oaa(a){return a&&a.getAudioTracks()&&0<a.getAudioTracks().length?a.getAudioTracks()[0]:null}function paa(a){return a&&a.getVideoTracks()&&0<a.getVideoTracks().length?a.getVideoTracks()[0]:null};var wz=function(a,b,c,d,e){this.j=new lz(a,b,c,d,void 0===e?null:e);this.s=hb("mr.mirror.cast.MediaStreamer");this.m=new bz;this.l=this.h=this.g=this.o=null};wz.prototype.start=function(a,b){var c=this;return dz(this.m,1,function(d){c.o=a;c.g=oaa(a);c.g&&"ended"==c.g.readyState&&(c.g=null);c.h=paa(a);c.h&&"ended"==c.h.readyState&&(c.h=null);if(!c.g&&!c.h)return hz(d),Promise.reject(Error("No MediaStream tracks to stream."));c.l=b;return c.j.start(c.g,c.h,c.l).then(function(){return hz(d,2)})})};
wz.prototype.stop=function(){var a=this;return fz(this.m,function(b){return a.j.stop().then(function(){a.g=null;a.h=null;a.o=null;a.l=null;hz(b,1)})})};var qaa=function(a){return dz(a.m,2,function(b){a.s.info("Suspending media streaming...");return a.j.stop().then(function(){a.s.info("Suspended media streaming.");hz(b,3)})})};
wz.prototype.resume=function(){var a=this;return dz(this.m,3,function(b){a.g&&"ended"==a.g.readyState&&(a.g=null);a.h&&"ended"==a.h.readyState&&(a.h=null);if(!a.g&&!a.h)return Promise.reject(Error("Cannot resume: All tracks have ended."));a.s.info("Resuming media streaming...");return a.j.start(a.g,a.h,a.l).then(function(){a.s.info("Resumed media streaming.");hz(b,2)})})};var xz=function(a,b,c){this.m=a;this.l=b;this.j=c;this.s=hb("mr.mirror.cast.WifiStatusMonitor");this.g=null;this.h=[]};xz.prototype.start=function(){var a=this;null==this.g&&(this.s.ua("Starting Wifi Status Monitoring."),this.h=[],Zy(this.j,"STATUS_RESPONSE",function(b){return raa(a,b)}),this.g=setInterval(function(){return yz(a)},12E4),yz(this))};xz.prototype.stop=function(){null!=this.g&&(this.s.ua("Stopping Wifi Status Monitoring."),clearInterval(this.g),this.g=null,$y(this.j,"STATUS_RESPONSE"))};
var raa=function(a,b){if(null!=a.g)if(b.status){var c={};null!=b.status.g&&(c.wifiSnr=b.status.g);null!=b.status.h&&(c.wifiSpeed=b.status.h[3]);0==Object.keys(c).length?a.s.K(function(){return"No status fields populated in response: "+JSON.stringify(b)}):(c.timestamp=Date.now(),30==a.h.length&&a.h.shift(),a.h.push(c),a.s.info(function(){return"Current Wifi status: "+JSON.stringify(c)}))}else a.s.K(function(){return"Ignoring response without status: "+JSON.stringify(b)})},yz=function(a){a.j.sendMessage({type:"GET_STATUS",
sessionId:a.m,seqNum:fo(a.l),get_status:["wifiSnr","wifiSpeed"]})};var zz=function(a,b,c,d){this.G=b.ii;this.J={extVersion:chrome.runtime.getManifest().version,extChannel:"public",mirrorSettings:or(a),sender:navigator.userAgent||"UNKNOWN",receiverProductName:b.mf};this.H=c;this.F=d;this.l=this.h=this.C=this.o=this.m=this.u=this.j=null;this.g=[]};zz.prototype.vh=function(a){null!=this.h&&clearInterval(this.h);this.j=a;this.u=Date.now();this.h=setInterval(this.D.bind(this,a),9E5)};
zz.prototype.mi=function(){null!=this.h&&(clearInterval(this.h),this.h=null);if(null!=this.j){var a=this.D(this.j);this.j=null;return a}return Promise.resolve()};zz.prototype.Zf=function(a,b){null==this.m&&(this.m=Date.now(),"function"===typeof a?this.o=a():"string"===typeof a&&(this.o=a),b&&"string"===typeof b.stack&&(this.C=b.stack))};
var saa=function(a,b){return(null==a.j?Promise.resolve():a.D(a.j)).then(function(){var c=b.map(function(d){d=Az(a,d);var e=d.map(function(g){return g.vd}).filter(function(g){return null!=g}),f=["["];d.map(function(g){return g.Wg}).forEach(function(g,h){0<h&&f.push(",");f.push(g)});f.push("]");return{vd:new Blob(e,{type:"application/gzip"}),Wg:new Blob(f,{type:"application/json"})}});a.g=[];return c})};
zz.prototype.D=function(a){var b=this;if(null!=this.l)return this.l;var c=Cb(this.G).then(function(d){d={receiverVersion:d.yg,receiverConnected:d.h,receiverOnEthernet:d.g,receiverHasUpdatePending:d.j,receiverUptimeSeconds:d.l};Object.assign(d,b.J);var e=Date.now();Object.assign(d,{startTime:b.u,endTime:e,activity:nz(a),receiverWifiStatus:Array.from(b.F.h)});b.u=e;null!=b.m&&(Object.assign(d,{streamingErrorTime:b.m,streamingErrorMessage:b.o,streamingErrorCause:b.C}),b.m=null,b.o=null,b.C=null);return d});
return(this.l=Promise.all([c.then(function(d){return eaa(a,d)}),c,faa(a)]).then(function(d){var e=m(d);d=e.next().value;var f=e.next().value;e=e.next().value;b.g.push({vd:d,Wg:new Blob([JSON.stringify(Object.assign({tags:f},e))],{type:"application/json"})});b.g=Az(b,b.H);b.l=null}))||Promise.resolve()};
var Az=function(a,b){b-=2;for(var c=[],d=a.g.length-1;0<=d;--d){b-=a.g[d].Wg.size+1;if(0>b)break;c.push({vd:null,Wg:a.g[d].Wg});if(null!=a.g[d].vd){var e=a.g[d].vd.size;b>=e&&(c[c.length-1].vd=a.g[d].vd,b-=e)}}return c.reverse()};var Bz=function(a,b,c,d){d=void 0===d?null:d;zk.call(this,b);var e=b.Qb;this.D=e.sessionId;this.G=a;this.L=d;this.s=hb("mr.mirror.cast.Session");this.o=new bz;this.m=new eo("mirror.cast.SeqNumGenerator");this.l=new Yy(b.id);this.u=new wz(e,this.G,this.m,this.l,this.L);this.C=null;this.g=new zz(a,e,c,new xz(this.D,this.m,this.l));this.F=null};t(Bz,zk);k=Bz.prototype;
k.start=function(a){var b=this;return dz(this.o,1,function(c){var d=wy();return b.u.start(a,b).then(function(){b.u.j.G&&(b.g.F.start(),taa(b));d.end();b.F=xy();hz(c,2);return b})})};k.stop=function(){var a=this;return fz(this.o,function(b){a.F&&(a.F.end(),a.F=null);a.g.F.stop();return a.u.stop().then(function(){return a.C?rz(a.C):Promise.resolve()}).then(function(){a.C=null;hz(b,4)})})};
k.fr=function(){var a=this,b={sessionId:this.D,seqNum:fo(this.m),type:"PRESENTATION",icons:[],title:xk(this.Zc)};this.s.info("Sending session metadata update to receiver: "+this.D);this.l.sendMessage(b).catch(function(c){a.s.K("Failed to send activity to sink: "+c.message)})};k.vh=function(a){this.g.vh(a)};k.mi=function(){return this.g.mi()};k.Zf=function(a,b){this.g.Zf(a,b);this.s.error(a,b);this.stop()};
var Cz=function(a,b){return saa(a.g,b)},taa=function(a){uaa(a).then(function(b){(b.g||[]).includes("video")?vaa(a,b):a.s.K(function(){return"Receiver incapable of Media Remoting: "+JSON.stringify(b)})}).catch(function(b){a.s.K("None/Invalid capabilites response. Media Remoting disabled.",b)})},uaa=function(a){return new Promise(function(b,c){var d={type:"GET_CAPABILITIES",sessionId:a.D,seqNum:fo(a.m)};a.s.info(function(){return"Sending GET_CAPABILITIES message: "+JSON.stringify(d)});az(a.l,d,"CAPABILITIES_RESPONSE",
3E4,function(e,f){if(null==e)return c(f),!0;if("ok"!=e.result||!e.capabilities)return c(Error("Bad response: "+JSON.stringify(e))),!0;if(e.h!=d.seqNum)return a.s.info(function(){return"Ignoring CAPABILITIES_RESPONSE with different seqNum: "+JSON.stringify(e)}),!1;a.s.ua(function(){return"Received CAPABILITIES_RESPONSE: "+JSON.stringify(e)});b(e.capabilities);return!0})})},vaa=function(a,b){dz(a.o,2,function(c){var d=a.h.Qb.mf||"<UNKNOWN>";if(!d.startsWith("Chromecast")&&!d.startsWith("Eureka Dongle"))return a.s.K('HACK: Media Remoting disabled because the receiver model--"'+
(d+'" according to discovery--is not a Chromecast.')),hz(c),Promise.resolve();a.C=new qz(a.h,b,a.G,a.m,a.l,a.L);return a.C.initialize(a.O.bind(a),a).catch(function(e){a.s.error("Media Remoting start failed: "+e.message,e)}).then(function(){return hz(c)})})};
Bz.prototype.O=function(){var a=this;return dz(this.o,2,function(b){return new Promise(function(c,d){qaa(a.u).then(function(){hz(b,3);a.H=!0;pk(a);c(a.W.bind(a))}).catch(function(e){a.Zf("Failed to suspend MediaStreamer before starting remoting",e);d(e)})})})};
Bz.prototype.W=function(){var a=this;return dz(this.o,3,function(b){return new Promise(function(c,d){a.u.resume().then(function(){hz(b,2);a.H=!1;pk(a);c()}).catch(function(e){a.Zf("Failed resume MediaStreamer after ending remoting mode",e);d(e)})})})};var Dz=function(){nk.call(this,"cast_streaming");this.m=this.F=this.J=this.H=this.l=null;this.ca=this.L="";this.ka=this.u=!1;this.pa=this.Aa.bind(this);this.O=this.W=this.X=this.lb=this.o=null};t(Dz,nk);k=Dz.prototype;k.xh=function(a){this.u=a||!1;this.ka=!0};k.getName=function(){return"cast_streaming"};
k.Ug=function(a,b,c,d,e){var f=this;if(!this.u)return nk.prototype.Ug.call(this,a,b,c,d,e);this.M.info("Start mirroring on route "+a.id);if(!this.ka)return Aj(Error("Not initialized"));var g=new Promise(function(h,n){f.C().then(function(){if(lk(b)&&c.shouldCaptureVideo)return Sj(!1).then(function(p){f.ca=p})}).then(function(){return e?e(a).promise:a}).then(function(p){f.L=b;waa(f,p);var r=f.H.createInterfacePtrAndBind(),y=f.J.createInterfacePtrAndBind(),A=xaa(p,c);yaa(f,p,b,d);if(!f.l)throw new Ej("Error to get mirroring service host");
f.F=new mojo.MirroringCastMessageChannelPtr;f.lb=wy();f.l.start(A,r,y,mojo.makeRequest(f.F));f.o=new zk(a,f.j.Qp.bind(f.j));pk(f.o);zaa(f,p,b);f.W=function(){return h(p)};f.O=n}).catch(function(p){f.M.error("Mirroring launch error: "+p);f.Qg(void 0===p.reason?9:p.reason);n(p)})});return Bj(g)};k.Vi=function(a,b){return new Bz(a,b,20969472,null)};k.bi=function(){yy(0)};k.Yh=function(){yy(1)};k.Aj=function(){yy(2)};k.Zh=function(){Nb("MediaRouter.CastStreaming.Session.End")};
k.Qg=function(a){Ob("MediaRouter.CastStreaming.Start.Failure",a,Dj)};k.ai=function(){Nb("MediaRouter.CastStreaming.Stream.End")};
k.Qk=function(a){var b=this;return this.u?Promise.resolve():(new Promise(function(c){return chrome.metricsPrivate.getIsCrashReportingEnabled(c)})).then(function(c){var d=c&&Fy(),e=[9351424];d&&e.push(20969472);return Cz(a,e).then(function(f){var g=f[f.length-1];f=dn(f[0].vd).catch(function(h){b.M.error("Failed to persist events Blob.",h)});d&&0<g.vd.size?Ay(g.vd,void 0,b.ZA.bind(b)):c&&By("stats.json",g.Wg,void 0,void 0);return f})})};k.ZA=function(a){if(a){a=Ey();var b=Date.now();a.g=b}};
k.Xj=function(a){if(this.u)return db();this.M.info("Received message to upload logs for "+a);return this.g?Cz(this.g,[20969472]).then(function(b){b=m(b).next().value;return 0==b.vd.size?"":Ay(b.vd,a)}):Promise.resolve(Aaa(this,a))};
var Aaa=function(a,b){var c=window.localStorage.getItem("mr.temp.mirror.cast.Service.eventsBlob");if(null==c||1>c.length)c=null;else{for(var d=new Uint16Array(c.length),e=0;e<c.length;++e)d[e]=c.charCodeAt(e);c=d.buffer;d=(new Uint8Array(c,c.byteLength-1,1))[0];c=new Uint8Array(c,0,c.byteLength-(0==d?2:1));c=new Blob([c],{type:"application/gzip"})}if(null!=c&&0!=c.size)return dn(new Blob),a.M.info("Uploading saved logs for feedback."),Ay(c,b)};k=Dz.prototype;
k.onError=function(a){this.O&&(this.O(a),this.W=this.O=null,this.Qg(9));this.M.info("Mirroring service error: "+a);this.C()};k.didStart=function(){this.W&&(this.W(),this.W=this.O=null);this.lb&&(this.lb.end(),this.lb=null);this.X=xy();kk(this.L)?this.bi():lk(this.L)?this.Yh():ik(this.L)&&this.Aj()};k.didStop=function(){this.C()};k.send=function(a){if(this.m){var b=JSON.parse(a.jsonFormatData);this.M.ua(function(){return"Sending message: "+JSON.stringify(b)});this.m.sendMessage(a.jsonFormatData,{namespace:a.messageNamespace})}};
k.bB=function(a){if(a&&(a.namespace_===mojo.MirroringWebRtcNamespace||a.namespace_===mojo.MirroringRemotingNamespace)&&this.F){var b=new mojo.MirroringCastMessage;b.messageNamespace=a.namespace_;"string"!==typeof a.data?this.M.info("Received non-string as JSON"):(b.jsonFormatData=a.data,this.F.send(b))}};
var waa=function(a,b){a.H=new mojo.Binding(mojo.MirroringSessionObserver,a,null);a.J=new mojo.Binding(mojo.MirroringCastMessageChannel,a,null);a.m=Ow(b.id);a.m.onMessage=a.bB.bind(a)},xaa=function(a,b){var c=new mojo.MirroringSessionParameters;c.receiverAddress=new mojo.IPAddress;c.receiverAddress.addressBytes=a.Qb.ii.split(".").map(function(d){return parseInt(d,10)});c.receiverModelName=a.Qb.mf;a=Baa(a.mediaSource);c.targetPlayoutDelay=Caa(a);!b.shouldCaptureVideo||!b.shouldCaptureAudio||a&&"0"===
a.searchParams.get("streamingCaptureAudio")?c.type=b.shouldCaptureVideo?mojo.MirroringSessionType.VIDEO_ONLY:mojo.MirroringSessionType.AUDIO_ONLY:c.type=mojo.MirroringSessionType.AUDIO_AND_VIDEO;return c},Caa=function(a){if(!a)return null;a=Number(a.searchParams.get("streamingTargetPlayoutDelayMillis"));return isNaN(a)||0>=a?null:new mojo.TimeDelta({microseconds:1E3*a})},Baa=function(a){if(!a)return null;try{return new URL(a)}catch(b){return null}},yaa=function(a,b,c,d){a.l=new mojo.MirroringServiceHostPtr;
b=b.Qb.tabId||-1;kk(c)?a.j.getMirroringServiceHostForTab(b,mojo.makeRequest(a.l)):lk(c)?a.j.getMirroringServiceHostForDesktop(-1,a.ca,mojo.makeRequest(a.l)):ik(c)?(b=new mojo.Url,b.url=c,a.j.getMirroringServiceHostForOffscreenTab(b,d||"",mojo.makeRequest(a.l))):a.l=null},zaa=function(a,b,c){kk(c)&&!chrome.tabs.onUpdated.hasListener(a.pa)&&chrome.tabs.onUpdated.addListener(a.pa);(kk(c)||ik(c))&&sk(a.o,b.Qb.tabId)};Dz.prototype.Aa=function(a,b,c){hk(14);this.o&&uk(this.o,a,b,c)};
Dz.prototype.C=function(){chrome.tabs.onUpdated.removeListener(this.pa);return this.u?this.ka?this.l?(this.l.ptr.reset(),this.F=this.l=null,this.m&&this.m.dispose(),this.m=null,this.H&&(this.H.close(),this.H=null),this.J&&(this.J.close(),this.J=null),tk(this.j,this.o.h.id),this.o=null,this.ca=this.L="",this.X&&(this.X.end(),this.X=null),this.Zh(),Promise.resolve(!0)):Promise.resolve(!1):Promise.reject("Not initialized"):nk.prototype.C.call(this)};
Dz.prototype.li=function(a,b,c,d,e,f){return this.u?Aj(Error("Mirroring service does not support updating stream")):nk.prototype.li.call(this,a,b,c,d,e,f)};Dz.prototype.send=Dz.prototype.send;Dz.prototype.didStop=Dz.prototype.didStop;Dz.prototype.didStart=Dz.prototype.didStart;Dz.prototype.onError=Dz.prototype.onError;var Daa=new Dz;ek("mr.mirror.cast.Service",Daa);
