(define (problem Go-Jack)
    (:domain bulldozer)
  (:objects a b d e g jack)
  (:goal (AND (at Jack g)))
  (:length (:serial 4 ) (:parallel 4))
  (:init (at jack a) 
	 ;;(at bulldozer e)
	 ;; (vehicle bulldozer)
	 (mobile jack)
	 (person jack)
	 (road a e)
	 (road e b)
	 (bridge b d)
	 (road d g)))