(define (problem Jack-back)
    (:domain bulldozer)
  (:objects a g jack bulldozer)
  (:length (:serial 4) (:parallel 4)) 
  (:goal (and (at bulldozer g) (at Jack a)))
  (:init (at jack a) (at bulldozer a)
	 (vehicle bulldozer)
	 (mobile jack)
	 (person jack)
	 (road a g) (road g a)))