;;; org-iv-autoloads.el --- automatically extracted autoloads  -*- lexical-binding: t -*-
;;
;;; Code:

(add-to-list 'load-path (directory-file-name
                         (or (file-name-directory #$) (car load-path))))


;;;### (autoloads nil "org-iv" "org-iv.el" (0 0 0 0))
;;; Generated autoloads from org-iv.el

(autoload 'org-iv/immediate-view "org-iv" "\
Use impatient-mode to view html-file generated by org-file quickly.

\(fn CONFIG-NAME)" t nil)

(register-definition-prefixes "org-iv" '("org-iv/"))

;;;***

;;;### (autoloads nil "org-iv-config" "org-iv-config.el" (0 0 0 0))
;;; Generated autoloads from org-iv-config.el

(register-definition-prefixes "org-iv-config" '("org-iv"))

;;;***

;;;### (autoloads nil nil ("org-iv-pkg.el") (0 0 0 0))

;;;***

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; coding: utf-8
;; End:
;;; org-iv-autoloads.el ends here
