(define-package "org-iv" "20171001.1022" "a tool used to view html (in browser) generated by org-file once the org-file changes"
  '((impatient-mode "1.0.0")
    (org "8.0")
    (cl-lib "0.5"))
  :commit "7f2bb1b32647655fd9d6684f6f09dcc66b61b0cd" :authors
  '(("kuangdash" . "kuangdash@163.com"))
  :maintainer
  '("kuangdash" . "kuangdash@163.com")
  :url "https://github.com/kuangdash/org-iv")
;; Local Variables:
;; no-byte-compile: t
;; End:
