/* Generated By:JavaCC: Do not edit this line. InterpretationParserConstants.java */
package net.sf.regulus.interpretation;

public interface InterpretationParserConstants {

  int EOF = 0;
  int ID = 5;
  int INT = 6;
  int NUMBER = 7;
  int SEP = 8;
  int L_BRACKET = 9;
  int R_BRACKET = 10;
  int SINGLE_QUOTE = 11;
  int COMMA = 12;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<ID>",
    "<INT>",
    "<NUMBER>",
    "\"=\"",
    "\"[\"",
    "\"]\"",
    "\"\\\'\"",
    "\",\"",
  };

}
