(define (problem strips-ferry2)
    (:init (place a)
	   (place b)
	   (auto c1)
	   (at c1 a)
	   (at-ferry a)
	   (ferryless b)
	   (empty-ferry))
  (:objects a b c1)
  (:goal (and (at c1 b)))
  (:domain ferry-strips))