(define (problem strips-ferry1) 
    (:init (place a) 
	   (place b) 
	   (auto c1) 
	   (auto c2)
	   (at c1 a)
	   (at c2 a)
	   (at-ferry a)
	   (ferryless b)
	   (empty-ferry))
  (:objects a b c1 c2)
  (:goal (and (at c1 b)
	      (at c2 b)))
  (:domain ferry-strips))