/* soapcandc_bindingProxy.h
   Generated by gSOAP 2.8.12 from src/api/soap/candc_soap.h

Copyright(C) 2000-2012, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapcandc_bindingProxy_H
#define soapcandc_bindingProxy_H
#include "soapH.h"
class candc_binding
{   public:
	/// Runtime engine context allocated in constructor
	struct soap *soap;
	/// Endpoint URL of service 'candc_binding' (change as needed)
	const char *endpoint;
	/// Constructor allocates soap engine context, sets default endpoint URL, and sets namespace mapping table
	candc_binding()
	{ soap = soap_new(); endpoint = "http://localhost:9004"; if (soap && !soap->namespaces) { static const struct Namespace namespaces[] = 
{
	{"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
	{"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"ns1", "urn:candc", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap->namespaces = namespaces; } };
	/// Destructor frees deserialized data and soap engine context
	virtual ~candc_binding() { if (soap) { soap_destroy(soap); soap_end(soap); soap_free(soap); } };
	/// Invoke 'parse_string' of service 'candc_binding' and return error code (or SOAP_OK)
	virtual int ns1__parse_USCOREstring(std::string _text, bool _start, std::string &_result) { return soap ? soap_call_ns1__parse_USCOREstring(soap, endpoint, NULL, _text, _start, _result) : SOAP_EOM; };
	/// Invoke 'parse_sentence' of service 'candc_binding' and return error code (or SOAP_OK)
	virtual int ns1__parse_USCOREsentence(std::string _text, std::string _printer, std::string &_result) { return soap ? soap_call_ns1__parse_USCOREsentence(soap, endpoint, NULL, _text, _printer, _result) : SOAP_EOM; };
	/// Invoke 'parse_oracle' of service 'candc_binding' and return error code (or SOAP_OK)
	virtual int ns1__parse_USCOREoracle(std::string _text, std::string _constraints, std::string _printer, std::string &_result) { return soap ? soap_call_ns1__parse_USCOREoracle(soap, endpoint, NULL, _text, _constraints, _printer, _result) : SOAP_EOM; };
};
#endif
