/*  Creator: make/0

    Purpose: Provide index for autoload
*/

index((goal_L_expansion), 3, assert_db_Local, assert_db_local).
index((retractall_L_hp), 2, assert_db_Local, assert_db_local).
index((retractall_L), 2, assert_db_Local, assert_db_local).
index((retractall_L), 1, assert_db_Local, assert_db_local).
index((retract_L_hp), 2, assert_db_Local, assert_db_local).
index((retract_L), 2, assert_db_Local, assert_db_local).
index((retract_L), 1, assert_db_Local, assert_db_local).
index((into_hp_L), 2, assert_db_Local, assert_db_local).
index((check_L), 1, assert_db_Local, assert_db_local).
index((call_L), 1, assert_db_Local, assert_db_local).
index((call_L), 2, assert_db_Local, assert_db_local).
index((install_L), 0, assert_db_Local, assert_db_local).
index((reset_L), 0, assert_db_Local, assert_db_local).
index((last_cons), 2, assert_db_Local, assert_db_local).
index((assertz_L_hp), 2, assert_db_Local, assert_db_local).
index((assertz_L), 2, assert_db_Local, assert_db_local).
index((assertz_L), 1, assert_db_Local, assert_db_local).
index((assert_L), 2, assert_db_Local, assert_db_local).
index((assert_L), 1, assert_db_Local, assert_db_local).
index((asserta_L_hp), 2, assert_db_Local, assert_db_local).
index((asserta_L), 2, assert_db_Local, assert_db_local).
index((asserta_L), 1, assert_db_Local, assert_db_local).
index((erase_L), 2, assert_db_Local, assert_db_local).
index((clause_L), 4, assert_db_Local, assert_db_local).
index((ref_L), 3, assert_db_Local, assert_db_local).
index((clause_L), 3, assert_db_Local, assert_db_local).
index((erase_L), 1, assert_db_Local, assert_db_local).
index((show_L), 1, assert_db_Local, assert_db_local).
index((listing_L), 1, assert_db_Local, assert_db_local).
index((listing_L), 0, assert_db_Local, assert_db_local).
index((was_dynamic_L), 2, assert_db_Local, assert_db_local).
index((make_dynamic_L), 3, assert_db_Local, assert_db_local).
index((dynamic_L), 1, assert_db_Local, assert_db_local).
index((install_L), 0, assert_db_Local, assert_db_local).
index((disable_L), 0, assert_db_Local, assert_db_local).
index((enable_L), 0, assert_db_Local, assert_db_local).
index((each_call_cleanup), 3, ecc_legacy, each_call_cleanup).
index((loading_source_file), 1, file_scope, file_scope).
index((assert_until_eof), 2, file_scope, file_scope).
index((assert_until_eof), 1, file_scope, file_scope).
index((asserta_until_eof), 2, file_scope, file_scope).
index((asserta_until_eof), 1, file_scope, file_scope).
index((set_prolog_flag_until_eof), 2, file_scope, file_scope).
index((call_on_eom), 1, file_scope, file_scope).
index((loading_source_file0), 1, file_scope, file_scope).
index((call_on_eof), 1, file_scope, file_scope).
index((call_on_eof), 2, file_scope, file_scope).
index((disable_in_file), 1, file_scope, file_scope).
index((is_current_source_term), 1, file_scope, file_scope).
index((enable_in_file), 1, file_scope, file_scope).
index((is_file_enabling), 1, file_scope, file_scope).
index((do_eof_actions), 2, file_scope, file_scope).
index((signal_eom), 1, file_scope, file_scope).
index((signal_eof), 1, file_scope, file_scope).
index((signal_eof), 0, file_scope, file_scope).
index((signal_eom), 1, file_scope, file_scope).
index((check_skip_id), 3, file_scope, file_scope).
index((filescope_did), 1, file_scope, file_scope).
index((contains_f), 2, file_scope, file_scope).
index((contains_eq), 2, file_scope, file_scope).
index((term_expansion_option), 3, file_scope, file_scope).
index((add_did_id), 3, file_scope, file_scope).
index((notice_file), 3, file_scope, file_scope).
index((ain), 1, hook_database, hook_database).
index((ain0), 1, hook_database, hook_database).
index((aina), 1, hook_database, hook_database).
index((ainz), 1, hook_database, hook_database).
index((if_flag_true), 2, hook_database, hook_database).
index((current_module_from), 2, hook_database, hook_database).
index((attributes_equal), 3, hook_database, hook_database).
index((ereq), 1, hook_database, hook_database).
index((dbreq), 1, hook_database, hook_database).
index((is_visible_module), 1, hook_database, hook_database).
index((hb_to_clause), 3, hook_database, hook_database).
index((paina), 1, hook_database, hook_database).
index((pain), 1, hook_database, hook_database).
index((painz), 1, hook_database, hook_database).
index((modulize_head), 2, hook_database, hook_database).
index((remove_term_attr_type), 2, hook_database, hook_database).
index((ainz_clause), 1, hook_database, hook_database).
index((ainz_clause), 2, hook_database, hook_database).
index((simple_var), 1, hook_database, hook_database).
index((find_module), 2, hook_database, hook_database).
index((module_of), 3, hook_database, hook_database).
index((callable_module), 2, hook_database, hook_database).
index((expand_to_hb), 3, hook_database, hook_database).
index((assert_if_new), 1, hook_database, hook_database).
index((asserta_if_new), 1, hook_database, hook_database).
index((asserta_new), 1, hook_database, hook_database).
index((assertz_if_new), 1, hook_database, hook_database).
index((assertz_new), 1, hook_database, hook_database).
index((assert_setting), 1, hook_database, hook_database).
index((assert_setting_if_missing), 1, hook_database, hook_database).
index((call_provider), 1, hook_database, hook_database).
index((call_provider), 2, hook_database, hook_database).
index((clause_true), 1, hook_database, hook_database).
index((modulize_head_fb), 4, hook_database, hook_database).
index((clause_asserted), 1, hook_database, hook_database).
index((clause_asserted), 2, hook_database, hook_database).
index((clause_asserted), 3, hook_database, hook_database).
index((clause_asserted_i), 1, hook_database, hook_database).
index((clause_asserted_i), 2, hook_database, hook_database).
index((clause_asserted_i), 3, hook_database, hook_database).
index((clause_i), 1, hook_database, hook_database).
index((clause_i), 2, hook_database, hook_database).
index((clause_i), 3, hook_database, hook_database).
index((assert_i), 1, hook_database, hook_database).
index((asserta_i), 1, hook_database, hook_database).
index((assertz_i), 1, hook_database, hook_database).
index((retract_i), 1, hook_database, hook_database).
index((retractall_i), 1, hook_database, hook_database).
index((clause_safe), 2, hook_database, hook_database).
index((erase_safe), 2, hook_database, hook_database).
index((eraseall), 2, hook_database, hook_database).
index((find_and_call), 1, hook_database, hook_database).
index((somehow_callable), 1, hook_database, hook_database).
index((find_and_call), 3, hook_database, hook_database).
index((std_provider), 3, hook_database, hook_database).
index((mpred_mop), 3, hook_database, hook_database).
index((mpred_op_prolog), 2, hook_database, hook_database).
index((mpred_split_op_data), 3, hook_database, hook_database).
index((retract_eq), 1, hook_database, hook_database).
index((safe_univ), 2, hook_database, hook_database).
index((safe_univ0), 2, hook_database, hook_database).
index((my_module_sensitive_code), 1, hook_database, hook_database).
index((add_library_search_path), 2, logicmoo_common, logicmoo_common).
index((locally), 2, logicmoo_common, logicmoo_common).
index((logicmoo_webbot), 0, logicmoo_lib, logicmoo_lib).
index((setup_logicmoo_operators), 0, logicmoo_lib, logicmoo_lib).
index((rescan_pack_autoload_packages), 0, logicmoo_packages, logicmoo_packs).
index((test_pengines), 0, logicmoo_remote, logicmoo_remote).
index((pengine_server), 0, logicmoo_remote, logicmoo_remote).
index((maybe_notrace), 1, logicmoo_startup, logicmoo_startup).
index((absolute_startup_script), 1, logicmoo_startup, logicmoo_startup).
index((before_boot), 1, logicmoo_startup, logicmoo_startup).
index((during_boot), 1, logicmoo_startup, logicmoo_startup).
index((after_boot), 1, logicmoo_startup, logicmoo_startup).
index((has_ran_once), 1, logicmoo_startup, logicmoo_startup).
index((has_ran_once), 2, logicmoo_startup, logicmoo_startup).
index((app_argv), 1, logicmoo_startup, logicmoo_startup).
index((app_argv1), 1, logicmoo_startup, logicmoo_startup).
index((app_argv_ok), 1, logicmoo_startup, logicmoo_startup).
index((app_argv_off), 1, logicmoo_startup, logicmoo_startup).
index((pack_upgrade_soft), 1, logicmoo_startup, logicmoo_startup).
index((is_startup_script), 1, logicmoo_startup, logicmoo_startup).
index((init_why), 2, logicmoo_startup, logicmoo_startup).
index((run_pending_inits), 0, logicmoo_startup, logicmoo_startup).
index((test_case_1), 0, multivar, multivar).
index((test_case_2), 0, multivar, multivar).
index((test_case_3), 0, multivar, multivar).
index((test_case_4), 0, multivar, multivar).
index((must), 1, must_sanity, must_sanity).
index((must_once), 1, must_sanity, must_sanity).
index((must_det), 1, must_sanity, must_sanity).
index((sanity), 1, must_sanity, must_sanity).
index((nop), 1, must_sanity, must_sanity).
index((scce_orig), 3, must_sanity, must_sanity).
index((must_or_rtrace), 1, must_sanity, must_sanity).
index((this_script_begin), 0, script_files, script_files).
index((this_script_ends), 0, script_files, script_files).
index((process_script_file), 0, script_files, script_files).
index((process_script_file), 1, script_files, script_files).
index((process_script_file), 2, script_files, script_files).
index((process_stream), 1, script_files, script_files).
index((visit_script_term), 1, script_files, script_files).
index((xlisting), 1, xlisting_lm, xlisting).
